Dockerfile, Dockerfile.go_build, docs/gettingstarted.rst
I think the weed docker image which build from the given Dockerfile is too large, so I made this minimal version and it's only about 19.6 MB.
=> Weed "minimal" docker image

go/weed/weed_server/common.go
fix bug about the collection in volume is wrong when curl -F "file=@/tmp/test.jpg" "localhost:9333/submit?collection=picture"
bug:
```
curl -F "file=@/tmp/test.jpg" "localhost:9333/submit?collection=picture"
{"fid":"1,012515d9d5","fileName":"test.mp3","fileUrl":"localhost:8080/1,012515d9d5","size":4}
ls /tmp/data1
1.dat 1.idx 2.dat 2.idx 3.dat 3.idx 4.dat 4.idx 5.dat 5.idx
```
fixed:
```
curl -F "file=@/tmp/test.jpg" "localhost:9333/submit?collection=picture"
{"fid":"4,01a750e97c","fileName":"test.mp3","fileUrl":"localhost:8080/4,01a750e97c","size":4}
ls /tmp/data1
picture_1.dat picture_1.idx picture_2.dat picture_2.idx picture_3.dat picture_3.idx picture_4.dat picture_4.idx picture_5.dat picture_5.idx
```
=> fix bug about the collection

.gitignore, go/weed/weed_server/common.go
```
./weed master \
-mdir="/tmp/weed_master_tmp" \
-defaultReplication="001" \
-volumeSizeLimitMB=1
```
```
./weed -v=5 volume \
-dir="/tmp/data1" \
-max=1  \
-mserver="localhost:9333" \
-port=8080 \
-rack=1
``
bug:
```
2015/01/08 18:58:27 http: multiple response.WriteHeader calls
2015/01/08 18:58:27 http: multiple response.WriteHeader calls
```
fixed:
not error log printed.
=> fix bug: 'http: multiple response.WriteHeader calls'

README.md
This change also rewrites all example lead-ins to come *before* the examples, and not after.
=> Note usable methods in examples

go/operation/system_message.pb.go
Please use `github.com/golang/protobuf/proto` instead of `code.google.com/p/goprotobuf/proto` .
The GFW in China  makes programmer's life so tough when project import `code.google.com...` .
=> use proto "github.com/golang/protobuf/proto"

go/weed/weed_server/volume_server.go, go/weed/weed_server/volume_server_handlers.go
It needs lock.
https://groups.google.com/forum/?hl=zh-CN#!topic/golang-nuts/zyQnord8hyc
=> use sync.RWMutex when masterNode changes

go/images/resizing.go
I have some kind of picture cannot be resize,  I dont know the specific reason for it. 
But I have wasted a lot time because weed-fs not print any error log about it .
So I think some error should be log here, instead of being ignored .
=> log image Decode error for some kind of pictures

README.md, go/filer/filer.go, go/images/preprocess.go, go/weed/benchmark.go, go/weed/fix.go, go/weed/mount.go, go/weed/mount_std.go, go/weed/version.go, go/weed/weed.go, go/weed/weed_server/master_ui/templates.go, go/weed/weed_server/volume_server_ui/templates.go, note/memory_usage.txt, note/security.txt, note/weedfs.txt
Among the changes, this replaces a couple instances of "Seaweed File System" with "SeaweedFS", for the same reason that nobody says "Mongo Data Base".
=> More consistency with SeaweedFS name

Dockerfile
I modified the Dockerfile to make sure it was built successfully in the docker image build system.  You may find the build information and result via https://registry.hub.docker.com/u/carmark/seaweedfs/.
Currently, I used my forked repository to as the automated build source, it could be modified on the main upstream.
I did test the images on my local system, the result is following:
> Pulling the images
root@ubuntu:/opt/weed# docker pull carmark/seaweedfs
Pulling repository carmark/seaweedfs
81726418f76b: Download complete
511136ea3c5a: Download complete
46e263e5de56: Download complete
cf677a5f718c: Download complete
6adb1b0566e7: Download complete
fdb314abe596: Download complete
cfed5ebfc893: Download complete
653376e72714: Download complete
46bed15d45c7: Download complete
8cee90767cfe: …
=> modify the dockerfile to make sure it was built successfully

go/weed/weed_server/volume_server_handlers_read.go
became
if !strings.HasPrefix(mt, "application/octet-stream")
In our situation,
mt can be 'application/octet-stream;charset=ISO-8859-1',
so I think HasPrefix will be more accurate.
=> if mt != "application/octet-stream"

go/storage/store.go
The name of a collection like 'something_something' is badly taken from a .dat file name.
=> fix extract collection name from .dat file

go/security/guard.go
This allows you to write something like this:
/usr/local/bin/weed master -mdir /srv/weed/master -whiteList=192.168.0.0/24,127.0.0.1
This will whitelist all the 192.168.0.XX hosts, as well as localhost.
=> Allow whitelisting by CIDR range, not just literally.

go/weed/server.go
Hello,
When you run ./weed server you can't pass distributed filer parameters to the filer. This should fix it.
Thanks :)
=> server_filer_fix

go/weed/signal_handling.go
I use cmd below to run weedfs in server.
``` shell
nohup ./weed -log_dir="./log/" volume -ip=10.144.152.250 -mserver="10.164.30.155:9333" -port=8887  -dir="./data0" -max=10000 &
```
when I close the terminal(i use Xshell), weedfs exit, too. I add the log and find weedfs receive signal "hangup", so I ignore syscall.SIGHUP
=> [bug fix]weed daemon exit due to hangup signal when terminal close

go/weed/weed_server/filer_server_handlers.go
uploading file with filer service could specify the collection name in get/post field, if no collection specified, the default collection setting against the filer service will be used
=> collection name could be specified in url

.travis.yml, go/storage/crc.go
This package is a drop-in replacement for the standard library hash/crc32 package, that features SSE 4.2 optimizations on x64 platforms, for a 10x speedup.
=> use klauspost/crc32 instead of hash/crc32

go/storage/needle_map.go
`baseNeedleMapper` contains `sync.Mutex` which should not be copied by value.
=> storage: do not copy sync.Mutex by value

go/storage/needle.go, go/storage/needle_test.go
```
before:
BenchmarkParseKeyHash-4 10000000           241 ns/op          16 B/op          1 allocs/op
after:
BenchmarkParseKeyHash-4 20000000           111 ns/op           0 B/op          0 allocs/op
```
=> faster ParseKeyHash

go/util/concurrent_read_map.go
It seems that we did not use the feture of rwlock now.
delete the sync.Mutex only use sync.RWMutex.
=> modify the lock

go/weed/weed_server/volume_server_handlers_read.go
Fixes **Content-Disposition** header as defined by RFC6266
Adds **dl=(0|1)** URI param to select inline (default) or attachment content disposition
=> Fix Content-Disposition header

weed/server/filer_server.go
This is an edge case
When the master cluster's status is not ready, filer should output fatal log e.g instead of go on running
```
I0630 17:27:04 41495 store.go:58] Failed listing masters on 100.107.5.2:9333: http://100.107.5.2:9333/cluster/status: 404 Not Found `
```
The reproduced step is:
1. restart master1, master2, master3 quickly(volume servers have been launched for a while)
2. start filer 1 and specify master1 in command option asap(while master 1's cluster status is not ready yet)
3. stop master1
Then the filer 1 will never get the master cluster's topo until master 1 is relaunched with available cluster status
And fix another bug in detectHealthyMaster func
=> fix bug when choosing the healthy master in filer service

weed/storage/needle_read_write.go
Chris:
This is a tiny fix which currently just influence the volume_checking.go.
=> deleted needle does not need checksum verification

weed/storage/volume_checking.go, weed/topology/volume_layout.go
The deleted index entry format is below 
id          |   offset           | size
8Bytes     4 Bytes         4Bytes
offset and size value are both 0
If the last index entry of a specific index file is a deleted one,  we will bypass the needle verification.
=> deleted needle does not need checksum verification(patch)

weed/filer/cassandra_store/cassandra_store.go
Filer can use a cassandra cluster as the storage of metadata.
After the fix we can use more than one cassandra node for filer.
Due to the function `NewCluster` in gocql, now we support two cassandra nodes setting only
=> Fix the filer connection of cassandra

weed/filer/postgres_store/postgres_store.go, weed/server/filer_server.go
Hi Chris,
After I added the initial PostgreSQL file store support, I realized that it did not support filer directories. This is something that I need, so I changed the implementation so that it implements the full filer API instead of the FlatNamespaceFiler interface. I implemented all of the methods except for "move".
This new implementation is quite different than the MySQL implementation and only deals with a single PostgreSQL server and does not support sharding.
Thanks,
Mike
=> Updating PostgreSQL file store integration to support directories.

weed/server/filer_server_handlers_read.go
Before #344, the filer will return json data, and cschiano make a template that render to html. But sometimes need json data, so I add some code will return json data when content-type is "application/json".
=> Return json data when content-type is "application/json"

weed/command/upload.go, weed/operation/submit.go, weed/storage/needle.go
fixes #413. When chunking .gz file, chunked manifest file is marked as 'gzipped', but actually not gzipped. so if it's loaded, it will be ungziped, and then panic.
=> fix bug: upload big .gz file more than maxMB

weed/operation/submit.go, weed/operation/upload_content.go, weed/server/common.go, weed/server/filer_server_handlers_write.go, weed/server/volume_server_handlers_read.go, weed/storage/needle.go, weed/storage/needle_read_write.go, weed/storage/store.go, weed/topology/store_replicate.go
The name of pairs must begin with 'Seaweed-'. Common use cases have been tested, other than some API I'm unfamiliar with, such as 'Filer server'.
=> support additional header name-value pairs

weed/filer/mysql_store/mysql_store.go
The length of a CHAR column is fixed to the length that you declare when you create the table. The length can be any value from 0 to 255. When CHAR values are stored, they are right-padded with spaces to the specified length. 
see https://dev.mysql.com/doc/refman/5.7/en/char.html
=> Fix:  the maximum-length character exceed 255

weed/command/mount.go, weed/command/mount_std.go
I notice that access via FUSE still can't work, because the API of http://[filter server]/__api__ has not been implemented. Is there still a plan to add it?
=> Fixes #266

weed/filer/embedded_filer/filer_embedded.go
Use mutex when performing move operation to make sure it is atomic. Based on conversation in #468.
=> Added locking on the filer move operation

weed/server/volume_server_handlers_read.go
In reference to #464.
When argument `?cm=false` is passed with request to the manifest file, the JSON content of the manifest file is displayed instead of the actual chunked content.
=> Show contents of manifest file when cm=false is passed

weed/topology/topology.go
Fix: interface conversion: interface {} is nil, not *topology.Collection.
```
2017/07/14 11:49:54 http: panic serving 172.20.0.1:51100: interface conversion: interface {} is nil, not *topology.Collection
net/http.(*conn).serve.func1(0xc4200be8c0)
/home/travis/.gimme/versions/go/src/net/http/server.go:1693 +0xd0
panic(0xb8ce60, 0xc4203ef100)
/home/travis/.gimme/versions/go/src/runtime/panic.go:489 +0x25a
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).FindCollection(0xc4201e76c0, 0xc4202de5bb, 0x24, 0xc4202de5bb, 0x24)
/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology.go:119 +0x92
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).collectionDeleteHandler(0xc4201e4400, 0x1080380, 0xc4202da620, 0xc420213800) …
```
=> Fix panic error when target collection is not exist.

weed/util/http_util.go
to fix #543 , I make some changes in util.Post, make it combine response body into error when encountered 4xx or 5xx statusCode. So that benchmark command can report more accurate infos like 'No free volumes left' rather than a simple '404 Not Found'
=> (fix #543)added response body to error when util.Post encounter 4xx response

weed/filer/embedded_filer/directory_in_map.go
Current filer's post handler prints error message when there is no existing directories in the file path.
```
// also delete the old fid unless PUT operation
if r.Method != "PUT" {
if oldFid, err := fs.filer.FindFile(path); err == nil {
operation.DeleteFile(fs.getMasterNode(), oldFid, fs.jwt(oldFid))
} else if err != nil && err != filer.ErrNotFound {
glog.V(0).Infof("error %v occur when finding %s in filer store", err, path)
}
}
```
The filer server code designed to not print error message in this situation. 
However the FindFile() method returns it's own declared error message instead of filer.ErrNotFound so it wasn't work. 
I changed to return filer.ErrNotFound.
=> filer: fixup print error message when make new directory

docker/Dockerfile
According to the information from https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md, "--virtual build-dependencies" is the right form.
"curl wget ca-certificates" are under the group "build-dependencies", so "apk del build-dependencies" should suffice. 
"...egrep -o '/chrislusf/seaweedfs/..." should be "...egrep -o 'chrislusf/seaweedfs/...", though one more slash does not cause problems.
Tried to use curl only (curl -o /tmp/linux_amd64.tar.gz ...), however it turned out that the following tar command failed with "gzip: stdin: not in gzip format" prompt. I now understand why you use both "curl" and "wget"
=> some minor fixes to docker/Dockerfile

weed/topology/node.go
This will fix replication on difference data center complains `{"error":"Cannot grow volume group! No free volume slot found!"}`.
This problem may related to Issue #562.
Thanks!
=> fix reserve volume on node

weed/storage/disk_location.go
index--->leveldb
operation:
unmount volume(vid=3)
mount volume(vid=3)
error:
I0502 16:02:19 03815 disk_location.go:59] new volume 3.dat error resource temporarily unavailable
fix:
add l.volumes[vid].close() in file storage/disk_location.go line 171 before delete(l.volumes, vid);
=> fix leveldb mount bug

weed/filer2/filer.go
when create a file use filer api,i would create every Directory the file need, but if there exist a file have the same name with the Directory, the filer will ignore it.that lead to some confusion
=> bugfix:check Directory attr  before create it

weed/filer2/redis/universal_redis_store.go
When a file is deleted by ttl, filer store entry needs to be deleted also. (if the filerstore supports ttl)
=> Set redis key ttl with entry.TTLSec

weed/glog/glog.go, weed/glog/glog_file.go
change log_dir to logdir for the "flag redefined:log_dir" error when use another package with "github.com/golang/glog"
=> change log_dir to logdir for the "flag redefined:log_dir" error when use another package with "github.com/golang/glog"

unmaintained/fix_dat/fix_dat.go, unmaintained/see_dat/see_dat.go, weed/command/export.go, weed/command/fix.go, weed/storage/needle_read_write.go, weed/storage/needle_read_write_test.go, weed/storage/volume_read_write.go, weed/storage/volume_vacuum.go
when volume file size exceeds 4294967295 (max of uint32), the volume offset will overflow. so just to change the offset to uint64.
=> fix needle Append return offset to avoid uint32 overflow

weed/wdclient/masterclient.go
在无volume时, master client即便在已经找到leader时仍宣称无主
=> Fix block-waiting for leader when there are no volumes

docker/Dockerfile, docker/entrypoint.sh, docker/seaweedfs-compose.yml
The container job is working, but for some reason I get an error when trying to use `weed shell` with the Docker Compose setup ( and therefore the replication-job mode with Compose ):
```
error: rpc error: code = Unimplemented desc = unknown service master_pb.Seaweed
```
I did successfully test the replication job with a local cluster on Docker swarm so I know that the job is running correctly.
=> Add replication-job Mode For The Docker Container

.travis.yml, go.mod, go.sum, weed/s3api/filer_multipart.go
This should enable go mod in CI, and the build error introduced in #1021 . If the master branch of go.uuid is still preferred, I could also make it work, just let me know.
=> Move travis-ci pipeline to go mod

weed/wdclient/masterclient.go
Here is a situation may cause bug:
Seaweedfs topo:
host1: master1(leader), volume1
host2: master2, volume2
host3: master3, volume3
When host1 down, master1 and volume1 crash simultaneously, the leader election take some time, volume1 hasn't send heartbeat to new leader, so the new leader cannot detect that volume1 crashed,  and won't send `DeletedVids` to the wdclient. **Now, wdclient caches the crashed volume1 location.**
---
这里有个场景会导致wdclient出现bug：
seaweedfs部署拓扑：
host1: master1(leader), volume1
host2: master2, volume2
host3: master3, volume3
如果host1挂了，master1和volume1同时下线，新leader选举需要一段时间，volume1没有给新leader发送过心跳，所以leader没有检测到volume1下线，因此没有给wdclient发送DeletedVids消息。**此时，wdclient将缓存着已经下线的volume1地址。**
=> fix wdclient bug

weed/storage/volume_loading.go
When .dat file is 666 readonly mode, seaweedfs currently do not read the file's last modified time, this cause the file to be expired, and will be deleted.
=> volume: read dat files' last modified time correctly

unmaintained/remove_duplicate_fids/remove_duplicate_fids.go
We had a few volumes that were twice the size they should be. This happened after volume servers in the middle of vacuuming were stopped. The problem that caused this is most likely mitigated by this commit https://github.com/chrislusf/seaweedfs/commit/58168a8c527e8adb5c36566f63cf32a26dba3df4
=> new tool based on see_dat to remove duplicate fids

weed/wdclient/vid_map.go, weed/wdclient/vid_map_test.go
The rand package in standard library isn't thread safe. It will panic cross multiple threads.
[Please see the doc of `rand.NewSource`](https://github.com/golang/go/blob/master//src/math/rand/rand.go#L41)
Here is a repo I copied from the stdlib, and added a new function `NewLocked` which is thread safe. For more information, please see the [repo](https://github.com/divinerapier/rand).
Thanks.
=> fix: non-thread-safe rand will panic

weed/s3api/filer_multipart.go, weed/s3api/s3api_objects_list_handlers.go, weed/s3api/s3api_xsd_generated.go
1, correct debug log when dirName is empty
```
I0929 20:05:49 26629 filer_util.go:68] create file: /buckets/test//60M.data
```
2, disable .uploads output to common prefixs 
```
common_prefixes =  {'list': [{u'LastModified': u'2019-09-29T20:00:58+08:00', u'ETag': u'"e599adac"', u'StorageClass': u'STANDARD', u'Key': u'60M.data', u'Owner': [{u'ID': u'0'}], u'Size': u'62914560'}], 'common_prefixes': [{u'{http://s3.amazonaws.com/doc/2006-03-01/}Prefix': u'.uploads/'}], 'truncated': False}
```
=> s3 api: fix listbucket common_prefixes issue

weed/command/benchmark.go
Weed benchmark command use "-master" option to set master server, but usage example give a misleading "-server" option.
=> fix benchmark cmd usage info

weed/server/filer_server_handlers_read.go
Hi,
I found that the `filer`'s storage will always return a `not found` error, which is sometimes wrong.
=> fix abused 404 status code

weed/operation/assign_file_id.go, weed/pb/master.proto, weed/pb/master_pb/master.pb.go, weed/server/master_grpc_server_volume.go, weed/server/master_server_handlers.go, weed/topology/volume_growth.go
Current assign operation can only use default volume number. Though we can use /vol/grow to add volumes，it is not convenient during runtime.
=> add volume number param in assign operation

weed/command/master.go, weed/command/scaffold.go, weed/sequence/etcd_sequencer.go, weed/server/master_server.go, weed/util/config.go
store the fid sequence in ETCD,  the master require a range of sequences from ETCD for dir/assign operation.
resolved problem:
when the master leader changed,   it will take a while for the new leader to recieve the max fid sequence from volume servers. In this duration, the operation dir/assign will return duplicate fid.
=> Add etcd sequencer

weed/topology/topology_vacuum.go
Hi, 
I think you want to stop the gc processing if it is time out.  But `break` can not out of `for-select` block.
Here is the [spec](https://golang.org/ref/spec#Break_statements)
And here is a simple poc:
``` go
package main
import (
"fmt"
"runtime"
"time"
)
func main() {
c := make(chan int)
go func() {
for {
c <- 1
}
}()
for {
select {
case <-time.After(time.Second * 3):
fmt.Printf("after 3s")
case <-c:
break
}
}
fmt.Println("over")
}
```
Output is nothing
=> can not break out of from for-select block

weed/command/volume.go, weed/util/httpdown/http_down.go
when the volume server is serving for user requests, we should stop the volume server after all the requests finished.
for example scene : online upgrade the volume server(s)
NOTE:
weed/util/httpdown/http_down.go 
this file is based on github.com/facebookarchive/httpdown, who's licence is MIT-licence, I only add a feature of supporting http TLS.
=> let volume server graceful stop

weed/topology/store_replicate.go
If a volume with 2 replications assigned to node1 and node2,  after node2 down, a file delete operation send to node1 will lead to file deleted successfully on replication in node1,  but file in node2 deleted failed. If node2 restart, the file may sometimes readable, but sometimes not readable. It also applies to write operation.
This patch can improve the data consistency by determining if all the replications are writable before write/delete operation.
=> improve data consistency when replication write

weed/server/filer_server_handlers_write.go
same as happens on the s3 API on delete bucket,
to reduce the IO requests on the system, 
you can just clear recursively folders without flagging them in volume server.
this will remove the user's ability to retrieve data under these folders without io spike or delays related to updating the volume servers (will not release disk space! , files/folders will be removed on delete bucket/drop collection)
=> Filer: Enable delete entries without flag volume

go.mod, go.sum, weed/filesys/filehandle.go
This fixes a mismatch between [path.Ext](https://godoc.org/path#Ext) function and the mimetype library.
path.Ext returns the extension with a leading dot, but mimetype previously (v0.3.17) did not have the leading dot. Now, in v1.0.0, mimetype has the leading dot https://godoc.org/github.com/gabriel-vasile/mimetype#MIME.Extension
=> Fix missing leading dot in extension

weed/command/scaffold.go, weed/filer2/redis/redis_cluster_store.go
I am running SeaweedFS in a multi-zone AWS environment where latency between the Filer and the Redis cluster is very important. However, by default the Go Redis client communicates with only the master node, which may be in a different AWS zone. This change will add configuration options to allow the Filer's Redis client to read from the closest Redis node, while still writing to the master Redis.
=> Add readOnly and routeByLatency options to Redis Cluster Store

weed/storage/volume_create.go, weed/storage/volume_create_linux.go, weed/storage/volume_create_windows.go
the volume server create volume on a host disk which has no free space, the volume server will core dump
=> resolve issue : create volume on no free space disk, the volume server core dump

weed/storage/disk_location.go, weed/storage/disk_location_ec.go
delete many volumes by collection name, the volume server will not be writen for a long time.
I decouple the volume.Destroy() from the the [ec]VolumesLock, to improve the concurrency.
=> decouple the volume.Destroy() from the operation of unmountVolume()

weed/server/volume_server_handlers_write.go
when the upload file is unchanged, the reponse should not have response body
=> remove the http 304 response body

weed/util/http_util.go
Hi Chris,
There was an error reading from `http.Response.Body`. The `err` obtained by `reader.Read` should be checked. And it is never possible to choose `m` to terminate reading.
=> fix: handle errors for ReadUrl

weed/util/http_util.go
Hi Chris,
I found that if the given `buf` size is smaller than the "response.body" size, there is an error. I think it should be reported as an error. And `response.body` should be drained to avoid `memory leaks`.
Thanks.
=> feat: drains http body if buffer is too small

weed/util/compression.go
Audio/wav files are yet very common in some domains and are 
good candidates for compression, up to 3 times with lowest compression
level.
=> Support wav files compression

weed/storage/disk_location.go
in the function of Store.MountVolume(), when loadExistingVolume() failed, the return value of funtion location.LoadVolume() will also be true,
the next funtion of s.findVolume() will return nil volume, the next opertion based on nill volume will make segment fault.
```
func (s *Store) MountVolume(i needle.VolumeId) error {
for _, location := range s.Locations {
if found := location.LoadVolume(i, s.NeedleMapType); found == true {
glog.V(0).Infof("mount volume %d", i)
v := s.findVolume(i)
s.NewVolumesChan <- master_pb.VolumeShortInformationMessage{
Id:               uint32(v.Id),
Collection:       v.Collection,
ReplicaPlacement: uint32(v.ReplicaPlacement.Byte()),
Version:          uint32(v.Version()),
Ttl:              v.Ttl.ToUint32(),
}
return nil
}
}
return fmt.Errorf("volume %d not …
```
=> when Store.MountVolume(), the volume server will be core

weed/pb/volume_server_pb/volume_server.pb.go, weed/server/volume_server_handlers_admin.go, weed/stats/disk_supported.go
Adding PercentFree & PercentUsage to the DiskStatus (stats)
Exposing DiskStatus in the /status route for volume server:
best to have volume stat and disk(os) stats in a single route
output:
=> Update stats and status volume server

weed/topology/node.go, weed/topology/volume_growth.go, weed/topology/volume_growth_test.go
Now weed master pick node randomly when assign a new volume, but it has some problems in scenarios where node capacities are not equal,  here is an example to illustrate our problem: 
We have 5 nodes with different free volumes, 50, 50, 30, 30, 30, and we use 3 replications. after uploading some files, the free volume list changes to 20, 20, 0, 0, 0.  Even there are 40 available volumes, we can't assign a new volume satisfy 3 copy.
This patch provide a new strategy to schedule volume by node weights instead of picking node randomly. Here is a test:
First, start seaweedfs cluster with 6 volume servers, each has different max volume number.
Assign 1000 volumes use default "100" replication strategy:
now we can see actual volume distribution,  agree with weight distribution on the whole:
526 …
=> schedule new volume by free volume number of nodes

weed/command/scaffold.go, weed/server/master_server.go, weed/topology/collection.go, weed/topology/topology.go, weed/topology/topology_test.go, weed/topology/volume_growth_test.go, weed/topology/volume_layout.go
Instead of treating replication as an exact count necessary for writable status, you can set:
```
[master.replication]
treat_replication_as_minimums = true
```
in the `master.toml` file to treat replication counts as minimums.
For instance, if you have `010` but you have 3 racks, the volume is still writable until you have less than 2 racks, but any amount more is acceptable. Volume writes will try to replicate to all available servers, however, if a server is down, it will miss some writes. Therefore, if you use this option you must be prepared to handle syncing yourself in the event of out-of-date replicas.
This is a step in the path to achieving asynchronous replication (#402). We are using this option on top of Pub/Sub to replicate writes to all volumes. If a volume is down, when it …
=> Added treat_replication_as_minimums master toml option

go.mod, go.sum, weed/command/filer_copy.go, weed/command/master.go, weed/command/mount_std.go, weed/command/msg_broker.go, weed/command/volume.go, weed/filesys/wfs.go, weed/server/filer_server.go, weed/server/webdav_server.go, weed/util/grace/pprof.go, weed/util/grace/signal_handling.go, weed/util/grace/signal_handling_notsupported.go
relate to #1289 
I move `signal_handling.go` and `pprof.go` into package `grace`.
Then the usage of `weed/shell` package won't initialize the grace package, which can avoid the graceful shutdown mess.
I use the `weed/shell` package to implement something like:
```
// to get all collections with: collection.list
// for each collection
//   check collection name or something to determine whether it should do `tier.upload` or `delete` or nothing
//   volume.tier.upload or collection.delete
// end
```
Seems like i can't do this kind of logic in the `scirpt` block in `[master.maintenance]`. Also the `weed shell` do not support passing a single command, then get the structure data it returned.
So i try to use the `weed/shell` package directly.
=> refactor: move signal handling and pprof to grace package

weed/command/benchmark.go, weed/operation/submit.go
Add fsync option for benchmark, provide convenience to compare performance between fsync and not.
./weed benchmark -master=localhost:9333 -c=64 -n=100000 -size=10000 -fsync=true
Concurrency Level:      64
Time taken for tests:   101.052 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      1003143900 bytes
Requests per second:    989.59 [#/sec]
Transfer rate:          9694.31 [Kbytes/sec]
Connection Times (ms)
min      avg        max      std
Total:        1.2      64.6       394.9      51.5
Percentage of the requests served within a certain time (ms)
50%     51.9 ms
66%     74.3 ms
75%     91.4 ms
80%    103.2 ms
90%    136.2 ms
95%    166.9 ms
98%    207.2 ms
99%    229.1 ms
100%    394.9 ms
=> add fsync option for benchmark

weed/storage/needle/async_request.go, weed/storage/store.go, weed/storage/volume.go, weed/storage/volume_read_write.go
Seaweedfs not flush data to disk default, this is not safe and may limit its usage scenarios.
The latest patch add fsync option in request, but it lead to great performance degradation.
In most cases, storage system use bin log to balance performance and data security, such as ceph filestore and hbase, but this just suitable for small object, its double write also lead to performance degradation for BLOB(especially for object large than 50KB), such as ceph filestore get poor performance when write large files.
We can do better for seaweedfs, since all seaweedfs write/delete is append mode. Its IO pattern 
is as same as bin log. So we can write seaweedfs just as write bin log in other storage system to receive both good performance and data security.
here is some tests for compare:
1. …
=> use async write to persistent file to disk - part1

weed/command/server.go, weed/command/volume.go, weed/server/volume_server.go, weed/storage/disk_location.go, weed/storage/store.go, weed/storage/volume.go, weed/topology/data_node.go, weed/topology/topology.go
Periodically check free disk space on volumes disks and mark volumes as readonly fi free space is low. 
ReadOnly volumes exclude from writable volumes and not assign for new files.
=> Set volumes ReadOnly if low free disk space

weed/s3api/s3api_errors.go, weed/s3api/s3api_handlers.go, weed/s3api/s3api_object_handlers.go
Fixes for S3 DeleteObject
* return 404 status code instead of 204 No content
* return xml encoded error with code `NoSuchKey`
Sample s3 response:
```
curl -v -X DELETE localhost:8333/not/exist
*   Trying ::1:8333...
* TCP_NODELAY set
* Connected to localhost (::1) port 8333 (#0)
> DELETE /not/exist HTTP/1.1
> Host: localhost:8333
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Accept-Ranges: bytes
< Content-Length: 201
< Content-Type: application/xml
< Date: Thu, 11 Jun 2020 14:56:48 GMT
< X-Amz-Request-Id: 1591887408636162435
<
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<Error><Code>NoSuchKey</Code><Message>The specified key does not …
```
=> Return NotSuchKey error code for bucket S3 DeleteObject method

weed/s3api/s3api_objects_list_handlers.go
AWS SDK expects LastModified time encoded in UTC:
```
<*awserr.requestError | 0xc00039bd00>: {
awsError: {
code: "SerializationError",
message: "failed to decode REST XML response",
errs: [
{
Layout: "2006-01-02T15:04:05.999999999Z",
Value: "2020-06-19T06:56:55+03:00",
LayoutElem: "Z",
ValueElem: "+03:00",
Message: "",
},
],
},
statusCode: 200,
requestID: "1592539015628364172",
bytes: nil,
}
SerializationError: failed to decode REST XML response
status code: 200, request id: 1592539015628364172
caused by: parsing time "2020-06-19T06:56:55+03:00" as "2006-01-02T15:04:05.999999999Z": cannot parse "+03:00" as "Z"
```
=> Return last modified in UTC

weed/storage/needle/needle_parse_upload.go
We would like to add this due to #1370 
If the Content-MD5 header is set profiling shows the md5 compute uses a significant amount of the total cpu but as its optional it can be avoided.
=> Optional md5 validation of uploads

docker/Dockerfile, docker/README.md
Add support for the following cpu architectures when building the Dockerfile:
- i386
- arm64
- armv6
- armv7
Update readme with instructions to build and push all cpu architectures at the same time.
=> Support multiple architectures when building Dockerfile

other/java/hdfs3/src/main/java/seaweed/hdfs/SeaweedAbstractFileSystem.java, other/java/hdfs3/src/main/java/seaweed/hdfs/SeaweedFileSystem.java, other/java/hdfs3/src/main/java/seaweed/hdfs/SeaweedFileSystemStore.java
1、Add SeaweedFS implementation of Hadoop AbstractFileSystem. The implementation delegates to the existing SeaweedFS FileSystem and is only necessary for use with Hadoop 2.x/3.x. Configuration example in Hadoop core-site.xml file:
```
<property>
<name>fs.AbstractFileSystem.seaweedfs.impl</name>
<value>seaweed.hdfs.SeaweedAbstractFileSystem</value>
</property>
```
2、Fix hiveserver2 startup NullPointerException
=> Add AbstractFileSystem and fix hiveserver2 startup NullPointerException

Makefile
I have Odroid HC2s with 12TB drives in them, so running the 5-byte build of SeaweedFS seemed correct.
=> add 5-byte large disk builds for arm and arm64

weed/topology/topology.go
1, there will be two leader when master server startup in a few seconds
2, raft server will get a leader even there is only one master, so there is no need to do hard code to set the server to be leader
=> fix bug:  two same volumeId in different collections

weed/server/volume_grpc_copy.go, weed/storage/disk_location.go, weed/storage/store.go
If we unmount first and then delete, the delete fails because the volume was unmounted. Delete ends up doing the same thing as the unmount anyways.
=> volume: Don't unmount before deleting volume in copy

go.mod, weed/command/scaffold.go, weed/filer/elastic/v7/elastic_store.go, weed/server/filer_server.go
1. can easily scale up the stateless filer server with Elastic cluster store .
2. treat Elastic-cluster as the MetaData service of the whole seaweedfs, we can search Elastic cluster Fast and directly using filename or self-defined metadata, and metadata management is more easy, specially use seaweedfs as the S3 object storage.
3. Elastic cluster also provide excellent put/get/query...performance, and no SPOF.
=> new filer store option to es7.

weed/command/server.go, weed/server/master_grpc_server.go
There's the potential where we're writing to a clientConn and it goes away
and we're stuck keeping a read lock on clientChansLock. This causes
KeepConnected to not be able to remove the client since it requires a write
lock on clientChansLock. This ends up backing up SendHeartbeat because it
can't get a read lock.
=> Fix deadlock with KeepConnected and SendHeartbeat

weed/s3api/s3api_object_handlers.go
1. spark 通过binaryFiles读取目录及目录通配符情况下会报错
**复现：**
```
scala> sc.hadoopConfiguration.set("fs.s3a.access.key", "xxx")
scala> sc.hadoopConfiguration.set("fs.s3a.secret.key", "xxx")
scala> sc.hadoopConfiguration.set("fs.s3a.impl","org.apache.hadoop.fs.s3a.S3AFileSystem")
scala> sc.hadoopConfiguration.set("fs.s3a.endpoint", "http://127.0.0.1:8333")
scala> val a = sc.binaryFiles("s3a://limd/aaa/*")  //以目录结尾、通配符结尾都会报错
a: org.apache.spark.rdd.RDD[(String, org.apache.spark.input.PortableDataStream)] = s3a://limd/aaa/* BinaryFileRDD[5] at binaryFiles at <console>:24
scala> a.count
org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input Pattern s3a://limd/aaa/* matches 0 files
at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:332)
at …
```
=> s3:  fix get object metadata problem

weed/filer/filechunks.go, weed/server/volume_server_handlers_write.go
See [All about AWS S3 ETags](https://teppen.io/2018/06/23/aws_s3_etags/)
Necessary for
```
aws --endpoint-url http://localhost:8333/ s3 sync s3://my-us-west-2-bucket  s3://seaweedfs-bucket --source-region us-west-2
```
=> We return etag using the same algorithm as aws s3

.github/workflows/go.yml
Currently the go workflows only try to run tests in the weed module, make it so it runs them recursively.
=> Run go test on gituh actions

docker/entrypoint.sh
Depending on a setup, 1GB volume limit is not the preferable size.
As weed can process multiple arguements and the later argument is the one to be used,
it is relatively easy to override the arguments defined in the entrypoint.
The arguments passed to the script will be shifted and appended at the end of the command. Since the first argument will fall into specific case, the argument can be predefined and the whole argument array shifted. Allowing to do "volume/server/master/etc $ARGS $@"
=> Allow custom command arguments to override default values in docker

weed/server/volume_grpc_client_to_master.go, weed/storage/store.go
When the volume server is stopped, the master server immediately sees the deletion of volumes
=> delete volumes from master on stop volume server

other/metrics/grafana_seaweedfs.json, other/metrics/grafana_seaweedfs_k8s.json
Removes the incorrect `* 5` factor from the QPS panel's PromQL query.
=> grafana: remove incorrect QPS factor

docker/Dockerfile.go_build, docker/Dockerfile.go_build_large
by using --build-args
example:
`docker build --build-arg BRANCH=support_ssd_volume -t seaweedfs:ssd_support .`
will build the support_ssd_volume branch and not the master
=> Dockerfile: support build branches other than master 

docker/Dockerfile.go_build, docker/Dockerfile.go_build_large
ARG/ENV should be uppercase
$ARG (is nothing)
$BRANCH should hold the branch name:
`docker build --build-arg BRANCH=support_ssd_volume -t seaweedfs:support_ssd_volume .`
=> fix Argument Name, and use the correct one.

docker/Dockerfile
This is necessary for `weed mount` to work inside the docker image as it needs `/bin/fusermount`. Adds <1mb.
=> Add fuse to docker image

weed/shell/command_s3_bucket_create.go
sentence "defined by the filer or master" implies there is no particular order. attempting to clarify that.
Not sure how the long string in multiline will render in a small terminal
=> [shell] Clarify bucket replication setting order

docker/Dockerfile.go_build, docker/Dockerfile.go_build_large, docker/Dockerfile.local
I noticed `weed mount` wasn't working with a tagged docker image, because https://github.com/chrislusf/seaweedfs/pull/1690 only added fuse to the `latest` build. This should add fuse to all builds. Also, I was wrong about it adding <1mb. It seems to add 6.5mb to the final image (89.3mb vs 81.8mb), but this probably isn't a concern for someone running a distributed filesystem.
=> Add fuse to all dockerfiles

weed/server/filer_server_handlers_write_autochunk.go
This is needed for the S3 gateway to conform to the S3 protocol -- the
server should always respect the Content-Type set by client.
=> filer: respect Content-Type on PUT

weed/filer/rocksdb/rocksdb_store.go, weed/filer/rocksdb/rocksdb_ttl.go
Also remove `MaybeDecompressData` since no Compress performed in `InsertEntry`
Did a quick benchmark on insert gzipped or raw large random values. (rocksdb use snappy by default), 
for values < 10k, raw values are much faster,
for values > 100k, gzipped values are slightly faster, but really close (-10% ~ +15%)
=> impl: TTL per entry for rocksdb; fix package name

weed/filer/rocksdb/rocksdb_store.go
rocksdb iterator `iter.Seek()` may reach EOF,
`iter.Next()` without check could cause segmentation violation.
How to reproduce:
List an invalid directory.
Also remove redundant limit check.
=> fix rocksdb crash when list directory

k8s/seaweedfs/values.yaml, weed/command/scaffold.go, weed/filer/mysql/mysql_store.go
added SetConnMaxLifetime setting (https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime)
so we can control the age of connection in the connection pool, keeping them young and alive.
updated k8s chart mysql setting to accumadate the new setting and set lower connections per filer (when having 3 filers, no need for 450 connections) and even 75 connection is more than enough.
=> MYSQL - Better Connection Pool Control

weed/command/mount_std.go
This PR basically enforces the use of the `-umask` setting provided instead of the one fingerprinted from the OS in case the folder already exists.
Scenario: I'm using the `seaweedfs-csi-plugin` and when `weed mount` is executed with `-dir` pointing to a folder that already exists, the `-umask` setting won't be applied at all. For example: I'm using the `mariadb` docker container which comes with `/var/lib/mysql` already setup in the container and it runs as an unprivileged `mysql` user. When `weed mount` mounts into `/var/lib/mysql`, it is setting the same umask (022) that was predefined in the docker image even when I'm running with `-umask=000`. This causes the container to fail to initialize due to `permission denied` on the folder.
> Note: Tested in my homelab and working as expected
=> Use provided umask on mount

weed/server/volume_server.go, weed/storage/disk_location.go, weed/storage/needle_map.go, weed/storage/store.go, weed/storage/volume.go, weed/storage/volume_loading.go, weed/storage/volume_read_write.go
NeedleMapType and NeedleMapKind co-exists in the code. Refer to the golang naming convention, NeedleMapKind is better than NeedleMapType as in the reflect.Kind comments:
```go
// A Kind represents the specific kind of type that a Type represents.
// The zero Kind is not a valid kind.
type Kind uint
```
=> renaming NeedleMapType to NeedleMapKind

k8s/README.md, k8s/seaweedfs/templates/seaweedfs-s3-secret.yaml
add missing s3 auth secret (if enabling s3 auth)
updated README to be more k8s newbie-friendly.
=> README and s3 auth

weed/command/scaffold.go, weed/filer/mysql/mysql_sql_gen.go, weed/filer/mysql/mysql_store.go, weed/filer/mysql2/mysql2_store.go, weed/filer/postgres/postgres_sql_gen.go, weed/filer/postgres/postgres_store.go, weed/filer/postgres2/postgres2_store.go
add escape (quote identifiers) for the dynamic SQL
so tables (collections) with special characters will work.
PostgreSQL uses the double quote "
mysql uses backtick `
=> postgres2 & mysql2

weed/command/scaffold.go, weed/filer/postgres/postgres_store.go, weed/filer/postgres2/postgres2_store.go
adding SetConnMaxLifetime configuration (https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime)
to enable refresh of stale connections.
=> better postgresql connection pool management

docker/Dockerfile
This way you can do not only
```
docker buildx build -t seaweedfs --platform=linux/arm,linux/arm64,linux/amd64 . --push
```
but also
```
docker buildx build -t seaweedfs:dev --build-arg RELEASE=dev --platform=linux/arm,linux/arm64,linux/amd64 . --push
```
=> Add build arg to choose dev or stable release

weed/server/master_grpc_server_volume.go, weed/topology/volume_layout.go, weed/topology/volume_location_list.go
Currently the file size of only one volume location is taken into
account in the stats. This commit multiplies the disk usages by the
amount of nodes holding a replica of the volume.
This will yield the expected amount of disk usage and matches the
total size calculations from before.
=> Show the real disk usage in stats calls

weed/topology/data_node_ec.go
This fixes the calculation of the amount of EC shards a node holds.
Previously a global counter was increased, but also used inside the
loop to apply disk usage deltas. This led to wrong absolute numbers.
The fix is to apply only deltas of single EC shards per iteration.
=> Fix EC shard count logic

weed/storage/store.go
If all volumes in one collection are expired and deleted at once, collection stats won't update until restart or new volume created.
Not a perfect fix if following `deleteVolumeById` goes wrong, stats could be inaccurate anyway.
=> fix: collection stats won't update if all volumes expired at once

weed/s3api/s3api_object_handlers.go, weed/server/filer_server_handlers_read.go
- `s3api`: passthrough 304 response code from filer, even if `Content-Lenght` is not present
this bug was leading to 404 responses when passing expired If-Modified-Since   
- `filer`: return 304 when `If-Modified-Since` **equal** `Last-Modified`, not only "later"
as browser saves the time that server returns (using Last-Modified) and uses it with If-Modified-Since on next call
(note that `volume` handler already behaves this way: https://github.com/chrislusf/seaweedfs/blob/master/weed/server/volume_server_handlers_read.go#L115 )
=> Fix If-Modified-Since behavior

weed/util/compression.go
RAR archives might not have .rar extension, see [Wikipedia](https://en.wikipedia.org/wiki/RAR_(file_format))
=> Detect rar archives by mime type

weed/filer/reader_at.go, weed/filer/reader_at_test.go, weed/util/chunk_cache/chunk_cache.go, weed/util/chunk_cache/chunk_cache_in_memory.go, weed/util/chunk_cache/chunk_cache_on_disk.go, weed/util/chunk_cache/on_disk_cache_layer.go
Very lightly tested, but for me this improved read time for a 1.4G file through FUSE from 4m to 9s. It looks like each FUSE read request winds up creating a new `ChunkReadAt`, which means that loading the entire chunk into memory is just thrashing GC, because it gets discarded after every read request.
=> make reader_at handle random reads more efficiently for FUSE

weed/server/volume_grpc_vacuum.go, weed/storage/store_vacuum.go
When delete volume during compact, something like this could happen:
1. `CommitCompactVolume` is done
2. `DeleteVolume` triggered right after commit, holds `volumesLock`
3. `GetVolume` RLock() waits for `volumesLock` Unlock(), after that it returns nil
4. `IsReadOnly` panic for nil pointer dereference
=> fix concurrent vacuum & delete panic

other/java/client/src/main/java/seaweedfs/client/SeaweedInputStream.java
When I create SeaweedInputStream on a non-existing file, it returns a NullPointerException. 
In order to avoid that, I have to check if the file exists before creating the stream. So as the check is already done in SeaweedInputStream, I propose to make the SeaweedInputStream return a FileNotFoundException, to avoid a double call to SeaweedFS API.
=> make SeaweedInputStream throw FileNotFoundException

weed/command/command.go, weed/command/fuse.go
It add fuse subcommand that allow use weed as mount type.
It's related with issues: #1323 #1674
=> create fuse subcommand to use weed with mount

weed/command/fuse.go
This PR change way that mount parameters are parsed allowing multi value parameters. Example:
mount -t weed fuse /mnt -o "filer='192.168.0.1:8888,192.168.0.2:8888',filer.path=/"
It is a pending feature from PR #2085.
=> fix parameter multiple values

weed/command/mount_std.go, weed/filesys/dir.go, weed/filesys/wfs.go, weed/filesys/xattr.go
this adds support for `.` and `..` directories in fuse mounts. they properly point to the correct inodes of directories of themselves (`.`) and to their parents (`..`), also for the mount root + parent.
this especially solves some errors on linux. on mac it works already out of the box as either macos or osxfuse apparently adds those directories automatically.
this is tested on macos and linux (debian). i don't know if it makes sense to test this on other platforms too. maybe windows/freebsd?
i am happy to hear your thoughts :)
=> Return artificial . and .. directories

weed/command/upload.go
Follow-up on #2113 . It now functions correctly, but it prints the command's usage upon any error now, which is not that nice. I already found where the problem of this is, but I did not want to change too much with one go.
Feel free to merge it if this printing of the usage does not bother you. Otherwise I can also adapt it a bit more.
=> Return correct exitcode when `wheed upload` fails

weed/shell/shell_liner.go
Check for errors when writing the shell history.
=> Check for history file errors as well

weed/command/scaffold.go, weed/filer/cassandra/cassandra_store.go
See https://pkg.go.dev/github.com/gocql/gocql#hdr-Data_center_awareness_and_query_routing
This changes the default hostselectionpolicy (previously unset, defaults to RR): https://github.com/gocql/gocql/blob/master/cluster.go#L19 (strange since the java driver defaults to token-aware: https://docs.datastax.com/en/developer/java-driver/4.2/manual/core/load_balancing/#token-aware)
This adds a new localDC config option and if it's set, it will fallback to dc-aware RR instead of across the whole cluster.
=> Cassandra: Use TokenAwareHostPolicy with fallback to localDC by default

weed/shell/command_fs_configure.go
should be "locationPrefix" other than "locationPrfix" by command flag's name.
=> fix typo in fs.configure help message text

weed/filer/cassandra/cassandra_store.go
This should nearly always be better
=> cassandra: Use LocalOne instead of One consistency

weed/filer/cassandra/cassandra_store.go
This changes this filer store from eventual to strong consistency at the cost
of read performance.
=> cassandra: use LocalQuorum for all queries

weed/filer/leveldb2/leveldb2_store.go, weed/filer/leveldb3/leveldb3_store.go, weed/filer/rocksdb/rocksdb_store.go
Improve `FindEntry` `CreateEntry` performance
More specifically when uploading a new file, we need to conduct a query for a key most likely does not exist. Using bloom filter could help speed up a lot.
A simple micro benchmark: [leveldb_test.go](https://github.com/qieqieplus/perf/blob/master/kvdb/tests/filter/leveldb_test.go)
=> add bloom filter for filer leveldb/rocksdb

unmaintained/see_meta/see_meta.go
Additional logs are output to match the `volume.fsck -findMissingChunksInFiler` command result.
=> Add the additional meta log

weed/filer/filer.go
Changed default permissions for directory creation. In the existing `0110`, there is no way to read the directory for other users until the file is given read and execute permissions. If it is not an executable file such as an image, it is generally thought that 644 permission is correct.
I think we need to add the umask option to the filer.
=> Change default permissions

weed/util/compression.go, weed/util/compression_stream.go
Every gzip writer alloc about 1 MB/obj when lazily initialized.
A simple test using minio/warp:
`warp put --host 10.100.1.133:8333 --obj.generator=csv --obj.size=4k`
shows 10% overall performance improvement and 90% memory allocation reduced for small compressible files.
=> reduce gzip allocation

.github/workflows/container_latest.yml, .github/workflows/container_release.yml, .github/workflows/container_test.yml
The `crazy-max/ghaction-docker-meta@v2` action was moved to `docker/metadata-action@v3`. Seems to be fully backwards-compatible.
=> chore(ci): move to using newer metadata action

.github/workflows/binary_test.yml, .github/workflows/container_latest.yml, .github/workflows/container_release.yml, .github/workflows/container_test.yml, .github/workflows/go.yml, .github/workflows/release.yml, .github/workflows/release_binaries.yml, .github/workflows/release_test.yml, docker/Dockerfile
Currently, it looks like there aren't any builds for PPC or Z-kernel platforms. The project is also missing multiple arches from the release system.
Below are the missing platforms added as part of this PR:
- `arm64`
- `386`
Below are the missing platforms not added to this PR due to compatibility issues ([see here](https://github.com/chrislusf/seaweedfs/pull/2288/checks?sha=46e78e9b3ef7b3a48553411ff56ef2dcf54ea5b3)):
- `ppc64le`
- `s390x`
This MR allows the team to support future architectures with minimal work if/when they decide to.
Supported Go and Buildx architectures confirmed against:
- https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63#a-list-of-valid-goarch-values
- https://github.com/logband/github-buildx-stats/runs/3448399619?check_suite_focus=true
Changes:
- …
=> feature(cross-platform): add multi-arch support to release

weed/filesys/meta_cache/meta_cache_subscribe.go
I upgraded weed mount from 2.49 and it seems there's a consistency problem. Picture's worth a thousand words: this is `weed server`  with 2 mounts on 2 servers. I ran these commands roughly alternating between these two servers. You can see that the `hi` file seems to be getting clobbered, as if the file length metadata wasn't updating:
With my change it now alternates as expected:
I'm not totally sure why this works, just looked through the commits and this one looked suspicious:  https://github.com/nivekuil/seaweedfs/commit/e6ba2f9c372f8f160003dac63d51b6dde0a512de
=> mount: fix consistency issue, invalidate mount meta cache more aggressively

other/metrics/grafana_seaweedfs.json
Mostly I wanted to fix the s3 dashboard to be contiguous. The first query now uses 
```
sum by (type) (increase(SeaweedFS_s3_request_total{type=~'PUT|COPY|POST|LIST'}[$__range]))*0.000005
```
before
after
In the process I also changed the dashboard default to 3 hours from 30 days, which seems more useful and doesn't incur a big initial load time for the user. I use grafana 8 so it seems some other things changed in the export format.
=> grafana dashboard updates

.github/workflows/binary_test.yml, .github/workflows/cleanup.yml, .github/workflows/container_latest.yml, .github/workflows/container_release.yml, .github/workflows/container_test.yml, .github/workflows/go.yml, .github/workflows/release.yml, .github/workflows/release_binaries.yml
Not sure if you want to do this since it'll clutter the Actions page (it can't seem to recognise job name changes).
What we can do is remove old runs, as described in: https://github.community/t/delete-old-workflow-results/16152/42
I'm happy to add this to the cleanup job in another PR if you wish.
Feel free to reject if you prefer the current naming!
=> fix(ci): use cleaner naming for jobs

.github/workflows/binary_test.yml, .github/workflows/container_latest.yml, .github/workflows/container_test.yml
Further update from #2291, apply the same logic to `latest` images.
Also includes:
- a quick fix to never push to Docker Hub from pull requests on test jobs
- a quick fix to never run the test jobs on anything other than `pull_request`
Test is fine to stay as-is since it's not pushing.
=> fix(ci): update latest to only run once

weed/util/network.go
This allows ipv6 addresses to be found for e.g. volume server IP.  Note that this may be a breaking change if the ipv6 came first in whatever order this is traversed. I think most setups would have the routable interfaces earlier in the iterator order, and any ipv6s are more likely to be routable than ipv4. It also might make sense to have additional checks for interface local/link local as documented here https://pkg.go.dev/net#IP.IsInterfaceLocalMulticast, though this patch at least works for me (pod has a routable ipv6 + a private, node-local ipv4)
=> Detect ipv6 addresses

weed/filer/leveldb/leveldb_store.go
when use `weed mount ` to upload small files to directory which has millions of files.
bloom improve performance obviously from 3 Mbps to 30 Mbps.
perf data after add bloom filter:
```
-   98.37%     0.00%  weed     weed                [.] runtime.goexit                                                                                                    ▒
- runtime.goexit                                                                                                                                                      ▒
- 59.82% github.com/seaweedfs/fuse/fs.(*Server).Serve.func2                                                                                                        ▒
- 59.80% github.com/seaweedfs/fuse/fs.(*Server).Serve.func1 …
```
=> add bloom filter to leveldb_store to improve fuse performance.

weed/filer/leveldb/leveldb_store.go, weed/filer/leveldb2/leveldb2_store.go, weed/filer/leveldb3/leveldb3_store.go
To improve performance of leveldb find key in condition of large directory(millions of files) which use uuid as filename.
#2325
=> CompactionTableSizeMultiplier of leveldb use default value.  #2325

k8s/helm_charts2/templates/filer-servicemonitor.yaml, k8s/helm_charts2/templates/ingress.yaml, k8s/helm_charts2/templates/s3-servicemonitor.yaml, k8s/helm_charts2/templates/volume-servicemonitor.yaml
This PR adds the following features to fix some unwanted behavior:
- The ServiceMonitor resources doesn't get created when `global.monitoring.enabled` isn't set or set to false.
Before users had to install Prometheus even when monitoring was disabled.
- The Ingress resources now get deployed to the right namespace
Before the Ingress resource got deployed to the default namespace.
=> Fixed unwanted behavior of the SeaweedFS helm chart

weed/s3api/auth_credentials.go
Hello! 
I guess I found a potential data race condition with `iam.identities`.
Method `loadS3ApiConfiguration` contains assignment to identities slice which is not safe. Cause it might be read in the same time by other goroutines (server handlers etc). This PR must fix this issue.
=> Fix: potencial iam identities data race

weed/filer/mongodb/mongodb_store.go
Hello!
I made a fix for nil pointer deference panic in *MongodbStore.ListDirectoryEntries method.
When *mongo.Collection.Find returns an error, *mongo.Cursor, which this method also returns, might be nil.
log:
```
Dec 02 12:59:11 mon001 weed[9050]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 02 12:59:11 mon001 weed[9050]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x13f6922]  
Dec 02 12:59:11 mon001 weed[9050]: goroutine 2054744 [running]:  
Dec 02 12:59:11 mon001 weed[9050]: go.mongodb.org/mongo-driver/mongo.(*Cursor).next(0xc0099cfa40, {0x28327c0, 0xc009af8f30}, 0xc0)
Dec 02 12:59:11 mon001 weed[9050]:         /go/pkg/mod/go.mongodb.org/mongo-driver@v1.7.0/mongo/cursor.go:102 +0x22
Dec 02 12:59:11 mon001 weed[9050]: …
```
=> MongodbStore.ListDirectoryEntries panics on Find method failure

README.md, other/metrics/seaweedfs-grafana-dashboard-heartbeat.json
In the current dashboard there is no way to know the status of
volume servers, as prometheus only accepts push information, if
any server volume goes offline, the last information sent will
be read continuously by grafana.
Added a graph that calculates the delta between the information
of the last push timestamp with the timestamp of 15 seconds ago,
if the timestamp has not been changed, server state will be 0,
if volume server sent any information the server state will be 1.
-This graph will have to be modified if the time interval of pushs
is modified, a suggestion for improvement is to send the interval
in seconds along with the metrics.
-Only local tests were run, maybe if the latency between pushgateway
and volume server is too high, the delta calculation could be
affected
.
=> feat: Added a volume heartbeat graph to grafana dashboard

weed/topology/volume_layout.go
Currently, when client request `curl "http://localhost:9333/dir/assign?dataNode=node1"`, master will assign volume randomly. However, it should try to assign volumes in node1.
Origin code will operate random assignment once DataCenter is empty.
=> assign fileId according to Rack and DataNode when DataCenter is empty

weed/command/scaffold/security.toml
... The property is read here: https://github.com/chrislusf/seaweedfs/blob/b70cb3e0b2a75543f0410d4c09f42aa95fcf2ee2/weed/server/volume_server.go#L69 but it was missing from documentation.
If this pull request is accepted, I'll also update the Wiki accordingly :)
=> BUGFIX: add access.ui setting to scaffolded security.toml

weed/filer/filer.go
Use context to break list job when grpc stream canceled by client.
=> filer list entries use context to break job

test/s3/compatibility/.gitignore, test/s3/compatibility/Dockerfile, test/s3/compatibility/README.md, test/s3/compatibility/prepare.sh, test/s3/compatibility/run.sh, test/s3/compatibility/s3tests.conf, weed/command/scaffold/security.toml, weed/s3api/s3api_object_copy_handlers.go, weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_server.go, weed/security/guard.go, weed/security/jwt.go, weed/server/filer_server.go, weed/server/filer_server_handlers.go, weed/server/master_grpc_server_volume.go, weed/server/master_server_handlers.go, weed/server/volume_server_handlers.go, weed/util/http_util.go
- one JWT for reading and one for writing, analogous to how the JWT
between Master and Volume Server works
- I did not implement IP `whiteList` parameter on the filer
Additionally, because http_util.DownloadFile now sets the JWT,
the `download` command should now work when `jwt.signing.read` is
configured. By looking at the code, I think this case did not work
before.
Page `Amazon-S3-API`:
```
You can use mTLS for the gRPC connection between S3-API-Proxy and the filer, as
explained in [Security-Configuration](Security-Configuration) -
controlled by the `grpc.*` configuration in `security.toml`.
Starting with version XX, it is also possible to authenticate the HTTP
operations between the S3-API-Proxy and the Filer (especially
uploading new files). This is configured by setting …
```
=>  FEATURE: add JWT to HTTP endpoints of Filer and use them in S3 Client 

weed/command/filer_copy.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1d58247]
goroutine 7482 [running]:
github.com/chrislusf/seaweedfs/weed/command.(*FileCopyWorker).uploadFileInChunks.func1(0x2)
/go/src/github.com/chrislusf/seaweedfs/weed/command/filer_copy.go:488 +0x2a7
created by github.com/chrislusf/seaweedfs/weed/command.(*FileCopyWorker).uploadFileInChunks
/go/src/github.com/chrislusf/seaweedfs/weed/command/filer_copy.go:455 +0x225
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1d58247]
goroutine 7480 [running]:
github.com/chrislusf/seaweedfs/weed/command.(*FileCopyWorker).uploadFileInChunks.func1(0x0) …
=> filer.copy: don't crash when volume creation fails

weed/filer/reader_at.go, weed/filer/stream.go
Padding zero for sparse file in web API like that in [FUSE](https://github.com/chrislusf/seaweedfs/blob/fe5b9e39cc5a3526a0fdadf8b518b67b02d5451b/weed/filer/reader_at.go#L132).
=> bugfix: padding zero for sparse file in web API

weed/command/scaffold/filer.toml, weed/filer/cassandra/cassandra_store.go
When filer is under heave perssure , inserting a new data will lead to the following error with default timeout(600ms)  of gocql :
```
filer.go:179] insert entry /buckets/tt77/myobjects115261: insert /buckets/tt77/myobjects115261: gocql: no response received from cassandra within timeout period
```
weed version:2.85
=> add gocql timeout setting

weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_bucket_skip_handlers.go, weed/s3api/s3api_server.go, weed/s3api/s3api_xsd_generated.go, weed/s3api/s3err/s3-error.go, weed/s3api/s3err/s3api_errors.go
weed/s3api: added new bucket handlers for more compatibility with AWS S3 Protocol
Otherwise any requests to the underlying handlers results in calls to
ListObjects (v1) that may intensively load gateway and volume servers.
Added the following handlers with default responses:
- GetBucketLocation
- GetBucketRequestPayment
Added the following handlers with NotFound and NotImplemented responses:
- PutBucketAcl
- GetBucketPolicy
- PutBucketPolicy
- DeleteBucketPolicy
- GetBucketCors
- PutBucketCors
- DeleteBucketCors
=> Added new bucket handlers for more compatibility with AWS S3 Protocol

weed/s3api/s3api_server.go
weed/s3api: rearrange s3 methods handlers to ensure correct methods requesting
Otherwise current calls for some methods (i.e. GetObjectAcl) ends up with wrong method selection (i.e. GetObject).
Added generic comment rule of traversing methods
=> Rearrange S3 API methods handlers traversal

weed/s3api/s3api_object_handlers.go, weed/s3api/s3err/s3api_errors.go
weed/s3api/s3err/s3api_errors.go
When user try to copy some file into another file, he received only "500 Internal server error". This error not informative.
Add error - "ErrExistingObjectIsFile", when user try to copy file into file, he receive "409 Existing object is a file"
=> add s3api error for copy in file, not directory

weed/filer/leveldb/leveldb_store_test.go, weed/filer/leveldb2/leveldb2_store_test.go, weed/filer/leveldb3/leveldb3_store_test.go, weed/filer/rocksdb/rocksdb_store_test.go, weed/storage/volume_vacuum_test.go, weed/storage/volume_write_test.go, weed/util/chunk_cache/chunk_cache_on_disk_test.go
A small testing enhancement here.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
=> test: use `T.TempDir` to create temporary test directory

weed/command/master.go, weed/command/server.go, weed/server/raft_server.go
Election timeout is fixed at 10 seconds. This means that when the leader dies, it takes 10 to 20 seconds to elect a new leader.
That may be too long for some people.  If the network between masters is good, I think a short election timeout is appropriate.
Make heartbeat interval and election timeout of masters configurable. Therefore, we can configure them according to our actual situation.
Specified on the command line, e.g.:
```shell
weed server --master.electionTimeout=3s --master.heartbeatInterval=300ms
```
Or specified in the configuration file, e.g:
```
master.electionTimeout=3s
master.heartbeatInterval=300ms
```
=> Make heartbeat interval and election timeout of masters configurable.

weed/shell/command_volume_fsck.go
With your helpful feedback from #2605 , I added/fixed the option to delete missing files volumes<->in filer to volume.fsck. It does successfully get rid of the errors that volume.fsck can catch.
What wasn't implemented from the ideas in #2605 is an option to write lists of affected files for weed external review/consumption.
PS: I had to drop a small functionality that dropped a whole volume rather than sending filewise deletion requests when all entries were orphaned. It did not really work (haven't fully established the reason, but my guess was that not all additional replicas on all volume servers were removed). However "only" doing the usual filewise deletion seems fast enough and has to be used for 1+ files anyhow, so I went with just that.
=> Added basic deletion capabilities to fsck.

weed/server/filer_server_handlers_read.go
Currently, we can get all entries under a directory by [List files under a directory](https://github.com/chrislusf/seaweedfs/wiki/Filer-Server-API#list-files-under-a-directory):
```bash
curl -H "Accept: application/json" "http://localhost:8888/javascript/?pretty=y&lastFileName=jquery-2.1.3.min.js&limit=2"
```
This PR add support to getting the entry of a file by adding "entry" parameter like below:
```bash
> curl 'http://localhost:8888/test01.py?entry&pretty=yes'
{
"FullPath": "/test01.py",
"Mtime": "2022-01-09T19:11:18+08:00",
"Crtime": "2022-01-09T19:11:18+08:00",
"Mode": 432,
"Uid": 1001,
"Gid": 1001,
"Mime": "text/x-python",
"Replication": "",
"Collection": "",
"TtlSec": 0,
"DiskType": "",
"UserName": "",
"GroupNames": null,
"SymlinkTarget": "",
"Md5": "px6as5eP7tF5YcgAv5m60Q==", …
```
=> filer: support get file entry

weed/server/filer_server_handlers_write.go
add "moving entry" to filer web server:
```bash
> curl -X POST 'http://localhost:8888/path/to/dst_file?from=/path/2/src_file&pretty=yes'
```
=> filer_web: support moving entry

weed/server/filer_server_handlers_write_autochunk.go, weed/server/filer_server_handlers_write_upload.go
```bash
> curl -F file=@report.js "http://localhost:8888/javascript/some_file?offset=10"
```
=> filer_http: support uploading file with offset

weed/server/filer_server.go
avoid Filer store is enabled for both leveldb2 and mysql if without config
=> Set default leveldb2 enabled

weed/server/filer_server_handlers_read.go
Some chunks in the metadata is manifest, which is not usable for client to get chunk checksum.
```bash
curl  -H "Accept: application/json" "http://localhost:8888/weed?metadata&resolveManifest=true&pretty=yes"
```
=> filer: support get metadata with resolved manifest chunk

weed/command/filer.go
run with `./weed filer -port=8888 -master=localhost:9333` outputs:
> I0307 22:46:41  8700 filer_server.go:139] default to create filer store dir in ./filerldb2
> I0307 22:46:41  8700 leveldb2_store.go:42] filer store leveldb2 dir: ./filerldb2
> I0307 22:46:41  8700 file_util.go:23] Folder ./filerldb2 Permission: -rwxr-xr-x
> I0307 22:46:41  8700 filer.go:124] existing filer.store.id = 1880000011
> I0307 22:46:41  8700 configuration.go:28] configured filer store to leveldb2
> I0307 22:46:41  8700 filer.go:89] the cluster has 1 filers
> I0307 22:46:41  8700 filer.go:230] Start Seaweed Filer 30GB 2.93  at 192.168.15.128:8888
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1d69ef8]
> 
> goroutine 1 …
=> [bugfix] filer: nil pointer dereference

weed/filer/mysql2/mysql2_store.go
support some databases(such as:[BaikalDB)](https://github.com/baidu/BaikalDB) which not support `IF NOT EXISTS` keyword in the `create table` command.
=> fix:support some databases which not support 'IF NOT EXISTS' keyword.

weed/operation/upload_content.go
Upstream request failed to timeout 60 seconds
At the same time, the volume server by default takes 30 seconds to connect, and taking into account one repetition, 60 seconds is a lot
https://github.com/chrislusf/seaweedfs/issues/2755
=> reduced the timeout for creating a connection from 30 to 10 seconds

weed/command/master.go, weed/command/scaffold/security.toml, weed/command/volume.go, weed/security/tls.go
This adds TLS support to the master server, and mTLS support to both the master and volume server conditional on specifying the correct certificate files in security.toml.  If this is acceptable, I'm happy to also update the necessary documentation.
=> Add mTLS support for both master and volume http server.

weed/filer/filer.go, weed/filer/filer_notify_append.go, weed/filer/leveldb/leveldb_store_test.go, weed/filer/leveldb2/leveldb2_store_test.go, weed/filer/leveldb3/leveldb3_store_test.go, weed/filer/rocksdb/rocksdb_store_test.go, weed/server/filer_grpc_server.go, weed/server/filer_grpc_server_rename.go, weed/server/filer_server_handlers_tagging.go, weed/server/filer_server_handlers_write_autochunk.go, weed/server/filer_server_handlers_write_cipher.go
Mostly,the parent dir has already exists or i can make the parent dir manually in advance.
Use the parameter,i can reduce one `metadata` request on per `upload` request.
=> filer: support uploading file without needEnsureParentDir

.github/workflows/binaries_dev.yml, .github/workflows/binaries_release0.yml, .github/workflows/binaries_release1.yml, .github/workflows/binaries_release2.yml, .github/workflows/binaries_release3.yml, .github/workflows/container_dev.yml, .github/workflows/container_latest.yml, .github/workflows/container_release1.yml, .github/workflows/container_release2.yml, .github/workflows/container_release3.yml, .github/workflows/go.yml
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> Pin actions to a full length commit SHA

weed/server/filer_server_handlers_write_autochunk.go
fix: `curl -F file=@report.js "http://localhost:8888/javascript/some_file?skipCheckParentDir=true`
=> fix-filer: calculation error of the method skipCheckParentDirEntry

weed/s3api/s3api_bucket_handlers.go
according to "https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html"
```
x-amz-id-2: YgIPIfBiKa2bj0KMg95r/0zo3emzU4dzsD4rcKCHQUAdQkf3ShJTOOpXUueF6QKo
x-amz-request-id: 236A8905248E5A01
Date: Wed, 01 Mar  2006 12:00:00 GMT
Location: /colorpictures
Content-Length: 0
Connection: close
Server: AmazonS3
```
=> Add "Location:" in response when creating bucket

weed/server/master_grpc_server.go, weed/topology/topology.go, weed/topology/topology_event_handling.go
how to reproduce the error ; 
1.  start a volume and a master  
2. Add code in the for loop of master_grpc_server.go, the for loop return after some times;   The purpose is to enter the defer func of SendHeartbeat;
3.  debug or time.Sleep in defer func , now restart volume， repeat register to master ;
4.  ms.topo will remove the dataNode , but at the same time volume register in topo ;
5. topo has the dn, but the dn's volumes not removed and sync to filer and master;
6. volume-server heartbeat sync is normal but fiiler and master doesn't know the volumes info ; 
7. so some volumes are lose can't get .
=> fix: master lose some volumes

weed/s3api/filer_multipart.go, weed/s3api/s3api_object_multipart_handlers.go
When initializing multipartUploading , a specified uploadid will be assigned.
But we can still upload part of object successfully if a wrong object name combined with right upload id are specified.
Actually a error should be returned in this situation.
Here is a example response when wrong object name or wrong upload id are specified.
> PUT /bucket1/nnnpp?uploadId=48134035-a1e8-4308-a3b4-872373405e3f&partNumber=1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 193.168.140.103:29000
> Accept: */*
> Date: Fri, 08 Apr 2022 09:12:59 +0000
> Authorization: AWS 1VL1TGB3NMTB6DKQBSN8:xwuT9u22zjzuz+Qi9sHROj231/A=
> Content-Length: 176
> Expect: 100-continue
>
< HTTP/1.1 404 Not Found
< Accept-Ranges: bytes
< Content-Length: 349
< Content-Type: application/xml
< Server: SeaweedFS S3
< X-Amz-Request-Id: …
=> check object name and uploadID when processing  multiupload

weed/shell/command_fs_configure.go, weed/shell/command_volume_vacuum.go
This PR corrects abnormal output with `volume.vacuum -h` and `fs.configure -h`.
For `volume.vacuum -h`, the PR changes its output from:
```
> volume.vacuum -h
Usage of volume.vacuum:
-collection string
vacuum this collection
-garbageThreshold float
vacuum when garbage is more than this limit (default 0.3)
-volumeId uint
the volume id
error: flag: help requested
```
to:
```
> volume.vacuum -h
Usage of volume.vacuum:
-collection string
vacuum this collection
-garbageThreshold float
vacuum when garbage is more than this limit (default 0.3)
-volumeId uint
the volume id
```
For `fs.configure -h`, the PR changes its output from:
```
> fs.configure -h
Usage of fs.configure:
-apply
update and apply filer configuration
-collection string
assign writes to this collection
-dataCenter string
assign …
```
=> fix return value

weed/s3api/http/header.go, weed/s3api/s3api_object_copy_handlers.go, weed/s3api/s3api_object_copy_handlers_test.go
by adding processing of metadata and tagging in s3 api CopyObject (judging whether to copy or overwrite according to the directive header)
=> fix the problem of metadata and tagging loss when files are copied

k8s/helm_charts2/templates/s3-deployment.yaml
Remove `deployments.spec.serviceName` from the s3 deployment template.
`serviceName` isn't a valid field and causes issues when deploying the
chart.
This is the full output for `kubectl explain deployments.spec`
```
KIND:     Deployment
VERSION:  apps/v1
RESOURCE: spec <Object>
DESCRIPTION:
Specification of the desired behavior of the Deployment.
DeploymentSpec is the specification of the desired behavior of the
Deployment.
FIELDS:
minReadySeconds      <integer>
Minimum number of seconds for which a newly created pod should be ready
without any of its container crashing, for it to be considered available.
Defaults to 0 (pod will be considered available as soon as it is ready)
paused       <boolean>
Indicates that the deployment is paused.
progressDeadlineSeconds      <integer>
The maximum …
```
=> fix: Remove invalid serviceName from s3-deployments template.

weed/mount/meta_cache/meta_cache_init.go, weed/mount/weedfs_dir_read.go
See: https://github.com/chrislusf/seaweedfs/issues/3097
1. There seems to be no guarantee that just because we added a `dirEntry` in Fuse, that the caller has to read it. The caller can advance the `input.Offset` as they please. This results in a partial result if we do not respect the offset.
2. The meta_cache async `EnsureVisited` will definitely cause duplicate entries on first cache and can cause undefined application behavior.
3. The meta_cache can cache a directory that had an error from the Filer, thus creating a potential partial cache.
1. We store the previous read as `entryStream`. It is a window that is cleared as the offset advances. (We assume the offset can not go backwards, and if it does, it will trigger a scan from the beginning)
2. The meta_cache async `EnsureVisited` …
=> mount: fix partial ReadDir results

weed/filer/filerstore_translate_path.go, weed/filer/filerstore_wrapper.go
Cosmetic spelling fixes on `FilerStorePathTranlator` -> `FilerStorePathTranslator`
=> fix: Minor spelling fixes on FilerStorePathTranlator.

docker/entrypoint.sh
Add the ability to send commands to weed shell from the docker image.
Allows an operator to perform maintenance commands like so:
```
docker run \
--rm \
-e SHELL_FILER=localhost:8888 \
-e SHELL_MASTER=localhost:9333 \
chrislusf/seaweedfs:local \
"shell" \
"fs.configure -locationPrefix=/buckets/foo -volumeGrowthCount=3 -replication=002 -apply"
```
`weed shell` commands aren't accessible from the Docker image currently, this PR adds support for this feature.
Extend existing Docker entrypoints to include `weed shell`
=> feat: Send commands to weed shell from the docker image.

weed/command/mount.go, weed/command/mount_std.go, weed/mount/weedfs.go, weed/mount/weedfs_xattr.go
In some user cases, we need use xattr(user define attr) to achive the logic, and we should disable user_attr to avoid user change it. cases include:
1. store  directory quota or other meta info in xattr 
2. store reference counting in xattr
3. user case don't need xattr
There is no place to disable xattr except change the source code and rebuild. I think this is a indispensable option.
Add mount option to disable xattr.
=> add disableXAttr in mount option

weed/command/filer_sync.go, weed/server/filer_grpc_server_sub_meta.go, weed/stats/metrics.go
For synchronization between clusters, we used filer.sync.
We want to monitor the synchronization of offset .
We may need to subtract these two timestamps to observe synchronization.
Metrics include:
(1) the offset of the filer.sync
(2) the last send timestamp of the filer subscription
(1) I added these two metrics.
(2) Started the metrics server in filer.sync.
(3) Change the format of "clientName".
=> feat(filer.sync): add metricsServer in filer.sync.

weed/command/filer.go, weed/command/server.go, weed/server/filer_server.go, weed/server/filer_server_handlers_read_dir.go, weed/server/filer_ui/filer.html
As #3149 mentioned, show delete directory button is danger. This PR will provide a filer command line parameter to let end user control the delete button show or not. 
Provide `-ui.deleteDir` parameter for filer to control filer UI show or hide the delete button for directory. Default is true so if user want to disable delete directory button just add `-ui.deleteDir=false` parameter when start filer server.
=> Add filer command line parameter to let Filer UI show/hide directory delete button

weed/command/update.go
remove "weed" from UsageLine, or weed will not show usage of weed update
remove "weed" from UsageLine
=> remove "weed" from UsageLine, or weed will not show usage of weed update

weed/filer/filechunk_manifest.go, weed/filer/filechunks.go
When the sub manifest is missing, the reader returns the origin manifest which contains manifest chunks, and the cacher will allocate a lot of memory for sub manifest. 
Returning half processed chunk data instead off raw chunk data, and return error when failed to read sub manifest.
=> fix: invalid chunk data when failed to read manifests

weed/s3api/s3api_object_multipart_handlers.go
https://docs.aws.amazon.com/AmazonS3/latest/API/API_AbortMultipartUpload.html
AbortMultipartUploadHandler should return 204 instead of 200
200->204
=> AbortMultipartUploadHandler should return 204 instead of 200

weed/command/mount.go
Running `weed mount` correctly.
=> weed mount: Fix link to osxfuse github page

weed/topology/topology_vacuum.go
Master server's `timewait` connection increase once every 15 minutes,and more and more every time
Change the grpc streaming mode to false.
=> fix: gc create a lot of connections quickly

weed/storage/disk_location.go
#3238  Volume server doesn't handle errors for GenerateDirUuid method. 
Log errors for GenerateDirUuid method and exit.
```
I0627 21:57:27 82171 file_util.go:23] Folder /var/lib/data-backup/restricted_folder Permission: -rw-------
I0627 21:57:27 82171 disk_location.go:39] Getting uuid of volume directory:/var/lib/data-backup/restricted_folder
F0627 21:57:27 82171 disk_location.go:68] cannot generate uuid of dir /var/lib/data-backup/restricted_folder: failed to read uuid from /var/lib/data-backup/restricted_folder/vol_dir.uuid : open /var/lib/data-backup/restricted_folder/vol_dir.uuid: permission denied
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
D:/codes/github/seaweedfs/weed/glog/glog.go:767 +0x8a …
```
=> fix 3238: handle errors for GenerateDirUuid method

weed/security/tls.go, weed/server/master_grpc_server.go, weed/wdclient/masterclient.go
https://github.com/chrislusf/seaweedfs/issues/2589
discovery dns name set as currentMaster
always set leader for keepconnected for set it as currentMaster
https://github.com/chrislusf/seaweedfs/issues/2589
=> avoid set currentMaster svc.local k8s discovery service domains

weed/server/webdav_server.go
Fixes the issue where files created via WebDAV show as 0-bytes size when read via fuse.
https://github.com/chrislusf/seaweedfs/issues/3217
Set the fileSize Attribute after writing the file, like is done for fuse writes.
None  -  reproduced as described in the issue, issued sync, found file-size and the ms5sum
to be as expected.
=> Fixes WebDAV 0-bytes files

weed/filer/meta_aggregator.go
Avoid synchronizing from scratch due to err
Update lastTsNs even if err exists
=> [Critical] Avoid synchronizing from scratch due to err

weed/shell/command_s3_bucket_quota.go
get bucket quota
output:
```
> s3.bucket.quota -name=bucket1 -op=get
bucket quota :100MiB
```
=> add getting bucket quota

weed/replication/sub/notification_gocdk_pub_sub.go
After a network failure, the queue for the seaweedfs stuck on the rabbitry
durable  - if true, then the queue will save its state and is restored after the server/broker is restarted
https://www.rabbitmq.com/queues.html#durability
=> rabbitpubsub enable durable

weed/filer/read_write.go
After running `s3.configure` in weed shell, we can't see the `/etc/iam/identity.json` entry unless we create directory `/etc/iam` manually.
We solving this problem by setting `SkipCheckParentDirectory` flag to `false`, so the directory where the entry resides will be created automatically.
- [√] I have added unit tests if possible.
- [√] I will add related wiki document changes and link to this PR after merging.
=> close SkipCheckParentDirectory flag

weed/storage/disk_location.go
Loading volumes is very slow when there are billions of objects
increase concurrency workers
=> speeding up loading volumes

weed/filer/s3iam_conf.go, weed/filer/s3iam_conf_test.go, weed/s3api/auth_credentials.go, weed/shell/command_s3_configure.go
Issue #3304 
Check duplicate access key in both [dynamic configuration](https://github.com/chrislusf/seaweedfs/wiki/Amazon-S3-API#dynamic-configuration) and [static configuration](https://github.com/chrislusf/seaweedfs/wiki/Amazon-S3-API#static-configuration).
- [√] I have added unit tests if possible.
- [√] I will add related wiki document changes and link to this PR after merging.
=> Check duplicate access key

weed/s3api/s3api_object_handlers.go
When using a lower version of the s3 client (java), an exception will be thrown if the `ETag` header cannot be read
[File upload should succeed should return `ETag` instead of `Etag`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_ResponseSyntax)
at `/go-1.18.1/src/net/textproto/header.go:39`, header is canonicalized by `textproto.CanonicalMIMEHeaderKey`
replace `w.Header().Set("ETag", etag)` with `w.Header()["ETag"] = []string{etag}`
replace `w.Header().Set("ETag", "\""+etag+"\"")` with `w.Header()["ETag"] = []string{"\"" + etag + "\""}`
=> File upload should succeed should return `ETag` instead of `Etag`

weed/filer/stream.go, weed/wdclient/masterclient.go
https://github.com/chrislusf/seaweedfs/issues/3310
Normally resolve urls at the moment of leader change
Normally resolve urls at the moment of leader change
https://github.com/chrislusf/seaweedfs/issues/3310
- [ok ] I have added unit tests if possible.
=> Use fallback if urls are not found

weed/iamapi/iamapi_management_handlers.go
PutUserPolicy append `Actions` that already existed in user identity. Causing the identity ended with duplicated actions
Add logic to filter our existed actions
=> avoid duplicated actions in PutUserPolicy

unmaintained/diff_volume_servers/diff_volume_servers.go, unmaintained/see_idx/see_idx.go, weed/storage/disk_location.go, weed/storage/erasure_coding/ec_encoder.go, weed/storage/idx/walk.go, weed/storage/needle_map/memdb.go, weed/storage/needle_map_leveldb.go, weed/storage/needle_map_memory.go
Regenerating leveldb index is very slow in case of leveldb is not fresh.
Set milestone for leveldb every 10000 operations.
If need to regerate leveldb index, just start from the milestone instead of the beginning.
The time can be reduced from dozens of minutes to seconds.
Reverse traversing the idx also need to walk all the entries. This methord is not very complated ,but every efficient.
relate to https://github.com/chrislusf/seaweedfs/discussions/3316
=> set milestone for regenerating leveldb index.

k8s/helm_charts2/templates/_helpers.tpl, k8s/helm_charts2/templates/filer-statefulset.yaml, k8s/helm_charts2/templates/master-statefulset.yaml, k8s/helm_charts2/values.yaml
Currently k8s HostPath Volumes are used for the following:
- Filer
- Logs
- Master
- Data
- Log
HostPath Volumes are known to present security risks and has a [warning attached in the k8s documentation](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath).
This PR gives the users the option to use PersistentVolumeClaims in-place of HostPath volumes. This PR follows and extends existing conventions, like the ones used for [volumes](https://github.com/chrislusf/seaweedfs/blob/master/k8s/helm_charts2/templates/volume-statefulset.yaml#L245-L254).
=> feat: k8s PVC Storage for Filer and Master

Makefile, weed/command/filer_backup.go, weed/command/filer_sync.go, weed/command/scaffold/replication.toml, weed/replication/replicator.go
There are buckets of many temporary files that do not need to be synchronized or backup
Add option with exclude directories to sync on filer
=> [filer] sync/backup/replicate exclude directories to sync on filer

weed/iamapi/iamapi_management_handlers.go
PutUserAction should replace an identity's action list. Currently, there is no way to remove an action using IAM API.
Discussion: https://github.com/chrislusf/seaweedfs/discussions/3376
Just replace the identity's action list by the API input
=> PutUserAction should completely replace identity actions

weed/command/master.go, weed/server/raft_server_handlers.go
This adds a `/cluster/healthz` route to the master servers. It returns a status code based on raft that can be used as a health check. This might solve part of #1953.
I made it similar to the `/healthz` route of the volume server api
=> Add healthy indicator for raft status

weed/server/volume_server_handlers.go, weed/server/volume_server_handlers_read.go, weed/server/volume_server_handlers_write.go, weed/stats/metrics_names.go, weed/topology/store_replicate.go
According to the time metrics for requests per volume, the server does not understand how much time it will take to write to disk, and how much to replicate.
https://github.com/seaweedfs/seaweedfs/issues/3369
Added write and replicate types to VolumeServerRequestHistogram metric
https://github.com/seaweedfs/seaweedfs/issues/3369
=> Detailed metrics VolumeServerRequestHistogram for writing to disk and replication

k8s/helm_charts2/templates/_helpers.tpl, k8s/helm_charts2/templates/filer-statefulset.yaml, k8s/helm_charts2/templates/master-statefulset.yaml, k8s/helm_charts2/templates/s3-deployment.yaml, k8s/helm_charts2/templates/volume-statefulset.yaml, k8s/helm_charts2/values.yaml
We want external [Filer-Stores](https://github.com/seaweedfs/seaweedfs/wiki/Filer-Stores) to be installed, and be ready before starting Filer. Otherwise Filer will Crashloop until the external Filer-Stores are ready.
Add support for user-defined [Init Containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/). These Init-Containers can check if the external Filer-Store is ready. 
We are adding init-containers to all components here, so users can use them as needed.
=> feat: Add support for k8s Init-Containers.

weed/command/filer.go, weed/command/server.go, weed/filer/stream.go, weed/server/filer_server.go, weed/server/filer_server_handlers_read.go
related to #3403 
Avoid large file downloads taking up too much io time, causing other requests to execute slowly, resulting in decreased throughput
In the 'weed/filer/stream.go:74' method, slow down the chunk download frequency to ensure that the download speed does not exceed 'downloadSpeedMBps' (filer startup parameter)
=> Add download speed limit support

weed/filer/postgres/postgres_store.go, weed/filer/postgres2/postgres2_store.go
I prefer to use PostgreSQL environment variables (i.e. PGDATABASE) to set connection parameters.
By simply removing "forced/required" parameters for the PostgreSQL connection uri. 
This allows the database driver to use the default option of grabbing the environment variables. The exception is connect_timeout which is hard coded at the moment anyways so I left that alone.
=> Allow postgresql to use standard environment variables for connection

weed/storage/backend/disk_file.go, weed/storage/backend/disk_file_darwin.go, weed/storage/backend/disk_file_linux.go, weed/storage/backend/disk_file_others.go
Restore Sync operation back.
For different system using different method to sync file data:
* For Linux using `fdatasync` make less IO operation (ignore sync metadata)
* For MacOS default is using `fcntl` with `F_BARRIERFSYNC`, this will resolve MacOS with ARM CPU version sync data too slow issue. As golang default implementation,  File.Sync is using `fcntl(fd, F_FULLFSYNC)` call which will flush all file system dirty data to disk and this is very very slow with MacOS running on ARM cpu. Using `F_BARRIERFSYNC` will make ARM CPU version's Mac running fast.
* For other OS just using `File.Sync`
=> Refactor for Sync method

weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_object_handlers_test.go
https://github.com/seaweedfs/seaweedfs/issues/2792
The current implementation does PUT/POST/DELETE requests from s3 API to filer with duplicate slashes in object path (if duplicate slashes were in object path). This leads to 301 Moved Permanently response from filer with `Location` that has duplicate slashes removed. When HTTP client in s3 API does second request to the redirected URL, it changes `PUT` method to `GET`. The workaround cleans the object path from duplicate slashes to prevent 301 redirect.
Tested in `local-dev-compose.yml`, the command sequence is the following:
```
aws --endpoint-url=http://localhost:8333 s3api create-bucket --bucket testbucket
aws --endpoint-url=http://localhost:8333 s3api put-object --bucket testbucket --key testdir//testfile --body ./testfile.obj
aws …
```
=> Remove duplicate slashes in object path to prevent 500 errors

weed/command/filer_sync.go
In filer.sync, when initializing the offset, the value of signaturePrefix should be spliced ​​with the path.
Otherwise, each initialization will only read the offset of the root path.
Offset is path dependent, splicing the path as the value of signaturePrefix.
```
initOffsetError := initOffsetFromTsMs(grpcDialOption, filerB, aFilerSignature, *syncOptions.bFromTsMs)
// Replace with:
initOffsetError := initOffsetFromTsMs(grpcDialOption, filerB, aFilerSignature, *syncOptions.bFromTsMs, getSignaturePrefixByPath(*syncOptions.aPath));
```
=> fix(filer.sync): initializing the offset is related to the path

weed/filer/filer_notify_test.go
fix println
fix redundant type from array
=> fix redundant type from array

weed/mount/weedfs.go, weed/mount/wfs_filer_client.go
When multiple filer requests are in-flight and the current filer disappears and a new one is selected by the first goroutine, then there can be a lot of race conditions while retrieving the current filer.
Load/save the current filer index atomically.
Turn off the current filer with many requests in-flight.
=> Avoid race conditions with current filer address

weed/mount/filehandle_read.go, weed/mount/weedfs_file_copy_range.go, weed/mount/weedfs_file_read.go, weed/mount/weedfs_unsupported.go
This is a FUSE implementation of the `copy_file_range` syscall.
See the man page for more information: https://man7.org/linux/man-pages/man2/copy_file_range.2.html
With a modified piece of C code taken from the man page. Find it below for reference.
Usage: `copy_file_range <source> <destination> [<src-offset> [<dst-offset> [<len>]]]`
```
#define _GNU_SOURCE
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>
int main(int argc, char *argv[])
{
int fd_in, fd_out;
struct stat stat;
off64_t len, ret;
off64_t *src_offset = NULL;
off64_t *dst_offset = NULL;
if (argc < 3) {
fprintf(stderr, "Usage: %s <source> <destination> [<src-offset> [<dst-offset> [<len>]]]\n", argv[0]);
exit(EXIT_FAILURE);
}
fd_in = open(argv[1], O_RDONLY);
if (fd_in == -1) { …
```
=> Implement copy_file_range syscall in FUSE

weed/storage/needle_map_memory.go
They all equal to the entry count in .idx file.
related to commit https://github.com/seaweedfs/seaweedfs/commit/c7892bc7c4a5df48cc1db946243573b3ded3d711
=> the statistical methord for fileCount should stay same

weed/mount/weedfs_file_copy_range.go, weed/mount/weedfs_file_read.go
Reuse the readDataByFileHandle method in Read calls as well.
=> Reuse readDataByFileHandle in Read call

weed/s3api/s3api_server.go
awsjs sdk needs to send a preflight request first, and these 4 headers are required。
=> fix:Handle preflight cors requests

weed/shell/commands.go
TestCommandEcBalanceSmall Unit test fails when CommandEnv is nil
`weed/shell/command_ec_test.go:31`
`balanceEcVolumes(nil, "c1", allEcNodes, racks, false)`
=> fix: TestCommandEcBalanceSmall Unit test fails when CommandEnv is nil

weed/mount/weedfs_file_lseek.go, weed/mount/weedfs_unsupported.go
This is a FUSE implementation of the `lseek` syscall.
See the man page for more information: https://man7.org/linux/man-pages/man2/lseek.2.html
With some C code and strace. Find it below for reference.
Usage: `lseek <file> <offset> <whence>`
```
#define _GNU_SOURCE
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>
int main(int argc, char *argv[])
{
int fd, whence;
struct stat stat;
off64_t offset, len, ret;
if (argc < 4) {
fprintf(stderr, "Usage: %s <file> <offset> <whence>\n", argv[0]);
exit(EXIT_FAILURE);
}
fd = open(argv[1], O_RDONLY);
if (fd == -1) {
perror("open (argv[1])");
exit(EXIT_FAILURE);
}
if (fstat(fd, &stat) == -1) {
perror("fstat");
exit(EXIT_FAILURE);
}
len = stat.st_size;
offset = atoi(argv[2]);
whence = atoi(argv[3]);
ret …
```
=> Implement lseek syscall in FUSE

weed/storage/needle_map_metric.go
https://github.com/seaweedfs/seaweedfs/pull/3388#discussion_r951292287
If size is invalid, then this file is marked deleted.
However multipal deleted files is also counted.
=> fix deletecount bug

weed/s3api/s3api_object_handlers.go, weed/server/filer_server_handlers_read.go
https://github.com/seaweedfs/seaweedfs/issues/3457
```
aws --endpoint-url http://127.0.0.1:8333 s3api put-object --bucket one --key bla/
MacBook-Pro-Lebedev:docker lebedev_k$ curl -I http://127.0.0.1:8333/one/bla/
Date: Tue, 23 Aug 2022 14:12:21 GMT
Server: SeaweedFS Filer 30GB 3.23
X-Seaweedfs-Is-Directory-Key: true
```
Must be
```
aws --endpoint-url http://127.0.0.1:8333 s3api put-object --bucket one --key bla/
curl -I http://127.0.0.1:8333/one/bla
Accept-Ranges: bytes
Access-Control-Expose-Headers: Content-Disposition
Content-Disposition: inline; filename="bla"
Content-Length: 0
Content-Type: httpd/unix-directory
Date: Tue, 23 Aug 2022 09:24:22 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e-0"
Last-Modified: Tue, 23 Aug 2022 09:24:18 GMT
Server: SeaweedFS …
```
=> s3: report metadata if the directory is explicitly created 

weed/command/master.go, weed/server/master_grpc_server_raft.go, weed/server/master_server.go, weed/server/master_server_handlers_ui.go, weed/topology/topology.go
When starting up the raft server and setting the instance in `Topology.RaftServer` / `Topology.HashicorpRaft` there are race conditions because other goroutines already try to access the reference, which is `nil` in the beginning.
Add an RWMutex to synchronize access.
=> Add raft server access mutex to avoid races

weed/filer/reader_cache.go, weed/server/filer_server_handlers.go, weed/server/volume_server_handlers.go
Fix race conditions during in-flight size checks. Therefore, it should be more accurate now.
Atomically checking for sizes.
Upload and download bigger chunks of data in parallel, for example like this:
`echo {1..100} | xargs -P100 -n1 sh -c 'dd if=/dev/zero bs=1m count=1 2>/dev/null | tee mount/patrick2 | tee mount/patrick3 | tee mount/patrick4 | tee mount/patrick5 >/dev/null'; md5sum <(cat mount/patrick2) <(cat mount/patrick3) <(cat mount/patrick4) <(cat mount/patrick5)`
=> Fix race conditions during in-flight size checks

weed/filer/reader_cache.go, weed/filer/reader_pattern.go, weed/mount/filehandle.go, weed/mount/filehandle_map.go, weed/mount/weedfs.go, weed/mount/weedfs_dir_lookup.go
Fix a few data races when reading files in mount, especially with concurrent operations.
Employ locks and atomic operations to update states.
=> Fix a few data races when reading files in mount

weed/server/filer_ui/filer.html
Fix issue #3518 
Do not reload page before all file uploaded.
Test manually, upload many files include big and small files.
=> Fix reload page before all file uploaded bug

weed/mount/filehandle.go
Fix corrupted mount reads after changes on fh. See #3535.
When a file is opened multiple times - no matter if single- or multi-threaded - and something was written, or a metadata attribute was changed, then the following reads would always return wrong / old data until all file handles were closed and the file was reopened.
The reason was that the outdated reader was not reset properly with a fresh chunk view.
The fix is to reset the reader instance on file handles properly.
With `dt` tool. See #3535.
=> Fix corrupted mount reads after changes on fh

.github/workflows/codeql.yml, .github/workflows/e2e.yml, docker/Dockerfile.e2e, docker/Makefile, docker/compose/e2e-mount.yml, weed/mount/filehandle.go, weed/mount/weedfs_file_read.go
There are no End-to-End tests for mount.
Implement a rudimentary Ent-to-End workflow that load- and integrity-tests a real FUSE mount using FIO.
The workflow can later be extended with other tests like S3 or WebDAV.
I left a TODO comment in one of the steps. We can later make the tests fail if data races were detected by go. Possibly after all the known ones got fixed.
Also found and fixed a bug while adding the tests.
The PR implements the tests.
=> Add an End-to-End workflow for FUSE mount

weed/shell/command_volume_tier_move.go
Often when moving from tiers the replication setting will need to be changed. 
Instead of manually searching for the transferred volumes on the new tiered storage, this will allow user to automatically perform the action with the volume.tier.move operation.
Regression test; new feature tests
- [ N/A ] I have added unit tests if possible.
=> Added ability to change replication settings upon volume.tier.move

weed/server/filer_server_handlers_read.go
After connecting `prometheus` to `weedfs`, the filer outputs a large number of logs of `no entry is found in filer store`. The http status code is already 404, I think the log level can be appropriately lowered
The log level we set online is `1`
Turn down the 404 log level
=> Turn down the 404 log level

weed/filer/arangodb/arangodb_store.go
Transactions currently fail in arangodb filer store, as the underlying driver needs a context key in order for its queries to know that they should be included in the transaction. (they are performed, however they time out) 
the underlying driver package does not provide a reliable method to extract the transaction id from the context, and so I am not removing the existing context key that is being added, it will be required for commit, rollback etc.
add the transaction id to the context using driver.WithTransactionID
=> Correctly pass arangodb driver Transaction ID into the context 

weed/filer/arangodb/arangodb_store_bucket.go, weed/filer/arangodb/helpers.go
The collection cache for buckets was not deleting from map, whilst also setting itself as a nil pointer, causing crash.
both delete the bucket from the collection cache when bucket is deleted, and also do not return a nil collection from the collection cache.
=> Fix crash in arangodb filer when attempting to access a deleted bucket

weed/filer/filer_deletion.go
As the storage of the `docker registry`, a lot of delete requests will be sent, and there are too many such logs output by the filer.
=> adjust log level

weed/notification/gocdk_pub_sub/gocdk_pub_sub.go, weed/server/filer_server_handlers_write_autochunk.go
seaweedfs log:
```
I0905 12:36:55.227469 common.go:70 response method:PUT URL:/buckets/search/.uploads/85786be95d5a8fe31afe7d42330efd7ed325cb0e/0006.part with httpStatus:500 and JSON:{"error":"unexpected EOF"}
```
ingress nginx log:
```
requestMethod | PUT
-- | --
requestSize | 5243529
requestUrl | search.s3-proxy.query.consul-test/categorizer/latest?uploadId=85786be95d5a8fe31afe7d42330efd7ed325cb0e&partNumber=6
responseSize | 0
status | 499
stream | stdout
ts | Sep 5, 2022 @ 17:36:55.000
upstreamAddr | 172.24.185.150:8080
upstreamStatus | -
userAgent | Botocore/1.20.106 Python/3.10.5 Darwin/21.3.0
```
replace internal error code(500) to client closed request code(499)
=> [s3] Replace code 500 to 499 for upload with ErrUnexpectedEOF

weed/shell/command_volume_check_disk.go
run `volume.check.disk -v -force` and catch error with very big message of diskInfos
```
sync volume 2473 on fast-volume-0:8080 and fast-volume-2:8080: doVolumeCheckDisk source:id:"fast-volume-0:8080"  diskInfos:{
.. lot of lines
```
print only dataNode.Id
=> do not print diskInfos with doVolumeCheckDisk in error log

weed/wdclient/masterclient.go, weed/wdclient/vid_map.go, weed/wdclient/vid_map_test.go
```go
type MasterClient struct {
vidMap
......
}
```
Since the vidMap of the masterClient is not a pointer type, and the receiver of the GetLocation method is a pointer type, during the leader switching process, after calling `resetVidMap`, the vidMap of the masterClient changes, in the GetLocation method `defer vc.RUnlock()` The vc used is the new vidMap, causing `fatal error: sync: RUnlock of unlocked RWMutex`
```txt
=== RUN   TestConcurrentGetLocations
fatal error: sync: RUnlock of unlocked RWMutex
goroutine 57 [running]:
runtime.throw({0x105339556?, 0x10531b8d4?})
/Users/lhhdz/wd/soft/go-1.18.1/src/runtime/panic.go:992 +0x50 fp=0x14000412dd0 sp=0x14000412da0 pc=0x104d3be00
sync.throw({0x105339556?, 0x100010000?})
/Users/lhhdz/wd/soft/go-1.18.1/src/runtime/panic.go:978 +0x24 …
```
=> fix bug due to data racing on VidMap

weed/server/volume_server_handlers.go
Deadlock when exception of `request cancelled from ` is thrown
1. unlock
2. Response `500`, can let the `filer` retry to the next volume
=> fix: volume Deadlock when exception is thrown

weed/server/master_grpc_server.go
The heartbeat will connect to the first mservers node when the volume is started, and should not process volume-related changes when it is not the leader.
As shown above, after a volume node restarts, the log of the first mserver is very difficult to understand
Plus isLeader's judgment
=> fix: volume heartbeat processing error

weed/server/master_grpc_server.go
A `null pointer` appears when `dn` is nil
test code.
=> fix:Sometimes a nil pointer exception is thrown

weed/mount/inode_to_path.go
Signed-off-by: fuweiwei <fuweiwei@virtaitech.com>
In weed_mount, during file lookup, it will try to allocate a new inode for a new file.
Upon inode conflicts, it will allocate the next inode number. But it will actually allocate the "n+2" inode number, and further allocation will still allocate the "n+2" number, leading to inode conflicts.
=> mount: fix new inode allocation

README.md
Various readme hashlinks not functional
Adding missing links and downcasing the links that were incorrectly cased.
N/A
There is an opinionated change in here, the sections seemed to run together when rendered, so I updated parents to use `#` instead of the same `##` as their children to differentiate sections. If this is not wanted, let me know and can revert back...
Best,
Ryan
=> docs: functional readme hashlinks

weed/command/filer_copy.go
```bash
grep -r concurrenct
weed/command/filer_copy.go:	concurrenctFiles  *int
weed/command/filer_copy.go:	concurrenctChunks *int
weed/command/filer_copy.go:	copy.concurrenctFiles = cmdFilerCopy.Flag.Int("c", 8, "concurrent file copy goroutines")
weed/command/filer_copy.go:	copy.concurrenctChunks = cmdFilerCopy.Flag.Int("concurrentChunks", 8, "concurrent chunk copy goroutines for each file")
weed/command/filer_copy.go:	fileCopyTaskChan := make(chan FileCopyTask, *copy.concurrenctFiles)
weed/command/filer_copy.go:	for i := 0; i < *copy.concurrenctFiles; i++ {
weed/command/filer_copy.go:	concurrentChunks := make(chan struct{}, *worker.options.concurrenctChunks)
```
`concurrenctFiles` -> `concurrentFiles`
`concurrenctChunks` -> …
=> refactor: `concurrentFiles` and `concurrentChunks` var name fix

weed/command/filer_sync.go
Just improving readability.
```bash
grep -r Concurrcy
filer_sync.go:	DefaultConcurrcyLimit = 32
filer_sync.go:	syncOptions.concurrency = cmdFilerSynchronize.Flag.Int("concurrency", DefaultConcurrcyLimit, "The maximum number of files that will be synced concurrently.")
filer_sync.go:		glog.Warningf("invalid concurrency value, using default: %d", DefaultConcurrcyLimit)
filer_sync.go:		concurrency = DefaultConcurrcyLimit
```
`DefaultConcurrcyLimit` -> `DefaultConcurrencyLimit`
Checked to ensure no more dangling references... `grep -ri Concurrcy` .. no more results.
=> refactor: `DefaultConcurrencyLimit` var rename

weed/wdclient/net2/managed_connection.go, weed/wdclient/resource_pool/managed_handle.go
```bash
grep -r indictes
wdclient/resource_pool/managed_handle.go:	// This indictes a user is done with the handle and releases the handle
wdclient/net2/managed_connection.go:	// This indictes a user is done with the connection and releases the
```
`indictes` -> `indicates`
Feel free to let me know if you prefer these small, specific PR's, or would rather me lump comment readability things into a more signficant PR.
Best,
Ryan
=> docs: `indicates` readability comment fix

weed/command/s3.go
'localFilerSocket' uninitialized causing nil pointer error when tart s3server standalone
```txt
I0914 17:41:27.582435 s3.go:172 S3 read filer buckets dir: /buckets
I0914 17:41:27.582450 s3.go:179 connected to filer localhost:8888 grpc address localhost:18888
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10279000c]
goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/command.(*S3Options).startS3Server(0x10420c060)
/Users/lhhdz/wd/projects/go/seaweedfs/weed/command/s3.go:197 +0x68c
github.com/seaweedfs/seaweedfs/weed/command.runS3(0x1041ef840, {0x1400004e1d0, 0x0, 0x0})
/Users/lhhdz/wd/projects/go/seaweedfs/weed/command/s3.go:148 +0x9c
main.main() …
```
=> fix 'localFilerSocket' nil pointer

weed/command/update.go
```bash
grep -r orignial
update.go:	updateOpt.name = cmdUpdate.Flag.String("name", name, "name of new weed. On windows, name shouldn't be same to the orignial name.")
update.go:			glog.Fatalf("On windows, name of the new weed shouldn't be same to the orignial name.")
```
`orignial` -> `original`
Chris, you're merging so fast, I'm reading through the code for my own use and will keep sending things I find... 
If it's too many PR's just tell me to stop or slow down :)
=> docs: `orignial` -> `original`

weed/replication/sub/notification_kafka.go
Small refactor on `partition` param
```bash
grep -r parition
weed/replication/sub/notification_kafka.go:func (progress *KafkaProgress) setOffset(parition int32, offset int64) error {
weed/replication/sub/notification_kafka.go:	progress.PartitionOffsets[parition] = offset
```
`parition` -> `partition`
Grep'd to ensure no dangling references
=> refactor(notification_kafka): `parition` -> `partition`

weed/replication/sink/filersink/filer_sink.go
```bash
grep -r replicte
weed/replication/sink/filersink/filer_sink.go:			return true, fmt.Errorf("replicte %s compare chunks error: %v", key, err)
weed/replication/sink/filersink/filer_sink.go:			return true, fmt.Errorf("replicte %s chunks error: %v", key, err)
```
`replicte` -> `replicate`
=> docs: `replicte` -> `replicate`

weed/filer/filer.go, weed/filer/filer_conf.go, weed/iamapi/iamapi_server.go, weed/replication/sink/localsink/local_sink.go, weed/s3api/auth_credentials.go, weed/s3api/auth_credentials_subscribe.go, weed/shell/command_s3_configure.go
Slightly more involved than the others.
```bash
grep -ri Direcotry
shell/command_s3_configure.go:		return filer.ReadEntry(commandEnv.MasterClient, client, filer.IamConfigDirecotry, filer.IamIdentityFile, &buf)
shell/command_s3_configure.go:			return filer.SaveInsideFiler(client, filer.IamConfigDirecotry, filer.IamIdentityFile, buf.Bytes())
replication/sink/localsink/local_sink.go:		glog.V(4).Infof("Create Direcotry key: %s", dir)
iamapi/iamapi_server.go:		if err = filer.ReadEntry(iam.masterClient, client, filer.IamConfigDirecotry, filer.IamIdentityFile, &buf); err != nil {
iamapi/iamapi_server.go:			return filer.SaveInsideFiler(client, filer.IamConfigDirecotry, filer.IamIdentityFile, buf.Bytes())
iamapi/iamapi_server.go:		if err = filer.ReadEntry(iam.masterClient, client, …
```
=> refactor: `Directory` readability

weed/util/queue_unbounded.go
```bash
grep -ri inbount
weed/util/queue_unbounded.go:		inbountLen := len(q.inbound)
weed/util/queue_unbounded.go:		if inbountLen > 0 {
```
`inbountLen` -> `inboundLen` ... case sensitive
grep returns no more `inbount`
=> refactor(queue_unbounded): `inbountLen` -> `inboundLen`

weed/filer/filechunk_manifest.go, weed/mount/dirty_pages_chunked.go, weed/wdclient/exclusive_locks/exclusive_locker.go
Another batch one, around the `interval` variables.
```bash
grep -ri Inteval
.git/COMMIT_EDITMSG:refactor: `saveChunkedFileIntevalToStorage` -> `saveChunkedFileIntervalToStorage`
.git/logs/refs/heads/interval-readability-batch:eff8f71957e5304e5114644a320471eb2a675ef4 5dcce0fa66a503ae27a9a5a16eb2095b2429bcd1 Ryan Russell <git@ryanrussell.org> 1663175974 -0500	commit: refactor: `saveChunkedFileIntevalToStorage` -> `saveChunkedFileIntervalToStorage`
.git/logs/HEAD:eff8f71957e5304e5114644a320471eb2a675ef4 5dcce0fa66a503ae27a9a5a16eb2095b2429bcd1 Ryan Russell <git@ryanrussell.org> 1663175974 -0500	commit: refactor: `saveChunkedFileIntevalToStorage` -> `saveChunkedFileIntervalToStorage`
weed/wdclient/exclusive_locks/exclusive_locker.go:	RenewInteval     = 4 * time.Second …
```
=> refactor(exclusive_locker): `Interval` readability batch of updates

weed/filer/filechunk_manifest.go
```bash
grep -ri Procesed
weed/filer/filechunk_manifest.go:			var localProcesed int
weed/filer/filechunk_manifest.go:				if totalWritten > localProcesed {
weed/filer/filechunk_manifest.go:					toBeSkipped := totalWritten - localProcesed
weed/filer/filechunk_manifest.go:						localProcesed += len(data)
weed/filer/filechunk_manifest.go:					localProcesed += toBeSkipped
weed/filer/filechunk_manifest.go:				localProcesed += len(data)
```
`localProcesed` -> `localProcessed`
`grep -ri Procesed` has no results after updates
=> refactor(filechunk_manifest): `localProcesed` -> `localProcessed`

weed/util/cipher_test.go
`plantext` -> `plaintext`
`plantext` -> `plaintext`
=> refactor(cipher_test): `plantext` -> `plaintext`

weed/shell/command_fs_rm.go
```bash
grep -ri entiries
shell/command_fs_rm.go:	var entiries []string
shell/command_fs_rm.go:			entiries = append(entiries, arg)
shell/command_fs_rm.go:	if len(entiries) < 1 {
shell/command_fs_rm.go:		for _, entry := range entiries {
```
`entiries` -> `entries`
`grep -ri entiries` has no remaining results
=> refactor(command_fs_rm): `entiries` -> `entries`

weed/pb/filer_pb/filer_client.go
```bash
grep -ri Funciton
pb/filer_pb/filer_client.go:type EachEntryFunciton func(entry *Entry, isLast bool) error
pb/filer_pb/filer_client.go:func ReadDirAllEntries(filerClient FilerClient, fullDirPath util.FullPath, prefix string, fn EachEntryFunciton) (err error) {
pb/filer_pb/filer_client.go:func List(filerClient FilerClient, parentDirectoryPath, prefix string, fn EachEntryFunciton, startFrom string, inclusive bool, limit uint32) (err error) {
pb/filer_pb/filer_client.go:func doList(filerClient FilerClient, fullDirPath util.FullPath, prefix string, fn EachEntryFunciton, startFrom string, inclusive bool, limit uint32) (err error) {
pb/filer_pb/filer_client.go:func SeaweedList(client SeaweedFilerClient, parentDirectoryPath, prefix …
```
=> refactor(filer_client): `EachEntryFunciton` -> `EachEntryFunction`

weed/command/filer.go, weed/command/master.go, weed/command/master_follower.go, weed/command/s3.go, weed/util/net_timeout.go
```bash
$ grep -r Listner | wc -l
19
$ grep -ri Listner | wc -l
25
$ grep -r Listner
util/net_timeout.go:func NewListener(addr string, timeout time.Duration) (ipListner net.Listener, err error) {
util/net_timeout.go:	ipListner = &Listener{
util/net_timeout.go:func NewIpAndLocalListeners(host string, port int, timeout time.Duration) (ipListner net.Listener, localListener net.Listener, err error) {
util/net_timeout.go:	ipListner = &Listener{
util/net_timeout.go:			return ipListner, nil, nil
command/s3.go:	s3ApiListener, s3ApiLocalListner, err := util.NewIpAndLocalListeners(*s3opt.bindIp, *s3opt.port, time.Duration(10)*time.Second)
command/s3.go:		if s3ApiLocalListner != nil {
command/s3.go:				if err = httpS.ServeTLS(s3ApiLocalListner, *s3opt.tlsCertificate, *s3opt.tlsPrivateKey); err != …
```
=> refactor(various): `Listner` -> `Listener` readability improvements

weed/filer/redis3/ItemList.go
```bash
grep -ri Incluseive
filer/redis3/ItemList.go:		if !nl.NodeScanIncluseiveAfter(prevNode.Reference(), startFrom, visitNamesFn) {
filer/redis3/ItemList.go:		if !nl.NodeScanIncluseiveAfter(nextNode.Reference(), startFrom, visitNamesFn) {
filer/redis3/ItemList.go:func (nl *ItemList) NodeScanIncluseiveAfter(node *skiplist.SkipListElementReference, startFrom string, visitNamesFn func(name string) bool) bool {
```
`Incluseive` -> `Inclusive`
`grep -ri Incluseive` has no results left
=> refactor(ItemList): `Incluseive` -> `Inclusive`

weed/shell/command_ec_balance.go, weed/shell/command_ec_common.go, weed/shell/command_ec_encode_test.go, weed/shell/command_ec_rebuild.go
```bash
grep -ri Decending
shell/command_ec_encode_test.go:	sortEcNodesByFreeslotsDecending(ecNodes)
shell/command_ec_rebuild.go:		sortEcNodesByFreeslotsDecending(allEcNodes)
shell/command_ec_common.go:func sortEcNodesByFreeslotsDecending(ecNodes []*EcNode) {
shell/command_ec_common.go:	sortEcNodesByFreeslotsDecending(ecNodes)
shell/command_ec_balance.go:	sortEcNodesByFreeslotsDecending(possibleDestinationEcNodes)
```
`Decending` -> `Descending`
`grep -ri Decending` has no results left
=> refactor(shell): `Decending` -> `Descending`

weed/server/volume_grpc_tier_download.go, weed/server/volume_grpc_tier_upload.go
```bash
grep -r suppported
server/volume_grpc_tier_upload.go:		return fmt.Errorf("destination %s not found, suppported: %v", req.DestinationBackendName, keys)
server/volume_grpc_tier_download.go:		return fmt.Errorf("remote storage %s not found from suppported: %v", storageName, keys)
```
`suppported` -> `supported`
`grep -ri suppported` has nothing left
=> refactor(server): `suppported` -> `supported`

weed/server/webdav_server.go
```bash
grep -r modifiled
server/webdav_server.go:	modifiledTime time.Time
server/webdav_server.go:func (fi *FileInfo) ModTime() time.Time { return fi.modifiledTime }
server/webdav_server.go:	fi.modifiledTime = time.Unix(entry.Attributes.Mtime, 0)
server/webdav_server.go:		fi.modifiledTime = time.Now()
server/webdav_server.go:			modifiledTime: time.Unix(entry.Attributes.Mtime, 0),
```
`modifiledTime` -> `modifiedTime`
`grep -ri modifiled` has no results left
=> refactor(webdav_server): `modifiledTime` -> `modifiedTime`

weed/pb/volume_server.proto, weed/pb/volume_server_pb/volume_server.pb.go
```bash
$ grep -r charactoer | wc -l
4
$ grep -ri charactoer | wc -l
8
$ grep -ri charactoer
pb/volume_server_pb/volume_server.pb.go:	QuoteCharactoer      string `protobuf:"bytes,4,opt,name=quote_charactoer,json=quoteCharactoer,proto3" json:"quote_charactoer,omitempty"`                  // Default: "
pb/volume_server_pb/volume_server.pb.go:func (x *QueryRequest_InputSerialization_CSVInput) GetQuoteCharactoer() string {
pb/volume_server_pb/volume_server.pb.go:		return x.QuoteCharactoer
pb/volume_server_pb/volume_server.pb.go:	QuoteCharactoer      string `protobuf:"bytes,4,opt,name=quote_charactoer,json=quoteCharactoer,proto3" json:"quote_charactoer,omitempty"`                  // Default: "
pb/volume_server_pb/volume_server.pb.go:func (x *QueryRequest_OutputSerialization_CSVOutput) …
```
=> refactor(volume_server): `charactoer` -> `character`

weed/shell/command_ec_rebuild.go
```bash
grep -r rebult
shell/command_ec_rebuild.go:		resp, rebultErr := volumeServerClient.VolumeEcShardsRebuild(context.Background(), &volume_server_pb.VolumeEcShardsRebuildRequest{
shell/command_ec_rebuild.go:		if rebultErr == nil {
shell/command_ec_rebuild.go:		return rebultErr
```
`rebultErr` -> `rebuildErr`
`grep -r rebult` has no results left
Calling it a day with this PR. That was really fun, thanks Chris!
=> refactor(command_ec_rebuild): `rebultErr` -> `rebuildErr`

docker/README.md, docker/compose/notification.toml
two one-off readability fixes in `/docker/*`
Completes this folder for typos.
=> docs(docker): readability fixes

weed/mount/meta_cache/cache_config.go, weed/mount/meta_cache/meta_cache_subscribe.go
Final one-off readability issues in the `/mount/meta_cache/` path.
This completes this folder.
=> docs(meta_cache): readability fixes

weed/server/master_grpc_server_cluster.go
```bash
grep -r seleted
weed/server/master_grpc_server_cluster.go:	seletedSet := make(map[pb.ServerAddress]*cluster.ClusterNode)
weed/server/master_grpc_server_cluster.go:		if _, found := seletedSet[nodes[x].Address]; found {
weed/server/master_grpc_server_cluster.go:		seletedSet[nodes[x].Address] = nodes[x]
weed/server/master_grpc_server_cluster.go:	for _, node := range seletedSet {
```
`seletedSet` -> `selectedSet`
`grep -ri seleted` has no remaining results
=> refactor(master_grpc_server_cluster): `seletedSet` -> `selectedSet`

weed/server/raft_hashicorp.go
```bash
grep -ri Speep
weed/server/raft_hashicorp.go:		timeSpeep := time.Duration(float64(c.LeaderLeaseTimeout) * (rand.Float64()*0.25 + 1) * float64(peerIdx))
weed/server/raft_hashicorp.go:		glog.V(0).Infof("Bootstrapping idx: %d sleep: %v new cluster: %+v", peerIdx, timeSpeep, cfg)
weed/server/raft_hashicorp.go:		time.Sleep(timeSpeep)
```
`timeSpeep` -> `timeSleep`
`grep -ri Speep` has no remaining results
=> refactor(raft_hashicorp): `timeSpeep` -> `timeSleep`

weed/server/filer_server_handlers_write.go
mute messages in log:
```
Sep 16, 2022 @ 15:35:26.142 | I0916 10:35:26.141851 common.go:113 error JSON response status 204: filer: no entry is found in filer store | fast-api-6d74b546d7-28466
Sep 16, 2022 @ 15:35:25.828 | I0916 10:35:25.828112 common.go:113 error JSON response status 204: filer: no entry is found in filer store | fast-api-6d74b546d7-28466
Sep 16, 2022 @ 15:35:25.396 | I0916 10:35:25.396755 common.go:113 error JSON response status 204: filer: no entry is found in filer store | fast-api-6d74b546d7-ljrzs
Sep 16, 2022 @ 15:34:18.617 | I0916 10:34:18.617726 common.go:113 error JSON response status 204: filer: no entry is found in filer store | fast-api-6d74b546d7-8xqlv
Sep 16, 2022 @ 15:32:53.717 | I0916 10:32:53.717126 common.go:113 error JSON response status 204: filer: no …
```
=> mute log filer: no entry is found in filer store

weed/shell/command_fs_meta_load.go
If you need to restore a specific bucket or volume file, you have to download all the meta data, and this is very long
Added parameter dirPrefix
```
> fs.meta.load -v=false -dirPrefix=/buckets/scraper/ /data/filer.meta
load /buckets/scraper/1579/3919_scrap
load /buckets/scraper/1579/3919_scrap/51910
total 9 directories, 60 files
/data/filer.meta is loaded.
```
=> fs.meta.load load any dirs with prefix "important"

weed/server/filer_server_handlers.go
This fix is a workaround for this [issue](https://github.com/seaweedfs/seaweedfs/issues/3660), and a fix for this [issue](https://github.com/seaweedfs/seaweedfs/issues/3611).
This is a problem I brought up on Slack earlier this month [here](https://seaweedfs.slack.com/archives/C9MGUC1UG/p1662486508498169).
The Filer currently does not allow cross origin requests. "Access-Control-Allow-Origin" header set to "*" is not enough to enable this functionality:
```go 
if r.Header.Get("Origin") != "" {
w.Header().Set("Access-Control-Allow-Origin", "*")
w.Header().Set("Access-Control-Allow-Credentials", "true")
}
```
This is visible in s3api_server.go where the OPTIONS request handler is writing back FOUR response headers to allow cross origin requests: 
```go …
```
=> Allow CORS on Filer

weed/command/volume.go, weed/server/volume_server.go, weed/storage/store.go, weed/util/grace/signal_handling.go
It is necessary to be able to scan a folder with volume files to add new / restored files from a backup without stopping the service
Added a HUP signal handler that adds new volume files
=> [volume] Add new volumes to HUP(reload) signal

weed/s3api/s3api_account.go, weed/s3api/s3api_server.go
In order to introduce s3 Acl related functions, it is necessary to add an Account structure to manage IAM-User, and use AccountId as the owner of the bucket/object instead of IAM-User (Identity) as the Owner, to ensure that IAM-Users under the same account will not Limited access due to Owner inconsistency
=> s3: add account

weed/s3api/auth_credentials_subscribe.go, weed/s3api/bucket_metadata.go, weed/s3api/bucket_metadata_test.go, weed/s3api/s3_constants/acp_canned_acl.go, weed/s3api/s3_constants/acp_grantee_group.go, weed/s3api/s3_constants/acp_grantee_type.go, weed/s3api/s3_constants/acp_ownership.go, weed/s3api/s3_constants/acp_permisson.go, weed/s3api/s3_constants/extend_key.go, weed/s3api/s3api_server.go, weed/server/filer_server_handlers_write_autochunk.go
Sync bucket info to s3 to lay the foundation for acl functionality
`BucketMetadata` encapsulates bucket-related attributes (resources), such as `Ownership` to control whether to verify ACL permissions, `ACL` or access control list defines which accounts can access bucket-specific functions, etc. (refer to [`Overview of managing access`](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-overview.html))
=> s3: sync bucket info from filer

weed/shell/command_volume_fsck.go, weed/storage/volume_read.go
https://github.com/seaweedfs/seaweedfs/issues/3746
volume fsck code eof
this is because there are deleted file entrys with negative size on the idx file, when we look up meta data it will result in a size mismatch. and will trigger another look up at offset with `offset+int64(MaxPossibleVolumeSize)` which will result in EOF
we can solve this problem by filtering all the deleted files from idx files before we binary search the last modified ts. because the purpose for volume fsck is to identify the isolated files on volume the deleted files should not matter.
I repro the error with negative index
```
root@xxxxxx:/tmp# see_idx -dir=. -volumeId=4
key:2 offset:1 size:271(271 B)
key:3 offset:39 size:193(193 B)
key:5 offset:67 size:4194329(4.00 MiB)
key:f offset:524362 size:1529875(1.46 MiB) …
```
=> ADHOC: filter deleted files from idx file binary search

other/java/client/src/main/java/seaweedfs/client/SeaweedWrite.java
Bitrot during network transfer
Provide `Content-MD5` when uploading chunks so volume server could reject corrupt data
The volume server already support that, and other clients do it.
The change is trivial.
Fixes: https://github.com/seaweedfs/seaweedfs/issues/3760
=> client-java: provide Content-MD5 when uploading chunks

weed/s3api/stats.go
Due to probe-bucket-sign, the number of labels in metrics has become so much that scraping stopped working in 1 minute
Do not create bucket label for metrics on 403 response code
=> avoid increasing the coordinates of metric labels

weed/server/raft_hashicorp.go, weed/stats/metrics.go
hashicorp raft has built-in metrics that are hidden
Configure a prometheus sink as the raft metrics sink
=> configure raft metrics

weed/storage/store.go
Normally you use multiple dirs for data when you have several separate drives for data. When using large HDD's parallel loading may greatly reduce startup time.
This change was tested on machine with 10x 18TB hdd drives. Each drive had approx 2TB data already with approx 2000 volumes / index files. Startup time was reduced exactly 10x times (number of drives) while cpu load was almost same as without parallel loading.
=> Allow parallel volume loading from different dirs during startup.

weed/server/master_grpc_server.go, weed/server/master_grpc_server_admin.go, weed/stats/metrics.go
https://github.com/seaweedfs/seaweedfs/issues/3452
It often happens that when you close the laptop lid, the terminal session before weed shell terminates and the admin lock remains forgotten for a long time
add metric shows who is currently blocking the cluster or not
=> metric shows who is currently blocking the cluster or not

weed/command/fuse.go
In current version, fuse takes "-o" as a parameter, so "o" is in `mountOptions.extraOptions`, it causes `mount` fails silently.
Fixes #3790
Check the "o" option explicitly and ignore it.
It's tested on ubuntu 22.04, and `mount` takes extra options normally.
=> Fix `mount -t weed` with extra options

weed/storage/needle_map/compact_map.go, weed/storage/needle_map/compact_map_perf_test.go, weed/storage/needle_map/compact_map_test.go
when use snowflak gen id ，The following error occurs :
write to local disk: mismatching cookie xxxxxxx
the file write failue
fix the bug of compact_map get error ; when the slot end small than the key return  nil false
add compact get test 
test idx  
[1655451851227025229-502m-single-1_388.idx.zip](https://github.com/seaweedfs/seaweedfs/files/9654785/1655451851227025229-502m-single-1_388.idx.zip)
=> fix: compact_map get error mismatching cokie

weed/storage/backend/disk_file.go
https://github.com/seaweedfs/seaweedfs/commit/52580743b9de1931b149e1df40e27048d99ca3bf
When the memory limit is reached in the virtualization environment (k8s), during the execution of vaccum, an OOM killer may come and unexpectedly kill the container with the volume and break the volum files
To minimize  OOM killer effect, do a forced fsync on every vaccum step
https://github.com/golang/go/issues/26650
=> revert disabling FSync for non Mac

other/java/client/src/main/java/seaweedfs/client/SeaweedInputStream.java
spark read file error  when file large then 2GB
=> fix bug : read error when position after 2147483647

weed/server/volume_grpc_vacuum.go, weed/stats/metrics.go, weed/storage/backend/disk_file.go, weed/storage/disk_location.go, weed/storage/erasure_coding/ec_volume.go, weed/storage/needle_map/memdb.go, weed/storage/volume.go, weed/storage/volume_vacuum.go
I would like to see the regression of the vacuum if it is when updating seaweedfs
https://github.com/seaweedfs/seaweedfs/issues/3837
add vacuum error count and  seconds metrics
=> vacuum metrics and force sync dst files

weed/shell/command_volume_fsck.go
volume.fsck `-findMissingChunksInFiler` was broken due to incorrect collectMtime format
duplicate code
no way to check single collection or volum id after https://github.com/seaweedfs/seaweedfs/issues/3835
=> Volume fsck by volume

weed/shell/command_volume_check_disk.go, weed/shell/command_volume_fsck.go
fix error: findExtraChunksInVolumeServers: purging volume 2823: delete fileId monitoring-thanos:2823,2a7a380095160caa00000000: volume 0 not found on fast-volume-1:8080
option verifyNeedle: It is necessary to be able to verify the integrity of the dat files so that all blobs are recoverable.
To fix a blob in time from a replica or from a backup
=> [volume.fsck] hotfix apply purging and add option verifyNeedle #3860

weed/pb/filer_pb/filer_client_bfs.go, weed/storage/needle_map_sorted_file.go
```
==================
WARNING: DATA RACE
Write at 0x00c0005b3f4f by main goroutine:
github.com/seaweedfs/seaweedfs/weed/pb/filer_pb.TraverseBfs()
/Users/kmlebedev/GolandProjects/seaweedfs/weed/pb/filer_pb/filer_client_bfs.go:42 +0x398
github.com/seaweedfs/seaweedfs/weed/shell.doTraverseBfsAndSaving()
/Users/kmlebedev/GolandProjects/seaweedfs/weed/shell/command_fs_meta_save.go:127 +0x3fd
github.com/seaweedfs/seaweedfs/weed/shell.(*commandVolumeFsck).collectFilerFileIdAndPaths()
/Users/kmlebedev/GolandProjects/seaweedfs/weed/shell/command_volume_fsck.go:200 +0x64b
github.com/seaweedfs/seaweedfs/weed/shell.(*commandVolumeFsck).Do()
/Users/kmlebedev/GolandProjects/seaweedfs/weed/shell/command_volume_fsck.go:164 +0x124a
github.com/seaweedfs/seaweedfs/weed/shell.processEachCmd() …
```
=> avoid data race of TraverseBfs

docker/Makefile, docker/README.md, docker/compose/local-auditlog-compose.yml, docker/compose/local-cluster-compose.yml, docker/compose/local-clusters-compose.yml, docker/compose/local-dev-compose.yml, docker/compose/local-hashicorp-raft-compose.yml, docker/compose/local-k8s-compose.yml, docker/compose/local-minio-gateway-compose.yml, docker/compose/local-mount-compose.yml, docker/compose/local-mount-profile-compose.yml, docker/compose/local-nextcloud-compose.yml, docker/compose/local-registry-compose.yml, docker/compose/local-replicate-compose.yml, docker/compose/local-s3tests-compose.yml, docker/compose/test-etcd-filer.yml, docker/compose/test-ydb-filer.yml, docker/seaweedfs-compose.yml, docker/seaweedfs-dev-compose.yml
- Upgrade from `docker-compose` to `docker compose`
- Upgrade the version in the compose yaml files from 2 -> 3.9
- `README` updates with guide to install/confirm compose v2 is installed
- `Makefile` updates
- `*-compose.yml` update
Confirmed everything still works on Ubuntu 20.04 with this. 
** Not tested on other platforms(No logical reason it should not work other than old docker and/or compose versions) **
You will probably still get a few issues about this from people with older installs. 
Hopefully the additions to the [SeaweedFS Docker README](https://github.com/seaweedfs/seaweedfs/tree/master/docker) are sufficient to guide users to self-help.
Please advise if there are any CI systems that I'm unaware of that will break with this `Makefile` upgrade. 
It works on my system :)
=> refactor(compose)!: upgrade to v2 closes #3699

other/metrics/grafana_seaweedfs_heartbeat.json
The metric seems to have changed from SeaweedFS_filer_ to SeaweedFS_filerStore_.
This commit replaces the refs in the dashboard with the new series name.
I've tested on my local grafana instance, now all the stats from the dashboard are displayed.
=> Corrected the dashboard to use the new series name.

weed/s3api/s3api_object_handlers.go
After we migrated from `ceph s3` to `SeaweedFS`, we found that the metadata key has changed, so we changed the returned key according to the `aws` standard
replace return result
=> fix: set user metadata key to lowercase

weed/s3api/s3api_objects_list_handlers.go
When the subdirectory traversal ends and maxKeys is satisfied, the returned `isTruncated` is wrong, causing the client to not be able to list all the data
The easiest case to reproduce, when `maxkeys` is set to 1, when the first subdirectory traversal ends, the return is an error
The judgment of `isTruncated` should also be added to the `eof` side.
=> fix: isTruncated returns problematic

k8s/helm_charts2/templates/volume-statefulset.yaml
when trying to set `tolerations` in the helm chart's `values.yaml` I received an error
```
Error: YAML parse error on seaweedfs/templates/volume-statefulset.yaml: error converting YAML to JSON: yaml: line 40: did not find expected key
```
the other statefulset templates have correctly intended the `tolerations` but `volume-statefulset.yaml` was incorrect
I am now able to set tolerations in my fork of this helm chart 😄
=> fix volume statefulset helm chart's tolerations

weed/shell/command_volume_check_disk.go, weed/shell/commands.go, weed/storage/needle_map/memdb.go
https://github.com/seaweedfs/seaweedfs/issues/3919
https://github.com/seaweedfs/seaweedfs/issues/3919
=> [voluche.chek.disk] needles older than the cutoff time are not missing yet

weed/shell/command_volume_check_disk.go, weed/shell/command_volume_fsck.go, weed/storage/needle_map/memdb.go, weed/storage/types/needle_id_type.go
When one of the volumes of servers in the replica is taken out for service, requests to delete ID files continue to be processed
Delete file IDs deleted on one of the volume replicas of the server
1. run `make cluster`
2. copy files `for i in {1..100}; do echo $i; done | xargs -I {} -P 10 s3cmd --no-ssl --host=127.0.0.1:8333 put /Users/tochka/Downloads/report.pdf put s3://test/c{}.pdf`
3.  unmount volumes `echo "volume.unmount -node  volume2:8082 -volumeId 1"| weed shell`
4.  delete files `for i in {1..100}; do echo $i; done | xargs -I {} -P 10 s3cmd --no-ssl --host=127.0.0.1:8333 rm s3://test/c{}.pdf`
5.  mount volumes `echo "volume.mount -node  volume2:8082 -volumeId 1"| weed shell`
6.  check disk
```
> volume.check.disk -v
Running in simulation mode. Use "-force" option to apply the …
```
=> [volume.chek.disk] sync of deletions the fix

weed/s3api/s3api_object_handlers.go
If somebody accidentally (or not) form a DeleteMultipleObjects request with empty Key field (like this 
```bash
curl -X POST "localhost:8333/test-bucket?delete=&x-id=DeleteObjects" -d '<?xml version="1.0" encoding="UTF-8"?><Delete xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Object><Key/></Object></Delete>'
```
), then seaweed will delete the whole bucket. Depending on Filer storage the bucket could be deleted even if it's not empty. If CanDropWholeBucket function returns true (like in case of Postgres storage) the non-empty bucket will be deleted (due to skip of isRecursive verification [here](https://github.com/seaweedfs/seaweedfs/blob/54d815fa0471034fbea4182675763d08b71310a9/weed/filer/filer_delete_entry.go#L72)). In other case, this bug will affect only empty buckets.
Just skip …
=> Bug fix: empty key in DeleteMultipleObjects request caused bucket delete

weed/command/filer_backup.go
`filer.backup`  can automatically delete expired backup.
`filer.backup` command line  add option `retention_duration`
=> [filer.backup] add retention_duration

other/java/hdfs-over-ftp/pom.xml
There are 1 security vulnerabilities found in io.springfox:springfox-swagger-ui 2.9.2
- [CVE-2019-17495](https://www.oscs1024.com/hd/CVE-2019-17495)
Upgrade io.springfox:springfox-swagger-ui from 2.9.2 to 2.10.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade io.springfox:springfox-swagger-ui to 2.10.0

weed/s3api/filer_multipart.go, weed/s3api/s3api_object_multipart_handlers.go
When the same file is uploaded multiple times, and the multipart upload is concurrent, it is easy to cause problems with the final merged file.
When used as the underlying s3 storage of a docker registry, since blob files can be reused, the first concurrent build will result in concurrent multipart uploads
add a uuid after uploadid
=> feat:add a uuid after uploadid

weed/server/filer_server_handlers_write_autochunk.go
related to [#4008](https://github.com/seaweedfs/seaweedfs/pull/4008),If the user directly uses gzip, `SeaweedFS` loses the original information of the header
for example,very common usage
=> fix: Lost Content-Encoding metadata

weed/command/filer.go, weed/command/filer_sync.go, weed/command/master.go, weed/command/s3.go, weed/command/server.go, weed/command/volume.go, weed/stats/metrics.go
IP of the metrics is bind to 0.0.0.0 at the moment. It cannot be changed to other IP (for example 127.0.0.1).
I added the ability to control the address of the metrics by analogy with the rest of the Seaweedfs components - using `ip.bind` option.
Compiled locally, ran and check output with `netstat -tunelp | grep -i weed`.
=> [metrics] Add the ability to control bind ip

weed/s3api/s3api_objects_list_handlers.go
https://github.com/seaweedfs/seaweedfs/issues/4015
avoid recursive deleting newly created empty directories
=> avoid recursive deleting newly created empty directories

weed/filer/filechunks.go
https://github.com/seaweedfs/seaweedfs/issues/3987
Currently, the ETag for a file that exists ONLY in remote is always `d41d8cd98f00b204e9800998ecf8427e-0` which is MD5 of empty string.
Doing a check if file is not saved in Volume server, then return the ETag as set by the remote
=> Return ETag from remote when file doesn't exist on Filer

weed/Makefile
1. Makefile references `weed` which is found on the PATH
the build command creates the binary in the local directory, so we should be refencing `./weed` instead
2. debug_s3 and debug_webdav require Filer, so changed the command so it starts that as well
=> Update Makefile - use binary in current directory

weed/s3api/s3api_object_multipart_handlers.go
Signed-off-by: changlin.shi <changlin.shi@ly.com>
fix error log at `weed/s3api/s3err/error_handler.go:99`
```
http: request method or response status code does not allow body
```
response with no content
=> fix response not allowed

weed/command/webdav.go, weed/server/webdav_server.go
The webdav protocol cannot use a special directory as the root directory.
I added `-filer.path` options to the `weed webdav` command, just like the `weed mount -filer.path`.
The filer server start at http://127.0.0.1:8888
Create a folder named testPath
Run the command like this:
`weed webdav -filer=127.0.0.1:8888 -filer.path=/testPath`
Connect using the webdav client tool
=> add -filer.path to webdav command

k8s/helm_charts2/templates/filer-statefulset.yaml, k8s/helm_charts2/templates/master-statefulset.yaml, k8s/helm_charts2/templates/s3-deployment.yaml, k8s/helm_charts2/templates/volume-statefulset.yaml, k8s/helm_charts2/values.yaml
Fixes: 4076. Host path prefix e.g. /storage should be configurable in values.yaml
hostPathPrefix added to values.yaml.
Has been tested in k3s.
=> Fixes: 4076: Host path prefix should be configurable

k8s/helm_charts2/templates/s3-deployment.yaml, k8s/helm_charts2/values.yaml
Fixes https://github.com/seaweedfs/seaweedfs/issues/4074.
S3 Gateway fails to start because it is listening only on localhost.
By binding to all interfaces.
Using k3s and AWS EKS.
=> Fixes 4074: S3 Gateway fails to start when installed via Helm

k8s/helm_charts2/templates/filer-statefulset.yaml, k8s/helm_charts2/templates/master-statefulset.yaml, k8s/helm_charts2/templates/s3-deployment.yaml, k8s/helm_charts2/templates/volume-statefulset.yaml
By default, system components are configured to save logs to disk in /logs. In clusters configured to collect logs from pods using third-party systems, such as Grafana Loki, this can be a waste of disk space. Need to be able to configure components to write logs to std
Add the following logic to the helm chart: if the type of logs is "HostPath", then write logs to disk, otherwise use -logtostderr flag
Override logs.type on "" for each component in your deploy
=> Add logtostderr option in helm chart

weed/filer/mysql/mysql_sql_gen.go, weed/filer/mysql/mysql_store.go, weed/filer/mysql2/mysql2_store.go
This PR was part of #4093
Escape columns names in SQL queries. For example directory is a [keyword](https://dev.mysql.com/doc/refman/8.0/en/keywords.html) so escaping makes sense.
Escaping columns makes sense as we already use directory with is a keyword.
I tested these changes locally on a mysql 8.0 server and everything worked as expected
=> filer.store.mysql: Escape table columns in SQL query

weed/command/scaffold/filer.toml
This PR was part of #4093
Remove [depreacted function](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html) usage in upsertQuery
Using VALUES() on `ON DUPLICATE KEY` queries is deprecated so we switch to a non-deprecated way.
I tested these changes locally on a mysql 8.0 server and everything worked as expected
=> filer.store.mysql: Replace deprecated upsert syntax

docker/seaweedfs.sql, k8s/helm_charts2/README.md, weed/command/scaffold/filer.toml, weed/filer/mysql/mysql_store.go, weed/filer/mysql2/mysql2_store.go
This PR was part of #4093
Allow all UTF8 chars in files or directories instead of just 3 byte UTF8 ones.
Switching mysql tables from utf8 to utf8mb4. I chose utf8mb4_bin as COLLATE instead of the [better](https://dba.stackexchange.com/questions/278010/what-is-the-difference-between-different-utf8mb4-binary-collations) utf8mb4_0900_bin because it has wider support across different mysql versions. utf8mb4_0900_bin would basically require mysql 8.0 and exclude mariadb and probably some more.
I tested these changes locally on a mysql 8.0 server and everything worked as expected
=> filer.store.mysql: Use utf8mb4 instead of 3 byte UTF8

k8s/helm_charts2/Chart.yaml
As of Helm 3.3.2, semver 2 is required. Setting anything else, breaks helm.
https://helm.sh/docs/topics/charts/#charts-and-versioning
chart version and appVersion `must` follow semver
=> Use semver 2 in  Chart.yaml

weed/mount/meta_cache/meta_cache.go
The mv operation does not delete the file on the mount side, but only deletes the directory.
For example, for directory A, we do "mv A B", and "cp -r  /tmp/A A".  
we get "cp: cannot create regular file './A/a.txt': File exists" 
or if we do "mv A B", and "mkdir A", we can see there are files  in the A directory.
In mount side, for newEntry, we have:
sourceInode, targetInode := wfs.inodeToPath.MovePath(oldPath, newPath)
It set oldPath.isChildrenCached to "false",  so  we can't delete oldentry in metacache if we use IsChildrenCached. 
We can replace isCachedFn with FindEntry to resolve this porblem.
There are files in the A directory, and we do
mv A B
mkdir A
To observe if there are files in directory A.
=> [mount] fix metacache update

k8s/helm_charts2/Chart.yaml, weed/util/constants.go
when folders are created via the s3 gateway, the mime type `httpd/unix-directory` is attached to the folder. https://github.com/seaweedfs/seaweedfs/blob/master/weed/s3api/s3api_object_handlers.go#L102
however, when listing files via the filer server, the filer checks if the mime type is empty to determine whether or not to display the folder listing. https://github.com/seaweedfs/seaweedfs/blob/master/weed/server/filer_server_handlers_read.go#L121
this causes folders uploaded via the s3 gateway to appear as blank white screen (404 error) when using the filer web ui
have filer server check if the mime type is either `httpd/unix-directory` or empty, instead of just empty, which will make it properly show directory listing on directories uploaded with s3
=>  make directory lister trigger if mime type is httpd/unix-directory

weed/filer/filer.go
Signed-off-by: Neo <zhaoxiaolong@virtaitech.com>
1. mount will seen directory of topics by subscribe which is created to save logs and should not be show to users.
1. system log dir may create through ensureParentDirectoryEntry. For example, the directory of /topics/.system/log/2022-xx-yy
will have 3 keys in filer: /topics, /topics/.system/,/topics/.sysmem/log.
2. the key of /topics will generate subscribe event which is not filer by the micro of SystemLogDir.
3. filter the system dir before subscribe event generated in ensureParentDirectoryEntry.
=> filter system log dir does not make subscribe event

weed/mount/filehandle_read.go
command "cat" read a file(data in entry.content) return empty. 
len(buf) is 4096, if the length of content less than 4096, we can's get data from content.
remove len(buf) 
cat a file with data in entry.content
=> [mount] Fix read file-data in entry.content

k8s/helm_charts2/templates/filer-statefulset.yaml, k8s/helm_charts2/templates/master-statefulset.yaml, k8s/helm_charts2/templates/s3-deployment.yaml, k8s/helm_charts2/templates/volume-statefulset.yaml, k8s/helm_charts2/values.yaml
Ability to use the seaweedfs-csi-driver with the seaweedfs helm chart.
adding namespace to volume `-ip` hostname.
Install csi driver and seaweedfs on seperate namespaces.
- [] I have added unit tests if possible.
- [] I will add related wiki document changes and link to this PR after merging.
=> compatibility patch for csi driver

weed/command/update.go, weed/security/tls.go, weed/server/raft_server.go, weed/shell/command_volume_fsck.go
The ioutil package has been deprecated as of Go v1.16: https://go.dev/doc/go1.16#ioutil
This commit replaces ioutil functions with their respective io/os functions.
=> Updated the deprecated ioutil dependency

weed/command/filer.go, weed/command/server.go, weed/server/filer_grpc_server.go, weed/server/filer_server.go, weed/server/filer_server_handlers_write.go
When I start the volume with ```-disk=nvme```,and use filer to upload files.The filer will prompt no free volumes left and upload failed.
```
E0225 11:45:13.938780 filer_server_handlers_write.go:48 failing to assign a file id: rpc error: code = Unknown desc = no free volumes left for {"replication":{},"ttl":{"Count":0,"Unit":0}}
E0225 11:45:13.939355 filer_server_handlers_write_upload.go:209 upload error: rpc error: code = Unknown desc = no free volumes left for {"replication":{},"ttl":{"Count":0,"Unit":0}}
I0225 11:45:13.939424 common.go:70 response method:POST URL:/ with httpStatus:500 and JSON:{"error":"rpc error: code = Unknown desc = no free volumes left for {\"replication\":{},\"ttl\":{\"Count\":0,\"Unit\":0}}"}
```
I added - disk so that filer can write volume with same disk tag. …
=> add -disk to filer command

weed/server/filer_server_handlers_write_autochunk.go
Filer API returns `500 Internal server error` status code if path/dir already exists. It should return 4XX client error.
If error message has suffix `already exists`, `409 Conflict` will be returned
PR is tested manually as I am not able to find related test cases. `weed` binary is generated using `go build ./weed` and empty storage started using below commands.
```
./weed master -mdir="." -ip=localhost
./weed volume -max=100 -mserver="localhost:9333" -dir="./data"
./weed filer -ip=localhost -port=8888 -master=localhost:9333
```
Then API is tested with help of `curl`.
```
> curl -vvv -X POST "http://localhost:8888/foo/"
*   Trying 127.0.0.1:8888...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST /foo/ HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.81.0
> Accept: */*
> 
* …
```
=> #4270 set http status code to 409 if dir already exists

weed/mount/weedfs_dir_mkrm.go, weed/mount/weedfs_link.go, weed/mount/weedfs_symlink.go
A POSIX filesystem does not implicitly create parent directories when they do not exist. Directories must be explicitly created and permissions be set.
This also fixes a bug where asynchronous operations would create a file in the filer before the parent directory was created. If the file was a symlink or another special type of file the directory would inherit that type and become unusable in the mounted FS.
Skip parent directory creation in mount
I have noticed that we had some files with the following permissions in the filer: `dLrwxrwxrwx (2281701887)`, which doesn't make any sense. After some research I found that this can only possibly happen here: https://github.com/seaweedfs/seaweedfs/blob/b9b613a/weed/filer/filer.go#L242
When the filer takes a symlink request and the parent …
=> Skip parent directory creation in mount

weed/command/master.go, weed/command/server.go
`weed server` was not correctly propagating
`-master.raftHashicorp` and `-master.raftBootstrap` flags when starting the master server.
Related to #4307
Propagating the following flags to the master server from the server command:
* -raftHashicorp
* -raftBootstrap
* Using the `masterOption` argument in `startMaster()` rather than global options.
* Exposing `-master.raftBootstrap` as a server command flag.
* Ran all unit tests and verified they passed.
* Ran master command to verify no change in behavior.
* Ran server command and verified the Hashicorp Raft server is used when the
`-master.raftBootstrap` flag is specified.
=> Fix -raftHashicorp and -raftBootstrap flag propagation.

go.mod, go.sum, weed/topology/topology.go
`topology.Leader()` was using a backoff that typically resulted in at least a 5s delay when initially starting a master and raft server. This changes the backoff algorithm to use exponential backoff starting with 100ms and waiting up to 20s for leader selection.
Related to #4307
Trying to reduce latency when querying the leader master server.
I've changed the backoff algorithm to use exponential backoff starting with 100ms and waiting up to 20s for leader selection.
* Verified all unit tests pass
* Verified `weed master` and `weed server` commands work as expected.
=> Use exponential backoff to query leader.

weed/filer/filer_conf.go
fix key corrupt when fs.configure copy path trie
bytes.copy(key)
=> fix key corrupt when fs.configure copy path trie

k8s/charts/seaweedfs/templates/filer-statefulset.yaml
If hostPath is used for filer persistence and the deprecated `enablePVC` option is left false, the filer storage is not persistent.
=> fix(chart): use hostpath filer persistence when deprecated enablePVC is unset

weed/s3api/s3_constants/s3_actions.go, weed/s3api/s3api_object_handlers.go, weed/server/filer_server_handlers_read.go
https://github.com/seaweedfs/seaweedfs/issues/3086
https://github.com/seaweedfs/seaweedfs/issues/3086
```
aws --endpoint-url http://127.0.0.1:8333 s3api head-object --bucket nextcloudext --key "rootFolder"
{
"AcceptRanges": "bytes",
"LastModified": "2023-04-11T09:25:13+00:00",
"ContentLength": 0,
"ETag": "\"d41d8cd98f00b204e9800998ecf8427e-0\"",
"ContentDisposition": "inline; filename=\"rootFolder\"",
"ContentType": "httpd/unix-directory",
"Metadata": {}
}
```
and
```
aws --endpoint-url http://127.0.0.1:8333 s3api head-object --bucket nextcloudext --key "rootFolder/"
{
"AcceptRanges": "bytes",
"LastModified": "2023-04-11T09:25:13+00:00",
"ContentLength": 0,
"ETag": "\"d41d8cd98f00b204e9800998ecf8427e-0\"",
"ContentDisposition": "inline; filename=\"rootFolder\"",
"ContentType": …
```
=> s3 fix get fake dir object key

k8s/charts/seaweedfs/templates/filer-service.yaml
When trying to deploy the filer statefulset with s3 baked in, the proper service port is not opened like it is for the separate s3 deployment. Added a conditional check to see if .Values.filer.s3.enabled, and added the port
When Values.filer.s3.enabled is true, the filer service does not expose the port
Added a conditional check to see if .Values.filer.s3.enabled, and added the port
Tested the helm deployment service creation
=> Fixing a service deployment bug

weed/s3api/s3api_objects_list_handlers.go
https://github.com/seaweedfs/seaweedfs/issues/3086
https://github.com/seaweedfs/seaweedfs/issues/3086
with slash
```
aws --endpoint-url http://127.0.0.1:8333 s3api list-objects-v2 --bucket nextcloudext --prefix "Proverka/" | jq '.Contents[] | .Key'
"Proverka/"
"Proverka/File"
"Proverka/File001"
"Proverka/File002"
"Proverka/File003"
"Proverka/File004"
"Proverka/File005"
```
without slash
```
aws --endpoint-url http://127.0.0.1:8333 s3api list-objects-v2 --bucket nextcloudext --prefix "Proverka" | jq '.Contents[] | .Key'
"Proverka/"
"Proverka/File"
"Proverka/File001"
"Proverka/File002"
"Proverka/File003"
"Proverka/File004"
"Proverka/File005"
"Proverka0"
"Proverka001/"
"Proverka1/"
"Proverka2/"
"Proverka3/"
"Proverka4/"
```
empty for entry file and not entry not eq prefix
```
aws …
```
=> s3 fix get list of dir object key with slash suffix

k8s/charts/seaweedfs/templates/filer-statefulset.yaml
Follow-up to #4384
... Not sure if there's other related lurking bugs related to this ongoing `enablePVC -> data.*.type` transition. What's the plan on that? Maybe better to carry it out sooner rather than later ;) (I'm offering to do the work!)
=> fix(chart): use filer data PVC correctly

weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_objects_list_handlers.go
```
> fs.tree /buckets/yournamehere-8l0wvspgzg423hom-1
yournamehere-oke81c27mfnzwpwt-1
└──asdf
└──asdf
```
run test
```
>       validate_bucket_listv2(bucket_name, 'asdf/', '/', None, 1000, False, ['asdf/'], [], last=True)
s3tests_boto3/functional/test_s3.py:342: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
bucket_name = 'yournamehere-8l0wvspgzg423hom-1', prefix = 'asdf/', delimiter = '/', continuation_token = None, max_keys = 1000, is_truncated = False, check_objs = ['asdf/']
check_prefixes = [], last = True
def validate_bucket_listv2(bucket_name, prefix, delimiter, continuation_token, max_keys,
keys = _get_keys(response)
prefixes = _get_prefixes(response)
> …
```
=> fix s3test test_bucket_listv2_delimiter_prefix_ends_with_delimiter

weed/mount/filehandle.go, weed/mount/weedfs_file_sync.go
the variables handle of FileHandle is invalid
update fuse client log which should output the fh of FileHandle. 
the variables handle of FileHandle is useless and delete it.
write a file, and watch the log
=> update fuse client log which should output the fh of FileHandle. 

weed/util/fla9/fla9.go
Set flags with dot in their name with environment variable like this:
```shell
export PORT_GRPC=9000
```
Change `.` to `_` when trying to find flag in environment variables
With this commands
```shell
export PORT=5000
export PORT_GRPC=5001
export IP_BIND=0.0.0.0
go run ./weed/weed.go master
```
=> use env for flags wtih dot in name

weed/operation/upload_content.go, weed/util/retry.go
When the disk space corresponding to a volume server is less than "minfreespace" (default 1%), "isDiskSpaceLow" will be set to true, and all volumes corresponding to the node are read only.
However, it takes 5 seconds for the volume to become read only until the master perceives "read only" through the heartbeat information. During this period, if the master allocates fid to the volume on this node, the write will fail.
According to my analysis, #4381 ， #3628 , #3345 failed to write because of this reason.
We add retry to mount for this situation, so that the master can assign fids to other nodes to avoid write failures.
env: more than 4 volume server nodes, ReplicaPlacement=002
When writing data through mount, use large files to fill up the disk corresponding to a volume server. At this …
=> mount: add retry for read only case

weed/topology/topology_vacuum.go
In our test environment(3master, 3filer, 9volume server), we found that many "volume is read only" errors were reported for a long period of time. It is found that the disk space of a certain volume server node has reached minfreeSpace, so that all volumes on the node are "read only".
Theoretically, the error will only last up to 5s (heartbeat time interval). Through the log, it is found that for a long period of time, when the master allocates fid, it will always be allocated to the "read only" volume. The states of master's writable and volume are inconsistent.
It is found that during the vaccum process, volume1 (for example) is on node1, node2, and node3, and only volume1 on node1 satisfies the GarbageRatio >= garbageThreshold condition, while volume1 on node2 and node3 does not.
At …
=> Writables inconsistency

weed/pb/filer_pb/filer_pb_helper.go, weed/s3api/s3api_objects_list_handlers.go
When write operations are highly concurrent, deletion sometimes deletes files supposedly from empty folders
https://github.com/seaweedfs/seaweedfs/issues/4015
Now not only subfolders are checked, but also the folder itself, that it has been created for more than 3 seconds
```
make dev
s3cmd --no-ssl --host-bucket=127.0.0.1:8333 --host=127.0.0.1:8333 put fileb s3://test/newFolder/subfolder/fileb
s3cmd --no-ssl --host-bucket=127.0.0.1:8333 --host=127.0.0.1:8333 rm s3://test/newFolder/subfolder/fileb
s3cmd --no-ssl --host-bucket=127.0.0.1:8333 --host=127.0.0.1:8333 ls s3://test/
```
localy
```
eaweedfs-filer-1   | I0425 13:14:07.934076 filer_grpc_server.go:40 ListEntries directory:"/buckets/test"  limit:10002
seaweedfs-s3-1      | + ensureDirectoryAllEmpty /buckets/test newFolder …
```
=> allow deleting only older empty  dir without recursion

weed/filer/filer_rename.go, weed/server/filer_grpc_server_rename.go
Http api does not prevent parent directory from moving to its subdirectory which can result in filer corruption.
refer to #4045 
Add parent-child directory relationship judgment.
curl -i -X POST 'http://localhost:8888/a/b/?mv.from=/a/' should be failed.
=> Fix: http rename move dir to subdir

weed/shell/command_volume_balance.go, weed/shell/command_volume_balance_test.go
currently shell volume.balance only support replication 001 010 100, and not support others like 011 ...
in isGoodMove function, use satisfyReplicaPlacement() to check if it is a good move.
i added tests in command_volume_balance_test.go
=> fix shell volume.balance bug

weed/command/scaffold/filer.toml, weed/filer/etcd/etcd_store.go, weed/filer/etcd/etcd_store_kv.go
An etcd cluster is not necessarily only dedicated to seaweedfs. This security enhancement adds a customizable key_prefix option to the etcd filer store. This will allow an etcd cluster administrator to limit the seaweedfs etcd user to only read/write a subset of keys under the key_prefix, instead of all keys on the etcd cluster.
Now that the seaweedfs etcd user can be authenticated by the etcd cluster, the seaweedfs etcd user should not have access to all keys on etcd cluster.
By adding a customizable key_prefix.
This means that the etcd cluster administrator can restrict the seaweedfs etcd user to read/write operations for keys under this key_prefix.
By specifying the key_prefix in the filer.toml, and restricting the seaweedfs etcd user to the "seaweedfs." prefix, and seaweedfs were able …
=> Feat: etcd filer store keys should have customizable prefix

weed/topology/node.go, weed/topology/topology_vacuum.go
start volume server with  -max=0.
After seaweedfs runs for a period of time, "no more writable volumes" appears. Checking the disk usage we found that there is still a lot of disk left. 
Through the master's api "dir/status", we can see that the number of volumes has reached the maximum value that the system can create.  Some with very small volumes (hundreds of MB) do not appear in the Master's writables.
After observing the log, it is found that after the vacuum is over, the master sets the volume to be writable, but immediately judges that the volume is full and sets it as unwritable.
It is judged that the reason for this problem is that the volume size obtained by the CollectDeadNodeAndFullVolumes function is obtained through the heartbeat information, which is the old size. This kind …
=> fix no more writables volumes while disk free space is sufficient

weed/server/filer_server_handlers_write_upload.go
fix #4526 
The main goroutine enters the loop and checks the condition atomic.LoadInt64(&bytesBufferCounter) >= 4. lf this condition is true,it waits on bytesBufferLimitCond.Wait().This will block the main goroutine until another goroutine calls bytesBufferLimitCond.Signal()
lf all the worker goroutines have finished their work and exited, there will be no more calls to "bytesBufferLimitCond.Signal().This means the main goroutine will wait indefinitely, leading to a deadlock
We use channels to  throttle
=> fix deadlock for filer upload

weed/command/s3.go, weed/security/tls.go
When deploying k8s, the certificate in accordance with the object, the manager certificate can be reissued quite often, for example, once every 3 months, which requires restarting the application in the pod.
https://github.com/seaweedfs/seaweedfs/pull/4507
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
annotations:
k8s.tochka.com/mutate-hosts: basic, extended
meta.helm.sh/release-name: fast
meta.helm.sh/release-namespace: s3
creationTimestamp: "2023-01-31T06:57:17Z"
generation: 1
labels:
app: fast-api
app.kubernetes.io/component: api
app.kubernetes.io/instance: fast
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: seaweedfs
app.kubernetes.io/version: 3.48-6fdff0b
helm.sh/chart: seaweedfs-0.4.70
name: fast-ing
namespace: s3
resourceVersion: "2467815081"
uid: …
```
=> S3 TLS credentials Refreshing

k8s/charts/seaweedfs/templates/ingress.yaml, k8s/charts/seaweedfs/values.yaml
- Allow TLS and Host name to be specified in values.yaml
The ingress right now isn't really usable because the host name is hard coded and you can't configure TLS.
This patch allows configuring TLS and hostnames for the ingress resources using values.yaml.
You guessed it, locally in my cluster.
- [N/A] I have added unit tests if possible.
- [Yes] I will add related wiki document changes and link to this PR after merging.
=> Helm chart fixes:

k8s/charts/seaweedfs/templates/filer-statefulset.yaml
Instead of providing a literal value as a string, you can provide the contents of valueFrom as a map.
Especially since the filer can only really be configured by environment variables, it's very common to want to have some of the values (like database passwords) in a secret.
Allow the user to supply a map instead of a string for an environment variable value. If they do, we put it under valueFrom.
This seemed like the best backwards compatible way of doing this.
Of course in the future it might be better to add proper configuration for the filer storage backend instead of hard coding memsql and having to override it. But this is a first step.
Run locally in my cluster
- [N/A] I have added unit tests if possible.
- [N/A] I will add related wiki document changes and link to this PR after …
=> Add secret support for filer environment variables.

k8s/charts/seaweedfs/templates/ca-cert.yaml, k8s/charts/seaweedfs/templates/cert-caissuer.yaml, k8s/charts/seaweedfs/templates/cert-clusterissuer.yaml, k8s/charts/seaweedfs/templates/client-cert.yaml, k8s/charts/seaweedfs/templates/filer-cert.yaml, k8s/charts/seaweedfs/templates/master-cert.yaml, k8s/charts/seaweedfs/templates/volume-cert.yaml, k8s/charts/seaweedfs/values.yaml
- Add parameter for whether to use v1alpha cert-manager CRDs, default off.
- Use self-signed Issuer only for the initial CA certificates, create a new Issuer that uses the generated CA certificate and use that for all the others
The enableSecurity flag in the Helm chart doesn't work. In particular:
- it creates certificates using the older v1alpha cert-manager Cards which have been superseded for years.
- The certificates are all self signed, instead of self signing the CA certificate and using that certificate to sign everything else.
- Add a values.yaml flag to use the old CRDs, off by default.
- Create a new issuer that uses the generated CA certificate.
- Adjust certificate resources to use slightly different format (TODO: retain the old format when using new Cards)
- Has been running …
=> Fix Helm chart enableSecurity flag

weed/shell/command_volume_delete_empty.go, weed/topology/volume_growth.go
https://github.com/seaweedfs/seaweedfs/issues/4531
skip deleting if ModifiedAtSecond not set
=> fix: deletes newly created volumes

unmaintained/see_dat/see_dat.go
Some fids scanned by the see_dat  cannot be read on the volume server.
Specify the length of the cookie as 8. If the beginning of  cookie is 0, it will not be printed out, resulting in fid printed mismatch with the real one.
=> fix: fid mismatch

weed/server/raft_server_handlers.go, weed/topology/node.go, weed/topology/topology.go
When a deadlock occurs, the leader master server pretends to be alive
https://github.com/seaweedfs/seaweedfs/issues/4522
Define a deadlock in the liveness handles, which will allow the container to be restarted with the leader of the master and control will take another
localy
```
make dev
curl -v -I  http://127.0.0.1:9333/cluster/healthz
*   Trying 127.0.0.1:9333...
* Connected to 127.0.0.1 (127.0.0.1) port 9333 (#0)
> HEAD /cluster/healthz HTTP/1.1
> Host: 127.0.0.1:9333
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 09 Jun 2023 11:24:46 GMT
Date: Fri, 09 Jun 2023 11:24:46 GMT
```
=> Healthz check for deadlocks

weed/server/filer_server_handlers_write_upload.go
The wrong http status code may be returned when an error occurs
when `err == nil && dataSize == 0 && uploadErr != nil`
as L74 will unexpectedly overwrite a non-nil `uploadErr` with a `nil` value
By the way, L73-L75 is not consistent with L102-L106
-   only change `uploadErr` when `err != nil`
-   only change `uploadErr` when `uploadErr == nil`
=> avoid overwriting non-nil uploadReaderToChunks.uploadErr with nil value

weed/command/backup.go, weed/shell/command_volume_delete_empty.go, weed/storage/disk_location.go, weed/storage/store.go, weed/storage/volume.go, weed/storage/volume_write.go, weed/storage/volume_write_test.go
-   phantom read: query empty state in different `v.dataFileAccessLock` scope may use outdated isEmpty when `v.Destroy()`
-   ~~race read `v.DataBackend.GetStat()`: `v.IsEmpty()` use `v.DataBackend.GetStat()` out of `v.dataFileAccessLock` scope~~ (outdated)
-   query empty state & apply effect within ***one*** scope of `v.dataFileAccessLock` to avoid phantom read
-   ~~let `v.IsEmpty()` use `v.DataBackend.GetStat()` in `v.dataFileAccessLock` scope~~ (outdated)
=> avoid data race read volume.IsEmpty

other/metrics/grafana_seaweedfs.json, other/metrics/grafana_seaweedfs_heartbeat.json, other/metrics/grafana_seaweedfs_k8s.json
When importing the dashboards to modern Grafana instances, if the variable `DS_PROMETHEUS` is not present as `templating` variables, it's not able to recognize the datasource from `__inputs` field
Adding it as templating variable solves the problem
Importing the dashboard json file, directly
=> feat: Add datasource as variable

weed/storage/volume.go
https://github.com/seaweedfs/seaweedfs/pull/4574#discussion_r1228129815
`return false, fmt.Errorf("v.DataBackend is nil")` when `v.DataBackend == nil`
=> doIsEmpty() return error if v.DataBackend is nil

weed/storage/volume.go
duplicate code: L306, L309 have the same `fileCount` query code
delete L309
=> remove duplicate `fileCount` query

weed/storage/backend/rclone_backend/rclone_backend.go
Although the Rclone backend implemented in https://github.com/seaweedfs/seaweedfs/pull/4402 works fine, the current implementation has the limitation of storing all files at the *root* of a Rclone remote, next to each other in the same "folder".
In a SeaweedFS deployment like mine with, hmm, tens of thousands of volume files, I'd like to have a way to split all those files into subfolders.
By introducing a new configuration property that lets the user provide a template generating the filename from the volume UUID.
Manually, by configuring such a backend:
```
[storage.backend]
[storage.backend.rclone.default]
enabled = true
remote_name = "onedrive"
key_template = "SeaweedFS/{{ slice . 0 2 }}/{{ slice . 2 4 }}/{{ slice . 4 }}"
```
And checking that volume files were uploaded in OneDrvive …
=> Support templating name of files stored via Rclone backend

weed/command/filer.go, weed/command/s3.go, weed/command/server.go
As it suggested by wiki, S3 servers commonly running behind a reverse-proxy server like nginx and  currently the connection between the two established using OS loop-back.
Unix socket are proven to be more efficient and robust than lo and using them alongside tcp port listening can help busy servers.
Basically I copy-pasted your previous commit about [adding Unix domain sockets to filer server](https://github.com/seaweedfs/seaweedfs/commit/da3d330616663e1c843514bd7a7a2c1833bf42d1)  with required changes.
I built the project and spin up an instance and test the connection between nginx & s3 server.
Unix socket listening on `/tmp/seaweedfs-s3-%port%.sock` by default.
=> Unix Socket listener for S3 server

weed/command/server.go
Changes in 3.53 resulted in a segfaults if launching `weed server -s3` without -s3.port.https, this fixes that. 
See [issues/4627](https://github.com/seaweedfs/seaweedfs/issues/4627)
Initialise the value in the server command.
By running it without setting the -s3.port.https option.
=> Fix the segfault from not setting s3 https port

weed/s3api/filer_multipart.go
The file paths were being having '/' changed to '\' by filepath.Dir() resulting in a file being created with '\' separators, but when trying to read the files, the same wasn't happening.
Failure to retrieve objects via S3 API in Windows
Running filepaths.ToSlash() on the result of filepath.Dir().
Ran it and I could now retrieve objects that were created in nested dirs, e.g. /some/nested/file.txt
=> Fix S3 API multipart upload on Windows

weed/mount/weedfs_xattr.go, weed/server/filer_grpc_server.go
Fix #4677 
The problem is caused by manifest.
If the file has two xattr, then mount will trigger saveEntry twice, and  twice (fs *FilerServer) UpdateEntry. With the last (fs *FilerServer) CreateEntry, the file will do 3 manifest operations.
Then CreateEntry and UpdateEntry will judge the previous manifest chunks as garbage, and  fs.filer.DeleteChunks(garbage) will delete the data by mistake.
1:  Use DeleteChunksNotRecursive instead of DeleteChunks to clear garbage。
2:  SetXAttr does not call saveEntry when writing data to the file (fh!=nil)
=> Fix large file chunks deleted by mistake

go.mod, go.sum
relates to http://shoenig/go-m1cpu#8
also relates to https://github.com/Homebrew/homebrew-core/pull/136799
Fix build with macOS < 12 due to go-m1cpu compilation issue
Upgrading that dependency to a known good one
Tested/verified in the associated homebrew PR
=> deps: patch go-m1cpu to build with macOS < 12

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/service-account.yaml, k8s/charts/seaweedfs/values.yaml
Sometimes, when deploying the Helm Chart to a specific namespace inside a Kubernetes Cluster that is shared accross many teams, you don't have the rights as a user to access ClusterRole and ClusterRoleBinding globally.
In order to bypass this limitation, we can use the default service account in the namespace, and disable the service-account part of the deployment.
This PR is tested in a live kubernetes environment without rights access to ClusterRole and ClusterRoleBinding.
=> Add variabilisation of RBAC

weed/s3api/s3api_object_handlers.go
fix #4691 
s3api should return to client 500 response from filer
checked locally in my cluster
=> s3api should return 500 code from filer

weed/storage/disk_location.go
Don't wait for a minute to save metrics initially
=> Save disk space metrics immediately

weed/command/fix.go
https://github.com/seaweedfs/seaweedfs/issues/4743
Update `weed fix` description to 
```
Description:
Fix runs the SeaweedFS fix command on dat files or whole folders to re-create the index .idx file.
You Need to stop the volume server when running this command.
```
```shell
$ go run ./weed/weed.go fix --help
Example: weed fix [-volumeId=234] [-collection=bigData] /tmp
Default Usage:
-collection string
an optional volume collection name, if specified only it will be processed
-ignoreError
an optional, if true will be processed despite errors
-options string
a file of command line options, each line in optionName=optionValue format
-volumeId int
an optional volume id, if not 0 (default) only it will be processed
Description:
Fix runs the SeaweedFS fix command on dat files or whole folders …
```
=> Update weed fix description

k8s/charts/seaweedfs/templates/master-statefulset.yaml
We should use `master.pvc_exists` instead of `volume.pvc_exists`.
=> fix: replace volume.pvc_exists with master.pvc_exists

weed/shell/command_s3_clean_uploads.go
wrong jwt error in `s3.clean.uploads`  
security.toml:
```toml
[jwt.signing]                      
key = "aaaaaaaaaaaa"           
expires_after_seconds = 30
[jwt.filer_signing]                
key = "bbbbbbbbbbb"           
expires_after_seconds = 30
```
```
> s3.clean.uploads -timeAgo 0
purge http://192.168.20.70:8888/buckets/test/.uploads/109f4b3c50d7b0df729d299bc6f8e9ef9066971f_19a49cbefa9c47cd8ecdf0f8993d1cdb?recursive=true&ignoreRecursiveError=true
failed cleanup uploads for bucket test: purge /buckets/test/.uploads/109f4b3c50d7b0df729d299bc6f8e9ef9066971f_19a49cbefa9c47cd8ecdf0f8993d1cdb: wrong jwt> 
```
`weed shell` is using `jwt.signing.key` for `s3.clean.upload` instead of `jwt.filer_signing.key`
```
$ go run ./weed/weed.go master
$ go run ./weed/weed.go filer -s3 
$ go run …
```
=> Fix s3.clean.uploads

weed/s3api/s3api_object_handlers.go, weed/s3api/stats.go, weed/stats/metrics.go
Lack of time to first byte metric for s3
Add a histogram metric for s3 time to first byte and observe it when filer returns response
Simple write and read to s3 interface and observing `SeaweedFS_s3_time_to_first_byte_seconds_bucket` metric
=> Add time to first byte metric for s3

k8s/charts/seaweedfs/templates/ingress.yaml
seaweedfs master ingress host  configuration do not work
the same as filer ingress， add  a host filed of master ingress
tested
- [X ] I have added unit tests if possible.
- [X ] I will add related wiki document changes and link to this PR after merging.
=> fix bugs:  seaweedfs master ingress host  configuration do not work

k8s/charts/seaweedfs/templates/_helpers.tpl, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml
Current parameter global.imagePullSecrets is a string, but will be good to able to specify array for it. A lot of community charts using "global.imagePullSecrets" parameter as a list and we can't override "global" parameters per subchart so I'm suggesting this solution.
I added additional helper function for that which is returns proper imagePullSecrets section:
- if global.imagePullSecrets parameter is a string it returns imagePullSecrets with single element (for backward compatibility);
- Otherwise it expects list and generates imagePullSecrets section with element for each list element;
Manually tested with:
- default parameters
- with global.imagePullSecrets overrided to string
- with global.imagePullSecrets overrided to list
=> [helm] add possibility to use array for imagePullSecrets

k8s/charts/seaweedfs/templates/ingress.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/values.yaml
1 - for testing it is useful to be able to not specify a host for ingress, in which case it will become the default host
2 - a separate instance for s3 contains an error when logging to stderr
1 - remove host from ingress
2 - additional if for logging for stderr
local
- [] I will add related wiki document changes and link to this PR after merging.
=> [helm] fix log to stderr and default host for ingress

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Allow setting service accounts to the helm chart's deployments. In our case, we use k8s service account to grant AWS permissions for services like S3.
Creating a new `serviceAccountName` field in `values`.
I haven't tested it, but its pretty straightforward. I'll probably work on setting up a test env that allows me generating new versions of the helm chart and test it. (is there an util in this repo that allows generating a helm package to test quickly?)
=> k8s: allow configuring serviceAccountName

k8s/charts/seaweedfs/templates/master-configmap.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Following my question in https://github.com/seaweedfs/seaweedfs/discussions/4796, I think that it would be a good idea if it was possible to set the contents of `master.toml` from the helm chart. This would have helped me avoid any undocument env variable parsing quirks.
Expose `master.config` in values, which can be a multi-line string that will be mounted at `/etc/seaweed/master.toml`.
I based most of the code on the other configmap, `security.toml`.
I ran the following:
```
git checkout master
helm template test . > output.yaml
git add output.yaml
git checkout aviau/master-config
helm template test . > output.yaml
git diff
```
This is the result:
```
diff --git a/k8s/charts/seaweedfs/output.yaml b/k8s/charts/seaweedfs/output.yaml
index ff0044732..15181f612 100644
--- …
```
=> helm: allow setting master.toml config

k8s/charts/seaweedfs/dashboards/seaweedfs-grafana-dashboard.json
No master server metrics on grafana dashboard
Added master server metrics to grafana Dashboard.
Panes:
- current leader across all masters
- leader changes
- received heartbeats by masters
- replica placement mismatches
- current leaders count. Helps to monitor if master "see" each other or there is no leader at all
- cluster admin lock. To know if somebody(client IP shown) locked the cluster.
New grafana dashboard includes two build-in alerts:
- Master servers raft leaders count (to detect split-brain or leader absent)
- Replica placement mismatch. Helps to detect errors on volume replication
WARNING: grafana alerts built-in to dashboard are considered legacy by GrafanaLabs. Though it is still very useful for provisioning.
Also added two panels on S3 request duration 99th percentile by …
=> Add master servers to grafana dashboard

weed/util/http_util.go
This fixed dropped `err` variables in the `weed/util` package.
=> weed/util: fix dropped errors

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
User can't customize k8s probes in their clusters via helm chart
Take out the hardcoded parameters of k8s probes from the templates in values.yaml
helm lint/helm template on local computer
=> improve k8s probes templating in helm chart

weed/s3api/auth_credentials.go, weed/s3api/auth_signature_v4.go, weed/s3api/auto_signature_v4_test.go, weed/s3api/chunked_reader_v4.go
S3 uploading is quite CPU intense.
This change is caching HMAC hashers for repeated use in subsequent requests and chunks, so they don't have to be initialized from scratch every time.
On my local computer this gives me ~5-6 times faster signature calculation and ~5-6.5% more throughput in S3 requests. The smaller the payload the better the throughput gets.
Existing unit tests + warp benchmarking tool.
=> Improve S3 request signing performance

weed/storage/erasure_coding/ec_encoder.go, weed/storage/erasure_coding/ec_test.go
This fixes three error handling issues in `weed/storage/erasure_encoding`.
An `err` was being passed into `encodeDatFile()` that was never used. I removed it.
An `err` variable in the tests was being dropped.
A deferred `Close()` was being used before an error was checked.
=> weed/storage/erasure_coding: Error Handling Fixes

weed/filer/filerstore_wrapper.go
redis as filer store, suppose bucket have objects:
```text
demo_v1
demo_v10
demo_v11
demo_v12
demo_v2
demo_v20
```
when request s3api list objects with params max-keys and prefix, like `http://localhost:8333/test?max-keys=2&prefix=demo_v2`, we got 0 result. Because the item's rank in redis is bigger than the max-keys.
drop `isLastItemHasPrefix`, compare the prefix and lastFileName directly.
=> Fix s3 api object list with params max-keys and prefix

weed/storage/store_ec_delete.go
This fixes a dropped `err` variable in `weed/storage`.
=> fix: weed/storage: dropped error

k8s/charts/seaweedfs/Chart.yaml, k8s/charts/seaweedfs/values.yaml
https://github.com/seaweedfs/seaweedfs/blob/0bb97709d41b1be4c74f01dcc65aac6d5f88bd16/k8s/charts/seaweedfs/values.yaml#L283
Getting  : 
aleopold@aleopold:~/desktop/helm/charts/qalita$ helm lint -f values.yaml .
coalesce.go:220: warning: cannot overwrite table with non table for qalita.seaweedfs.volume.resources (map[])
coalesce.go:220: warning: cannot overwrite table with non table for qalita.seaweedfs.volume.resources (map[])
coalesce.go:220: warning: cannot overwrite table with non table for qalita.seaweedfs.volume.resources (map[])
coalesce.go:220: warning: cannot overwrite table with non table for qalita.seaweedfs.volume.resources (map[])
when values are : 
```yaml
seaweedfs:
volume:
resources: |
requests:
memory: "100Mi"
cpu: "50m"
...
```
Please replace to : 
```yaml
resources: null …
```
=> Wrong default value for volume.ressource

weed/s3api/auth_credentials.go, weed/s3api/auth_credentials_test.go, weed/s3api/auto_signature_v4_test.go
https://github.com/seaweedfs/seaweedfs/issues/4519
optimization iam lookup for reducing algorithm complexity  O(n) -> O(1) 
created additional structures
```
go test -v  | grep -e Anony -e TestCanDo
=== RUN   TestCanDo
--- PASS: TestCanDo (0.00s)
=== RUN   TestCheckaAnonymousRequestAuthType
--- PASS: TestCheckaAnonymousRequestAuthType (0.00s)
```
- [ yes] I have added unit tests if possible.
- [ no ] I will add related wiki document changes and link to this PR after merging.
=> [s3] optimization iam lookup for reducing algorithm complexity

docker/compose/s3tests.conf, weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_bucket_skip_handlers.go
pass tests:
test_bucket_acl_default
test_bucket_acl_canned_private_to_private
https://github.com/seaweedfs/seaweedfs/issues/4519
https://github.com/seaweedfs/seaweedfs/issues/4259
Put bucket ACL only responds success if the ACL is private.
```
./weed -v 4 server -s3 -filer -volume.max=0 -master.volumeSizeLimitMB=1024 -volume.preStopSeconds=1 -s3.port=8000 -s3.allowEmptyFolder=falses3.allowDeleteBucketNotEmpty=false -s3.config=./docker/compose/s3.json
S3TEST_CONF=/Users/lebedev/GolandProjects/seaweedfs/docker/compose/s3tests.conf tox -- s3tests_boto3/functional/test_s3.py::test_bucket_acl_default s3tests_boto3/functional/test_s3.py::test_bucket_acl_canned_private_to_private
======================================================== test session starts …
```
=> [s3acl] Step 0: Put bucket ACL only responds success if the ACL is private.

weed/iamapi/iamapi_management_handlers.go, weed/s3api/auth_credentials_test.go, weed/s3api/s3_constants/s3_actions.go, weed/s3api/s3_constants/s3_config.go, weed/s3api/s3api_server.go
https://github.com/seaweedfs/seaweedfs/issues/4519
**Warning**: This change breaks backwards compatibility with permissions for ACL handles. To restore access, you must add ReadAcp/WriteAcp rights!
>Uses the acl subresource to set the access control list (ACL) permissions for a new or existing object in an S3 bucket. You must have WRITE_ACP permission to set the ACL of an object. For more information, see [What permissions can I grant?](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#permissions) in the Amazon S3 User Guide
Since ACLs allow public access to resources, more rights are needed
Replace action read/write to readAcp/writeAcp for handlers with acl
```
go test -v | grep TestCanDo
=== RUN   TestCanDo
--- PASS: TestCanDo (0.00s)
```
- [ yes ] I have added unit …
=> [iam] Replace action read/write to readAcp/writeAcp for handlers with acl 

weed/replication/sub/notification_aws_sqs.go
This fixes a dropped `err` variable in `weed/replication/sub`.
=> weed/replication/sub: fix dropped error

weed/shell/command_ec_balance.go, weed/storage/disk_location_ec.go
=> fix(ec): volumes created by foreign collection due to bug in ec balance

k8s/charts/seaweedfs/templates/s3-service.yaml, k8s/charts/seaweedfs/templates/volume-service.yaml
When deploying, one could configure the affinity of filers and volumes so that they are colocated; eg: on any node there can be a) no filer and no volume OR b) one filer pod AND one volume pod. In scenario B, it would make sense than that the filer pod communicates with the volume pod on the same node, and avoid any network hops between nodes. 
This is accomplished by setting internalTrafficPolicy to "Local" for the volume service.
=> Allow override internalTrafficPolicy

weed/shell/command_volume_fix_replication.go
https://github.com/seaweedfs/seaweedfs/issues/4646
the message is not read
```
volume 98510 replication 010 is not well placed &{location:0xc0012940f0 info:0xc0009eec60}
```
replace on:
```
volume 98510 replication 010 is not well placed fast-volume-1.s3-fast-volume.service.stagedc.consul:8080
```
=>  fix: logger place msg

k8s/charts/seaweedfs/templates/s3-ingress.yaml, k8s/charts/seaweedfs/values.yaml
It is necessary to be able to raise a separate Ingress for the seaweedfs-s3 service
Add separate ingress in helm chart
helm lint/helm test in CI
=> add ingress for seaweedfs s3

weed/operation/upload_content.go
This fixes a dropped `err` variable in the `weed/operation` package.
=> weed/operation: fix dropped error

k8s/charts/seaweedfs/templates/security-configmap.yaml, k8s/charts/seaweedfs/values.yaml
As described in this [issue](https://github.com/seaweedfs/seaweedfs/issues/4891) - currently when deploying using the repo helm chart, there is no option to customize the `security.toml`. More specifically we need to enable jwt signing for all supported options. Currently only volume write is enforced, we want to enforce it also for volume read and filer read and write.
Adding configuration to the `values.yaml` for each jwt signing option will enable to customize this behavior for any supported option.
Default configuration in `values.yaml` is keeping current behavior where only volume write is enforced OOTB (all other new values are `false`). This way it doesn't introduce any change in current behavior, but only expands it.
Changed different config values and verified file content is …
=> Helm chart jwt signing configuration

weed/replication/sink/localsink/local_sink.go
When using filer.backup to sync a seaweedfs directory to a local directory, I find that the file mode is not synchronized.
Chmod()ing the file as needed when synchronizing.
Ran it manually and noticed that when I set the executable bit on a file that has already been backed up, the backup is correctly updated with the executable bit.
- [N/A - cannot find an existing unit test] I have added unit tests if possible.
- [N/A] I will add related wiki document changes and link to this PR after merging.
=> Fix filer.backup local sink to propagate file mode changes

weed/server/filer_server.go, weed/server/filer_server_handlers.go
As described in this [issue](https://github.com/seaweedfs/seaweedfs/issues/4891), we want to enable all security options via the helm chart.
Section 1 from the issue was solved in this [MR](https://github.com/seaweedfs/seaweedfs/pull/4894) by providing configuration for jwt signing to all supported servers.
This MR solves section 2 - where the `liveness` and `readiness` probes fails on `filer` when jwt read jwt signing is enabled.
Added a `healthz` endpoint to filer which doesn't require any jwt authentication, similar to an endpoint on the volume server,  for the purposes of health checks.
Checked with jwt signing applied to that liveness doesn't fail.
=> added healthz endpoint to filer

docker/Dockerfile.go_build, docker/Dockerfile.rocksdb_dev_env, docker/Dockerfile.rocksdb_large, go.mod, go.sum
[crypto/sha256](https://tip.golang.org/pkg/crypto/sha256/)
SHA-224 and SHA-256 operations now use native instructions when available when GOARCH=amd64, providing a performance improvement on the order of 3-4x.
up version golang to 1.21
=> golang up version to 1.21.3

Makefile, README.md
Simple and easy benchmark launch
https://blog.min.io/how-to-benchmark-minio-warp-speedtest/
I added the make command benchmark and described it in the README
localy
```
warp: Benchmark data written to "warp-mixed-2023-10-16[102354]-l70a.csv.zst"                                                                                                                                                                                               
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 4m59s.
* Throughput: 6.19 obj/s
Operation: GET, 45%, Concurrency: 20, Ran 5m0s.
* Throughput: 279.85 MiB/s, 27.99 obj/s
Operation: PUT, 15%, Concurrency: 20, Ran 5m0s.
* Throughput: 89.86 MiB/s, 8.99 obj/s
Operation: STAT, 30%, Concurrency: 20, Ran 5m0s.
* Throughput: 18.63 obj/s
Cluster Total: …
```
=> add make benchmark with WARP

weed/filer/filerstore_wrapper.go
#4668 the S3 api list file error when function [ListDirectoryPrefixedEntries](https://github.com/seaweedfs/seaweedfs/blob/f24c7e803f0a14d35e2bb40a2ed838c80b8cf2e8/weed/filer/redis3/universal_redis_store.go#L135C64-L135C64) of filer store is not implemented and the parent directory have more than two directory and the sort of directory name is before the listed directory
example when using filer store like cassandra(ListDirectoryPrefixedEntries not implemented) :
myseaweedfs/test/ has only two object
myseaweedfs/test/config
myseaweedfs/test/keys/
mc ls myseaweedfs/test/keys can list file under keys directory
myseaweedfs/test/ has three directory
myseaweedfs/test/config
myseaweedfs/test/data/
myseaweedfs/test/keys/
mc ls myseaweedfs/test/keys can not list file under keys directory
```shell …
```
=> remove compare to fix #4668 issue

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Remove hardcoded podManagmentPolicy value in SeaweedFS Helm Chart
Move podManagmentPolicy field values in SeaweedFS Helm Chart values.yaml
helm lint/helm template on local machine, CI jobs in repository
=> Remove hardcoded podManagmentPolicy value in a helm chart

weed/server/volume_grpc_copy.go
closes #4934
fixes #2633
might fix #3528
Replaced `volFileInfoResp.DatFileSize` with a high enough number (1024*1024)
compiled it, confirmed that it works
=> fix copying .vif file in VolumeCopy

weed/server/volume_server_handlers_read.go, weed/stats/metrics_names.go
Add not found and internal errors as metrics to `SeaweedFS_volumeServer_request_total`  so we can find out if something is wrong with volume server (data loss for example)
I used these two functions in every internal and 404 responses
```go
func NotFound(w http.ResponseWriter) {
stats.VolumeServerRequestCounter.WithLabelValues(stats.ErrorGetNotFound).Inc()
w.WriteHeader(http.StatusNotFound)
}
func InternalError(w http.ResponseWriter) {
stats.VolumeServerRequestCounter.WithLabelValues(stats.ErrorGetInternal).Inc()
w.WriteHeader(http.StatusInternalServerError)
}
```
for example:
```go
if err != nil || count < 0 {
glog.V(3).Infof("read %s isNormalVolume %v error: %v", r.URL.Path, hasVolume, err)
if err == storage.ErrorNotFound || err == storage.ErrorDeleted {
NotFound(w)
} else { …
```
=> Add ErrorGetNotFound and ErrorGetInternal to volume server metrics

weed/server/volume_server_handlers_read.go
https://github.com/seaweedfs/seaweedfs/pull/4960#discussion_r1376344671
Looks like VolumeServerRequestCounter increase twice if cookie is not valid
delete `stats.VolumeServerRequestCounter.WithLabelValues(stats.ErrorGetNotFound).Inc()`
Run weed server
=> Fix twice increase metric counter

weed/command/filer.go
Fixes seaweedfs/seaweedfs#4971
Filer's gRPC port got lost in passing to S3 server.
Using another function to build filerAddress.
go test ./...
Local run.
=> Pass correct Filer's gRPC port to S3 server.

weed/shell/command_volume_fix_replication.go
A volume ID is considered to be misplaced only if **all** the replicas don't meet the configured replica placement setting.
It should be considered misplaced even if only one of the replicas is in in the wrong place.
fixes #4836
=> fix isMisplaced() in command_volume_fix_replication.go

weed/server/webdav_server.go
This fixes a dropped `err` variable in `weed/server`.
=> weed/server: fix dropped webdav error

weed/shell/command_ec_decode.go
Thank you for this great project! 
What I use:
+ Software: version 30GB 3.58 d1e83a3b4df0c515d0aeb75dfbc8f398a771a90a linux amd64
+ One machine is used as master/filer/volume-server, and several others as volume-servers only.
It reports "ec volume x missing shard y" when running ``ec.decode`` subcommand in the weed shell.
After searching the issue list, I find there is already an issue: #4833 
I'm not sure if you can reproduce this issue. Maybe something not properly configured in my cases(?).
Just like the comment in #4833, it can sometimes work after restarting the volume server process, or just run ``kill -s HUP $(pgrep -f "weed volume")`` without restarting the process. But sometimes it doesn't work.
```golang
doEcDecode()
collectEcShards()
volumeServerClient.VolumeEcShardsCopy()   // …
```
=> ec.decode: mount the collected ec shards

weed/shell/shell_liner.go
help shell command is not working with upper-case letters:
- fs.mergeVolumes
- fs.meta.changeVolumeId
- s3.circuitBreaker
- volume.deleteEmpty
- ...
check command name case-insensitively
Build and test manually
=> Fix shell 'help' for all commands

weed/command/filer_backup.go, weed/command/filer_sync.go
Often applications create temporary .tmp files that need to be excluded from the backup
add option filerExcludeFileName in `filer backup` for exclude file names that match the regexp to sync on filer for 
localy
=> filer backup add option for exclude file names that match regexp to sync on filer

weed/shell/command_fs_merge_volumes.go
I had 500 half-full volumes on my cluster, this means 15TB of wasted disk, It was hard and time-consuming to merge volumes individually.
So i wrote a function to create a map (named `plan`) based on current status of volumes and decide how volumes must merge.
This function respect replication policy, volume TTL, collection, read-only volumes and max volumes size limit.
Now it's possible to
+ Merge volumes of a single collection
+ Merge only with specified destination volume (`-toVolumeId`)
+ Merge only with specified source volume (`-fromVolumeId`)
I run this locally and on my cluster.
=> fs.mergeVolumes: Make a plan based on volumes size

k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml
The volume server has an incorrect metricsPort configuration(`containerPort: {{ .Values.filer.metricsPort }}`), and the master's metricsPort configuration is also problematic when `global.monitoring.enabled=false`.
fix charts templates
PR is tested by performing a local Helm lint test
=> [helm] fix: use metricsPort correctly

weed/command/filer_backup.go, weed/command/filer_sync.go
The `weed filer.backup` command is responsible for backup, but it also deletes files, which is not obvious.
Added an option responsible for deleting files and by default it is disabled.
=> fix: add doDeleteFile option for filer backup

weed/mount/page_writer/upload_pipeline.go
Waiting for writes to complete with acquired lock may lead to deadlock, fixes #4952
=> Waiting for writes to complete with acquired lock may lead to deadlock

k8s/charts/seaweedfs/Chart.yaml, k8s/charts/seaweedfs/templates/s3-ingress.yaml, k8s/charts/seaweedfs/values.yaml
A templating error for `s3.ingress.annotations` as well as documenting both the `annotations` and `tls` values in values.yaml. Example error when deploying this helm chart as an Application via Argo CD, which inflates the templates with `helm template` and then does a `kubectl apply` on the resulting manifests:
> Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template seaweedfs --namespace seaweedfs --kube-version 1.27 --values /tmp/ce2b630b-aeca-4c10-a49a-f232ad7a4712 <api versions removed> --include-crds` failed exit status 1: Error: template: seaweedfs/templates/s3-ingress.yaml:15:18: executing "seaweedfs/templates/s3-ingress.yaml" at …
=> helm chart: fix annotations templating for s3.ingress.annotations and document it and s3.ingress.tls in values.yaml

weed/command/mq_broker.go
This picks up and logs a dropped `err` variable in `weed/command`.
=> weed/command: fix dropped error

weed/storage/needle_map/memdb.go
https://github.com/seaweedfs/seaweedfs/issues/4991
Sorting needles by offset when mapdb wants to save idx to file
I tested using `reprod.py` in issue. Also tested vacuum manually because vacuum use `SaveToIdx`
=> Fix weed fix

weed/server/filer_server_handlers_write_autochunk.go
if upload content by s3 client and set content-md5 in header,then will verify recived and saved content,if not equal delete thos chunks
while set content-md5 in request header using aws s3 go client to upload files,weedfs not check the md5.
after saved content to volume and got the md5bytes ,if not equal ,delete thoes chunks
=> verify content-md5 in header

.github/workflows/helm_chart_release.yml
When updates are done to the helm chart that are distinct from a release of SeaweedFS itself, the helm chart is not released because the GitHub Workflow only runs when someone tags a branch. 
This changes the helm chart release to run on any push to the `master` branch in the `k8s/charts` directory. It will no longer run on tagging, as you need to bump the helm chart version every time you release anyway, so tagging wouldn't have worked for a release unless the chart version directory was updated
I created a PR on my fork to merge this `patch-1` branch into the `master` branch on my fork: https://github.com/jessebot/seaweedfs/pull/1
After merging that, I created and merged this PR: https://github.com/jessebot/seaweedfs/pull/2
The second PR just updates a small comment in the values.yaml …
=> Update helm_chart_release.yml - run helm chart release on push to master on changes to k8s/chart files

k8s/charts/seaweedfs/templates/_helpers.tpl, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
As an administrator, I would like to create backups of S3 data stored in SeaweedFS to  external media or a storage provider for long-term archival and compliance purposes. I would also like to restore the backups to a live state in the event of an audit, system failure, or security incident.
By adding support for initializing SeaweedFS using existing volume claims, and adding annotation to `VolumeClaimTemplates` we can enable [Restic](https://restic.readthedocs.io/en/stable/010_introduction.html)-based backup tools like [Velero](https://velero.io/) and [K8up](https://k8up.io/k8up/2.7/index.html) to conduct automated backups and restoration of SeaweedFS data.
The full process is documented here: [s3-backups.md](https://github.com/small-hack/argocd-apps/blob/eso-helm-chart-test/alpha/seaweed …
=> Enable support for Restic-based tools (K8up, Velero) to perform backup and restore operations

k8s/charts/seaweedfs/Chart.yaml, k8s/charts/seaweedfs/README.md, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/s3-secret.yaml, k8s/charts/seaweedfs/templates/seaweedfs-s3-secret.yaml, k8s/charts/seaweedfs/values.yaml
Allowing users to specify their own existing S3 configuration Kubernetes Secret via the values.yaml. Before this change, you could either enable auth and use the default secret with one admin user and one readonly user or disable auth entirely or enable auth and skip the secret creation, but there was no way to specify an existing secret. There was also an issue where the kubernetes secret and volumes/volumemounts were being created even if you didn't enable auth.
I've added `filer.s3.existingConfigSecret` and `s3.existingConfigSecret`  to values.yaml for the helm chart, so a user can specify their own s3 config with whatever name they'd like as long as it has a key called `seaweedfs-s3-secret`.
Example parameters for your values.yaml to use authentication and provide your own secret: …
=> Helm chart: Allow existing S3 config secret for the filer statefulset and the s3 deployment

weed/shell/command_volume_fix_replication_test.go
TestMisplacedChecking() is missing "replicas" for some of the tests.
I added the missing "replicas" to the test and modified it to cover issue #4836
=> fix TestMisplacedChecking() and add test-case

weed/security/jwt.go
If a JWT is not included in the Authorization header or a query string, attempt to get a JWT from an HTTP only cookie.
**The problem**
The Filer can receive and parse a JWT from an `Authorization: Bearer` header and from a query string, but not from an HTTP only cookie. 
**Why would the JWT be in an HTTP only cookie?**
A JWT would be in an HTTP only cookie when using a web client that receives JWTs from a server configured to send the JWT back to the client in an HTTP only cookie for security reasons. When a server sets an HTTP only cookie on a response, the browser then begins to send the cookie with each subsequent request. The JavaScript code run in the browser cannot access the JWT for security reasons, making the traditional method of appending the JWT to the Authorization header …
=> Add a way to use a JWT sent in an HTTP only cookie

k8s/charts/seaweedfs/templates/_helpers.tpl, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml
When both `master.data.type` and `master.logs.type` is `persistentVolumeClaim`, deployment of the Helm chart fails:
```
create Pod seaweedfs-master-0 in StatefulSet seaweedfs-master failed error: Pod "seaweedfs-master-0" is invalid: spec.containers[0].volumeMounts[1].name: Not found: "master-config"
```
This is due to a condition that omits the entire volumes section in this case:
https://github.com/seaweedfs/seaweedfs/blob/d5d9fbb8aa5e86f2b866e25f58bf36a7a989478d/k8s/charts/seaweedfs/templates/master-statefulset.yaml#L217C20-L217C20
The issue was introduced by #4797, as it did not take into account this condition.
I removed the conditions entirely, including the ones for volume-statefulset. They also interfere with a bunch of other options (`extraVolumes`, `enableSecurity`).
For the …
=> Always include volumes in statefulsets

weed/filer/abstract_sql/abstract_sql_store.go
https://github.com/seaweedfs/seaweedfs/issues/5062
Reducing chaos when inserting rows
falls back to update only if error contains  msg "duplicate entry"
localy
=> [filerstore] mysql falls back to update only if error contains  msg "duplicate entry"

weed/filer/remote_mapping.go
- Remote gateway problem with mappings in filer when they are not present
So this comes from here: 
https://github.com/seaweedfs/seaweedfs/pull/5054#issuecomment-1848402868
There is a problem with `weed filer.remote.gateway`.
When you have a fresh installation and no mounts, then the mapping config file is not present. So when you try to use `weed filer.remote.gateway` it can't access the mapping file and will encounter an error.
So There was two solutions:
- You can do a dummy mount to mapping file get creates.
- I changed the code to work even when the mapping file is not present.
So easy, just adding an if statement to check if the error was `file not found error` then ignores it and set the oldContent to `nil`
This procedure is not from me and is present in `InsertMountMapping` …
=> Remote gateway Bug fix

.github/workflows/helm_ci.yml
Right now, there's no check in ci to make sure that the Version in Chart.yaml for the seaweedfs helm chart has been bumped.
This adds the `--target-branch` flag to the `ct` `list-changed`,`lint`, and `install` commands we run for the helm chart. This will validate the chart against the previous version of the chart for things such as the chart version.
We use it in the community nextcloud/helm chart:
https://github.com/nextcloud/helm/blob/main/.github/workflows/lint-test.yaml
If the chart version isn't bumped, it will error like [this](https://github.com/nextcloud/helm/actions/runs/7045807982/job/19244291477#step:7:37):
```logtalk
Linting chart "nextcloud => (version: \"4.5.3\", path: \"charts/nextcloud\")"
Checking chart "nextcloud => (version: \"4.5.3\", path: \"charts/nextcloud\")" for …
```
=> Update helm_ci.yml - add `ct` flag `--target-branch ${{ github.event.repository.default_branch }}`

k8s/charts/seaweedfs/Chart.yaml, k8s/charts/seaweedfs/templates/post-install-bucket-hook.yaml
This fixes #5107 where there was a templating error in the bucket creation job, due to removed named templates (`master.hostpath_exists` and `master.existing_claims`) which you can see [here](https://github.com/seaweedfs/seaweedfs/pull/5081/files#diff-6cbd4f7b20a68ffff3c0a6d9364c83eefab404de24666459d1cf2bfc3ecfecdcL165) in #5081.
I removed the named templates from the `post-install-bucket-hook.yaml`.
Please merge this PR, https://github.com/seaweedfs/seaweedfs/pull/5106, first so we get better checks. edit: it's been merged already :)
This also bumps the chart version.
```console
helm template . --values test-values.yaml
```
where test-values.yaml is exactly the same as values.yaml except that `filer.s3.createBucket` is set like:
```yaml
filer:
s3:
createBuckets:
- name: bucket-a …
```
=> Fix: helm: remove deprecated values that caused helm template error for post install hook

k8s/charts/seaweedfs/templates/_helpers.tpl, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Missing support for sidecar containers
By adding the relevant template on all components
Installed the helm chart with a single sidecar as well multiple sidecars on different components.
For example:
When adding this to values.yaml:
```volume:
sidecars:
- name: log-reader # Sidecar container
image: busybox # Use another busybox image
command: ["/bin/sh"] # Override the default command
args: ["-c", "watch echo hello"]
```
I get this:
```> k describe po seaweedfs-volume-0
Containers:
seaweedfs:
..
Image:         chrislusf/seaweedfs:3.59    <------ original container
..
log-reader:
..
Image:         busybox                     <------ sidecar 
..
Command:
/bin/sh
Args:
-c
watch echo hello
State:          Running
```
=> #5122  Add support for sidecar containers

weed/command/scaffold/filer.toml, weed/filer/mysql/mysql_store.go
it is necessary to pass arbitrary connection param to the msql driver like [tls](https://github.com/go-sql-driver/mysql#tls)
add dsn to filer config
localy
=> chore: add dsn for connection to mysql

weed/command/filer.go, weed/command/s3.go, weed/command/scaffold/security.toml, weed/command/server.go, weed/filer/filer.go, weed/s3api/s3api_handlers.go, weed/s3api/s3api_server.go, weed/security/jwt.go, weed/server/filer_server.go, weed/server/filer_server_handlers.go
When making a request to a server at a different domain from a browser, the browser will impose a set of restrictions known as CORS. When making a request with credentials from a browser to a server on a different domain, the server with a different domain cannot accept the credentials in the usual way. The usual way is to use the header "Access-Control-Allow-Credentials" with value true. The browser fails the request when the "Access-Control-Allow-Origin" header has a value of *(wildcard). If the value of "Access-Control-Allow-Origin" is set to a specific domain, the browser will let the request through.
This issue appears when making a request to the Filer or S3 Gateway from a web client with credentials included. This happens when the client needs to send HTTP-only cookies to …
=> Set allowed origins in config

weed/command/filer_remote_gateway_buckets.go
- Chnaged ProcessEvenFn to be concurrent just like filer.remote.sync
So the problem appeared in a comparison between `filer.remote.sync` and `filer.remote.gateway`
In action `filer.remote.sync` was much more faster, and I measured the difference and it was something between 80x to 100x performance difference.
So I checked out the code and it was a simple procedure used in `filer.remote.sync` which I think is used for concurrency.
Here is the part of code I changed in `weed/command/filer_remote_gateway_buckets.go`:
```
// read filer remote storage mount mappings
if detectErr := option.collectRemoteStorageConf(); detectErr != nil {
return fmt.Errorf("read mount info: %v", detectErr)
}
eachEntryFunc, err := option.makeBucketedEventProcessor(filerSource)
if err != nil {
return err
}
processor …
```
=> Using filer.remote.sync concurrency in filer.remote.gateway

weed/shell/command_volume_fsck.go
Looks like `volume.fsck` collects all files in filer till `time.Now()` but volume needles are till  `-cutoffTimeAgo`  
So `volume.fsck` reports some false positive missing  files in volume servers
collect files in filer from `-cutoffTimeAgo`
Before fix:
```
warp put --insecure --host localhost:8333 --noclear  --obj.size 1KiB --concurrent 1 --noprefix
> volume.fsck -cutoffTimeAgo 5s -findMissingChunksInFiler
/buckets/warp-benchmark-bucket/11394.87m749gW5KB75qF1.rnd
/buckets/warp-benchmark-bucket/11396.jusCHNUdrzv4Yw(a.rnd
/buckets/warp-benchmark-bucket/11401.2FMrMvdJy1TnZd0f.rnd
/buckets/warp-benchmark-bucket/11404.NreBSco(vKG2eubJ.rnd
/buckets/warp-benchmark-bucket/11415.osX(4At7JylRjD2t.rnd
/buckets/warp-benchmark-bucket/11420.9eR8L)1kCyvVMXt8.rnd …
```
=> Fix cutoffTimeAgo in findMissingChunksInFiler

weed/shell/command_volume_fsck.go
Adding modifyTimeAgo to `volume.fsck` like `fs.verify`
Only collect volume needles and filer entries modified after `modifyTimeAgo` flag
I removed some files from filer and some other files from volume server and checked if `volume.fsck` can find missing chunks and files.
```
> volume.fsck -cutoffTimeAgo 0s -modifyTimeAgo 10m
total 2 directories, 162307 files
dataNode:192.168.91.169:8080    volume:2        entries:27196   orphan:1        0.00%   1059B
dataNode:192.168.91.169:8080    volume:3        entries:26898   orphan:1        0.00%   1059B
dataNode:192.168.91.169:8080    volume:4        entries:26662   orphan:1        0.00%   1059B
Total           entries:162310  orphan:3        0.00%   3177B
> volume.fsck -cutoffTimeAgo 0s -modifyTimeAgo 1m
total 2 directories, 162307 files
Total …
```
=> Add modifyTimeAgo to volume.fsck

k8s/charts/seaweedfs/templates/master-servicemonitor.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml
master pods metrics were not scraped by prometheus:
- missing `metricsPort` option
- and incorrect service monitor matching labels
- manually tested in my how deployment ! can do more ?
=> fix: k8s-chart-helm master metrics scraping

weed/server/volume_grpc_read_all.go
This removes an unneeded `err` variable from `streamReadOneVolume()`.
=> weed/server: remove unneeded err from streamReadOneVolume() signature

weed/server/webdav_server.go, weed/server/wrapped_webdav_fs.go
Pass ETag in webdav responses is not implemented
Added Etag function
locally
```
curl -I http://127.0.0.1:7333/test.pdf
Accept-Ranges: bytes
Content-Length: 202218
Content-Type: application/pdf
Etag: dd2de77517aa4534fa285899ae8a257a
Last-Modified: Wed, 03 Jan 2024 13:12:57 GMT
Date: Wed, 03 Jan 2024 13:17:35 GMT
md5 test.pdf              
MD5 (test.pdf) = dd2de77517aa4534fa285899ae8a257a
```
=> fix: return etag with md5 in webdav responses

weed/server/webdav_server.go
At the time of restart, the master server may be unavailable due to the selection of a leader and errors may occur during Assign operations. Which lead to the creation of empty files via webdav.
```
curl -T test.pdf http://127.0.0.1:7333/test/
Method Not Allowed
> fs.meta.cat /webdav/test/test.pdf
{
"name":  "test.pdf",
"isDirectory":  false,
"chunks":  [],
"attributes":  {
"fileSize":  "0",
"mtime":  "1704301263",
"fileMode":  438,
"uid":  501,
"gid":  20,
"crtime":  "1704301263",
"mime":  "",
"ttlSec":  0,
"userName":  "",
"groupName":  [],
"symlinkTarget":  "",
"md5":  "",
"rdev":  0,
"inode":  "0"
},
"extended":  {},
"hardLinkId":  "",
"hardLinkCounter":  0,
"content":  "",
"remoteEntry":  null,
"quota":  "0"
}chunks 0 meta size: 35 gzip:63
```
In case of chunk writing errors, deletes …
=> fix: webdav avoid create empty files

weed/s3api/s3api_bucket_handlers.go
https://github.com/seaweedfs/seaweedfs/issues/5155
https://github.com/seaweedfs/seaweedfs/issues/5155
locally
```
aws --endpoint-url http://127.0.0.1:8000 s3api get-bucket-versioning --bucket test --debug
2024-01-04 01:11:38,946 - MainThread - urllib3.connectionpool - DEBUG - http://127.0.0.1:8000 "GET /test?versioning HTTP/1.1" 200 125
2024-01-04 01:11:38,947 - MainThread - botocore.parsers - DEBUG - Response headers: {'Accept-Ranges': 'bytes', 'Content-Length': '125', 'Content-Type': 'application/xml', 'Server': 'SeaweedFS S3', 'X-Amz-Request-Id': '1704312698946573000', 'Date': 'Wed, 03 Jan 2024 20:11:38 GMT'}
2024-01-04 01:11:38,947 - MainThread - botocore.parsers - DEBUG - Response body:
b'<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Status>Suspended</Statu …
```
=> Fix missing VersionConfiguration node in get-bucket-versioning response

weed/command/server.go, weed/command/webdav.go, weed/server/webdav_server.go
By default, all files sent via the webdav are divided into 4 MB chunks
```
> fs.meta.cat /buckets/webdav/weed-large-disk-20240103-2027-linux-amd64.tar.gz
{
"name":  "weed-large-disk-20240103-2027-linux-amd64.tar.gz",
"isDirectory":  false,
"chunks":  [
{
"fileId":  "13,246c035113",
"offset":  "0",
"size":  "4193628",
"modifiedTsNs":  "1704444726306330276",
"eTag":  "NKVthpvjO2ajrLs0n0Nk8A==",
"sourceFileId":  "",
"fid":  {
"volumeId":  13,
"fileKey":  "36",
"cookie":  1812156691
},
"sourceFid":  null,
"cipherKey":  "",
"isCompressed":  false,
"isChunkManifest":  false
},
{
"fileId":  "13,26fc0594b9",
"offset":  "4193628",
"size":  "4193628",
"modifiedTsNs":  "1704444726481273482",
"eTag":  "+5FJ69N8Z7IJRpy5Jmb48w==",
"sourceFileId":  "",
"fid":  {
"volumeId":  13,
"fileKey":  "38", …
```
=> chore: add maxMB option for webdav

weed/command/filer_sync.go
I would like to have a backup cluster where nothing is deleted instantly.
Add an option to skip synchronization of deleted and updated files.
Trying to create an existing file will result in an error that can be ignored.
```
make test
```
=> chore: filer sync add doDeleteFiles option for create only mode

Makefile, weed/filer/stream.go, weed/operation/upload_content.go, weed/s3api/stats.go, weed/server/filer_server_handlers.go, weed/server/filer_server_handlers_read.go, weed/server/filer_server_handlers_read_dir.go, weed/server/filer_server_handlers_write.go, weed/server/filer_server_handlers_write_upload.go, weed/server/master_grpc_server.go, weed/server/volume_server_handlers.go, weed/server/volume_server_handlers_read.go, weed/stats/http_status_recorder.go, weed/stats/metrics.go, weed/storage/needle/needle_read.go, weed/topology/store_replicate.go
Monitoring response statuses from fillers and volumes
add code lable for request_total metrics 
```
make test
```
and localy:
```
make server
curl -vs -X DELETE http://127.0.0.1:8080/test
curl -vs -X GET http://127.0.0.1:8888/test
curl -vs -X DELETE http://127.0.0.1:8888/test
curl -s http://127.0.0.1:9324/metrics | grep request_total
SeaweedFS_filerStore_request_total{store="leveldb2",type="find"} 8
SeaweedFS_filerStore_request_total{store="leveldb2",type="prefixList"} 4
SeaweedFS_filer_request_total{code="200",type="DELETE"} 1
SeaweedFS_filer_request_total{code="404",type="GET"} 5
SeaweedFS_volumeServer_request_total{code="404",type="DELETE"} 2
```
=> chore: add status code for request_total metrics

weed/storage/needle/needle_write.go, weed/storage/volume_write.go
volume over size MaxPossibleVolumeSize
https://github.com/seaweedfs/seaweedfs/issues/5182
1. when write, n.Size is not init yet before prepareWriteBuf, so n.Size.IsValid()  alaways false!
2. v.nm.ContentSize() only have write data use size not include delete use size, so if volume has many delete ops(n) before full, more than n*32 bytes can also write to volume, even volume true offset is large than MaxPossibleVolumeSize
=> fix write volume over size MaxPossibleVolumeSize

docker/compose/local-sync-mount-compose.yml, weed/command/filer_remote_gateway_buckets.go, weed/command/filer_remote_sync_dir.go, weed/command/filer_sync.go, weed/command/filer_sync_jobs.go
At the first start, StartTsNs synchronization is not immediately saved in the KV
https://github.com/seaweedfs/seaweedfs/issues/5195
https://github.com/seaweedfs/seaweedfs/issues/5194
sync logs:
```
I0112 11:01:52.291144 filer_sync.go:283 sync 172.23.1.17:8889 to 172.23.1.22:8889 progressed to 2024-01-12 11:01:50.707339332 +0000 UTC 7.82/sec
I0112 11:01:53.668629 filer_sync.go:244 start sync 172.23.1.17:8889(26522631) => 172.23.1.22:8889(714225182) from 2023-12-30 07:32:41.375628109 +0000 UTC(1703921561375628109)
--
I0112 11:37:17.308526 filer_sync.go:283 sync 172.23.1.17:8889 to 172.23.1.22:8889 progressed to 2024-01-12 11:37:12.989976139 +0000 UTC 2.46/sec
I0112 11:37:20.519268 filer_sync.go:244 start sync 172.23.1.17:8889(26522631) => 172.23.1.22:8889(714225182) from 2023-12-30 …
```
=> Fix filer sync set offset

weed/command/filer_sync.go
if doDeleteFiles is false then the files are deleted 
```
/usr/bin/weed filer.sync -a  192.168.0.1:8889 -b 192.168.0.2:8889 -a.path / -b.path b.doDeleteFiles=false
I0112 10:51:34.052780 filer_sink.go:97 delete entry: /buckets/webdav/2/2/012975d1b383bde2750347ebdd6a5186a00fb9d9.json
```
invert login if 
```
localy
```
=> fix: doDeleteFiles deletes files

weed/storage/needle/needle_read.go, weed/storage/volume_checking.go, weed/storage/volume_read.go
vacuum volume when size mismatch, related https://github.com/seaweedfs/seaweedfs/pull/5190
put mismatch check in ReadData, so vacuuming can read data oversized。
1. write/and delete chunks, reproduce size mismatch
2. upgrade to this fixed version
3. vacuum can do well even size mismatch, and random check chunk csum is right
=> can vacuum volume when size mismatch

weed/command/scaffold.go
Minor typos in `weed scaffold --help` output.
=> chore: fix typos in scaffold help output

weed/server/filer_server.go, weed/server/filer_server_handlers.go
Check the storage life
filer healthz handler check filer store
localy
```
make server
curl -v http://127.0.0.1:8888/healthz
*   Trying 127.0.0.1:8888...
* Connected to 127.0.0.1 (127.0.0.1) port 8888
> GET /healthz HTTP/1.1
> Host: 127.0.0.1:8888
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: SeaweedFS Filer 30GB 3.62
< Date: Wed, 17 Jan 2024 10:04:23 GMT
< Content-Length: 0
```
=> chore: filer healthz handler check filer store

weed/command/filer_sync.go
#4758 [filer]filer.sync with default concurrency(32) leaves lot of orphans 
- `.uploads` folder is used during s3 multi-part uploads and will be deleted after a successful upload
- During filer.sync, as the real data is referenced by two files (the final file and temp file in .uploads), it will be synced twice
skip .uploads folder during sync
@chrislusf  may be it's a better idea not to include `.uploads` folder in system log?
- add `-s3` param to `local-sync-mount-compose.yml` 
- using the following python code to upload a large(100MB) file to node-1
```
from minio import Minio
from minio.error import S3Error
def main():
client = Minio("192.168.207.2:8333",
access_key="",
secret_key="",
secure=False
)
source_file = "test.mp4"
bucket_name = "test"
destination_file = "test.mp4"
found = …
```
=> fix: skip s3 .uploads

other/java/client/src/main/java/seaweedfs/client/SeaweedRead.java
When a file cannot be located, return 0 maybe not a good solution.
Issues in   #5218 
Throw an exception directly when the file cannot be located.
I would like to ask everyone, is it feasible to handle issues by directly throwing an IOException? This is to avoid the risk of falling into an infinite loop when calling the SeaweedInputStream.read method.
=> Update the solution when a file cannot be located.

k8s/charts/seaweedfs/templates/_helpers.tpl, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
While weed can have multiple disks passed as a parameter, this is not currently possible with the 
current Helm Chart. This PR solves essentially this. 
This is a problem because the only option to extend the cluster storage capacity is to either 
-  add a new node and install a new volume server  on it
-  add a new instance of the volume server on the same node (changing the antiafinity rule) 
Both options feels awkward/suboptimal when "weed" allows to manage multiple disk on one instance
- change of structures for data
The `data` property for `Values.volume` becomes `dataDirs` and is now an array.
- Changes in `templates/volume-statefulset.yaml`
- We basically loop over `dataDirs` to make sure we create the appropriate `volumes` and `persistenVolumeClaims" needed.
- `maxVolumes` is …
=> Enable multiple disks per volume server. Also streamline the use of /logs & /idx

weed/server/filer_server_handlers_read.go
```
____________________ test_get_object_ifmodifiedsince_failed ____________________
@pytest.mark.fails_on_dbstore
def test_get_object_ifmodifiedsince_failed():
bucket_name = get_new_bucket()
client = get_client()
client.put_object(Bucket=bucket_name, Key='foo', Body='bar')
response = client.get_object(Bucket=bucket_name, Key='foo')
etag = response['ETag']
last_modified = str(response['LastModified'])
last_modified = last_modified.split('+')[0]
mtime = datetime.datetime.strptime(last_modified, '%Y-%m-%d %H:%M:%S')
after = mtime + datetime.timedelta(seconds=1)
after_str = time.strftime("%a, %d %b %Y %H:%M:%S GMT", after.timetuple())
time.sleep(1)
e = assert_raises(ClientError, client.get_object, Bucket=bucket_name, Key='foo', IfModifiedSince=after_str)
status, error_code = …
```
=> fix: s3tests test_get_object_ifnonematch_good

weed/shell/command_volume_balance.go
The `volume.balance` command failed to properly balance volumes, because when
it sorted nodes by capacity, it used this comparison function:
```golang
func(a, b *Node) int {
return int(a.localVolumeRatio(capacityFunc) - b.localVolumeRatio(capacityFunc))
})
```
This doesn't work because `int(-0.1)` is zero, not a negative number, so nodes
were not properly sorted.
Make use of `cmp.Compare()` instead, which returns the expected
result. 
On a SeaweedFS cluster that was imbalanced, I ran `volume.balance`, but it didn't move anything. After applying this PR, I ran it again and this time it moved the volumes properly.
=> weed/shell: Fix volume.balance logic

weed/topology/topology.go
Metrics show SeaweedFS_master_replica_placement_mismatch count 1
```
SeaweedFS_master_replica_placement_mismatch{alias="dev-seaweedfs-03", cluster_name="dev_01", collection="s3tests-9l6epbl489iir29a082ua-10", group="seaweedfs_dev_01", id="121", instance="dev-seaweedfs-03.host:9324", job="seaweedfs_master_exporter", project="storage"} | 1
SeaweedFS_master_replica_placement_mismatch{alias="dev-seaweedfs-03", cluster_name="dev_01", collection="s3tests-9l6epbl489iir29a082ua-10", group="seaweedfs_dev_01", id="122", instance="dev-seaweedfs-03.host:9324", job="seaweedfs_master_exporter", project="storage"} | 1
SeaweedFS_master_replica_placement_mismatch{alias="dev-seaweedfs-03", cluster_name="dev_01", collection="s3tests-9l6epbl489iir29a082ua-12", group="seaweedfs_dev_01", id="126", …
```
=> fix: clean metric MasterReplicaPlacementMismatch for unregister volume

weed/shell/command_volume_balance.go, weed/shell/command_volume_balance_test.go
Reading through the `volume.balance` code, I noticed a few things that made the code more complex than it needed to be:
- The case where `*collection == "ALL_COLLECTIONS"` was treated separately, while it's actually taken care of by the default case in the if/else conditional;
- The `balanceVolumeServers*()` functions required a `volumeSizeLimit` argument, but never used it;
- The loop over a map used the `for key, _ := range x` syntax, instead of the equivalent `for key := range x` (which makes the linter happy).
See descriptions of the individual commits for details.
I ran the tests, deployed the new code on my test cluster and used the `volume.balance` command successfully.
=> weed/shell: Cleanup volume balance logic

weed/storage/volume_info/volume_info.go
The `*.vif` files are written with the executable bit set (`0755`), but there's no need for them to be executable.
Set `*.vif` file permissions to `0644` instead.
Changing permissions on `*.vif` files to `0644` and restarting `weed volume`, making sure everything still works properly.
=> weed/storage: Fix volume info file permissions

weed/filer/stream.go, weed/server/common.go, weed/server/filer_server_handlers_read.go, weed/server/volume_server_handlers_read.go
Return status 500 when volume server unavailable for at least one chunk; was returning status 206.
https://github.com/seaweedfs/seaweedfs/issues/5232
Split `StreamContent` in two parts,
- first prepare, to get chunk info and return stream function
- then write chunk, with that stream function
That allow to catch error in first step before setting response status code in `processRangeRequest`
That is the point, I would like to add unit tests on `processRangeRequest`, but I can not find other http test to follow them.
I don't know very much golang, Where can I begin to add them? Or may be e2e test could be enough, but seam to rely on `fio` only?
However, I tested it manually with curl requests after stopping volume servers.
=> fix: http range request return status 500

weed/shell/command_cluster_check.go
The `cluster.check` command only took the empty (`""`) and `hdd` disk types into consideration, but a cluster with only `ssd` or `nvme` disk types would be equally valid.
This commit simply checks that _any_ disk type is defined, and that some volumes are available for it.
Spawned a cluster and ran `cluster.check` on it.
=> weed/shell: Cluster check other disk types

.github/workflows/helm_chart_release.yml
Close #5264
Publish at new release (tags) instead of each push to master, to avoid silent breaking changes
@jessebot for your information
=> fix: publish helm chart at new release

weed/s3api/s3api_object_handlers_postpolicy.go
S3 POST form item to http header is missing. such as Cache-Control.
Add some S3 POST form item to header, include "Cache-Control", "Expires", "Content-Disposition" and "X-Amz-Meta-*"
By hand on a test server.
=> Add s3 postpolicy support header

weed/server/filer_server_handlers_write_autochunk.go, weed/server/volume_server_handlers.go, weed/util/constants.go
To avoid misunderstandings, this is not an internal error, as in fact there is no error that would be printed in the error log.
replaced the error code when canceling a request by a client from 500 to 499
localy
=> [volume] requests that were canceled by the client are not an internal server problem(500 => 499)

weed/server/filer_server_handlers_write.go
Too many logs when deleting non existing object in filer: "filer: no entry is found in filer store"
Make these "error" silent: only log error when not ErrNotFound
=> filer: reduce delete entry ErrNotFound logs

weed/shell/command_fs_verify.go
```
> fs.verify
file:/buckets/warp-benchmark-bucket/344.j30Nte2lxIjeumqI.rnd failed verify fileId 7,022ab2a353d3aa: rpc error: code = Unknown desc = not found
file:/buckets/warp-benchmark-bucket/344.htMZRe)4neHjD(M8.rnd failed verify fileId 7,022df7575d1b43: rpc error: code = Unknown desc = not found
total 7 directories, 147390 files
verified 147389 files, error 0 files
```
add a separate atomic counter 
```
file:/buckets/warp-benchmark-bucket/344.j30Nte2lxIjeumqI.rnd failed verify fileId 7,022ab2a353d3aa: rpc error: code = Unknown desc = not found
file:/buckets/warp-benchmark-bucket/344.htMZRe)4neHjD(M8.rnd failed verify fileId 7,022df7575d1b43: rpc error: code = Unknown desc = not found
total 7 directories, 147390 files
verified 147389 files, error 6250 files
```
localy
=> fix: fs verify error counter

weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_server.go
Permission verification is not performed when deleteing S3 bucket
add admin permission verification
=> fix: only admin auth can delete S3 bucket

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Not uniform and incomplete environment variable configuration
- Allow to reference variables from secret, in each deployed component
- Same from global extraEnvironmentVars
=> k8s-chart-helm: unify extraEnvironmentVars

weed/storage/store.go
`total_disk_size` is only shows actual disk size but there is no metric for deleted bytes
So we can't get find out what is size of collection content without deleted bytes
So I'm adding deleted bytes as a metric
But I have two questions:
1- should I add collectionVolumeDeletedBytes to `else` too? I didn't understand what is shouldDeleteVolume
```go
if !shouldDeleteVolume {                                                              
collectionVolumeSize[v.Collection] += int64(volumeMessage.Size)                     
collectionVolumeDeletedBytes[v.Collection] += int64(volumeMessage.DeletedByteCount) 
} else {                                                                              
collectionVolumeSize[v.Collection] -= int64(volumeMessage.Size)                     
if …
```
=> Add deleted bytes to total_disk_size

weed/command/compact.go
User running weed compact isn't informed what command is going to do.
There are two methods of data modification and none is listed as default
Adding short info in CLI help
If it compiles, it will be 👌
=> Document default method used by compact

k8s/charts/seaweedfs/README.md
Fixing an inconsistency between the helm chart readme and the wiki
Updating the helm chart readme to match the details on the wiki, with links to the relevant wiki article
Only a readme change, but I also tested running multiple filer replicas with leveldb on a K8s cluster and everything worked correctly, so the info in the wiki seems accurate.
=> Helm chart readme - clarify details about multiple filers and datastore

weed/command/filer_sync.go
Empty temporary folders are synchronized:
```
> fs.ls -l /buckets/some/.uploads
drwxrwxrwx   0 seaweed seaweed      0 /buckets/some/.uploads/fffb6e5dab032b115cbf196272e47a6cdbfa9ac9_6fad541aee2d46f0b1a9c5d63b31d380
total 6208
> fs.du /buckets/some/.uploads
block:   0	logical size:         0	/buckets/some/.uploads
```
Add a postfix slash to the check function
=> fix: sync without dir /buckets/some/.uploads/hash_hash

weed/replication/sink/s3sink/s3_sink.go
```
I0321 08:32:17.891003 s3_sink.go:78 sink.s3.region: us-east-2
I0321 08:32:17.891059 s3_sink.go:79 sink.s3.bucket: backups
I0321 08:32:17.891068 s3_sink.go:80 sink.s3.directory: /
I0321 08:32:17.891077 s3_sink.go:81 sink.s3.endpoint: http://lol:8333
I0321 08:32:17.891086 s3_sink.go:82 sink.s3.acl:
I0321 08:32:17.891110 s3_sink.go:83 sink.s3.is_incremental: false
I0321 08:32:17.891121 s3_sink.go:84 sink.s3.s3_disable_content_md5_validation: true
I0321 08:32:17.891130 s3_sink.go:85 sink.s3.s3_force_path_style: true
I0321 08:32:17.891139 s3_sink.go:86 sink.s3.keep_part_size: true
I0321 08:32:17.891149 s3_sink.go:92 sink.s3.uploader_max_upload_parts: 1000
I0321 08:32:17.891160 s3_sink.go:94 sink.s3.uploader_part_size_mb: 0
I0321 08:32:17.891170 s3_sink.go:95 sink.s3.uploader_concurrency: 8 …
```
=> fix: panic: assignment to entry in nil map on S3Sink.CreateEntry

weed/iamapi/iamapi_management_handlers.go
[#5401 ](https://github.com/seaweedfs/seaweedfs/issues/5401)
allow s3 configuration not exist when request iam
curl -X POST http://localhost:8111/?Action=ListAccessKeys
=> Fix iam service response 500

weed/s3api/s3api_objects_list_handlers.go
Fixes s3 api regression introduced in #5350 reported here: https://github.com/seaweedfs/seaweedfs/pull/5350#issuecomment-2014709870
Taking into account the prefix when splitting on the delimeter to decide whether or not something is a common prefix.
For the failing test the object was: `foo/bar`, with prefix `foo/` and delimeter `/`. the old code split on `/` even though `/` was in `foo/` so it included `foo/` as a commonPrefix when it shouldn't have been, only paths like: `foo/bar/baz` should get prefixed.
Tests are passing again, including the list for restic that @kmlebedev provided in the previous PR discussion.
=> fix s3api: delimeter properly takes prefixes into account

go.mod, go.sum, weed/weed.go
Defaults are chose to be as less impactful as possible.
To enable reporting some environment variables must be set
* SENTRY_DSN (from project settings)
* SENTRY_ENVIRONMENT (production, prod, test or whatever is used in organization)
* SENTRY_RELEASE (`weed@0.27.0`)
All defaults to empty string if not set.
I guess it's better to define Release option at compile time, but I personally prefer to pass it as environment variable.
Lack of monitoring in small environment.
Added support for sentry reporting. May be used with saas Sentry (free or paid) or self-hosted version.
Hope for gh actions
=> add basic support for sentry error reporting

docker/compose/test-etcd-filer.yml, weed/command/scaffold/filer.toml, weed/filer/etcd/etcd_store.go, weed/filer/etcd/etcd_store_test.go
This PR introduces several enhancements to the EtcdStore. The specific issues addressed include:
**1. Lack of TLS Handshake for Secure Communication**: Previously, communication with Etcd did not leverage TLS handshakes, leaving data transmissions potentially vulnerable to eavesdropping or tampering.
**2. Absence of Client Certificate Authentication**: The system did not support client certificate authentication with Etcd, limiting the ability to enforce stricter security policies.
**3. Initial Etcd Connection Check Missing**: The system proceeded without verifying the initial connection to Etcd, which could lead to failures in subsequent operations if the Etcd server was unreachable or misconfigured.
**4. Inaccurate key_prefix Handling in Etcd**: We're fixing a bug where file listing …
=> Add TLS support, initial etcd connection check, fix key_prefix handling for etcd backend meta storage

weed/command/shell.go
`-filer` option is ignored when `-master` is not set but master addresses present in config.
If in this case filer address exists in `shell.toml` too it for some reason icorrectly parsed and causes errors like
```
dial tcp: lookup 127.0.0.1:1111.1112,127.0.0.2: no such host
error: rpc error: code = Unimplemented desc = unknown service filer_pb.SeaweedFiler
transport: Error while dialing: dial tcp 127.0.0.1:11111: connect: connection refused
```
:warning: Note: I use non default grpc ports
Only working combinations I found:
1. both -master and -filer provided through command line / env
2. master address in config without filer address (so later one is auto-discovered)
1. Always checking for filer address
2. `*shellInitialFiler` dereferenced before usage
With hope for gh actions
=> fix filer address parsing

weed/filer/etcd/etcd_store.go
After modifying the ListDirectoryEntries function (in previous pr) and adding clientv3.WithRange(clientv3.GetPrefixRangeEnd(store.etcdKeyPrefix+string(directoryPrefix))), the implementation of ListDirectoryPrefixedEntries has become feasible, making the use of fsw.prefixFilterEntries redundant.
The logic of ListDirectoryEntries has been transferred to ListDirectoryPrefixedEntries, with the addition of prefix in the call to genDirectoryKeyPrefix. This makes the call to fsw.prefixFilterEntries unnecessary and reduces the complexity of the directory listing
Tested localy with s3cmd
Testing case:
1. upload test01 file to s3://bucket/
2. upload test02 file to s3://bucket/test/
3. upload test03 file to s3://bucket/test/
4. list s3://bucket/ output: 
5. list s3://bucket/test
6. list …
=> Move ListDirectoryEntries logic to ListDirectoryPrefixedEntries in etcd meta storage backend

weed/operation/assign_file_id.go, weed/stats/metrics_names.go, weed/topology/volume_growth_test.go, weed/topology/volume_layout.go
https://github.com/seaweedfs/seaweedfs/issues/3886
iDo grow if writable volumes not found in current dataCenter
1. make cluster
2. checking the empty list of volumes in dc3
```
> volume.list -dataCenter=dc3
Topology volumeSizeLimit:100 MB hdd(volume:6/1326 active:6 free:1320 remote:0)
DataCenter dc3 hdd(volume:0/442 active:0 free:442 remote:0)
Rack v3 hdd(volume:0/442 active:0 free:442 remote:0)
DataNode volume3:8083 hdd(volume:0/442 active:0 free:442 remote:0)
Disk hdd(volume:0/442 active:0 free:442 remote:0)
Disk hdd total size:0 file_count:0 
DataNode volume3:8083 total size:0 file_count:0 
Rack v3 total size:0 file_count:0 
DataCenter dc3 total size:0 file_count:0 
total size:0 file_count:0 
```
**Before**
3. put file **10.11s**
```
docker exec -it seaweedfs-filer-1 time curl -v -X …
```
=> [master] grow volumes if no writable volumes in current dataCenter

weed/filer/filerstore_wrapper.go
In certain scenarios (see #5426) , the prefixFilterEntries function could enter an  loop (not actually infinite, it has 10000limit) when processing file entries list with specific prefixes.
Adjusted the logic in the prefixFilterEntries function to improve the condition that determines when to continue processing records. The updated condition allows processing to continue only if the last processed filename is lexicographically smaller than the search prefix, preventing an infinite loop.
local tests with ceph s3 tests from #5427
=> fix: adjust condition in prefixFilterEntries prevent infinite loop

weed/s3api/s3api_objects_list_handlers.go
When using the etcd filer backend with SeaweedFS's S3 API, an issue has been identified related to gRPC stream handling in scenarios where the number of objects being listed is capped by the MaxKeys parameter. To reproduce this behavior, we can follow these steps with test data:
Three objects are created within a bucket using the ceph s3 tests create_objects method:
```create_objects(client, bucket_name, ['foo', 'bar', 'baz'])```
List Objects with MaxKeys: 
```client.list_objects(Bucket=bucket_name, MaxKeys=2)```
Error Log: Upon execution, the following warning is logged, indicating a premature stream closure caused by a context canceled error:
```{"level":"warn","ts":"2024-03-31T14:45:36.154175+0300","logger":"etcd-client","caller":"v3@v3.5.12/retry_interceptor.go:62","msg":"retrying of …
```
=> fix: ensure complete gRPC stream consumption in doListFilerEntries to prevent context canceled errors.

weed/storage/backend/disk_file.go
If sync fails then close is never called. We should always be calling close on the file.
The issue described in #4530 and #5066. When vacuuming the file is not closed properly so the file could not be deleted.
Always make sure to close the file, even if error occurs during sync.
By running the seaweed, storing data, clearing it and then letting the vacuum process run.
=> fix: always close volume file (#4530)

weed/s3api/filer_multipart.go, weed/s3api/s3api_object_copy_handlers.go, weed/s3api/s3api_object_multipart_handlers.go
If there are putObjectPart requests with the same uploadId during completeMultiPart, it can result in data loss. putObjectPart requests might be due to timeout retries.
S3 completeMultiUpload makes data lost.
If there are putObjectPart requests with the same uploadId during completeMultiPart, it can result in data loss. putObjectPart requests might be due to timeout retries.
Add an uuid id to the part object name to avoid covering, if this partId has retry requests.
1. I use aws go client SDK to simulate multi-upload, when doing completedMultiUpload to loop putObjectPart one part simultaneously.
2. read the object with readDeleted=false to check whether it has data lost.
=> fix completed multiupload lost data

k8s/charts/seaweedfs/values.yaml
`values.yaml `contains incorrect empty values for `volume.logs` and `volume.idx`
values.yaml contains incorrect empty values for `volume.logs` and `volume.idx`
Desk checked and tested in fork.
- [na ] I have added unit tests if possible.
- [na] I will add related wiki document changes and link to this PR after merging.
=> Correct type for volume logs and idx values

k8s/charts/seaweedfs/templates/s3-ingress.yaml, k8s/charts/seaweedfs/values.yaml
The s3 ingress is defined differently form the other components. A side effect of this is that the default for `s3.ingress.annotations` is set to be the wrong type resulting in the warning:
`coalesce.go:289: warning: destination for seaweedfs.s3.ingress.annotations is a table. Ignoring non-table value ([])`
Define the ingress in the same way as the other components.
Tested in local fork.
- [na] I have added unit tests if possible.
- [na] I will add related wiki document changes and link to this PR after merging.
=> helm chart: make s3 ingress annotations consistent

weed/s3api/filer_multipart.go
In https://github.com/seaweedfs/seaweedfs/pull/5460 was introduced new name.Entry format, also need to update listObjectParts function to prevent:
E0404 19:03:17.647191 filer_multipart.go:380 listObjectParts registry fd23b6c00eadbcf277506b49656f9f3064da3644_d76c4c6996374b4494e47656a925d1d6 parse 0001_e6d50f75-04f7-43ea-b31d-7c0ca54f9264.part: strconv.Atoi: parsing "0001_e6d50f75-04f7-43ea-b31d-7c0ca54f9264": invalid syntax
E0404 19:03:17.742943 filer_multipart.go:380 listObjectParts registry d1566cac57e95651a1996dc03775cd7057ea2081_456b792ee40d4c5b9ea5148bcc5eefdf parse 0001_e208f5fe-e2f8-44f9-89aa-389a3ffb8d69.part: strconv.Atoi: parsing "0001_e208f5fe-e2f8-44f9-89aa-389a3ffb8d69": invalid syntax
E0404 19:03:17.767043 filer_multipart.go:380 listObjectParts registry …
=> fix: correctly form partNumber from new entry.Name format in "listObjectParts"

weed/s3api/filer_multipart.go, weed/s3api/filer_multipart_test.go, weed/stats/metrics.go, weed/stats/metrics_names.go
https://github.com/seaweedfs/seaweedfs/pull/5466
Fix s3 test after https://github.com/seaweedfs/seaweedfs/pull/5460
before
```
> fs.meta.cat /buckets/s3tests-dd5yzog4kxg6oyf0sgvkz-1/mymultipart
{
"name": "mymultipart",
"isDirectory": false,
"chunks": [
{
"fileId": "17,274308ee6411",
"offset": "0",
"size": "8",
"modifiedTsNs": "1712310513156040000",
"eTag": "liHt+a4GC4KwqQsJleGvKA==",
"sourceFileId": "",
"fid": {
"volumeId": 17,
"fileKey": "10051",
"cookie": 149840913
},
"sourceFid": null,
"cipherKey": "",
"isCompressed": false,
"isChunkManifest": false
},
{
"fileId": "18,274416d812ee",
"offset": "8",
"size": "8",
"modifiedTsNs": "1712310513159642000",
"eTag": "runjjLTUDsJ5RUJWdTm0yA==",
"sourceFileId": "",
"fid": {
"volumeId": 18,
"fileKey": "10052",
"cookie": 383259374
},
"sourceFid": …
```
=> [s3] fix s3 test_multipart_resend_first_finishes_last 

.github/workflows/s3tests.yml, Makefile, weed/s3api/filer_multipart.go, weed/s3api/s3_constants/header.go
```
@pytest.mark.fails_on_dbstore
def test_multipart_upload():
bucket_name = get_new_bucket()
key="mymultipart"
content_type='text/bla'
objlen = 30 * 1024 * 1024
metadata = {'foo': 'bar'}
client = get_client()
(upload_id, data, parts) = _multipart_upload(bucket_name=bucket_name, key=key, size=objlen, content_type=content_type, metadata=metadata)
client.complete_multipart_upload(Bucket=bucket_name, Key=key, UploadId=upload_id, MultipartUpload={'Parts': parts})
>       client.complete_multipart_upload(Bucket=bucket_name, Key=key, UploadId=upload_id, MultipartUpload={'Parts': parts})
s3tests_boto3/functional/test_s3.py:6063: 
```
extracheck get entry
=> [s3] add s3 pass test_multipart_upload

.github/workflows/s3tests.yml, weed/s3api/filer_multipart.go, weed/stats/metrics_names.go
```
_________________________________ test_multipart_upload_size_too_small __________________________________
def test_multipart_upload_size_too_small():
bucket_name = get_new_bucket()
key="mymultipart"
client = get_client()
size = 100*1024
(upload_id, data, parts) = _multipart_upload(bucket_name=bucket_name, key=key, size=size, part_size=10*1024)
>       e = assert_raises(ClientError, client.complete_multipart_upload, Bucket=bucket_name, Key=key, UploadId=upload_id, MultipartUpload={'Parts': parts})
s3tests_boto3/functional/test_s3.py:6242: 
>           raise AssertionError("%s not raised" % excName)
E           AssertionError: ClientError not raised
```
return error if part size less 5mb
s3 tests in actions
=> [s3] add s3 pass test_multipart_upload_size_too_small

weed/filer/filechunk_manifest.go, weed/filer/stream.go, weed/server/filer_server.go, weed/server/filer_server_handlers_proxy.go, weed/server/filer_server_handlers_read.go, weed/util/http_util.go
Have the filer server authenticate reads with the volume server when the signing read keys are set.
https://github.com/seaweedfs/seaweedfs/issues/3352
The filer doesn't generate a JWT when reading data from the volume server resulting in unauthorised errors when fetching a file and the signing keys are configured.
Generate the JWT keys if configured and pass them in the request.
=> fix: filer authenticate with with volume server

weed/server/filer_grpc_server.go
chunks disorder after doing manifest in cleanupChunks. 
keep the original order
1. set ManifestBatch = 10
2. putObject  file size 52M, so the object will have one menifest chunk
3. CopyObject with src == dst ,make sure chunk is in order
=> fix append disorder

weed/shell/command_volume_balance.go, weed/shell/command_volume_fix_replication.go, weed/shell/command_volume_tier_move.go
After one volumeServer down, volume.fix.replication  fix volume replications only to one volumeServer.
`keepDataNodesSorted` sorted dataNodes by `float64(diskInfo.MaxVolumeCount-diskInfo.VolumeCount)`,but it only `diskInfo.FreeVolumeCount--` after fixed one volume.  So keepDataNodesSorted always gets the same result in fixing all under replicated volumes, this will make the first volumeServer full.
diskInfo.VolumeCount++ with diskInfo.FreeVolumeCount--
1. stop one volume server
2. volume.fix.replication fix under replicated volume to different volumeServers.
=> fix "volume.fix.replication" move many replications only to one volumeServer

weed/util/http_util.go
```
filer_server_handlers_read.go:291 failed to stream content /buckets/registry/docker/registry/v2/repositories/company/service/tags/_manifests/tags/latest/current/link: read chunk: http://192.168.1.21:8080/439,fc138c121ee17c6660855d43?readDeleted=true: 499 status code 499
```
499 code add to retry
=> filer read chunk retry if status code 499

go.mod, go.sum, weed/images/cropping.go, weed/images/resizing.go
disintegration/imaging was last updated in 2019 and uses x/image that has known issues.
cognusion/imaging forks master from upstream, includes unreleased commits from master, revs the relevant dependencies, and will be maintained for at least security updates.
Of note, this fork is being used by other projects that needed a modern fork of that package.
Existing test suite passed.
=> Migrates from disintegration/imaging c2019 to cognusion/imaging c2024.

weed/cluster/lock_manager/lock_ring.go
LockRing.lastUpdateTime was being set outside of a lock in SetSnapshot, and blowing up in race conditions.
This update properly uses the exiting locking.
Existing test suite passes. Contrived races now properly wait.
=> Fixes race with unlocked setter.

weed/util/log_buffer/log_read.go
in log_read.go, logBuffer.LastTsNs is being read _outside_ a lock. In log_buffer.go it is being written inside a lock.
As logBuffer is an RWMutex, I am using the Read lock/unlock to lock the reads.
Existing test suite passes.
=> Fixes unlocked read from logBuffer.LastTsNs that is racey.

weed/storage/volume_checking.go
https://github.com/seaweedfs/seaweedfs/issues/5508
skip file size checking for volume with TTL, since the compact deletes files with expired ttl
=> fix: skip file size checking for volume with TTL

k8s/charts/seaweedfs/Chart.yaml, k8s/charts/seaweedfs/templates/filer-ingress.yaml, k8s/charts/seaweedfs/templates/master-ingress.yaml, k8s/charts/seaweedfs/templates/s3-ingress.yaml, k8s/charts/seaweedfs/values.yaml
- fixes #5542 
Please read the above issue to learn more about this PR.
I've converted all annotations back to map types. The reason is that this is the default behavior of helm charts to have annotations be maps. I've also bumped the helm chart version to release the chart.
**Background**: The two PRs that originally changed these were because they said it allowed them to override annotations (https://github.com/seaweedfs/seaweedfs/pull/4799) but that can still be done by setting any of the annotation fields to `{}` if you'd like to not have any annotations, or by just using the standard map to supply your own in your local values.yaml.
The second PR (https://github.com/seaweedfs/seaweedfs/pull/5463) was to make all the annotations behave the same way, which is non-standard.
Clone the …
=> helm: Fix annotations parameters to be standard maps

weed/sequence/memory_sequencer.go, weed/server/master_server.go
1. a log "just for test" may be a history comment.   default config it will be used.
2. make 'raft' type clearer to create its sequencer
Its simple and no need new tests
=> reduce ambiguity about use memory_sequencer

weed/util/lock_table.go
This fixes a race condition in which multiple Goroutines release and acquire locks for the same file. Because the lock entries in the lock table and the counters in the lock entries themselves are independent and not synchronized, it can happen that two Goroutines acquire a lock and a third Goroutine releases the same lock in between them, leading to two lock entries being created. Those two lock entries would now wait forever on entry.cond.Wait() and can't proceed.
The fix is to track the locks that are in flight in the lock table itself, so that it knows when it is safe to release a lock before creating a second instance.
The `FUSE Mount` step in the e2e workflow is failing. This PR should fix it and make it succeed again.
=> Fix deadlock in lock table locks

weed/stats/disk_notsupported.go, weed/stats/disk_openbsd.go
Allowing OpenBSD to run seaweedfs. Without this change, disk sizes aren't available. 
`syscall.Statfs_t` is [slightly different.](https://github.com/golang/go/issues/47958) The code otherwise is identical.
I'm successfully running seaweedfs on OpenBSD/arm64. I haven't tested it on other architectures, but it should work the same.
=> Add support for OpenBSD

weed/command/fix.go, weed/storage/needle_map_memory.go, weed/storage/volume_checking.go, weed/storage/volume_vacuum.go
https://github.com/seaweedfs/seaweedfs/issues/5508
The expected file size is the same if the index contains deleted files
localy with deleted files
```
I0511 13:11:41.569305 needle_map_memory.go:54 max file key: fc138c121ef41b05 count: 78 deleted 69 for file: /tmp/test_214.idx
volume id:214  size:2753138712  collection:"test"  file_count:78  delete_count:69  deleted_byte_count:2549291818  replica_placement:100  version:3  ttl:261  compact_revision:147  modified_at_second:1715412455 
```
localy without deleted files
```
./unmaintained/see_idx/see_idx -volumeId 214 -collection test | sort -n -k 1
key:fc138c121e7a65a7 offset:1 size:6865369(6.55 MiB)
key:fc138c121ea23c2e offset:858176 size:8405250(8.02 MiB)
key:fc138c121ea56068 offset:1908836 size:7537738(7.19 MiB)
key:fc138c121ea979d9 …
```
=> fix: recreate index include deleted files

k8s/charts/seaweedfs/dashboards/seaweedfs-grafana-dashboard.json
See #5589 (I actually found more hardcoded values)
Replace all hardcoded datasource uids with the variable
Deployed on my Grafana instance.
=> Replace hardcoded datasource uids in the grafana dashboard

k8s/charts/seaweedfs/dashboards/seaweedfs-grafana-dashboard.json
We have seaweed deployed to multiple namespaces that we'd like to monitor. 
This adds a new variable for the namespace that allows us to select which one we want to monitor
Deployed to our Grafana instance
=> Allow selecting the namespace visualized by the grafana dashboard

k8s/charts/seaweedfs/templates/filer-servicemonitor.yaml, k8s/charts/seaweedfs/templates/master-servicemonitor.yaml, k8s/charts/seaweedfs/templates/s3-servicemonitor.yaml, k8s/charts/seaweedfs/templates/volume-servicemonitor.yaml, k8s/charts/seaweedfs/values.yaml
We deploy seaweedfs using the helm chart. Our Monitoring requires additional labels as it uses ServiceMonitorSelectors, which currently cannot be set.
Allow adding additional labels to the ServiceMonitor
* template rendered using "helm template"
* deployed in our internal cluster
=> Helm: Allow adding additional labels to the service monitors

k8s/charts/seaweedfs/values.yaml
When filer.secretExtraEnvironmentVars is configured, helm prints a warning during rendering (the result will still be correct):
```
coalesce.go:289: warning: destination for q-mes.seaweedfs.filer.secretExtraEnvironmentVars is a table. Ignoring non-table value ([])
coalesce.go:289: warning: destination for q-mes.seaweedfs.filer.secretExtraEnvironmentVars is a table. Ignoring non-table value ([])
coalesce.go:289: warning: destination for q-mes.seaweedfs.filer.secretExtraEnvironmentVars is a table. Ignoring non-table value ([])
```
I changed the default to be a dict. That seems to be the intended type, looking at the commented out example below.
Rendered the template using "helm template ."
=> Helm: Fix warning when rendering with secretExtraEnvVars set

k8s/charts/seaweedfs/dashboards/seaweedfs-grafana-dashboard.json
The Grafana dashboard in the helm chart still uses the deprecated AngularJS Graphs (resolves #5592).
I updated them using the Migration feature in the Grafana UI and exported them.
I reimported the Dashboard into our Grafana instance and the result looks fine.
=> Update the Grafana panels using the to the new time series

weed/replication/sink/s3sink/s3_sink.go
Async S3 replication wasn't working, because the Content-MD5 value was not encoded as base64.
https://github.com/seaweedfs/seaweedfs/issues/5572
The content-md5 value is encoded as base64.
=> [s3] Fixed s3 replication by sending content-md as base64

weed/iamapi/iamapi_management_handlers.go, weed/s3api/auth_credentials.go, weed/s3api/auth_credentials_test.go, weed/s3api/s3_constants/s3_actions.go, weed/s3api/s3_constants/s3_config.go, weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_server.go
iam DeleteBucket is added so the admin can give the permission to a different account to delete a specific bucket. 
we bypass the hasAccess check in the checkBucket function because the check was done before, when we check the iam permission, if iam permission are active, and we add the DeleteBucket iam in the iam permission check code
tested in a local setup where many s3 accounts are created with a single bucket
=> added s3 iam DeleteBucket permission management

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/post-install-bucket-hook.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
This change adds the possibility to configure the security context on pod and container for each component installed by the Helm chart.
By adding `podSecurityContext` and `containerSecurityContext` to each components section in the values.yaml.
If security context settings are provided and the `enabled` parameter is set to true, the values will be inserted.
```
master:
containerSecurityContext:
enabled: true
allowPrivilegeEscalation: false
```
No security context settings are provided by default.
* Deployed the latest version of the chart (3.67) into a new cluster
* Upgraded the installed release with the updated version of the chart
* Without setting the security context to ensure that no setting was injected during the upgrade
* With security settings added for each component, and …
=> Add ability to configure security context for the different components

weed/command/scaffold/filer.toml, weed/filer/mongodb/mongodb_store.go
a secure mongodb setup with security comes with tls/ssl encryption and user authentication.  The filer mongodb backend did only support connecting without encryption and authentication. This PR adds support for that.
Configuration in filer.toml can now be extended with additional configuration parameters as in this example:
```
[mongodb]
enabled = true
uri = "mongodb://localhost:27017/tls=true"
username = "seaweedfs"
password = "seaweedfs"
database = "seaweedfs"
ssl = true
ssl_ca_file = "./mongodb/ssl/ca.crt"
ssl_cert_file = "./mongodb/ssl/client.pem"
ssl_key_file = "./mongodb/ssl/client.pem"
```
Tested with my mongodb setup.
i think there is no dedicated wiki page for monodb yet, but if needed i can update wiki
=> add filer configuration options for username/password and tls

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Currently, the supported storage types are either persistent, or `hostPath`, so for ephemeral storage generally `hostPath` is used (e.g. logs storage).
`hostPath` mounts a directory from the host node's filesystem and can pose a security risk on shared/multi-tenant k8s clusters, so its usage is often restricted.
Adding support for `emptyDir` storage gives another option for ephemeral storage, which does not pose a security risk on shared/multi-tenant K8s cluster, so is generally allowed
Adding support for the `emptyDir` storage type in all places that allow defining a storage type.
This PR introduces `emptyDir` as a new option, and if it's not explicitly used in the `values.yaml` file, it has no effect on existing users.
Tested a deployment on a local K8s cluster, verifying that volumes …
=> helm chart - add support for emptyDir storage type

k8s/charts/seaweedfs/values.yaml
Currently when overriding the default value for `s3.resources` with own requests and limits installing or upgrading the release will output `coalesce.go:286: warning: cannot overwrite table with non table for seaweedfs.s3.resources (map[])`.
By changing the default value of `s3.resources` from `{}` to `null`.
* Deployed the latest version of the chart (3.67) into a new cluster using the following command
`helm upgrade --install seaweedfs --namespace seaweedfs --create-namespace -f .\override.yaml --version 3.67 seaweedfs/seaweedfs`
`override.yaml` contains the following example values.
```yaml
s3:
enabled: true
resources: |
requests:
memory: "64Mi"
cpu: "200m"
limits:
memory: "128Mi"
cpu: "500m"
```
This renders the output
```
Release "seaweedfs" does not exist. Installing it now. …
```
=> Helm: Fix warning when providing resource requests/limits for S3

k8s/charts/seaweedfs/Chart.yaml
Increasing the helm chart version to get a release with the [emptyDir storage](https://github.com/seaweedfs/seaweedfs/pull/5610) feature and the [s3 resources fix](https://github.com/seaweedfs/seaweedfs/pull/5611) that were merged yesterday
=> increase helm chart version to include the emptyDir storage feature

weed/shell/command_volume_server_leave.go
Fixes an error made when copying a `volume.unmount` command file.
=> Replaces volume.unmount in the help of the volumeServer.leave

weed/storage/needle_map_sorted_file.go
volume.fsck triggers (*SortedFileNeedleMap).Delete(), which is directly writing to .sdx file in `erasure_coding.MarkNeedleDeleted`, causing the command to fail.
We had to change O_RDONLY to O_RDWR to avoid error.
This is a bug-fix PR. No additional logic was introduced.
=> Fix sorted needle file's write mode for (*SortedFileNeedleMap).Delete()

weed/shell/command_volume_tier_upload.go
when the volume is already uploaded, VolumeTierMoveDatToRemote will return nil stream and nil error, causing `stream.Recv()` making SIGSEGV panic.
We added an additional check to avoid the panic.
This is a bug-fix PR. No additional logic was introduced.
=> Fix volume.tier.upload nil pointer panic

weed/shell/command_ec_encode.go
ec.encode and volume.tier.upload uses `collectVolumeIdsForEcEncode`, which does not ignores remote volumes, causing both commands to do extra work and outputting garbage messages.
We added an additional check to ignore the remote volume.
This PR is too minor to create a unit-test. However I've tested this code on my own production cluster.
=> Ignore remote volume when selecting volumes in operation (ec.encode/volume.tier.upload)

weed/shell/command_volume_fsck.go
volume.fsck is slow because:
1. it collects each volume server's data in single thread.
2. it checks each needle's modification time to verify it's before -cutoffTimeAgo time.
1. We query each volume server concurrently, so the performance would be better.
2. We allow user to manually disable -cutoffTimeAgo (by setting it to zero), so that situations like volume.fsck during maintainance downtime period would be faster.
I've test this change on our production seaweedfs cluster. However, I'm not sure whether a unit test is needed.
=> Support concurrent volume.fsck & support disabling -cutoffTimeAgo to improve speed

weed/stats/disk_common.go, weed/stats/disk_notsupported.go, weed/stats/disk_openbsd.go, weed/stats/disk_solaris.go, weed/stats/disk_windows.go
This pull request adds support for disks on the Solaris family of operating systems. Tested on Illumos. Also added divide-by-zero checks, and factored out common diskspace calculations to reduce code duplication.
=> Solaris disk support

weed/s3api/s3api_object_handlers_postpolicy.go
- according to: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html
- default status is 204
- change `case ... default: ` to set status `NoContent` as `204`
- generate presign post url to upload
- upload it, check status return 204
=> fix(s3api): make post api upload object default return 204

weed/server/master_grpc_server.go
Setting the capacity of clientChan to 100 is too conservative; it will block jobs like KeepConnected/SendHeartbeat/ProcessGrowRequest when a large number of events occur.
Set the capacity of clientChan to 10000
=> Set the capacity of clientChan to 10000

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml
The current Helm chart template doesn't mount the filer and master logs PVC when the type is set to `persistentVolumeClaim`.
References:
- [filer -logdir flag](https://github.com/seaweedfs/seaweedfs/blob/fce8fc1e16978e398f4d55177328ea50ac8210b9/k8s/charts/seaweedfs/templates/filer-statefulset.yaml#L132-L134)
- [filer volume mounts](https://github.com/seaweedfs/seaweedfs/blob/fce8fc1e16978e398f4d55177328ea50ac8210b9/k8s/charts/seaweedfs/templates/filer-statefulset.yaml#L200-L202)
- [master -logdir flag](https://github.com/seaweedfs/seaweedfs/blob/fce8fc1e16978e398f4d55177328ea50ac8210b9/k8s/charts/seaweedfs/templates/master-statefulset.yaml#L113-L115)
- [master volume mounts](https://github.com/seaweedfs/seaweedfs/blob/fce8fc1e16978e398f4d55177328ea50ac8210b9/k8s/charts/seaweedfs/templates/ …
=> Allow using a PVC to store filer and master logs

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
The current Helm chart template only allows defining global pod labels and annotations. This PR adds the ability to define labels and annotations at the component level.
Added `podLabels` and `podAnnotations` Helm values for each component.
I couldn't find tests for Helm chart templating with values other than the default. Please let me know if I missed them and I'm happy add tests.
I tested it e2e and I can see labels and annotations show up:
**Filer**
```bash
test.filer.annotation.key1: test.filer.annotation.value1
test.filer.annotation.key2: test.filer.annotation.value2
test.filer.label.key1: test.filer.label.value1
test.filer.label.key2: test.filer.label.value2
```
**Master**
```bash
test.master.annotation.key1: test.master.annotation.value1
test.master.annotation.key2: …
```
=> Allow defining labels and annotations per component

weed/server/master_grpc_server.go
In the KeepConnected function, the parameter req.ClientAddress that is passed in might be ""（weed shell...）, leading to:
1. Multiple clients using the same key in clientChans.
2. The following code segment may result in goroutine leakage.
```
go func() {
// consume message chan to avoid deadlock, go routine exit when message chan is closed
for range messageChan {
// no op
}
}()
```
fix: Ensure that the clientAddress is unique
=> fix: Ensure that the clientAddress is unique

weed/command/filer.go, weed/server/filer_server.go
[5455](https://github.com/seaweedfs/seaweedfs/issues/5455)
There is an issue in filer sync when new nodes are getting added to the cluster(config: 1 master, 3 filer, 3 volume) using leveldb2 filer. When we scale volume and filer on 4th node, it doesn't sync all the data from the start but picks any data within 1 minute range. 
Yes, the default behavior for seaweedfs remains same. If anyone wants to enable it, a flag is added in filer  "joinExistingFiler"
=> Fix Filer Sync Issue: 5455

weed/command/filer.go, weed/command/server.go, weed/server/filer_server.go
https://github.com/seaweedfs/seaweedfs/issues/5455
There is an issue in filer sync when new nodes are getting added to the cluster(config: 1 master, 3 filer, 3 volume) using leveldb2 filer. When we scale volume and filer on 4th node, it doesn't sync all the data from the start but picks any data within 1 minute range.
Yes, the default behavior for seaweedfs remains same. If anyone wants to enable it, a flag is added in filer "joinExistingFiler"
=> Meenakshi fix filer sync

weed/shell/command_volume_fsck.go
sometimes volume.fsck report 'volume not found' when a volume server has multiple disk types
reuse volumeId to VInfo map when is exists.
I have tested on my cluster.
=> fix issue: sometimes volume.fsck report 'volume not found'

k8s/charts/seaweedfs/Chart.yaml, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Convert all strings to be maps `{}` instead of strings `""` or `null` for `resources` parameters for all StatefulSets and Deployments, in order to be consistent with helm chart standards.
- Fixes #5681 
- Change all `resources: null` to `resources: {}` in values.yaml
- Change all instances of templating that string to templating a map. So from this:
```golang
{{- if .Values.filer.resources }}
resources:
{{ tpl .Values.filer.resources . | nindent 12 | trim }}
{{- end }}
```
To this (note we're using `with` which is an implicit `if`. This also removes the trim as it's not needed for maps:
```golang
{{- with .Values.filer.resources }}
resources:
{{ . | nindent 12 }}
{{- end }}
```
I've also bumped the chart version, but if this is merged, it will be a major version, as the previous types are …
=> fix #5681 convert all resources parameters to maps instead of strings

weed/shell/command_fs_verify.go
A full crawl creates a very excessive load on the filerStore if you need to check the recorded files for the last day, week, month
Get a list of files from the filler log
localy
```
make server
warp put --host=127.0.0.1:8000 --access-key=some_access_key1 --secret-key=some_secret_key1 --autoterm --duration 30s
fs.verify -v -metadataFromLog -modifyTimeAgo 2000s -concurrency 2
verified 1957 files, error 4178 files 
```
=> [fs.verify] getmeta data from filer log

weed/pb/filer_pb_tail.go, weed/shell/command_fs_verify.go
https://github.com/seaweedfs/seaweedfs/pull/5678
If data from the log has been updated or deleted, then do not consider this an error
If chunks are not found, then check for the presence of an entry in the filerstore
localy
=> [fs.verify] skip failed files if entry not found on filerStore

weed/shell/command_fs_verify.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x192be07]
goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/shell.(*commandFsVerify).verifyProcessMetadata.func1.1({0x2c16618, 0xc000d40f40})
/builds/infrastructure/utils/storage/seaweedfs/weed/shell/command_fs_verify.go:166 +0x107
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcFilerClient.func1(0xc0007dcc08)
/builds/infrastructure/utils/storage/seaweedfs/weed/pb/grpc_client_server.go:262 +0x68
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcClient(0xd0?, 0xc0?, 0xc0007a12d8, {0xc000d36480, 0x12}, 0x90?, {0xc0007a12c8?, 0xc0007a13b0?, 0xc0007a12e8?})
/builds/infrastructure/utils/storage/seaweedfs/weed/pb/grpc_client_server.go:129 +0x490 …
```
=> chore: hot fix panic fs.verify

weed/command/server.go
Addressed an inconsistency where the master.raftBootstrap option was assigned to cmdMaster instead of cmdServer.
The master.raftBootstrap option was incorrectly assigned to cmdMaster instead of cmdServer. This inconsistency could cause confusion and potential misconfigurations when users attempt to bootstrap the Raft cluster using the wrong command context.
I have corrected the assignment by changing cmdMaster.Flag.Bool to cmdServer.Flag.Bool for the master.raftBootstrap option. This ensures that the option is correctly tied to the cmdServer commands, aligning with the other master options.
Manual testing was performed to ensure that the master.raftBootstrap option works correctly in the cmdServer context.
=> fix: correct command flag for master.raftBootstrap option in server.go

k8s/charts/seaweedfs/templates/_helpers.tpl, k8s/charts/seaweedfs/values.yaml
/closes #5694
Currently, the computation of the image names is not in line with the values.yaml and a bit inconsistent. 
This simplifies the name handling to two core mechanisms:
1. You can use the default image. There is a common template for that, which can be configured
2. You can override the image name and by passing all parameters yourself
I also removed the db-schema image. It does not seem to be used.
I was thinking about splitting the image name into the image and repository path in the values-file aswell, to have it in the correct format `<registry>/<repository>/<name>:<tag>`. But that would probably break a lot of existing setups that already overwrite some parts of the image naming.
Rendered it with my own values file to see if I still get the same results.
There are some …
=> Helm-Chart: clean up image handling

k8s/charts/seaweedfs/templates/cluster-role.yaml, k8s/charts/seaweedfs/templates/service-account.yaml
/closes #5612 
The template has a flag for disabling the cluster role. This has the side-effect that disables the service account,  which breaks the deployment.
I moved the cluster role to its own template to make sure the service account is not accidentally toggled out.
Installed this without cluster role into a separate namespace.
I would love to see a wiki page explaining what the cluster role is for - the comments in the chart suggest that it is used for migration, but I don't really understand what is being migrated. Is that still required?
=> Move cluster role to a separate template.

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/service-account.yaml, k8s/charts/seaweedfs/values.yaml
Recently through PR https://github.com/seaweedfs/seaweedfs/pull/5721 cluster role creation and service account dependency is removed but there is still left over in filer startefulset where `serviceAccount` usage depends in `createClusterRole` condition which is unnecessary. 
Originally part of issue https://github.com/seaweedfs/seaweedfs/issues/5612
Also added option for automountServiceAccountToken for service account at global level
Remove the condition of `createClusterRole` condition usage from filer statefulset. 
Helm templated and installed.
=> [Helm chart] Remove createClusterRole dependency from serviceAccount usage from filer statefulset

weed/shell/command_volume_tier_upload.go
Old issue https://github.com/seaweedfs/seaweedfs/issues/3804 was said to be fixed but didn't seem to work
Fix loop so it doesn't exit on the first iteration.
=> volume.tier.upload: Fix deleting replicated volumes

weed/storage/disk_location.go, weed/storage/disk_location_test.go
Somehow my volumes are bigger than the volumeSizeLimit. I'm not sure how this happened, but when it does the calculation for how much unused space there is on a disk, there is an underflow on the unsigned integer, which causes it to report a large amount of unused space.
This results in no new volumes being allocated.
```
Jul 08 22:09:58 zaphod weed[2298821]: I0708 22:09:58.446979 store.go:600 disk /disks/disk1 max 64 unclaimedSpace:574462MB, unused:17592186039891MB volumeSizeLimit:30000MB
```
Perform the calculation of the per-volume unused space as a signed integer. Then we can check if we are <0 before adding it to the disk total unused space.
It does mean we have 2 casts, maybe there's a nicer way?
Manually and unit tests.
We can now see each volume reports it negative number in the …
=> Detect underflow when calculating unused space

weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_object_handlers_delete.go
return an error when deleting a file
There should not be a `filer_pb.ErrNotFound` error at this location
since it is already passed on the server side
https://github.com/seaweedfs/seaweedfs/blob/master/weed/server/filer_grpc_server.go#L296
=> [s3] revert skip deletion error, since the error file was not found is already skipped on the side of the grpc function

k8s/charts/seaweedfs/templates/filer-statefulset.yaml
/closes #5767 
* we generate a checksum of the s3-secret in an annotation. If the config is changed during an upgrade, the filer will automatically rolled over. 
* this is a common pattern in Helm: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
* This only applies to changes made via helm. Manual changes outside this chart will not trigger a rollover until the next helm upgrade.
* installed in a fresh namespace
* tested with disabled s3 config
* tested with enabled s3/auth 
* tested with enabled s3/auth and a custom secret
=> helm: restart filer when the s3-configuration changes

weed/topology/data_node.go
当volume server使用如下参数启动时：
```
weed volume -port=9001 -disk=hdd,ssd -dir=/data/weed/volume11,/data/weed/ssd11 -mserver=127.0.0.1:9333 -max=0
```
* 需设置不同的disk label
* 需设置-max=0参数
启动后，volume server第一次心跳上报最大volume数量为0，第二次心跳上报时会计算正确的volume数量上报给master，此时该BUG发生，其导致的结果之一是 `volume.list` 命令输出的结果不正确，且此问题必现，下面是一个有问题的输出示例
```
> volume.list
Topology volumeSizeLimit:30000 MB hdd(volume:0/2 active:0 free:2 remote:0) ssd(volume:0/0 active:0 free:0 remote:0)
DataCenter DefaultDataCenter hdd(volume:0/2 active:0 free:2 remote:0) ssd(volume:0/0 active:0 free:0 remote:0)
Rack DefaultRack hdd(volume:0/2 active:0 free:2 remote:0) ssd(volume:0/0 active:0 free:0 remote:0)
DataNode 10.10.132.90:9001 ssd(volume:0/0 active:0 free:0 remote:0) hdd(volume:0/2 active:0 free:2 remote:0)
Disk hdd(volume:0/2 active:0 free:2 …
```
=> Different disk labels should not use the same DiskUsages instance while master received volume heatbeat

weed/server/master_grpc_server_volume.go
近期我方随着迁移到seaweedfs的业务越来越多，生产开始频繁出现 `No more writable volumes` 错误，且在不重启master的情况下**无法恢复**，seaweedfs官方仓库近期有两个可能导致新volume创建卡住的pr，见 https://github.com/seaweedfs/seaweedfs/pull/5639 https://github.com/seaweedfs/seaweedfs/pull/5654
经过验证，这两个pr均未能彻底解决问题，于是开始尝试重现，观察日志，发现有两个要素
1. 业务量很大，频繁创建新volume
2. 创建新volume时，网络发生抖动，同时发生多次master leader选举
通过以下方式模拟生产问题
1. 使用如下命令模拟master节点网络不稳定（任意master节点，leader、非leader均可）
```
tc qdisc add dev ens192 root netem delay 12000ms
sleep 4
tc qdisc del dev ens192 root
```
2. 使用jmeter快速写入数据
3. 将单个volume size设置为100MB
经过模拟，每次网络抖动有超过30%概率导致 "no more writable volumes" 错误，且在master不重启的情况下 永远无法恢复。
通过在分配volume节点的各个分支判断处增加日志后发现，问题发生时，`VolumeLayout.growRequestCount`的值为1，这将导致该master节点将永远无法创建新的volume
https://github.com/seaweedfs/seaweedfs/blob/4e7d8eb3f167d2112cdb9c04308e68d6dc639997/we …
=> Fix "no more writable volumes" error when volume grows and master leader changed at the same time

weed/command/filer.go, weed/command/master.go, weed/command/s3.go, weed/command/server.go, weed/command/volume.go
1. There is a minor bug: the bindIp parameter was used for the metrics handlers, which was not replaced by the ip parameter if bindIp was not set.
2. There is a need for the ability to configure a separate IP address for the metrics handler. In unsecured networks, this handler cannot be set to localhost. I have made a fix for this.
To solve this, I added the metricsHttpIp parameter for all services that use the metrics handler.
For testing, I ran seaweedfs with the parameter `metricsHttpIp=localhost` and the `parameter ip=<host ip>`.
[ ] I have added unit tests if possible.
[+] I will add related wiki document changes and link to this PR after merging.
> Added flag descriptions.
=> -metricsIp cmd flag

weed/server/master_grpc_server_assign.go
The problem is described in #5818
The master server will still discard the grow request if not necessary in `ProcessGrowRequest`, but the assign request will fail before that.
By checking that the request is not necessary, the assign request and hence the write operation can succeed when there is a lot of volumes that are not crowded, but there are no free volumes to allocate. This usually happens when the cluster is full then cleaned up.
I tested the PR on our cluster of 8 volume servers + 1 master/filer server. Now the error will not be triggered.
=> Check `ShouldGrowVolumes` before returning error in assign.

weed/filer/filer_deletion.go, weed/server/master_grpc_server_volume.go, weed/server/master_server_handlers.go
if volumeServer set grpc.port , filer will fail to delete chunk, because master doesn't sync grpc port to filer.
`filer_deletion.go:59 deleting fileIds len=3 error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:19083: connect: connection refused"`
sync grpc port to filer when LookupByMasterClientFn
1. volumeServer set grpc.port
2. delete chunks success
=> fix delete chunk failed if volumeSever specified grpc.port

weed/shell/command_volume_server_evacuate.go
fix evacuate volume to different disk types
set different  types disk free count to -1
volumeServer.evacuate
=> fix evacuate volume to different disk types

weed/server/master_grpc_server_volume.go, weed/server/master_server.go, weed/server/raft_hashicorp.go, weed/server/raft_server.go, weed/topology/topology.go
when using HashicorpRaft， it may allocate a reduplicated volume ID to new volume just after restarting masters， the volume ID had been allocated to others。
when master restarts, it does these jobs:
1. restore snap
2. select leader , after this step, if leader master gets a growing request, the nextMaxVolumeId may be the old one in the raft log 
3. sync raft log
4. apply log
when the master became the leader， using raft.Barrier() to wait for all applying logs to be done, then began to serve leader service.
grow volume after restarting the masters.
=> fix allocate reduplicated volumeId to different volume

weed/command/filer.go
=> [filer] fix panic filer on webdav.maxMB

k8s/charts/seaweedfs/values.yaml
Signed-off-by: Andrei Kvapil <kvapss@gmail.com>
when isntalling with `global.enableSecurity: true` cert manager can't issue certificate, because it expects algorithm name passed in upper case
Update default value from `rsa` to `RSA`
=> fix case for keyAlgorithm in Helm chart

weed/shell/command_volume_fsck.go
increase fsck speed
Reading the needle meta takes too long if we have a big cluster.  
The volume needles if it is in entry chunks do not need to check the cutoff time. so only check the needles that would be deleted in fsck to increase performance.
1. upload some objects
2. delete  objects but not delete volume data
3. use fsck to repair
=> fsck: only check the appendNs of deleted needle

k8s/charts/seaweedfs/templates/cosi-cluster-role.yaml, k8s/charts/seaweedfs/templates/cosi-deployment.yaml, k8s/charts/seaweedfs/templates/cosi-service-account.yaml, k8s/charts/seaweedfs/values.yaml
Signed-off-by: Andrei Kvapil <kvapss@gmail.com>
This PR introduces automatic configuration for COSI Driver, which enables automatic provisioning of S3 Buckets in Kubernetes
fixes: https://github.com/seaweedfs/seaweedfs/issues/5838
I tested this PR manually as part of adoption SeaweedFS in Cozystack https://github.com/aenix-io/cozystack/pull/131 
We deploy SeaweedFS with enabled security settings
=> Add seaweedfs-cosi-driver

weed/command/backup.go
when run command backup destory volume has no error log
add command backup destory volume error log
=> add command backup destory volume error log

weed/command/update.go
tar包解压文件时，获取Header指针时会出现nil情况，此时打印数据获取Header.Name会报错
增加Header指针的判空分支
=> Fix extractToFile gz file nil bug

weed/command/s3.go
1. s3opt.certProvider.KeyMaterial return maybe nil, certs.Certs[0] get nil bug
2. receiver names are different
1. add judge nil
2. update receiver names to same
=> Fix KeyMaterial nil bug

k8s/charts/seaweedfs/templates/cosi-deployment.yaml
Fix secret mounting for seaweedfs-cosi-driver, in case seaweedfs running with `enableSecurity=true`
=> Fix secretName for seaweedfs-cosi-driver

weed/shell/command_volume_grow.go
https://github.com/seaweedfs/seaweedfs/pull/5821
ometimes you want to increase the number of active volumes in a comment, but it is not trivial to execute an assign http request
localy
```
> volume.grow 
> collection.list
collection:""   volumeCount:2   size:16 fileCount:0     deletedBytes:0  deletion:0
Total 1 collections.
```
=> [shell] volume.grow 

weed/server/webdav_server.go
https://github.com/seaweedfs/seaweedfs/issues/5864
All errors in the handler are returned as 404
Passed an error inside the file information structure and caught it in the etag search function
Localy
```
while true; do curl -o /dev/null -vs "http://127.0.0.1:7333/buckets/warp-benchmark-bucket/xyla1SAS/99.dIWkjopAvnLG(3VR.rnd" 2>&1;done
Accept-Ranges: bytes
Content-Length: 10485760
Content-Type: application/octet-stream
Etag: 07c5c42f36b1a44f4a04bf5989082a21
Last-Modified: Tue, 06 Aug 2024 09:17:59 GMT
Date: Tue, 06 Aug 2024 13:19:38 GMT
HTTP/1.1 500 Internal Server Error
Date: Tue, 06 Aug 2024 13:19:38 GMT
Content-Length: 21
Content-Type: text/plain; charset=utf-8
```
non-existent-file is 404
````
curl -o /dev/null -vs …
```
=> [webdav] status code 500 if internal error from filer

k8s/charts/seaweedfs/templates/volume-resize-hook.yaml, k8s/charts/seaweedfs/values.yaml
Currently Helm chart does not support updating PVC size of volumes server
Added hook which is triggered only if `.volume.dataDirs[*].type==persistentVolumeClaim` and `.volume.dataDirs[*].size` updated
the job is rendedred to:
```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
name: "seaweedfs-volume-resize-hook"
annotations:
helm.sh/hook: pre-install,pre-upgrade
helm.sh/hook-weight: "0"
helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
template:
spec:
serviceAccountName: seaweedfs-volume-resize-hook
restartPolicy: Never
backoffLimit: 1
containers:
- name: resize
image: bitnami/kubectl
command: ["sh", "-xec"]
args:
- |
kubectl patch pvc data1-seaweedfs-volume-0 -p '{"spec":{"resources":{"requests":{"storage":"20Gi"}}}}'
kubectl patch pvc data1-seaweedfs-volume-1 -p …
```
=> Add volume-resize-hook

weed/s3api/s3api_server.go, weed/s3api/s3err/error_handler.go
added support of `Access-Control-Expose-Headers` in response to facilitate access to keys present in the Response Header.
Added `Access-Control-Expose-Headers` to `setCommonHeaders` function in file `weed\s3api\s3err\error_handler.go`
Ran the updated seaweedfs code and tested it in browser.
=> added access-control-expose-headers to put request

weed/server/master_grpc_server.go
当一个volume server停止服务时，调用lookup接口查询某个volume的位置时，会出现调用不同的master节点，返回不同的ip列表的情况；
进一步排查发现只有ec后的volume会有这个情况：
1. leader节点返回的ip列表没有停止服务的机器
2. 非leader节点会继续返回已经停止服务的机器
解决办法：
1.通过代码debug发现在master接收volume心跳时，defer代码中会删除停止心跳的volume server的volumes和ec shards，但是处理ec shards时，没有将ec shards正确的添加到对应的slice
2.在判断是否需要通知其他节点时，因为正常停机时，volume server会发出停机心跳，所以volume的信息其实在其他地方已经处理了，这时的 `len(message.DeletedVids) > 0` 是不能匹配的，需要增加判断条件，针对ec shards的变化通知其他节点
=> fix ec volume lookup data sync

weed/s3api/s3api_object_handlers.go
The net.http client has a feature for lazy decoding of content. For example:
The server responds with Content-Encoding: gzip.
The HTTP client decodes the gzip content and returns the body.
However, this behavior is now triggering another bug in the code at weed/s3api/s3api_object_handlers.go:214.
When the Accept-Encoding header is not provided, the server returns a 404 error. If I add a condition based on the request method, the response differs from what is expected. For instance, Minio and Ceph do not unpack the responses and return them as-is, including all the original headers (such as Content-Encoding).
added Accept-Encoding: identity in proxyToFiler
PUT file with content-encoding: gzip
GET without header accept-encoding and receive 200 with content-encoding: gzip
GET with header …
=> Dont try lazy decode content in proxyToFiler if no accept-encoding provided

weed/server/master_server.go, weed/server/master_server_handlers_admin.go, weed/topology/collection.go
get the size of a collection without using the cli is useful in a context where we use seaweedfs as a microservice and we want to meter the fs usage for a given user, that writes in a single s3 bucket. Using s3 api is slow because we have to loop over all files. So this endpoint comes very useful to get directly from seaweedfs the total usage with a single call.
The endpoint is `/collection/info` with POST form fields:
- `collection`
- `detail` (if 'true' provides details for each volume, otherwise only the total)
=> add http endpoint to get the size of a collection

k8s/charts/seaweedfs/values.yaml
The values.yaml file was missing the configuration for the logs storage, which was already correctly set up in the templates/filer-statefulset.yaml and templates/master-statefulset.yaml files. 
[5653](https://github.com/seaweedfs/seaweedfs/pull/5653)
Added the following configuration for master and filer to the values.yaml file to ensure consistency across all related components:
```
```
The changes were validated by deploying the updated Helm chart in a test environment, ensuring that the logs are correctly provisioned.
=> Allow using a PVC to store filer and master logs - changes in values.yaml

weed/shell/command_remote_mount_buckets.go
Incorrect (I think?) help strings for command documentation.
Correcting the help string.
untested, doc string change, are there tests for that?
=> filer.remote.gateway not filer.remote.sync for remote.mount.buckets help string.

weed/command/filer_remote_gateway.go
See also related PR #5934 
Incorrect (I think?) help strings for command documentation.
Correcting the help string.
untested, doc string change, are there tests for that?
=> filer.remote.gateway not filer.remote.sync for filer.remote.gateway help string.

weed/storage/volume_read.go
This allows to spot bitrot problems at volume servers with metric monitoring during routine cluster operation.  Without this patch CRC errors are not reported to a metric server during reading of a file from a fuse mounted filesystem. 
We add `stats.VolumeServerHandlerCounter.WithLabelValues(stats.ErrorCRC).Inc()`
call when CRC error is detected. It is done in a similar manner as it is already implemented in   `ReadBytes` from `weed/storage/needle/needle_read.go` code.
Hand checked by creating a corrupted volume. Than reading a corrupted file from fuse filesystem. Observed the entries related to `ErrorCRC` shows up at `SeaweedFS_volumeServer_handler_total` metric.
It is quite strange but it seems that `ReadBytes` from  `weed/storage/needle/needle_read.go`  code is not unused when a file …
=> update metric for ErrorCRC if it happens during volume readNeedleDataInto

weed/shell/command_fs_verify.go
If volume replication is large then 1 it is useful to know which volume server has problems.
This patch adds volume server info to the log message of `fs.verify` shell command.
Manually, by created 2 replicas and corrupting a file in one of them.
=> Show volume server which failed to verify a chunk

weed/storage/volume_backup.go
volume.move tail EOF
`move hdd volume 143180 xx => xxfailed, err:tail volume 143180 from xx to xx: rpc error: code = Unknown desc = streamFollow: fail to locate by appendAtNs 1724628315000000000: read entry 3088: EOF`
check max entryCount when readRightNs
move the err volume success
=> fix volume.move io.EOF

weed/s3api/stats.go
Metrics are created for non-existent buckets
```
curl -s http://127.0.0.1:9324/metrics | grep LIST                                                            
SeaweedFS_s3_request_seconds_bucket{bucket="withouttest",type="LIST",le="0.0001"} 1
SeaweedFS_s3_request_seconds_bucket{bucket="withouttest",type="LIST",le="0.0002"} 1
SeaweedFS_s3_request_seconds_bucket{bucket="withouttest",type="LIST",le="0.0004"} 1
SeaweedFS_s3_request_seconds_bucket{bucket="withouttest",type="LIST",le="0.0008"} 1
SeaweedFS_s3_request_seconds_bucket{bucket="withouttest",type="LIST",le="0.0016"} 1
SeaweedFS_s3_request_seconds_bucket{bucket="withouttest",type="LIST",le="0.0032"} 1
SeaweedFS_s3_request_seconds_bucket{bucket="withouttest",type="LIST",le="0.0064"} 1 …
```
=> [s3] reducing the number of metrics for 403

weed/storage/volume_read.go
…  to a writer.
Partial fix for issues #5972 and #5959
Also improves, error message which reports which needle and at what volume is faulty.
Partial fix for issue #5972, i.e. non reporting CRC errors by volume server on request of a needle.
At least we get error message when the full needle is requested.
If the complete needle is already in the buffer, we check CRC before `write`. If CRC is wrong,
the error is generated and *no write* is done.
A check of partially read needle (when offset >0 and/or required data size is smaller then needle) requires change of the logic (since only full needle has error). Also if buffer is smaller than the needle, we cannot perform the CRC check before data is sent.
Manually:
~~~~~~~~~~~
> curl -w '%{header_json}\n%{http_code}\n' …
=> Do CRC check if the buffer contains the full needle data before it is sent

weed/server/common.go
The code which attempts to send the data, sets Content-Length to expected values. But if there were an error and we issue http.Error the Content-Length header should be reset to the error message length.
This should be unnesesary, since it is already done net/http package, see
https://cs.opensource.google/go/go/+/refs/tags/go1.23.0:src/net/http/server.go;drc=773767def0e0f29584a69bd760430167b7479d7d;l=2245
But maybe SeaweedFS uses an earlier version.
This is followup to commit bc01f09
which generates proper http headers in case of the http.Error call
We Del "Content-Length" which automatically recreated with the proper length.
Manually
~~~~~~~~~~~~~~
curl -w '%{header_json}\n%{http_code}\n'  http://redacted.net:18081/3,049728c119 -o tt
% Total    % Received % Xferd  Average Speed   Time …
=> Remove "Content-Length" header if http.Error is issued

k8s/charts/seaweedfs/values.yaml
As we discuss in #1627, volume server will meet issue https://github.com/seaweedfs/seaweedfs/issues/3964 if /status is used as a liveness probe/readiness probe while the size of response body is larger than 10KB, caused by https://github.com/kubernetes/kubernetes/issues/122948, and probe.Warn (instead of probe.Succeess currently) after https://github.com/kubernetes/kubernetes/pull/122970.
Use `/healthz` instead of `/status` as default route in readiness/liveness in helm chart values file.
Helm templated and installed.
=> [Helm chart] use `/healthz` as default route in readiness/liveness

weed/util/chunk_cache/chunk_cache.go
The patch addresses issue #3745.
The cache should return the exact amount of data requested by the buffer. By construction of the cache it is always all requested data range or we have error happening.
The old use of minsize miscalculate the requested data size, if non zero offset is requested.
Redownloading of cached needles, if the cache request comes with non zero offset.
Manually.
=> bug fix in the data received from cache processing

weed/filer/reader_at.go, weed/filer/reader_at_test.go, weed/filer/reader_cache.go, weed/util/chunk_cache/chunk_cache.go
The patch addresses #3745.
In particular it protects against putting the same needle into the cache multiple time. This is done by implementing a new method which checks if fileId is already in the cache.
It also does not create `downloader` if fileId is already in the cache. This would not
be normally triggered prior to the patch since only the 1st needle of a file were subject to caching.
New feature: several needles of the large file are cached as long as they collectively less than `maxFilePartSizeInCache` (new parameter in the Chunk Cache).
Rationale for the above: prior to the parch only the first needle of a file was subject to caching (2MB by default). This is quite small size for a modern data analysis. With this patch,  the cached portion of a file limited to total permitted …
=> Feature limit caching to prescribed number of bytes per file

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml
The Filer StatefulSet was missing `ports` declarations for the s3 and s3-tls ports when filer.s3.enabled is true. The s3 Deployment was missing a `ports` declaration for s3-tls.
These modifications do not bring any functional changes: `ports` declaration are mostly informational.
Adding the appropriate `ports` declarations in the Helm templates.
Manual generation and inspection of the Helm charts:
- When disabling `filer.s3.enabled`/`s3.enabled`, no swfs-s3 ports are present in the resulting chart.
- When enabling `filer.s3.enabled`/`s3.enabled`, swfs-s3 ports are present in the filer STS/s3 Deployment and their associated Services
- When enabling `filer.s3.enabled`/`s3.enabled` and setting a non-zero value for `httpsPort`, swfs-s3-tls ports are present in the filer STS/s3 Deployment and …
=> helm chart: add s3 and s3-tls ports where missing

weed/filer/cassandra/cassandra_store.go
At the moment, all errors from Casandra's "FindEntry" are being replaced with "filer_pb.ErrNotFound". The (fs *File server) DeleteEntry method returns err = 'nil' if "FindEntry" returned filer_pb.ErrNotFound. Because of this, we cannot accurately determine whether the object has been deleted if cassandra was experiencing problems.
It is suggested to return all errors about cassandra, except Not Found, if they were received during the data collection process
=> changing FindEntry error handling in cassandra store

weed/operation/upload_content.go
Addresses #5524
Prior to the patch, the encryption disabled compression.
Now we compress (if beneficial) ==> encrypt (if requested). As result, data takes less space on the volume servers.
Lucky bonus: the old volumes/meta is compatible with new method, since `isCompressed` flag was always `false` when encryption is on.
Effectively by not disabling compression.
filler was run with `-encryptVolumeData`, test data was saved into the weed fuse mount, the data was read back and checksums were compared. No deviation was observed. Meanwhile the volume server storage was checked, and it shows that it takes less space than uncompressed file sizes.
A relevant part of `fs.meta on_a_file`
````
"cipherKey": "HY/Kzc9W26EQIzBC8sX7LGQ7lpzBNiTkY+DvVj7KJtA=",
"isCompressed": true,
````
=> Feature: compress before encryption

weed/filer/filechunk_group.go, weed/mount/filehandle_read.go
I encounter the following panic, function `Read` tries to read offset larger than file size.
```
ActiveLock 83 Read unlocked 2119352381 type=0 with waiters 0 active r0 w0.
ActiveLock 84 Read locked 2119352381 type=0 with waiters 0 active r0 w0.
I0907 12:06:52.668940 reader_at.go:179 zero2 [0,1048576) of file size 13 bytes
I0907 12:06:52.669356 page_writer.go:54 ReadDirtyDataAt 2119352381 [61931325, 62979901)
ActiveLock 84 Read unlocked 2119352381 type=0 with waiters 0 active r0 w0.
ActiveLock 85 Read locked 2119352381 type=0 with waiters 0 active r0 w0.
I0907 12:06:52.686595 reader_at.go:179 zero2 [0,1048576) of file size 13 bytes
I0907 12:06:52.686950 page_writer.go:54 ReadDirtyDataAt 2119352381 [62979901, 64028477)
ActiveLock 85 Read unlocked 2119352381 type=0 with waiters 0 active r0 …
```
=> fix invalid file read

weed/server/filer_server_handlers_write.go
```
curl -v -X DELETE http://localhost:8888/buckets/test/lol.pdf
* Host localhost:8888 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8888...
* connect to ::1 port 8888 from ::1 port 61713 failed: Connection refused
*   Trying 127.0.0.1:8888...
* Connected to localhost (127.0.0.1) port 8888
> DELETE /buckets/test/lol.pdf HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Server: SeaweedFS 30GB 3.73
< Date: Mon, 16 Sep 2024 07:48:53 GMT
< Content-Length: 0
```
```
curl -v -X DELETE http://localhost:8888/buckets/test/lol.pdf
* Host localhost:8888 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8888...
* connect to ::1 port 8888 from ::1 port 62455 failed: Connection refused
*   Trying …
```
=> [filer] fix return 204 for DELETE on entry not found

weed/storage/volume_checking.go, weed/storage/volume_loading.go
https://github.com/seaweedfs/seaweedfs/issues/6031
After truncate idx file get not working volume
Let's just raise an error from the function above to try to sort the idx file
=> [volume] remove truncate idx file if size not healthy

weed/shell/command_volume_check_disk.go
https://github.com/seaweedfs/seaweedfs/issues/6000
for the pair volume A and B(A's file count great than B)
- append entries in A and not in B to B.
- Regardless of whether an error occurs, do next:
- append entries in B and not in A to A.
After each round of sync, choose the larger volume to be the source.
We tested it as follows:
```shell
lock; volume.check.disk -nonRepairThreshold 1.1 -slow -syncDeleted -v -volumeId 30508 -force; unlock;
```
After the modifications, we were able to fix the previously unfixable volumes.
=> Vol check disk bug

weed/s3api/s3api_server.go
The lastTsNs must be before configuration is first loaded.
=> fix: Prevent potential metadata change events from being lost.

weed/server/raft_server.go
master  failed  send rpc to peers for empty grpc address.
SeaweedFS master start with null string for connectionString itself, only set peers' connectionString.
it works for most cases,because leader do not need to flush rpc to itself.
When it  takes a snapshot, master will recoder all connectionStrings to file include itself.
1. if the follower restart it will reload leaders snapshot, then the leader's connectionString will be empty from view of the follower.
2. This follower becomes a leader for some reason, it will fail to the flush rpc to the original leader.
Init connectionString with server's grpc value.
check snapshot file.
=> master:fix empty target in Build()

k8s/charts/seaweedfs/values.yaml
Signed-off-by: Andrei Kvapil <kvapss@gmail.com>
Fix an issue when buckets are created as files, not as folders
see https://github.com/seaweedfs/seaweedfs-cosi-driver/pull/1
yes
=> Bump COSI-driver version v0.1.2

weed/filer/filerstore_wrapper.go
https://github.com/seaweedfs/seaweedfs/issues/6072
replace error  table doesn't exist to filer_pb.ErrNotFound
=> [filer] avoid 500 if table doesn't exist

weed/server/volume_grpc_erasure_coding.go
fix ‘no space left’ bug
If current location found current Volume ec, will cause location is nil ( ' no space left '), redundant judgment
Return true or remove func
=> Update volume_grpc_erasure_coding.go , fix no space left bug

k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
The helm chart doesn't seem to support running multiple volume servers with host paths for mounts. 
I have 5 drives mounted in one machine. With a replication of 000 I could mount all the drives into the volume server and it would work. But to support replication between drives I found that really needed multiple volume servers. When I tried to increase the number of replicas I found the mounts weren't generic enough and I could get 1 pod running but not any more. 
Ultimately I could use `extraVolumeMounts` and `subPathExpr: $(POD_NAME)` to generically mount in the pod, but  the dataDirs logic always created a volumeMount that conflicted with anything I put in extraVolumeMounts. 
Added a "custom" type for the dataDirs parameter to allow use of extraVolumes and extraVolumeMounts 
After …
=> feat: Add support for "custom" dataDirs type for volume server in kubernetes helm chart

k8s/charts/seaweedfs/templates/volume-statefulset.yaml
This PR addresses open issue #6106. Currently, when deploying SeaweedFS via a Helm chart, if custom dataDirs are specified in the values.yaml file and the maxVolumes parameter is not included, the deployment fails with the following error:
"volume.go:169 The max specified in -max not a valid number -ip.bind=0.0.0.0"
The following comment is present in the default values.yaml file included in the chart:
"maxVolumes: 0  # If set to zero on non-windows OS, the limit will be auto configured. (default "7")
I interpreted this comment as three cases:
1. If maxVolumes is not present, set the default to 7,
2. If maxVolumes is present and is equal to 0, set the value to 0, or
3. If maxVolumes is present and is not equal to 0, set the value to the number specified
I found that I could not use a …
=> Fix dataDirs.maxVolumes default value when not included in a values.yaml

weed/s3api/stats.go, weed/server/filer_server_handlers.go, weed/server/volume_server_handlers.go, weed/stats/metrics.go, weed/topology/store_replicate.go
Resolves ##6117
The in-flight request metric currently does not exist. 
add in-flight metric for s3/file/volume-server
=> feat: add in-flight metric for s3/file/volume-server

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Trying to spread the pods across AZs.
By providing an option to specify `topologySpreadConstraints`.
Helm was deployed to an existing cluster and proper topology spreading was verified.
=> Support topologySpreadConstraints in helm chart

k8s/charts/seaweedfs/templates/filer-cert.yaml, k8s/charts/seaweedfs/templates/filer-service-client.yaml, k8s/charts/seaweedfs/templates/filer-service.yaml, k8s/charts/seaweedfs/templates/filer-servicemonitor.yaml, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-cert.yaml, k8s/charts/seaweedfs/templates/master-configmap.yaml, k8s/charts/seaweedfs/templates/master-service.yaml, k8s/charts/seaweedfs/templates/master-servicemonitor.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/s3-service.yaml, k8s/charts/seaweedfs/templates/s3-servicemonitor.yaml, k8s/charts/seaweedfs/templates/volume-cert.yaml, k8s/charts/seaweedfs/templates/volume-service.yaml, k8s/charts/seaweedfs/templates/volume-servicemonitor.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Added resource-level annotations to be able to set helm chart hooks globally
I want to add SeaweedFS as a subchart of other Helm Charts, and I want to use Helm Hooks to install it before the parent Helm Chart.
Adding annotations at the resource level for the resources
`helm template seaweedfs k8s/charts/seaweedfs -f values-override.yml`
=> feat: add resource annotations

other/metrics/grafana_seaweedfs.json
Replaced `SeaweedFS_filer_` with `SeaweedFS_filerStore_` because the metric name was not found.
The grafana dashboard is not using the correct metric name for the filer
Updating the json to have the correct string
In my local grafana instance with version 2.7.6 (large disk) running
=> Fix invalid metric name

weed/server/filer_server_handlers_write_autochunk.go
to resolve comment: https://github.com/seaweedfs/seaweedfs/pull/5983/files#r1803961113
pass correct file name instead of empty string
=> fix permission check in put request

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Trying to pass additional parameters to filers.
By providing an option to specify `rack` and `dataCenter`.
Deployed to cluster and tested the config.
=> Support specifying rack and dataCenter for filers in helm chart

weed/mount/weedfs_rename.go, weed/server/filer_server_handlers_write.go
renaming should not be allowed for worm files/dirs, since a file may be moved from a worm path to a non-worm path
check if it is a worm file/dir before renaming
=> stop renaming worm files

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/notification-configmap.yaml, k8s/charts/seaweedfs/values.yaml
Following #6155, adding the possibility to configure event notifications by setting the content of the `notification.toml` configuration file from the helm chart.
Expose `filer.notificationConfig` in values, which can be a multi-line string that will be mounted at `/etc/seaweed/notification.toml`.
I based most of the code on the work done for `master.toml`.
**Note**: I've also bumped the chart version (major).
Clone the repo and `cd k8s/charts/seaweedfs/` and run:
```
git checkout master
helm template . > output-master.yaml
git checkout dacalabrese-filer-notification-config
helm template . > output-filer-notification-config.yaml
diff --color output-master.yaml output-filer-notification-config.yaml
```
The output shows the addition of introduced resources:
```
31a32,48
> # Source: …
```
=> [helm] Allow setting notification.toml config

weed/server/master_grpc_server.go, weed/stats/metrics.go
when master thransfer leader, the old master will disconnect with all filers and volumeServers, if the cluster is a big one, the broadcast messages may be much more than the max len of the channel 100, and if the KeepConnect just not listen on the channel in disconnect, the broadcastToClients will hang. and the whole cluster will not serve!
Related to： https://github.com/seaweedfs/seaweedfs/commit/91e4eca1e98cb5195346d90a2cc1fb9c92557213
1.  broadcast to client with no block, and add metirc to monitor full err
2. volumeServer heartbeat no need to broadcast when transfer leader
hard code the len the message channel to 1, it's easy deadlock when transfer leader, after fix, it will not deadlock
=> fix deadlock hang when broadcast to clients

weed/shell/command_volume_balance.go, weed/shell/commands.go
Manual rebalancing takes a long time, during which other shell scripts are blocked. It seems quite safe to do rebalancing, since most of the time is spent copying volumes, if you do not interfere with the work.
This also allows you to manually launch rebalancing for specific nodes in parallel, which significantly speeds up the process.
Added an option to not block through lock those who understand what they are doing
=> [shell] add admin noLock for balance

k8s/charts/seaweedfs/templates/s3-servicemonitor.yaml
Fixes issue #6217
Applying fully qualified labels to the ServiceMonitor which match [the service template](https://github.com/seaweedfs/seaweedfs/blob/113c9ce6a83e0554e73aa881a6eb94690a05a0a7/k8s/charts/seaweedfs/templates/s3-service.yaml#L9):
```
helm upgrade --install seaweedfs
```
=> [helm] fix s3 servicemonitor label matching

weed/shell/command_ec_encode.go
fix https://github.com/seaweedfs/seaweedfs/issues/6205#issuecomment-2465004586
When error happens, the generated ec shards are left on the source server, taking up spaces.
When error happens, the spreading step should clean up both the source and target servers, to recover to original state.
=> delete aborted ec shards from both source and target servers

weed/storage/needle/needle_read.go, weed/storage/volume_read.go
This addresses #6189 
Solution: essentially the old condition
`(n.Checksum != crc)`
replaced with
`(n.Checksum != crc && uint32(n.Checksum) != crc.Value())`
which check against old way of CRC calculation.
=> added backward compatible CRC check and extra explanatory comments

weed/command/filer_backup.go, weed/command/filer_sync.go, weed/util/http/http_global_client_util.go
After [this commit](https://github.com/seaweedfs/seaweedfs/commit/a829f36d17cedfe12a1c4a58e58ee464a958cd4e) we encountered errors in our replication pipeline. 
Replication process stuck in infinite loop with one file 
`
E1112 12:21:42.319391 filer_pb_tail.go:97 process directory:"/buckets/cdn-original" event_notification:{old_entry:{name:"639d0e2bc883f1425d517e5eb45c7e673382188a" chunks:{file_id:"6932,ffa4df5bd3deb37d00fd39fe" size:29080 modified_ts_ns:1731273999542172466 e_tag:"6xzLaouM+XTjCC1RdcK9Rw==" fid:{volume_id:6932 file_key:18421093961341776765 cookie:16595454}} attributes:{file_size:29080 mtime:1731273999 file_mode:432 crtime:1731273999 mime:"application/pdf" md5:"\xeb\x1c\xcbj\x8b\x8c\xf9t\xe3\x08-Qu½G"}} new_entry:{name:"639d0e2bc883f1425d517e5eb45c7e673382188a" …
=> feat(filer.backup): add ignore errors option

other/java/client/src/main/java/seaweedfs/client/ReadChunks.java
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
at java.base/java.util.TimSort.sort(TimSort.java:254)
at java.base/java.util.Arrays.sort(Arrays.java:1308)
at java.base/java.util.ArrayList.sort(ArrayList.java:1804)
at java.base/java.util.Collections.sort(Collections.java:178)
at seaweedfs.client.ReadChunks.readResolvedChunks(ReadChunks.java:17)
at seaweedfs.client.SeaweedRead.nonOverlappingVisibleIntervals(SeaweedRead.java:229)
at seaweedfs.client.SeaweedInputStream.<init>(SeaweedInputStream.java:68)
at seaweed.hdfs.SeaweedHadoopInputStream.<init>(SeaweedHadoopInputStream …
```
=> fix java.lang.IllegalArgumentException: Comparison method violates its general contract!

k8s/charts/seaweedfs/templates/post-install-bucket-hook.yaml
https://github.com/seaweedfs/seaweedfs/issues/6238. Post-install hook attempts to create buckets before `master` and `filer` services are ready. It fails to create the buckets and exits successfully despite failing! 
Added a simple bash while loop that checks if both services are up using wget (Taken from the `readinessProbe`) before attempting to create buckets. I also found hard-coded port numbers of both `filer` and `master` so I templated those as well.
Tested with helm install on a local setup with minikube.
N/A
=> Add a loop to wait for master and filer services in post-install-bucket-hook

weed/shell/command_volume_move.go, weed/shell/commands.go
Manual rebalancing takes a long time, during which other shell scripts are blocked. It seems quite safe to do moving, since most of the time is spent copying volumes, if you do not interfere with the work.
This also allows you to manually launch moving to new DC for specific nodes in parallel, which significantly speeds up the process.
https://github.com/seaweedfs/seaweedfs/pull/6209
and fix `lock is lost`
Added an option to not block through lock those who understand what they are doing
on dev
```
192.168.0.1:8137 => 192.168.1.1:8092 volume 3907 processed 253.40 GiB
192.168.0.1:8137 => 192.168.1.1:8092 volume 3907 processed 253.53 GiB
192.168.0.1:8137 => 192.168.1.1:8092 volume 3907 processed 253.65 GiB
192.168.0.1:8137 => 192.168.1.1:8092 volume 3907 processed 253.78 GiB
```
=> [shell] add noLock param for volume.move

weed/shell/command_volume_fix_replication.go
https://github.com/seaweedfs/seaweedfs/pull/6209
set noLock for skip change param
```
> volume.fix.replication -n
replicating volume 3317 100 from 192.168.1.1:8101 to dataNode 192.168.0.3:8117 ...
replicating volume 11417 100 from 192.168.1.3:8090 to dataNode 192.168.0.1:8101 ...
```
=> [shell] don't require lock when there are no changes for volume.fix.replication

weed/server/master_grpc_server_volume.go
https://github.com/seaweedfs/seaweedfs/issues/6121
Returned the advanced growth of volumes to compensate for the volumes leaving due to crowded
Also added a limit on the growth of volumes available for writable, if suddenly something goes wrong with the calculation of crowded volumes
On dev cluster
=> [master] Revert back automatic volume grow in case of compensate for crowded volumes

weed/shell/command_ec_common.go, weed/shell/command_ec_common_test.go, weed/shell/command_volume_list_test.go, weed/shell/volume.ecshards.txt
- Favor target shards with less preexisting shards, to ensure a fair distribution.
- Randomize selection when multiple possible target shards are available.
- Add logic to account for replication settings when selecting target shards (currently disabled).
Improve EC shards re-balancing logic across racks.
- Favor target shards with less preexisting shards, to ensure a fair distribution.
- Randomize selection when multiple possible target shards are available.
- Add logic to account for volume replication settings when selecting target shards (currently disabled).
New test for `pickRackToBalanceShardsInto()`.
=> Improve EC shards rebalancing logic across racks

weed/s3api/auth_signature_v4.go
golang server now do not strips off 'Expect' header, so we can remove this piece of code now.
```
// curl -v -X POST "http://localhost:8080" -H "Expect: 100-continue" --data "Hello, World"
func Test100ContinueServer(t *testing.T) {
http.HandleFunc("/", handler)
http.ListenAndServe(":8080", nil)
}
func handler(w http.ResponseWriter, r *http.Request) {
expectValue := r.Header.Get("Expect")
// output: Expect Header: 100-continue
fmt.Printf("Expect Header: %s\n", expectValue)
body, err := io.ReadAll(r.Body)
if err != nil {
http.Error(w, "Failed to read request body", http.StatusInternalServerError)
return
}
defer r.Body.Close()
fmt.Printf("Request Body: %s\n", string(body))
fmt.Fprintf(w, "Request received and processed")
}
```
=> change comment for expect header

weed/shell/command_ec_common.go, weed/shell/command_ec_common_test.go
- Favor target nodes with less preexisting shards, to ensure a fair distribution.
- Randomize selection when multiple possible target nodes are available.
- Add logic to account for replication settings when selecting target nodes (currently disabled).
Added new unit tests for `pickEcNodeToBalanceShardsInto()`.
=> Improve EC shards rebalancing logic across nodes

weed/shell/command_ec_common.go, weed/shell/command_ec_common_test.go
Unifies the logic for `pickRackToBalanceShardsInto()` with ca499de1.
Minor change to unify error reporting for EC re-balancing across shards & racks.
No changes on existing unit tests for the function, other than a check for a non-error status.
=> Display details upon failures to re-balance EC shards racks.

weed/shell/command_ec_balance.go, weed/shell/command_ec_common.go, weed/shell/command_ec_common_test.go
Implements a stopgap solution for EC re-balancing based on system topology, as Seaweed currently has no support for shard placement strategy options.
The plan is to rely on volume replication settings to filter destination racks/nodes for EC shards which need to move. Since EC shards have no replication information, we read EC replica settings from command line arguments, or master defaults if left unspecified.
Moving forward, we'll need a better solution in place - maybe as simple as a new `shard_placement` field.
New unit test for `parseReplicaPlacementArg()`, updated unit tests for `getDefaultReplicaPlacement()`.
=> Resolve replica placement for EC volumes from master server defaults.

weed/command/scaffold/security.toml, weed/command/volume.go, weed/security/guard.go, weed/server/filer_server.go, weed/server/master_server.go, weed/server/volume_server.go
When adding or removing a new server volume, each disk requires updating all whitelists and a lengthy restart of each server volume in turn.
Added reading and reloading of whitelist from security config
No, in progress
=> [security] reload whiteList on http seerver

weed/shell/command_ec_common.go, weed/shell/command_ec_common_test.go, weed/shell/command_ec_test.go
Simplifies the implementation for `ec.balance` by reducing the number of nested parameters passed across functions, whenever possible.
TODO cleanup for https://github.com/seaweedfs/seaweedfs/discussions/6179.
No functional changes, no test changes.
=> Share common parameters for EC re-balancing functions under a single struct.

weed/command/scaffold/security.toml
The value of the `https.client.enabled` parameter in the `scaffold/security` file, which is used as an example for configuration setup, has been updated. Previously, this parameter was always set to true. After introducing TLS, some users encountered issues caused by the parameter being enabled by default, even though it was not used before. The value has now been changed to false to prevent such situations in the future.
- [ - ] I have added unit tests if possible.
- [ - ] I will add related wiki document changes and link to this PR after merging.
=> Replaced https.client.enabled with false in scaffold/security

weed/shell/command_ec_balance.go, weed/shell/command_ec_common.go, weed/shell/command_ec_common_test.go, weed/shell/command_ec_decode.go, weed/shell/command_ec_encode.go, weed/shell/command_ec_rebuild.go
`ec.encode` performs (basic) re-balancing after volumes are EC encoded. This change unifies this re-balancing logic with the one for `ec.balance`.
Among others, it enables recent changes related to topology aware re-balancing at EC encoding time.
No algorithmic changes; this MR swaps the EC re-balancing logic for `shell.EcBalance()`, which already has unit test coverage.
=> Unify the re-balancing logic for `ec.encode` with `ec.balance`.

weed/shell/command_ec_encode.go, weed/shell/command_ec_test.go
TODO cleanup. `ec.encode` now shares its re-balancing logic with `ec.balance`; this MR deletes the old logic.
No unit tests affected - other than a test for `shell.balancedEcDistribution()` going away.
=> Delete legacy balancing code for `ec.encode`.

weed/shell/command_ec_common.go, weed/shell/command_ec_common_test.go, weed/shell/command_ec_encode.go
TODO cleanup for https://github.com/seaweedfs/seaweedfs/discussions/6179 .
When a `volumeId` parameter is passed to `ec.encode`, limit the subsequent EC rebalance to collection(s) for that volume ID,
instead of the whole topology.
Added unit tests for the new function `shell.collectCollectionsForVolumeIds()`
=> Limit EC re-balancing for `ec.encode` to relevant collections when a volume ID argument is provided.

weed/shell/command_ec_balance.go, weed/shell/command_ec_common.go, weed/shell/command_ec_encode.go
Begin the implementation of parallel EC re-balancing operations within `shell.EcBalance()`.
This impacts both `ec.encode` and `ec.balance`.
No algorithmic changes, other than running EC sub-tasks in parallel. Following changes will likely require at least unit testing.
=> Begin implementing EC balancing parallelization support.

weed/s3api/stats.go, weed/stats/metrics.go
Metrics related to collections and buckets should be deleted after they become inactive. If not, we will end up with more and more huge metrics as the system runs, especially in environments where buckets are created, uploaded to, and deleted over time.
1 Delete collection metrics after the collection is deleted.
2 Record and delete bucket metrics after they become inactive for 10 minutes.
Tested in my development environment on the master branch.
=> fix: record and delete bucket metrics after inactive

weed/shell/command_ec_common.go
Makes EC re-balancing for racks concurrent within `shell.EcBalance()`. Impacts both `ec.encode` and `ec.balance`.
No algorithmic changes, other than running EC sub-tasks in parallel.
=> Parallelize EC balancing for racks.

weed/server/master_grpc_server_volume.go, weed/server/master_server_handlers_admin.go, weed/topology/topology_event_handling.go, weed/topology/topology_vacuum.go
#4046
When `volume.vacuum.disable` was executed, generally we wish the vacuum process which executed by master server automatically to stop immediately. Then  we can vacuum specific volumes or collections manually. For now, the master will continue vacuuming until a round of vacuum process is completed. What if I have 10000 volumes to vacuum? It will take a long time.That makes `volume.vacuum.disable` meaningless.
Return immediately if `isDisableVacuum` was detected.
To distinguish whether the vacuum process was executed by master or not I add a flag `automatic` in `Vacuum` function. That makes `isDisableVacuum` flag only works for automatic vacuum process.
- [ √] I have added unit tests if possible.
=> [shell] feat:stop vacuum immediately once volume.vacuum.disable was executed

weed/shell/command_ec_encode.go, weed/shell/command_volume_move.go
Make `ec.encode` to parallelize flagging volume replicas as writeable.
No algorithmic changes; this PR parallelizes existing EC encoding operations, which are already unit-tested.
=> Parallelize volume replica operations within `ec.encode`.

weed/shell/command_ec_balance.go, weed/shell/command_ec_common.go, weed/shell/command_ec_encode.go
Allows configuring the maximum number of concurrent tasks for `ec.balance` and `ec.encode`.
No functional / test changes.
=> Allow configuring the maximum number of concurrent tasks for EC parallelization.

weed/s3api/s3api_object_handlers_delete.go
Fix: #6379
We check for the AllowEmptyFolders option prior to cascade deleting parent folders in S3 DeleteMultipleObjectsHandler.
We ran SeaweedFS in a Kubernetes Cluster with a joint Filer and S3 server in one container, with leveldb2 as the filer storage, and AllowEmptyFolders set to true.
When using the Distribution Registry as the S3 client, it calls the DeleteMultipleObjectsHandler as part of the artifact upload process (uploads to a temp location, then performs a copy and delete). Without this fix, the deletion cascade deleted parent folder until the entire contents of the bucket were gone.
With this fix, the existing content of the bucket remained, and the newly uploaded content was added.
=> Fix for DeleteMultipleObjectsHandler wrongly deleting parent folders

go.mod, go.sum
There are some dependencies that still depends on the unmaintained bolt after https://github.com/seaweedfs/seaweedfs/pull/3554. Replace it so that we can have one less dependency, and build on newer architecture like RISC-V.
Two lines of `replace` are required because Go refuses to replace `github.com/boltdb/bolt` with `go.etcd.io/bbolt` when the latter is also present in the dependency tree. Replace it again with `github.com/etcd-io/bbolt` solves the issue.
We are able to build SeaweedFS and pass tests on Arch Linux RISC-V: https://github.com/felixonmars/archriscv-packages/pull/4376
The PR does not introduce visible changes to usage.
=> Replace bolt dependency with bbolt

weed/server/volume_server_ui/volume.html
currently we use different time format in web ui:
change time format in volume server UI to `"2006-01-02 15:04"` to match them
=> use same time format in volume volume UI and filter UI

k8s/charts/seaweedfs/dashboards/seaweedfs-grafana-dashboard.json, other/metrics/grafana_seaweedfs.json, other/metrics/grafana_seaweedfs_heartbeat.json, other/metrics/grafana_seaweedfs_k8s.json, weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_object_handlers_put.go, weed/s3api/stats.go, weed/stats/metrics.go
We added metrics to calculate the sent and received traffic of a bucket, meaning the number of bytes sent to and received from a bucket are counted. There are somethings like that in MinIo and other storages.
https://min.io/docs/minio/container/operations/monitoring/metrics-and-alerts.html#bucket-api
By adding metrics and increasing them only if the bytes are transferred to or from the filer successfully
It is tested locally.
=> Add bucket's traffic metrics

weed/shell/command_fs_merge_volumes.go
Currently, the fs.mergeVolumes command does not work when jwt.signing.key is set. This issue arises because the JWT token is not passed to UploaderOptions during the chunk upload process to another volume. In this pull request (PR), we have added the necessary changes to ensure that the fs.mergeVolumes command functions correctly when security is enabled.
Current error:
By generating a JWT token using security.GenJwtForVolumeServer and passing it to Uploader.
This PR was tested locally, by generating numerous chunks and merging them.
=> Add JWT authentication to fs.mergeVolumes command

weed/storage/backend/s3_backend/s3_backend.go, weed/storage/backend/s3_backend/s3_sessions.go, weed/util/parse.go
We need to use the cloud tier functionality and have chosen Alibaba Cloud OSS. However, we encountered the following error: `SecondLevelDomainForbidden: Please use virtual hosted style to access.`
This error occurs because Alibaba Cloud OSS no longer supports Path-Style access requests.
Added a `force_path_style` configuration option, which defaults to true (to ensure no impact on existing functionality).
By verifying the functionality of Cloud Tier on S3 services that support Path-Style and those that do not (in this case, OSS).
=> cloud tier: support for Alibaba Cloud OSS

weed/filer/ydb/ydb_types.go
If you choose YDB as filer store, you can't PUT object if bucket has TTL with errors like
> s3api_object_handlers_put.go:162 upload to filer error: insert entry /buckets/remd/2025_01_22_emdr-rmis-1_110_110.16.25.01.000000077: pool.With failed with 1 attempts: non-retryable error occurred on attempt No.1 (idempotent=false): execute statement: operation/BAD_REQUEST (code = 400010, address = broker:2136, nodeID = 1, issues = [{'ydb/core/kqp/session_actor/kqp_session_actor.cpp:1180: ydb/core/kqp/query_data/kqp_query_data.cpp:277: Parameter $expire_at type mismatch, expected: { Kind: Optional Optional { Item { Kind: Data Data { Scheme: 2 } } } }, actual: Type (Data), schemeType: Uint32, schemeTypeId: 2 '}]) at `github.com/ydb-platform/ydb-go-sdk/v3/internal/conn.invoke(conn.go:415)` at …
=> filer store YDB: fix upsert with TTL

k8s/charts/seaweedfs/README.md
fix error from commande in readme : 
$ kubectl label node kind-worker2 sw-volume=true,sw-backend=true error: invalid label spec: sw-volume=true,sw-backend=true
=> Update README.md - space for label creation

weed/s3api/s3api_object_handlers_delete.go, weed/s3api/s3api_object_handlers_multipart.go, weed/s3api/s3api_object_handlers_put.go, weed/stats/metrics.go
Two metrics for deleted and uploaded objects in S3 per bucket are added in this pull request.
By adding two counter metrics and increasing them in PutObjectHandler, CompleteMultipartUploadHandler, DeleteMultipleObjectsHandler, DeleteObjectHandler handlers.
It was tested locally.
=> Add metrics for uploaded and deleted s3 objects

weed/shell/command_ec_common.go, weed/storage/super_block/replica_placement.go, weed/storage/super_block/replica_placement_test.go
This PR increases the visibility of configuration holes which can cause `ec.encode` to become no-op.
Added unit tests for new `super_block.ReplicaPlacement` methods.
=> `ec.encode`: Display a warning on EC balancing if no replica placement settings are found.

weed/s3api/s3api_bucket_handlers.go
Signed-off-by: Tom Crasset <25140344+tcrasset@users.noreply.github.com>
Tested manually with 
```
AWS_ENDPOINT_URL=http://localhost:8333 aws s3api get-bucket-location --bucket e015df27-0cec-4fc3-a1be-349e4de829b8
```
Closes #6484
=> verify if bucket exists in GetBucketLocationHandler

weed/shell/command_ec_common.go, weed/shell/command_ec_common_test.go
The replica placement type specifies number of _replicas_ on DCs and racks; that means we can have one EC
shard copy on each, even if the replica setting is zero.
This PR reworks replica placement parsing for EC rebalancing, so we check allow (replica placement + 1) when
selecting racks and nodes to balance EC shards into.
Updated unit tests to reflect the new rebalancing target nodes/racks logic.
=> Improve EC shards balancing logic regarding replica placement settings.

weed/shell/command_ec_common.go
Fix a missing newline on warnings for missing replica settings at EC rebalancing time.
See 79136812.
No testing required.
=> Nit: fix missing newline on EC balancing warnings regarding replica settings

weed/shell/command_ec_common.go
Effectively undoes c9399a68. After ff8bd862, a replica placement type `000` will no longer break
shards re-balancing, so there's no display a warning for them.
No tests required/impacted.
=> Remove warning on EC balancing if no replica placement settings are found.

weed/command/master.go
Alternative to https://github.com/seaweedfs/seaweedfs/pull/6520
When we change the base image to one with GNU Wget, the call to `http://seaweedfs-master.seaweedfs:9333/cluster/status` fails because it does not implement the HTTP HEAD method.
the issue:
```
root@tmp-shell:/# wget --version
GNU Wget 1.21.2 built on linux-gnu.
root@tmp-shell:/# wget --spider http://seaweedfs-master.seaweedfs:9333/cluster/status && echo "exit $?"
Spider mode enabled. Check if remote file exists.
--2025-02-07 00:26:52--  http://seaweedfs-master.seaweedfs:9333/cluster/status
Resolving seaweedfs-master.seaweedfs (seaweedfs-master.seaweedfs)... 10.244.97.67
Connecting to seaweedfs-master.seaweedfs (seaweedfs-master.seaweedfs)|10.244.97.67|:9333... connected.
HTTP request sent, awaiting response... 405 Method Not …
```
=> fix: bucket-hook fails with gnu wget

weed/s3api/auth_signature_v4.go
The S3 clients tend to omit them when signing the request, and so the server should too
=> omit http and https ports when using X-Forwarded-Port

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml
the issue of conditional rendering based on a boolean value.
helm chart s3 allowEmptyFolder value not Effective
[#6204](https://github.com/seaweedfs/seaweedfs/issues/6204)
Added type check for boolean values: The if condition has been updated to check whether the value of .Values.someBool is of type bool using the typeOf function. This ensures that the flag were rendered when the value is explicitly set as true or false, and prevents rendering when the value is not a boolean or is missing.
helm template test
=> fix helm: s3 allowEmptyFolder flag if (#6204)

k8s/charts/seaweedfs/templates/_helpers.tpl
The seaweedfs gets the image pull secrets from the global variables of the charts. This section applies to all subcharts of a helm chart. This is a problem for us, as charts have conflicting formats for the secret:
* some, like seaweed want strings with the secret names
* others take objects
This PR changes the chart so it takes all three formats:
* a single string
* a list of strings
* a list of objects (these are rendered directly to yaml)
* I've tested that all three formats are rendered correctly
=> Helm: Support map format for image pull secrets

weed/command/s3.go
s3 command ignore tlsVerifyClientCert and cacert.file arguments from command line, so there is now way use mTLS for s3 https endpoint.
Fix what values are checked in startS3Server - check valued in s3opt structure (set from command line) instead of defaults in s3Options. 
With local ca and certificates:
`weed s3  -cacert.file ./localca.crt -cert.file ./localhost.crt -key.file ./localhost.pem  -port.https=8334 -filer xxx -tlsVerifyClientCert`
Check with openssl s_client  for "Acceptable client certificate CA names"; without patch - list is empty; after - contain certificate from command line.
Check with curl is connection required client (right) certificate; without patch client certificate is ignored; after - with wrong / missing client certificate - ssl error; with right certificate - …
=> fix: s3 command ignore -tlsVerifyClientCert and -cacert.file arguments

weed/shell/command_fs_merge_volumes.go
fix: error info size bug in command_fs_merge_volumes.go
a log bug in command_fs_merge_volumes.go
modified.
N/A
=> fix: error info size bug in command_fs_merge_volumes.go

weed/stats/metrics.go, weed/storage/disk_location.go
https://github.com/seaweedfs/seaweedfs/issues/4598
re-generating and writing the Volume UUID if it is empty
it was checked on the local stand, all volume servers have a non-empty UUID, otherwise the UUID was re-written to the file.
=> added re-generating and writing the Volume UUID if it is empty

k8s/charts/seaweedfs/Chart.yaml, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml
What problem are we solving?
Fix: #6579
How are we solving the problem?
In the Helm chart, we remove volume and volumeMounts for the certificates that are not used by the statefulset/deployment in question (s3, filer, volume and master).
How is the PR tested?
We ran SeaweedFS in a Kubernetes Cluster with a joint Filer and S3 server in one container, with leveldb2 as the filer storage.
We have a Kyverno policy that restarts pods when their mounted secrets are changed. Then using `cmctl renew` to renew the various certificates, we observed that only the relevant statefulset was restarted. Thereafter we used s3cmd to write to an s3 bucket to prove that the Seaweed cluster was still operational.
Checks
[ ] I have added unit tests if possible.
[ ] I will add related wiki document changes and …
=> Removed unused certificate mounts from helm chart

weed/command/scaffold/filer.toml, weed/filer/cassandra2/README.txt, weed/filer/cassandra2/cassandra_store.go, weed/filer/cassandra2/cassandra_store_kv.go
When listing directory children, Cassandra LSM storage would still need to traverse all sub folders.
Partition key adds dishash, so when listing a directory's direct children, no grand children are traversed by Cassandra LSM.
=> add cassandra2

weed/shell/command_ec_common.go, weed/shell/command_ec_common_test.go
We're computing negative counts for nodes with no shards available, which makes no sense. This figure is also surfaced to end users, and can be confusing.
This PR ensures free shard slot counts are never less than zero.
Added unit tests for `countFreeShardSlots()`.
=> Fix calculation of node's free EC shard slots.

weed/server/filer_server_handlers_write_merge.go
Since we have already checked mergeErr before and returned when mergeErr != nil, mergeErr must be nil here. In fact, it should return err, not the default mergeErr.
=> fix: fix the wrong error return value

weed/command/mount_std.go, weed/mount/weedfs.go
clear cache directory when mount exits. 
fix the issue:  https://github.com/seaweedfs/seaweedfs/issues/6604
Add the code that clearing the cache directory when fuse mount exits
=> clear cache directory when mount exits

weed/mount/meta_cache/meta_cache.go
Files uploaded with TTL are not listed in a mounted volume.
```bash
weed server -filer &
weed mount -dir=/somefolder &
curl -F --file=@somefile http://localhost:8888/somefile?ttl=1m
ls /somefolder
```
No somefile in the /somefolder folder.
`MetaCache` checks if directory entries have expired in the `ListDirectoryEntries` method. When checking if an entry has expired by comparing the current time with the expiration time, the conversion of TTL to seconds was missing. Adding `time.Second` unit solves this problem.
Same procedure to reproduce the problem was used.
=> Fixes files with TTL are not listed in a mounted folder.

k8s/charts/seaweedfs/templates/cosi-deployment.yaml, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
There are typos and invalid YAML syntax in the Helm chart. Additionally, there is an incorrect default secret name in the COSI deployment (though I'm unsure about this).
Fixing YAML syntax errors by removing a trailing `:`,  typos by renaming the default secret name of the COSI deployment and `replicationPlacement` in the global section of the Helm chart values. The latter might be a breaking change for users overriding this value in their values file. We may add the previous `replicationPlacment` value as a fallback.
Run `helm template --debug` on the chart in `k8s/charts/seaweedfs`.
=> Fix typos and YAML syntax issues

weed/command/filer.go, weed/command/server.go, weed/command/webdav.go
Standalone `weed webdav` does not have ip binding option and by default bind to all. Adding support to allow it bind ip like `weed s3` does.
By adding an option `-ip.bind` to `weed webdav` command.
The change is backward compatible, when `-ip.bind` not specified, it listens to all as it already does. This does not change the behaviour of `weed server -webdav` and `weed filer -webdav`.
- Tested on our environment:
For standalone one, it listens on correct port:
```
~ % ./weed webdav -ip.bind 127.1.2.3 -filer 127.0.2.3:6001
I1231 18:13:29.706768 webdav.go:68 Starting Seaweed WebDav Server 30GB 3.80  at 127.1.2.3:7333
I1231 18:13:29.712261 webdav.go:107 connected to filer 127.0.2.3:6001 grpc address 127.0.2.3:16001
I1231 18:13:29.721308 needle_map_leveldb.go:66 Loading …
```
=> Allow standalone webdav server to bind specific address

docker/compose/fluent.conf, docker/compose/local-auditlog-compose.yml, weed/s3api/s3api_object_handlers_delete.go, weed/s3api/s3err/audit_fluent.go
- auditing deleting individual records restored
- added logging output to stdout of fluent container for convenient manual testing
audit deleting individual key does not work
I returned the missing code block
built a new version and tested it locally
=> fix: restore deletion audit of individual objects

weed/mount/meta_cache/meta_cache.go
Fixes files with TTL cannot be read from a mounted folder.
Similar problem with #6621. 
```bash
weed server -filer &
weed mount -dir=/somefolder &
curl -F --file=@somefile.txt http://localhost:8888/somefile?ttl=1m
ls /somefolder
cat /somefoler/somefile.txt
```
An error message is displayed saying no such file when a user tries to read the file.
`MetaCache` checks if an entry has expired in the `FindEntry` method. When checking whether the entry has expired by comparing the current time with the expiration time, the conversion of TTL to seconds was missing. Adding `time.Second` unit solves this problem.
Same procedure to reproduce the problem was used.
=> Fixes files with TTL can not be read in a mounted folder

weed/filer/filer.go
Because from the Cassandra store, we get errors not only "filer_pb.ErrNotFound" , we may have missed some other errors related to issues in cassandra\scylla. This does not guarantee that we will create the parent directories at the moment.
In addition to errors when requesting, cassandra store will also return the nil value for the Entry during the "FindEntry" request. This will help fix the problem and stop further directory creation, as some of them may be skipped due to unhandled errors.
=> added a check for the nil value when requesting FindEntry.

weed/command/filer.go
This prevent crash filler with nil pointer dereference as s3 expect this parameters.
New two parameters are added to filer command - copy of s3 parameters:
- s3.cacert.file - path to the TLS CA certificate file
- s3.tlsVerifyClientCert - whether to verify the client's certificate
When S3 is started within filler - crash with nil pointer deference because this parameters are not set = nil.
Missing parameter are copied from s3 to filler command.
Start filler with -s3 -> no crash.
Start filler with -s3 and  -s3.cacert.file and - s3.tlsVerifyClientCert  -> check is s3 endpoint require certificates from cacerf file and certificate is require.
- [-] I have added unit tests if possible.
- [-] I will add related wiki document changes and link to this PR after merging.
=> feat/fix: add s3.cacert.file/tlsVerifyClientCert to filer command

weed/command/scaffold/filer.toml
When adding or deleting a file, the directory listing also needs to be updated. However, in racing conditions, the atomicity may not hold.
https://github.com/seaweedfs/seaweedfs/discussions/6670
Use lua to ensure atomicity on the server side.
=> add lua redis store to ensure atomicity

weed/server/filer_server_handlers_tagging.go
the dbErr != nil and err is nil
when call writeJsonError with a nil value error, it may panic when call `err.Error()`
https://github.com/seaweedfs/seaweedfs/blob/669a3917af5afafbe12586e8ff2007980d0ab77d/weed/server/common.go#L117-L122
use the correct err
=> fix call writeJsonError with a nil value error after check another err

weed/storage/needle/volume_ttl.go, weed/storage/needle/volume_ttl_test.go
issues repoted here: https://github.com/seaweedfs/seaweedfs/issues/6682
Add fitTtlCount to fit ttl into suitable unit, avoiding overflow from int to byte when count > 256
By manually tested with aws-cmd, buckets Expiration Days from 1to 1000;
When retrieving the bucket lifecycle configuration, if the set expiration days are not integer multiples of weeks, months, or years, a minor precision loss may occur. This is because the TTL conversion will round to the nearest suitable cycle while ensuring the count value remains under 256. However, this is generally acceptable in practice, as long-term expiration settings typically prioritize coarse-grained units (e.g., months or years) over exact day counts.
- [✅] I have added unit tests if possible.
- [ - ] I will add related wiki document …
=> Fix volume ttl

weed/command/filer.go, weed/command/s3.go
https://github.com/seaweedfs/seaweedfs/issues/6684
Check option if not nill
=> [filer] void panic if s3opt.tlsCACertificate is nill

go.mod, go.sum, weed/s3api/chunked_reader_v4.go
https://github.com/seaweedfs/seaweedfs/issues/6713
A proven algorithm is used
localy
```
2025-04-23 17:46:26,934 - ThreadPoolExecutor-0_0 - botocore.auth - DEBUG - CanonicalRequest:
PUT
/test/chunkObject.txt
content-encoding:aws-chunked
content-type:text/plain
host:filer01.dev:8443
x-amz-content-sha256:STREAMING-UNSIGNED-PAYLOAD-TRAILER
x-amz-date:20250423T124626Z
x-amz-decoded-content-length:227305
x-amz-sdk-checksum-algorithm:CRC64NVME
x-amz-trailer:x-amz-checksum-crc64nvme
content-encoding;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-sdk-checksum-algorithm;x-amz-trailer
STREAMING-UNSIGNED-PAYLOAD-TRAILER
2025-04-23 17:46:26,934 - ThreadPoolExecutor-0_0 - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20250423T124626Z …
```
=> [s3] fix checksum algorithm CRC64NVMe

docker/Dockerfile.go_build, docker/Dockerfile.rocksdb_dev_env, docker/Dockerfile.rocksdb_large
fix build https://github.com/seaweedfs/seaweedfs/actions/runs/14620792259/job/41019999808
```
0.061 go: ../go.mod requires go >= 1.24 (running go 1.23.8; GOTOOLCHAIN=local)
```
up golang version to 1.24
=> golang up version to 1.24

weed/shell/command_volume_list.go
For a long time, the `volume.list` output is not ordered.
It's because integer overflow in the compare func of `slices.SortFunc`. The `a.Id` & `b.Id` are uint32, which will give a large number when a < b due to integer underflow. The correct writing should be `int(a.Id) - int(b.Id)`
Tested by hand
=> fix: volume.list volume info output not in order

weed/command/server.go
S3 Feature: please add s3.ip.bind command line parameter #6733
( https://github.com/seaweedfs/seaweedfs/issues/6733 )
Reas s3.ip.bind command line. If not set default to ip.bind
weed.exe server -dir=".\data" -ip="127.0.0.1" -filer -s3 -s3.cert.file="certs\public.crt" -s3.key.file="certs\private.key" -s3.config=".\s3.config" -s3.ip.bind="0.0.0.0"
process	PID	protocol	local address	local port	state
weed.exe	44212	TCP	127.0.0.1	8080	LISTEN
weed.exe	44212	TCP	0.0.0.0	8333	LISTEN
weed.exe	44212	TCP	::	8333	LISTEN
weed.exe	44212	TCP	127.0.0.1	8888	LISTEN
weed.exe	44212	TCP	127.0.0.1	9333	LISTEN
weed.exe	44212	TCP	127.0.0.1	18080	LISTEN
weed.exe	44212	TCP	0.0.0.0	18333	LISTEN
weed.exe	44212	TCP	::	18333	LISTEN
weed.exe	44212	TCP	127.0.0.1	18888	LISTEN
weed.exe	44212	TCP	127.0.0.1	19333	LISTEN …
=> fix #6733 add s3.ip.bind command line parameter

.github/workflows/depsreview.yml
attempt to fix failing dependency-review workflow due to the below error.
Error: Invalid purl: version must be percent-encoded
=> bump depdency-review-action 4.3.0 -> 4.3.2

weed/command/filer.go, weed/command/s3.go, weed/command/server.go
Issue #6746: S3 Feature: please add s3.idleTimeout command line parameter
( https://github.com/seaweedfs/seaweedfs/issues/6746 )
Following the command line parameter scheme, I have adde "idleTimeout" parameter to the S3 standalone and "s3.idleTimeout" to the server and filer options. I have kept the default value 10
weed s3 without idleTimeout parameter:
time telnet 127.0.0.1 8333
Connected to 127.0.0.1. 
telnet: Connection closed by foreign host
real    10.030
user    0.15000
sys     0.000
weed s3 with -idleTimeout=20:
time telnet 127.0.0.1 8333
Connected to 127.0.0.1.
telnet: Connection closed by foreign host
real    20.033
user    0.000
sys     0.000
weed server with filer and s3 API without idleTimeout parameter:
time telnet 127.0.0.1 8333
Connected to 127.0.0.1.
telnet: Connection …
=> fix: S3 Feature: please add s3.idleTimeout command line parameter #6746

weed/command/filer.go
Addendum to issue #6733
While analyzing the issue regarding the idle Timeout parameter (#6746) I noticed that, to keep consistency, it would be necessary to have a “s3.ip.bind” command line parameter in the filer.go as well.  
add “s3.ip.bind” to filer.go using "ip.bind" as default.
weed.exe filer -defaultStoreDir=".\data" -ip="127.0.0.1" -master="127.0.0.1:9333" -s3 -s3.cert.file="certs\public.crt" -s3.key.file="certs\private.key" -s3.config=".\s3.config" -s3.idleTimeout=30 
process PID protocol local address local port state
weed.exe 26404 TCP 127.0.0.1 8888 LISTEN
weed.exe 26404 TCP 127.0.0.1 8333 LISTEN
weed.exe 26404 TCP 127.0.0.1 18888 LISTEN
weed.exe 26404 TCP 127.0.0.1 18333 LISTEN
weed.exe filer -defaultStoreDir=".\data" -ip="127.0.0.1" -master="127.0.0.1:9333" -s3 …
=> Addendum to issue #6733

k8s/charts/seaweedfs/templates/cosi-deployment.yaml
`matchLabels` are immutable. Thus, matching against the version, which changes with every release, blocks Helm upgrades. To resolve this, the label is removed. See #6090 where this was similarly done.
See #6090
Not tested. Just common sense and copied the solution from #6090.
=> fix: remove blocking match label

weed/storage/erasure_coding/ec_volume.go
`NeedleHeaderSize` happens to have the same size as `NeedleMapEntrySize`, except when running the 5 bytes offset variant of Seaweedfs, because it does not contain OffsetSize. This causes ECX corruption on deletes, due to the drifting offset computation (offset is always computed on a basis of 16 bytes per record instead of 17 bytes).
Using the correct constant.
None for now
=> Use the correct constant when computing the offset in SearchNeedleFromSortedIndex

weed/shell/command_ec_common.go, weed/shell/command_ec_encode.go
The current logic for `ec.encode` is:
1. EC shards for a volume are generated and added to a single server.
2. The original volume is deleted.
3. EC shards get re-balanced across the entire topology.
There's a small, but real, possibility of losing data between 2 and 3, if the underlying volume storage/server/rack/DC happens to fail.
As a fix, this MR reworks `ec.encode` so:
* Newly created EC shards are spread across all locations for the source volume.
* Source volumes are deleted only _after_ EC shards are converted and balanced.
Existing functional/units tests should pass without failures after this change.
=> Improve safety for weed shell's `ec.encode`.

weed/filer/mongodb/mongodb_store.go
Mongodb filer not supported ListDirectoryPrefixedEntries method on database level, which will work faster on folders with hight files count.
Implemented ListDirectoryPrefixedEntries using mongodb regex search. Regex search by prefix uses index while executed, so searching time is ok.
Run local aio deployment with mongodb filer store setted up. Confirm same beheviour with prefixFilterEntries version (when err ErrUnsupportedListDirectoryPrefixed raised)
=> Add prefix listing in mongodb_store.go

weed/shell/command_ec_common.go, weed/shell/common.go
https://github.com/seaweedfs/seaweedfs/issues/6779
Prepare to parallelize operations in `volume.fix.replication` via `ErrorWaitGroup`s.
Code shuffle, no test impact.
=> Move `shell.ErrorWaitGroup` into a common file, to cleanly reuse across `weed shell` commands.

weed/shell/command_ec_balance.go, weed/shell/command_ec_encode.go, weed/shell/common.go
https://github.com/seaweedfs/seaweedfs/issues/6779
Minor code cleanup for `weed shell` commands supporting parallelization.
No functional changes.
=> Nit: unify the default `--maxParallelization` value for `weed shell` commands supporting this option

weed/storage/needle/needle_write.go, weed/storage/store.go, weed/storage/volume_write.go
input/output error is wrapped and could not be checked, and volume has io error cannot be correctly reported as deleted to master in heartbeat
mock disk failure by command echo 1 | sudo tee /sys/block/sd*/device/delete to produce input/output error
=> correctly report volume with input/output error to master

k8s/charts/seaweedfs/templates/volume-statefulset.yaml
Unnecessary diffs in ArgoCD related to: https://github.com/argoproj/argo-cd/issues/11143
Including explicit apiVersion and kind fields in volumeClaimTemplates
=> Helm chart - volume statefulset -  volumeClaimTemplates -  add apiVersion and kind for better compatibility with argocd

weed/command/fuse.go, weed/command/mount.go, weed/command/mount_std.go
When using a fuse mount that systemd participates in (e.g., using /etc/fstab and converted by systemd-fstab-generator, or an explicit systemd.mount unit), systemd uses the following process to mount:
First it composes arguments for `mount` and invokes. it then monitors `/proc/self/mountinfo`. At this point, if `mount` exits without found the entry in `mountinfo`, the task is marked as failed, says "there is no mount".[^1]
[^1]: https://github.com/systemd/systemd/pull/14234
The reason is that, as implemented in PR https://github.com/seaweedfs/seaweedfs/pull/2141, `weed fuse` will fork out a daemon process and the daemon process complete the mount operation and stays to provide fuse translation. After fork, the main process exits immediately and the daemon process may not yet initiated a …
=> Ensure `weed fuse` master process exits after mounted

weed/command/scaffold/filer.toml, weed/filer/mysql/mysql_store.go
#6806
https://github.com/seaweedfs/seaweedfs/issues/6806
add enable_tls to filer.toml and use crypto to handle mysql tls
by testing under the case:
1.use old filer.toml and run weed filer
2.weed scaffold filer.toml and check the new properties
3.use the new filer.toml to start weed filer and successfully connect to mysql with tls
- [✅] I have added unit tests if possible.
- [✅] I will add related wiki document changes and link to this PR after merging.
=> Fix mysql tls enable

weed/storage/needle_map/compact_map.go, weed/storage/needle_map/compact_map_test.go
https://github.com/seaweedfs/seaweedfs/issues/6804
`CompactMap()` relies on fixed-size storage buckets of 10,000 elements, and a separate storage for overflow (i.e. out of order) needle IDs. The problem is that most of that fixed storage bucket space ends up allocated but never used; this is particularly true for out-of-order needle IDs, but happens also with perfectly ordered needle writes.
This MR reworks `CompactMap()` so:
- Underlying data structures are simplified.
- Needle buckets are now variable-size slices instead of fixed-size arrays.
- Data handling is performed via optimized built-in functions such as `copy()` instead of ad-hoc loops.
- `if` and `for` sections are unrolled, whenever possible.
The result is a dramatic improvement in memory usage, at the cost of slightly …
=> Rewrite `needle_map.CompactMap()` for more efficient memory usage

weed/s3api/filer_multipart.go
https://github.com/seaweedfs/seaweedfs/issues/6821
do not limit the list entries as there may be dups, and existing logic already consider duplicated entries
Write a script to upload large file with 10000 * 5MB size, with each part 5MB, and randomly choose parts which will be uploaded twice, then the upload will be success.
=> unlimit the list entries in completeMultipartUpload

weed/filer/filer.go
Currently, when configuring TTL for a specific path prefix using `fs.configure`, the TTL is incorrectly applied to both files and directories. This leads to directories being deleted prematurely before their contained files expire, making valid files inaccessible through the filesystem interface. This issue affects scenarios where path-specific TTLs are used to manage file lifecycles, particularly in log management and temporary file storage systems.
Reference: [Issue #6820](https://github.com/seaweedfs/seaweedfs/issues/6820)
- Modified the `CreateEntry` function to set TTL of directories to zero
- Ensures directories persist until all contained files have expired
- Maintains consistent access to valid files through the filesystem interface
- Preserves the original TTL behavior for files …
=> Fix TTL Behavior for Directories in Path-Specific Configuration

weed/storage/volume_write.go
d8c574a5ef1a811f9a0d447097d9edfcc0c1d84c mistakenly treat fsync as the same sync write requests.
set fsync correctly
=> revert part of d8c574a5ef1a811f9a0d447097d9edfcc0c1d84c

weed/storage/needle_map/compact_map.go, weed/storage/needle_map/compact_map_test.go
https://github.com/seaweedfs/seaweedfs/pull/6813
introduced a bug that if an item is out of order beyond a look back window, them CompactMap would fail to set the item.
If using filer with file id generated by master, sequential or snowflake, the bug would not be triggered, since the file id is incremental and would not be re-used.
If using some random way to generate file id, the risk of hitting this would be high.
correct the logic.
Added a new test specifically for this.
=> fix insert beyond look back window

weed/storage/needle_map/compact_map.go, weed/storage/needle_map/compact_map_cases_test.go, weed/storage/needle_map/compact_map_perf_test.go, weed/storage/needle_map/compact_map_test.go, weed/storage/needle_map/old/compact_map.go, weed/storage/needle_map/old/compact_map_perf_test.go, weed/storage/needle_map/old/compact_map_test.go
https://github.com/seaweedfs/seaweedfs/issues/6804
This PR introduces a new `CompactMap()` implementation for in-memory map of needle indices, optimized for memory usage.
The idea behind it is replacing the bucket+overflow approach with a map of sorted indices segments, which are in turn accessed through binary search. This guarantees a best-case scenario (ordered inserts/updates) of _O(n)_ and a worst case scenario of _O(log n)_ runtime; notably, memory usage is unaffected by index ordering.
Note that even at _O(log n)_, the clock time for both reads and writes is very low, with `weed benchmark` actually running slightly faster than the existing implementation.
The end result is 20-30% improvement in memory usage, compared with v3.89. See …
=> New `needle_map.CompactMap()` implementation for reduced memory usage

weed/server/filer_grpc_server_kv.go
When KvPut receives an empty value, it should delete the key and return immediately
Previously, the function would call KvDelete but then continue execution and call KvPut with the empty value, recreating the entry that was just deleted
Added missing return statement after successful KvDelete operation
Manual testing with grpcurl commands sending empty values to `KvPut`
`grpcurl -plaintext -d '{"key":"dGVzdGtleQ==", "value":""}' localhost:18888 filer_pb.SeaweedFiler/KvPut`
Verified that keys are properly deleted and not recreated
=> fix(filer): add missing return after KvDelete in KvPut with empty value

weed/mount/weedfs.go, weed/mount/weedfs_file_copy_range.go
When copying files (e.g. `cp` command) within a SeaweedFS mounted file system (FUSE), the code eventually calls `CopyFileRange`, which unconditionally allocates a buffer. The size of the buffer, depending on the code path, will either be the size of the file or `math.MaxInt64`. In the case of the former, many concurrent copies can OOM the process. In the case of the latter, a single copy will result in the equivalent of a `make([]byte, math.MaxInt64)`, which will panic.
Further details in issue #6862 . 
- Protect against massive allocations by using a fixed buffer size and a streaming implementation.
- Smooth GC pressure by using an allocation pool.
- Protect against OOM by throttling concurrent copy operations via a semaphore that scales with the mount's configured concurrent writers.
- …
=> FUSE Mount: Fix buffer allocation during copy

weed/shell/command_volume_list.go
Improve output consistency for volume.list (i.e. same output if system state didn't change between calls)
By adding sortMapKeys() call in all map-related operations.
Because it's a inspect-only command, we tested it by hand
=> Correctly sort in volume.list to ensure output consistency

weed/shell/command_volume_tier_upload.go
Fix an error causing weed shell panics originating from a wrong error handling.
Correctly implement the error handling logic
Tested by hand. Because this error only occurs in deep code branch, unittest is hard to implement.
=> Fix wrong error handling in volume.tier.upload when stream == nil but copyErr != nil

weed/command/fuse_std.go
While -disableXAttr works with the 'weed mount' command, disableXAttr doesn't work with the linux mount command (fstab, unit file, distro mount command).
The change simply adds this ability to runFuse()
I built seaweedfs and placed it on to an existing test system and confirmed an entry in /etc/fstab with disableXAttr in the options list worked properly. A test system that sets an ACL then returns 'Operation not supported'.
This resolves issue 6865
=> allow distro mount command to use disableXAttr

weed/s3api/auth_signature_v4.go
Correct signature calculation in case of proxied request with changed protocol (https -> http for example), more in 
https://github.com/seaweedfs/seaweedfs/issues/6839
Taking into account `X-Forwarded-Proto` header for host extraction in [auth_signature_v4.go](https://github.com/seaweedfs/seaweedfs/blob/7151a54b28518c93af627911c885f20ad931bc8e/weed/s3api/auth_signature_v4.go#L725C2-L738C10)
I've builded a local image and deployed it into my k3s cluster where I'm using seaweedfs hidden after traefik proxy (https->http).
Then I've checked with tcpdump that recevied request is correct and checked seaweedfs logs, assuring that the default port is not added for https scheme
=> Fix url scheme using for forwarded request with changed proto

weed/filer/ydb/ydb_queries.go, weed/filer/ydb/ydb_store.go, weed/filer/ydb/ydb_store_kv.go, weed/filer/ydb/ydb_store_test.go, weed/filer/ydb/ydb_types.go
- partitioning of tables is not used
- an outdated driver is being used
- ydb has a new query api with no restrictions on the length of the list operation, we use the old table
- reading a non-existent bucket would create a table for it
- primary key values were declared optional
- retries were not used
- some operations, in particular deletions, check only on the hash of the directory
- added partitioning settings with some default values
- migrated to the new YDB query client and updated the driver
- prevented automatic table creation when reading non-existent buckets
- most of the fields are required (NOT NULL)
- WithIdempotent() for retry in case of problems
- query statements include directory in every case
load testing on self-hosted ydb cluster
existing tests
=> ydb filer improvements

weed/s3api/s3api_put_object_helper.go, weed/s3api/s3api_put_object_helper_test.go
https://github.com/seaweedfs/seaweedfs/issues/6895
Before: When IAM was disabled, only authTypeStreamingSigned was handled (returning an error), while authTypeStreamingUnsigned would use the raw request body
After: When IAM is disabled, authTypeStreamingUnsigned requests are now processed through newChunkedReader() to properly strip checksum headers and extract the actual data
unit test
=> Fix chunked data reading if iam not enabled

k8s/charts/seaweedfs/Chart.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
This patch adds some missing master options to the helm chart of master statefulSet.
Lifting the master options from `master.go` to the chart
Tested by editing the master statefulSet in an existing k8s cluster
```
kg sts seaweedfs-master -oyaml
...
- command:
- /bin/sh
- -ec
- |
exec /usr/bin/weed \
-logtostderr=true \
-v=1 \
master \
-port=9333 \
-mdir=/data \
-ip.bind=0.0.0.0 \
-defaultReplication=000 \
-metricsPort=9324 \
-volumeSizeLimitMB=1000 \
-raftHashicorp \
-raftBootstrap \
-electionTimeout="5s" \
-heartbeatInterval="500ms" \
-ip=${POD_NAME}.${SEAWEEDFS_FULLNAME}-master.vmsp-platform \
-peers=${SEAWEEDFS_FULLNAME}-master-0.${SEAWEEDFS_FULLNAME}-master.vmsp-platform:9333,${SEAWEEDFS_FULLNAME}-master-1.${SEAWEEDFS_FULLNAME}-master.vmsp-platform:9333,${SEAWEEDFS_FULLNAME}-master-2.$ …
```
=> chore: keep master statefulSet chart up-to-date

weed/storage/backend/s3_backend/s3_sessions.go
When using the Cloud Tier feature in our business operations, we configured multiple S3 backends. Coincidentally, two Endpoints shared the same Region, which led to some unexpected behaviors due to the current cache mechanism.
Include both Endpoint and Region as Cache Key simultaneously.
=> update s3 session cache key

weed/shell/command_remote_cache.go
https://github.com/seaweedfs/seaweedfs/issues/6940
Enhance `remote.cache` to support:
* cache metadata only
* delete local extra files
=> enhance remote.cache to sync meta only, delete local extra

weed/s3api/chunked_reader_v4.go, weed/s3api/s3api_object_handlers_put.go, weed/s3api/s3err/s3api_errors.go
https://github.com/seaweedfs/seaweedfs/issues/6713
replace  `We encountered an internal error, please try again.` to `The Content-Md5 you specified did not match what we received`
localy
before 
```
aws --endpoint-url https://filer01.dev:8443 s3 cp /tmp/test.txt s3://test/test.txt --ca-bundle GolandProjects/seaweedfs/docker/compose/tls/SeaweedFS_CA.crt --checksum-algorithm CRC64NVME
upload failed: ../../tmp/test.txt to s3://test/test.txt An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.
```
after
```
aws --endpoint-url https://filer01.dev:8443 s3 cp /tmp/test.txt s3://test/test.txt --ca-bundle /Users/whitefox/GolandProjects/seaweedfs/docker/compose/tls/SeaweedFS_CA.crt --checksum-algorithm …
```
=> fix: s3 return BadDigest

k8s/charts/seaweedfs/templates/_helpers.tpl, k8s/charts/seaweedfs/templates/all-in-one-deployment.yaml, k8s/charts/seaweedfs/templates/cosi-deployment.yaml, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/s3-deployment.yaml, k8s/charts/seaweedfs/templates/sftp-deployment.yaml, k8s/charts/seaweedfs/templates/volume-resize-hook.yaml, k8s/charts/seaweedfs/templates/volume-service.yaml, k8s/charts/seaweedfs/templates/volume-servicemonitor.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Signed-off-by: Andrei Kvapil <kvapss@gmail.com>
* **Single-volume limitation** – the chart could deploy only one volume StatefulSet, making topology-aware layouts (different zones/DCs, dedicated node pools, etc.) impossible without duplicating the whole chart.
* **Unsafe PVC resize hook** – the pre-install/upgrade hook tried to patch every PVC whose declared size differed, 
1. volumes map
* Introduced a top-level `volumes`
* Each entry inherits all settings from `volume` but can override any of them (replicas, nodeSelector, dataCenter, disk layout, etc.).
* Setting `volume.enabled=false` makes the chart rely solely on the new map.
2. Safer resize logic
* Added Helm helper `common.resource-quantity` that converts Kubernetes quantities to a float64.
* Patches a PVC only if any …
=> Introduce named volumes in Helm chart

weed/command/s3.go, weed/s3api/auth_credentials.go, weed/s3api/auth_credentials_test.go
starting s3 needs a configuration file, which is not so convenient.
Simplest way to start and use the object store server:
```
export AWS_ACCESS_KEY_ID=admin_access
export AWS_SECRET_ACCESS_KEY=admin_secret
weed server -s3 -dir=/tmp/dir
```
These should work too:
```
AWS_ACCESS_KEY_ID=admin_access AWS_SECRET_ACCESS_KEY=admin_secret weed s3
AWS_ACCESS_KEY_ID=admin_access AWS_SECRET_ACCESS_KEY=admin_secret weed filer -s3
```
Manual.
=> S3 API: simpler way to start s3 with credentials

weed/shell/command_volume_balance.go
**Related Issues:** Fixes #7033 
When using `volume.balance` command in clusters with erasure coding (EC) volumes enabled, the operation fails with "no space left" error. This occurs because the balance strategy's capacity calculation doesn't account for EC shard usage, leading to incorrect load ratio calculations.
The `capacityByMaxVolumeCount` function only returns `MaxVolumeCount` without considering EC volume usage:
```go
func capacityByMaxVolumeCount(diskType types.DiskType) CapacityFunc {
return func(info *master_pb.DataNodeInfo) float64 {
diskInfo, found := info.DiskInfos[string(diskType)]
if !found {
return 0
}
return float64(diskInfo.MaxVolumeCount)  // Only considers MaxVolumeCount
}
}
```
This causes nodes with many EC volumes to be misjudged as "low load" and selected as …
=> fix: consider EC shard count in volume.balance capacity calculation

weed/filer/filechunk_manifest.go, weed/filer/reader_cache.go, weed/filer/stream.go, weed/util/http/http_global_client_util.go
If you set the `jwt.signing.read.key` parameter in security.toml, you will encounter an “Input/output error” when trying to read a file from weed mount.
`weed mount` logs:
```shell
E0731 21:32:40.395505 reader_at.go:163 fetching chunk &{FileId:1,ceea99843c5c OffsetInChunk:0 ViewSize:13 ViewOffset:0 ChunkSize:13 CipherKey:[] IsGzipped:true ModifiedTsNs:1753984005346050238}: http://192.168.2.41:8080/1,ceea99843c5c?readDeleted=true: 401 Unauthorized
E0731 21:32:40.395534 filehandle_read.go:66 file handle read /shared/test.txt: http://192.168.2.41:8080/1,ceea99843c5c?readDeleted=true: 401 Unauthorized
W0731 21:32:40.395548 weedfs_file_read.go:51 file handle read /shared/test.txt 0: http://192.168.2.41:8080/1,ceea99843c5c?readDeleted=true: 401 Unauthorized
```
Mb fix for #6740.
Added JWT token …
=> Fixed weed mount reads with jwt.signing.read.key

weed/s3api/auth_credentials.go, weed/s3api/auth_credentials_test.go, weed/s3api/s3api_bucket_handlers.go
Changing ListBucketsHandler to use the same authentication flow as other endpoints:
```
// Before (inconsistent)
identity, s3Err = s3a.iam.authUser(r)
// After (consistent)  
identity, s3Err = s3a.iam.authRequest(r, s3_constants.ACTION_LIST)
```
=> S3: fix list buckets handler

weed/shell/command_ec_encode.go
https://github.com/seaweedfs/seaweedfs/issues/6963#issuecomment-3144232994
If the a volume is replicated, need to mount the shards on the one with ec shards generated.
=> mount ec shards correctly

weed/s3api/auth_signature_v4.go, weed/s3api/auto_signature_v4_test.go
https://github.com/seaweedfs/seaweedfs/issues/7080
add back payload hashing
=> S3: Fix iam payload hash

k8s/charts/seaweedfs/values.yaml
This was removed because by design the all-in-one configuration will only support one pod in a deployment set.
Removing the value from `values.yaml` that doesn't do anything.
It doesn't need to be, it's only a removal.
=> chore: remove default replica count for all-in-one deployment

weed/topology/capacity_reservation_test.go, weed/topology/data_center.go, weed/topology/data_node.go, weed/topology/node.go, weed/topology/race_condition_stress_test.go, weed/topology/rack.go, weed/topology/topology.go, weed/topology/volume_growth.go, weed/topology/volume_growth_reservation_test.go, weed/topology/volume_growth_test.go
https://github.com/seaweedfs/seaweedfs/issues/7148
Capacity misjudgment issue in volume growth with high concurrent writes
atomically reserve capacity before creating volumes
unit tests
=> Master: volume assignment concurrency

k8s/charts/seaweedfs/templates/volume/volume-servicemonitor.yaml
dereferencing .Values.volume.annotations directly fails when using Flux helm controller.
"seaweedfs/templates/volume/volume-servicemonitor.yaml" at <.Values.volume.annotations>: nil pointer evaluating interface {}.volume"}
Use `$volume.annotations` instead of `.Values.volume.annotations`
Manually, locally
=> Fix volume annotations in volume-servicemonitor.yaml

k8s/charts/seaweedfs/templates/shared/_helpers.tpl, k8s/charts/seaweedfs/values.yaml
being able to override registry, repository, and image name separately
implementing the missing "default" value with global reference
local testing with `helm template`
_AFAICT there are no unit tests for the Helm chart_
_I found no relevant existing Helm documentation_
=> fix missing support for .Values.global.repository

weed/s3api/s3api_object_handlers_put.go, weed/s3api/stats.go
Currently, `SeaweedFS_bucket_traffic_received_bytes_total` stays unpopulated with data and it's graph in is empty in Grafana.
New function BucketTrafficReceived (similar to BucketTrafficSent) is called in s3api_object_handlers_put.go#putToFiler called after file being successfully uploaded into Filer.
Via modified for tests `make benchmark`
=> Populate bucket_traffic_received_bytes_total metric

weed/shell/command_volume_fix_replication.go
Right now shell command `volume.fix.replication` prints raw processed bytes size, but in new commands `util.BytesToHumanReadable(uint64(resp.ProcessedBytes))` often used.
Using `util.BytesToHumanReadable(uint64(resp.ProcessedBytes))` in `volume.fix.replication` command
=> Human-readable processed bytes in volume.fix.replication

weed/command/admin.go
Fixes #7272
The admin interface login functionality has a redirect loop issue where users entering correct credentials are continuously redirected back to the login page instead of accessing the admin dashboard.
See the issue in https://github.com/seaweedfs/seaweedfs/issues/7272
- Configure proper cookie session options in admin server:
* Set Path, MaxAge attributes
* Ensure session cookies are correctly saved and retrieved
Tested on Chrome, Firefox, and Edge.
Verified cookie behavior is consistent across browsers
=> fix(admin): resolve login redirect loop in admin interface (#7272)
