seaweedfs/seaweedfs

go/weed/filer.go, go/weed/server.go
I didn't test all of them, but they look good.  I tested only filer.redis.server.
=> more args for server

go/storage/needle_read_write.go, go/storage/store.go, go/storage/volume.go, go/topology/topology.go, go/weed/weed_server/volume_server_handlers_helper.go
There are some small typos in comments and output messages, it may be good to fix them ASAP.
Please review them.
=> fix some typos

go/storage/needle.go
See description on #59 and #56, and the both cases have been tested.
=> Fix the #59 and #56

README.md
=> Use proper HTTP verbs in README curl examples

README.md
http://en.wikipedia.org/wiki/Exbibyte
=> 2^60 is an exbibyte

docs/usecases.rst
https://github.com/chrislusf/weed-fs/issues/77#issuecomment-72482062
=> usecase: Data Migration Example

README.md
This updates README.md to consistently use the name "SeaweedFS", per #94.
=> Consolidate toward name SeaweedFS

go/weed/download.go, go/weed/upload.go
Apparently I forgot to save these files before submitting #121
=> Fix a couple more weedfs -> SeaweedFS instances

go/weed/weed_server/master_ui/templates.go, go/weed/weed_server/volume_server_ui/templates.go
Thanks very very much about providing master ui !!!
It is so useful !!
=> [ui] seaweedfs logo and icon

go/weed/export.go
Added -newer argument, which takes a date/time in RFC3339 format and exports only files newer than this time
Using LastModified in TarHeader ctime and mtime
=> Using LastModified in export to export only new files and fill up ctime and mtime in tar archive

go/weed/weed_server/master_server_handlers_admin.go
There is a bug that master can not redirect urlquery to slave volumn.
=> fix bug : master cann't redirect urlquery string

go/weed/weed_server/filer_server_handlers.go
The filer service uploading/updating operation does not have a dereplication
if someone run the following 2 commands orderly:
curl -F "filename=@server.crt" "http://localhost:8888/path/to/b/"
curl -F "filename=@server.crt" "http://localhost:8888/path/to/b/"
2 file ID will be assigned finally and the 1st one will not be deleted and the corresponding data would occupy the storage service for ever
=> dereplicate filer post request & support filer get req with raw fileId

go/topology/store_replicate.go, go/weed/weed_server/volume_server_handlers_read.go
Fix chunk manifest replicate upload error
Escape the redirect url in volume read handler
=> Fix chunk manifest replicate upload error

go/weed/weed_server/master_server_handlers_admin.go
Adding feature: lookup a file in a collection, 404 is returned from master when collection is not found or file is not in that collection.
=> master: redirect handler accept collection parameter

weed/server/filer_server.go, weed/server/filer_server_handlers_read.go, weed/server/filer_server_handlers_write.go, weed/storage/store.go
Chris
I made some code change for filer, please take a review,thanks!
=> filer server concern the lead change

weed/server/filer_server_handlers_write.go
Chris
I made some refactoring work, please help to review at your available time. Feel free to give me your suggestions~
Thanks!
=> made a little change for Amazon S3 API's compatibility(v2)

weed/filer/cassandra_store/cassandra_store.go, weed/filer/flat_namespace/flat_namespace_filer.go, weed/filer/flat_namespace/flat_namespace_store.go, weed/filer/redis_store/redis_store.go
bug: `filer delete` just delete key.
=> fix bug: filer DELETE

weed/server/filer_server_handlers_read.go, weed/server/filer_ui/templates.go
I added a small template to be able to browse the directories and the files instead of a raw json. Please do not hesitate to contact me if I can help.
Regards,
Clément
=> Add a visualization for the filer

weed/server/filer_server_handlers_read.go
@cschiano @chrislusf 
I just merge the new list directory function and existed read file logic together. Please take a review, any concern, please let me know
Thanks!
=> recover filer read handler logic

Dockerfile
During building docker image from this Dockerfile,  i encount this issue
This change make it works correctly.
=> Make Docker build works correctly

weed/storage/volume.go, weed/storage/volume_checking.go, weed/storage/volume_vacuum.go, weed/storage/volume_vacuum_test.go
Chris:
This is the draft code for issue [374](https://github.com/chrislusf/seaweedfs/issues/374), please help to review and give me feedback.
Thanks!
=> supplemental data between compacting and commit compacting

weed/server/raft_server.go
fix raft_server.go isPeersChanged bug
=> fix raft_server.go isPeersChanged bug

weed/storage/disk_location.go, weed/storage/needle_map_memory.go
Chris:
Please help to review, thanks!
=> concurrent loading volume when starting volume server

weed/util/http_util.go
fix the bug that we can't get filename when download file.
=> fix the bug that we can't get filename when download file.

weed/command/filer_copy.go, weed/command/upload.go, weed/operation/submit.go
fixed #407. Chunks and chunkManifest will be stored in the same data center currently.
=> support uploading files to specific dataCenter

weed/server/volume_server.go, weed/server/volume_server_handlers_admin.go, weed/server/volume_server_handlers_sync.go, weed/storage/disk_location.go, weed/storage/store.go, weed/storage/volume.go, weed/storage/volume_checking.go, weed/storage/volume_loading.go, weed/storage/volume_read_write.go, weed/storage/volume_super_block.go, weed/storage/volume_vacuum.go
- Logs volume id if actual volume size differs dataFileSize
- Add routes to delete, mount and unmount volumes online without restarting server
=> Online mount, unmount + deletion of single volumes

weed/command/mount_std.go, weed/server/filer_server.go, weed/server/filer_server_handlers_api.go
File read is not supported yet. It needs more modification of filer backend.
=> complement weed mount

weed/command/mount_std.go, weed/filer/client_operations.go, weed/server/filer_server_handlers_api.go, weed/server/filer_server_handlers_write.go, weed/util/http_util.go
Add file read and directory/file delete.
=> complement weed mount: add read and delete

weed/images/preprocess.go, weed/images/resizing.go, weed/server/volume_server_handlers_read.go
=> WebP resize support

README.md
Fixed several typos in README.md. This is my first time to create a pull request to an extraordinary open source project. Admire your work.
=> Fixed several typos in README.md

backers.md
Hi, Chris, this is Mingli from 彩云天气
=> update backer.md by adding colorfulclouds

backers.md
=> Add Haravan to backers.md

weed/storage/volume.go
Fix for the following issue on master: https://github.com/chrislusf/seaweedfs/issues/635
=> Fix for issue #635

unmaintained/change_superblock/change_superblock.go
=> fix the tool for change replication factor

weed/filer2/filer.go
check https://github.com/chrislusf/seaweedfs/issues/684
=> bugfix:delete Directory cache when filer2 delete Directory

weed/server/volume_server_handlers.go
combine similar cases together :)
=> better way to handler switch case

weed/images/preprocess.go, weed/images/resizing.go, weed/server/volume_server_handlers_read.go
增加了chunk图片文件支持width和height参数，希望可以接纳，写的有问题的话，望指正。或者麻烦考虑增加一下支持这个特性，谢谢
=> 增加chunk图片文件支持width和height

weed/util/pprof.go, weed/util/signal_handling.go
=> [bugfix] Fix interrupt hook overwritten bug

Makefile
Implements https://github.com/chrislusf/seaweedfs/issues/775
=> Build statically linked release executables.

weed/command/mount.go, weed/command/mount_std.go, weed/filesys/dir.go, weed/filesys/dir_link.go, weed/filesys/dir_rename.go, weed/filesys/file.go, weed/filesys/filehandle.go, weed/filesys/wfs.go, weed/glide.lock, weed/glide.yaml
merge for performance improvements
related to
https://github.com/chrislusf/seaweedfs/issues/805
=> switching_to_seaweedfs_fuse

weed/operation/assign_file_id.go, weed/operation/delete_content.go, weed/operation/lookup.go, weed/operation/stats.go, weed/operation/sync_volume.go, weed/operation/upload_content.go, weed/server/master_server_handlers_admin.go, weed/topology/allocate_volume.go, weed/topology/topology_vacuum.go, weed/util/http_util.go
- Due to be not familar with filer,   **only master & volume non-streaming rpc** timeout is set
-  http timeout is set
timeout is set to **_5s both rpc and http_**.
=> Fix https://github.com/chrislusf/seaweedfs/issues/823

unmaintained/fix_dat/fix_dat.go, unmaintained/repeated_vacuum/repeated_vacuum.go, weed/command/backup.go, weed/command/benchmark.go, weed/command/filer_copy.go, weed/command/filer_export.go, weed/filer2/redis/universal_redis_store.go, weed/filesys/dir_link.go, weed/filesys/dir_rename.go, weed/filesys/wfs.go, weed/operation/submit.go, weed/storage/needle.go, weed/storage/replica_placement_test.go, weed/storage/store.go, weed/storage/volume.go, weed/storage/volume_vacuum.go, weed/topology/data_node.go, weed/topology/node.go, weed/topology/store_replicate.go, weed/topology/topology_vacuum.go, weed/topology/volume_growth.go, weed/topology/volume_layout.go
just use go fmt to format all the code and fix some typos
=> go fmt and fix some typo

weed/command/backup.go, weed/command/upload.go, weed/operation/compress.go, weed/security/guard.go, weed/topology/topology_vacuum.go
Hi! I've just fixed the typos. Please check this
=> fixing of typos

weed/operation/upload_content.go
This reverts commit 31038acccf73541204b320fc334d0acad0b9923a.
=> Revert "fix https://github.com/chrislusf/seaweedfs/issues/780"

weed/storage/needle/file_id.go, weed/storage/needle/file_id_test.go, weed/storage/needle/volume_id.go, weed/storage/needle/volume_id_test.go
1,  add function ParseFileIdFromString()
2,  modify the reciever of the VolumeId method from *T to T, because the original type of the VolumeId is POD
3, add UT case
=> add function ParseFileIdFromString

weed/command/command.go, weed/command/webdav.go, weed/filer2/filer_client_util.go, weed/filesys/dir.go, weed/filesys/dir_link.go, weed/filesys/dir_rename.go, weed/filesys/dirty_page.go, weed/filesys/file.go, weed/filesys/filehandle.go, weed/filesys/wfs.go, weed/filesys/wfs_deletion.go, weed/server/webdav_server.go
=> add WebDav

.gitignore, weed/weed.go
- add binary file to .gitignore
- remove unused global variable
Signed-off-by: Lei Liu <liul.stone@gmail.com>
=> weed.go: remove unused global variable

weed/filer2/filerstore.go
Signed-off-by: divinerapier <poriter.coco@gmail.com>
Before wraps the store, I think it should be checked if has been wrapped.
=> avoid double warpping

weed/command/backup.go
When use `weed backup` command,  it would be better if  backup volumes could have different `ttl` and `replication` than the origin volumes.
In the production environment, volume may have several replica, but in the backup machine, volume may have only one replica.
=> weed backup: add ttl and replication parameter

go.mod, weed/util/bytes.go, weed/util/bytes_test.go
=> use std encoding lib

unmaintained/load_test/load_test_leveldb/load_test_leveldb.go, unmaintained/remove_duplicate_fids/remove_duplicate_fids.go, unmaintained/see_dat/see_dat.go, weed/server/filer_server_handlers_write.go, weed/server/master_server_handlers.go, weed/shell/command_volume_list.go
Now dir/lookup api return http 200 when volumeId not exist, I think it is more reasonable to return to http 404.
=> master api: return http 404 when volumeId not exist

weed/command/shell.go
change the filer config to Configurable
=>  fix: weed shell filer config is constant 

weed/command/mount_darwin.go, weed/command/mount_freebsd.go, weed/command/mount_linux.go, weed/server/master_grpc_server_collection.go, weed/server/master_grpc_server_volume.go, weed/server/master_server.go, weed/server/master_server_handlers.go, weed/server/master_server_handlers_admin.go, weed/server/raft_server.go, weed/topology/topology.go
=> misc updated

weed/sequence/memory_sequencer.go, weed/sequence/sequence.go, weed/server/master_server_handlers.go, weed/topology/topology.go
统一 leader 和 follower 输出错误信息，之前 vid 不存在时 leader 不会打印错误信息，仅返回 http 404
=> fix leader master /dir/lookup api error message

weed/server/master_server_handlers_admin.go, weed/topology/topology_map.go
1，Layouts consistent with other fields, capitalized
2，/vol/vacuum、/col/delete return the appropriate http status code
=> enhanced master api logic

weed/storage/store.go
Io hanged during heartbeat because of the write lock. Hanging time depends on volume number. Since deleting expired volume is low frequency，we can do this out of volume collecting.
Here is a simple comparing test with 500 volumes in a volume server:
test command: 
weed benchmark -master=localhost:9334 -c=32 -n=50000 -size=81920 -read=false 
before optimization:
Completed 25454 of 50000 requests, 50.9% 1274.0/s 99.6MB/s
Completed 26714 of 50000 requests, 53.4% 1260.0/s 98.5MB/s
Completed 27828 of 50000 requests, 55.7% 1114.0/s 87.1MB/s
Completed 28963 of 50000 requests, 57.9% 1135.0/s 88.7MB/s
Completed 30233 of 50000 requests, 60.5% 1270.0/s 99.3MB/s
Completed 31507 of 50000 requests, 63.0% 1274.0/s 99.6MB/s
Completed 32732 of 50000 requests, 65.5% 1225.0/s 95.7MB/s
Completed 33847 of …
=> use read lock to avoid io hang during heartbeat

unmaintained/remove_duplicate_fids/remove_duplicate_fids.go, weed/command/scaffold.go, weed/command/shell.go, weed/operation/assign_file_id.go, weed/server/master_server.go, weed/storage/backend/memory_map/memory_map_backend.go, weed/util/config.go, weed/util/parse.go
PR #1092 make filer configurable, But the filer configuration is still constant in the startAdminScripts function.
=> fix master maintenance logic

weed/server/filer_server_handlers_write.go
support set custom fs attr.mode with filer api
=> filer: Add attr.mode in query string

weed/topology/topology_vacuum.go
I have many full volumes in my seaweedfs cluster, even if I deleted many files in these volumes, they always unwritable. I list files for the same volume and find the different replication file size is not equal:
-rw-r--r-- 1 root root 31474986952 Jun 21 18:29 /var/lib/data/weed1/volume/131.dat
-rw-r--r-- 1 root root     5699488 Jun 21 18:29 /var/lib/data/weed1/volume/131.idx
-rw-r--r-- 1 root root 21504730080 Jun 21 18:29 /var/lib/data/weed2/volume/131.dat
-rw-r--r-- 1 root root     3140128 Jun 21 18:29 /var/lib/data/weed2/volume/131.idx
This is caused by volume vacuum: If volume have 2 replications, assigned to node1 and node2. When volume server in node2 is stopped, replication in node1 will be vacuum first. But when volume server in node2 restart, it will never be vacuumed, because …
=> fix the bug of volume never be vacuumed

weed/server/volume_server_ui/templates.go
making relevant data visible and readable.
=> DiskStats: adding Total & Percent Usage

weed/server/volume_server_ui/templates.go
=> display bug, header is Free but data was Used

k8s/README.md, k8s/seaweedfs/.helmignore, k8s/seaweedfs/Chart.yaml, k8s/seaweedfs/templates/_helpers.tpl, k8s/seaweedfs/templates/ca-cert.yaml, k8s/seaweedfs/templates/cert-clusterissuer.yaml, k8s/seaweedfs/templates/client-cert.yaml, k8s/seaweedfs/templates/filer-cert.yaml, k8s/seaweedfs/templates/filer-service.yaml, k8s/seaweedfs/templates/filer-statefulset.yaml, k8s/seaweedfs/templates/ingress.yaml, k8s/seaweedfs/templates/master-cert.yaml, k8s/seaweedfs/templates/master-service.yaml, k8s/seaweedfs/templates/master-statefulset.yaml, k8s/seaweedfs/templates/s3-deployment.yaml, k8s/seaweedfs/templates/s3-service.yaml, k8s/seaweedfs/templates/seaweefs-grafana-dashboard.yaml, k8s/seaweedfs/templates/secret-seaweedfs-db.yaml, k8s/seaweedfs/templates/security-configmap.yaml, k8s/seaweedfs/templates/service-account.yaml, k8s/seaweedfs/templates/volume-cert.yaml, k8s/seaweedfs/templates/volume-service.yaml, k8s/seaweedfs/templates/volume-statefulset.yaml, k8s/seaweedfs/values.yaml
seaweedfs on k8s deployment through helm chart & stateful sets
=> SEAWEEDFS-K8S: helm chart

k8s/seaweedfs/templates/s3-deployment.yaml, k8s/seaweedfs/templates/secret-seaweedfs-db.yaml, k8s/seaweedfs/values.yaml
updated config, to the new 1.58
=> FILER/S3: filer Dir Buckets

weed/util/config.go
Try fix #1272 
Simple deepcopy a new viper.Viper. Test on commands: `server, master, volume` only.
=> Fix data race about config

weed/server/volume_server_ui/templates.go
making volume stats size info readable By bytesToHumanReadble #1206
=> making volume stats size info readable.

unmaintained/volume_tailer/volume_tailer.go, weed/security/guard.go, weed/server/master_server.go
make the `go build ./...` pass
=> fix build error

weed/server/volume_server_handlers_write.go
rename 'needle' which collides with imported package name
=> rename 'needle' which collides with imported package name

unmaintained/see_dat/see_dat.go, unmaintained/see_idx/see_idx.go, weed/server/volume_server_ui/templates.go, weed/util/bytes.go
1. move BytesToHumanReadable to util package as public func
2. add BytesToHumanReadable of size output for  see_dat and see_idx
=> add BytesToHumanReadable  for see_dat and see_idx

weed/server/master_ui/templates.go, weed/topology/data_node.go, weed/util/inits.go, weed/util/inits_test.go
check volume ids directly in the master ui in demo likely (max 100 volumes) environment.
=> add Volume Ids column only for max 100 volumes for convenience in the master ui.

weed/stats/disk_notsupported.go, weed/stats/disk_windows.go
Discs statistics on Windows platform.
=> Discs statistics on Windows platform.

weed/topology/data_node.go
dn.volumes Iterate when write will cause master exit
=> fix dn.volumes Iterate when write issue

test/s3/basic/basic_test.go, weed/s3api/auth_credentials.go, weed/s3api/s3api_object_copy_handlers.go
``` go
SerializationError: failed to decode REST XML response
status code: 200, request id: 1595662331094206600, host id:
caused by: parsing time "2020-07-25T15:32:11.0941848+08:00" as "2006-01-02T15:04:05.999999999Z": cannot parse "+08:00" as "Z"
```
same as [#1297 ]
auth handler in reverse
=> fix s3api bug

weed/filer2/abstract_sql/abstract_sql_store.go, weed/filer2/cassandra/cassandra_store.go, weed/filer2/etcd/etcd_store.go, weed/filer2/filer.go, weed/filer2/filer_buckets.go, weed/filer2/filer_delete_entry.go, weed/filer2/filer_notify.go, weed/filer2/filerstore.go, weed/filer2/leveldb/leveldb_store.go, weed/filer2/leveldb/leveldb_store_test.go, weed/filer2/leveldb2/leveldb2_store.go, weed/filer2/leveldb2/leveldb2_store_test.go, weed/filer2/mongodb/mongodb_store.go, weed/filer2/mysql/mysql_store.go, weed/filer2/postgres/postgres_store.go, weed/filer2/redis/universal_redis_store.go, weed/filer2/redis2/universal_redis_store.go, weed/server/filer_grpc_server.go, weed/server/filer_grpc_server_rename.go, weed/server/filer_server_handlers_read_dir.go
=> Wip prefix search

k8s/seaweedfs/templates/filer-statefulset.yaml, k8s/seaweedfs/templates/master-statefulset.yaml, k8s/seaweedfs/templates/s3-deployment.yaml, k8s/seaweedfs/templates/seaweefs-grafana-dashboard.yaml, k8s/seaweedfs/templates/volume-statefulset.yaml, k8s/seaweedfs/values.yaml
*Adding more command-line options for pods, master,filer,volume
*Increasing timeouts & timing on readiness & liveness probes (reducing possibility of restarts/recreating of pods)
*fix grafana dashboard graph title
*General cleanup (anyvision + spaces/indentation)
=> Helm Chart Updates

weed/topology/topology_vacuum.go, weed/topology/volume_location_list.go
This PR fix a potential race condition when range VolumeLocationList
=> Fix a race condition when handle VolumeLocationList

weed/topology/topology_vacuum.go, weed/topology/volume_layout.go, weed/topology/volume_layout_test.go
This PR correct the behave of the original PR #1479
=> Correct the oversized state of volume after compaction

weed/server/raft_server.go, weed/server/raft_server_handlers.go
remove deleted peers if resumeState = true
=> Raft remove peers

weed/stats/metrics.go, weed/storage/store.go
Need for alerting if a lot of read only volumes
=> add number of read only volumes to prometheus metrics

weed/command/filer.go, weed/command/s3.go, weed/command/server.go, weed/s3api/s3api_server.go
My use case is two  ingresses one is normal and common where use different backends for the respective s3 api backends,  example buckets on ssd and hdd
=> Multi domainname

weed/storage/store.go
need to see https://github.com/chrislusf/seaweedfs/issues/1570
=> collection Volume ReadOnly Count with detailed status

weed/shell/command_volume_mark.go, weed/shell/command_volume_move.go
this is a fast solution to mark writable manually 
https://github.com/chrislusf/seaweedfs/issues/1570
=> add shell command volume mark writable

weed/pb/grpc_client_server.go
https://github.com/chrislusf/seaweedfs/issues/1570
=> add WaitForReady to grpc DialOption

weed/security/tls.go
=> fix tls grpc ca path

docker/local-registry-compose.yml, weed/server/master_server.go
Disable master api separately from UI
=> security master use access.ui

weed/storage/disk_location.go
=> fix race condition when loading volumes concurrently

weed/shell/command_bucket_create.go
States the replication setting that will be honour if not defined.
=> [shell] Add more information to bucket.create

weed/server/filer_server_handlers_read.go
Solve the Chinese name disorder of download file
=> Solve the Chinese name disorder of download file

docker/local-k8s-compose.yml, docker/nginx/proxy.conf, docker/prometheus/prometheus.yml, docker/seaweedfs-compose.yml
=> docker-compose

unmaintained/diff_volume_servers/diff_volume_servers.go, weed/command/export.go, weed/server/volume_grpc_copy_incremental.go, weed/server/volume_grpc_tail.go, weed/storage/erasure_coding/ec_decoder.go, weed/storage/erasure_coding/ec_test.go, weed/storage/erasure_coding/ec_volume.go, weed/storage/erasure_coding/ec_volume_test.go, weed/storage/store_ec.go, weed/storage/types/offset_4bytes.go, weed/storage/volume_backup.go, weed/storage/volume_checking.go, weed/storage/volume_read_write.go, weed/storage/volume_vacuum.go, weed/util/chunk_cache/chunk_cache_on_disk.go
=> fix typo offset.ToAcutalOffset to offset.ToActualOffset

k8s/seaweedfs/templates/cronjob.yaml, k8s/seaweedfs/templates/filer-service-client.yaml, k8s/seaweedfs/templates/filer-statefulset.yaml, k8s/seaweedfs/templates/s3-deployment.yaml, k8s/seaweedfs/templates/s3-service.yaml, k8s/seaweedfs/values.yaml
s3 auth
s3 pod disable/enable
s3 service in filer
cronJob fixes & enhancement (collection Filter on fix.replication)
volume minFreeSpacePercent to 7% to avoid k8s killing pods
make filer-client svc type:ClusterIP to (enable internal Load Balancing, and easier External  Access)
=> K8S chart updates

weed/filer/filer_notify.go, weed/notification/gocdk_pub_sub/gocdk_pub_sub.go, weed/replication/sub/notification_gocdk_pub_sub.go
https://github.com/google/go-cloud/issues/2958
https://github.com/chrislusf/seaweedfs/issues/1773
=> Do reconnect to RabbitMQ

docker/Dockerfile.s3tests, docker/Makefile, docker/compose/local-s3tests-compose.yml, docker/compose/s3.json, docker/compose/s3tests.conf
https://github.com/chrislusf/seaweedfs/issues/1810
`make s3tests`
```
s3tests_1  | s3tests_boto3.functional.test_s3.test_copy_object_ifnonematch_failed ... ok
s3tests_1  | 
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | XML: /opt/s3-tests/nosetests.xml
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Ran 118 tests in 38.826s
s3tests_1  | 
s3tests_1  | OK
seaweedfs_s3tests_1 exited with code 0
```
=> ceph s3-tests include in the docker compose files

weed/server/filer_server_handlers_read.go
add logging for 
https://github.com/chrislusf/seaweedfs/issues/1838
=> log error write entry

go.mod
currently, it is an old 2+ years driver
=> update pg to latest version

weed/s3api/filer_util.go
=> s3: "isLast" returns true when the file does not exist

weed/filer/stream.go
https://github.com/chrislusf/seaweedfs/issues/1889
=> error if read chunk zero data size

weed/filer/filer_delete_entry.go, weed/s3api/s3api_object_handlers.go
https://github.com/chrislusf/seaweedfs/issues/1857
=> s3 delete-objects pass OK for fail to delete non-empty folder

weed/pb/filer_pb/filer_client.go
=> make “List” correctly judge whether it is the last file

weed/s3api/s3api_objects_list_handlers.go
=> s3: count correction for the number of files in the dir

weed/s3api/s3api_object_handlers.go
https://github.com/chrislusf/seaweedfs/issues/1917
=> dir + slash key does not exist

weed/command/master.go, weed/command/server.go, weed/command/volume.go
https://github.com/chrislusf/seaweedfs/issues/1942
=> GOMAXPROCS use defaults to the value of runtime.NumCPU

weed/shell/command_volume_check_disk.go
https://github.com/chrislusf/seaweedfs/issues/1930
=> add missingKeysThreshold for fsck

go.mod, go.sum, weed/command/scaffold.go, weed/sequence/snowflake_sequencer.go, weed/server/master_server.go
=> Add a snowflake sequencer as more robust fid generator, but less compressable than small auto-inc id

weed/command/scaffold.go, weed/filer/mysql/mysql_sql_gen.go, weed/filer/mysql/mysql_store.go, weed/filer/mysql2/mysql2_store.go, weed/filer/postgres/postgres_sql_gen.go, weed/filer/postgres/postgres_store.go, weed/filer/postgres2/postgres2_store.go
Added the ability to write your own insertQuery to support the UPSERT syntax most of the RDBMS in now day already support.
=> Adding Customisation - insertQuery for postgres/mysql 

weed/command/scaffold.go, weed/filer/mysql/mysql_sql_gen.go, weed/filer/mysql/mysql_store.go, weed/filer/mysql2/mysql2_store.go, weed/filer/postgres/postgres_sql_gen.go, weed/filer/postgres/postgres_store.go, weed/filer/postgres2/postgres2_store.go
and rename config to upsertQuery
=> add enableUpsert=true

weed/command/scaffold.go
postgres syntax was fixed, missed the postgres2 syntax
=> fix postgres2 upsertQuery syntax also

weed/server/volume_server_handlers_write.go
https://github.com/chrislusf/seaweedfs/issues/2007
https://github.com/chrislusf/seaweedfs/pull/1508
=> revert volume etag

weed/command/scaffold.go
seems a comment error in generated filer config toml, this pr fix this
=> fix path-specific filer store comment error

weed/filer/filechunks.go, weed/operation/upload_content.go, weed/server/filer_server_handlers_write_upload.go
https://github.com/chrislusf/seaweedfs/issues/2007
=> fix aws style Etag for chunks

other/java/client/src/main/java/seaweedfs/client/FilerClient.java, other/java/client/src/test/java/seaweedfs/client/SeaweedFilerTest.java
I think that an `exists` method might be useful directly in the FilerClient.java
=> Add exists() to java client

.github/workflows/container_latest.yml, .github/workflows/container_release.yml
A brainless copy of the DockerHub config to github.
These two workflows will either trigger on a new tag or on new push to master, respectively.
DOCKER_USERNAME/DOCKER_PASSWORD and GHCR_USERNAME/GHCR_TOKEN secrets need to be set for the login to work and so the images can be pushed.
=> Gh container build

weed/filer/stream.go
Monitoring chunk download error
=> Chunk download stats

weed/command/server.go
=> freespace params fix

k8s/seaweedfs/Chart.yaml
the helm package will build number version  2.50 to 2.5
=> use string version

weed/filer/abstract_sql/abstract_sql_store.go, weed/filer/cassandra/cassandra_store.go, weed/filer/elastic/v7/elastic_store.go, weed/filer/etcd/etcd_store.go, weed/filer/filer.go, weed/filer/filer_delete_entry.go, weed/filer/filerstore.go, weed/filer/filerstore_translate_path.go, weed/filer/filerstore_wrapper.go, weed/filer/hbase/hbase_store.go, weed/filer/leveldb/leveldb_store.go, weed/filer/leveldb2/leveldb2_store.go, weed/filer/leveldb3/leveldb3_store.go, weed/filer/mongodb/mongodb_store.go, weed/filer/mysql/mysql_sql_gen.go, weed/filer/redis/universal_redis_store.go, weed/filer/redis2/universal_redis_store.go, weed/filer/rocksdb/rocksdb_store.go
https://github.com/chrislusf/seaweedfs/issues/2125
=> avoid crashes Galera Cluster

weed/command/fuse.go
Fix problem with foreground "weed fuse". This is related with issue #2137 and discussion #2135.
=> start "weed fuse" in background

weed/command/fuse.go
Related to #2159
Let's continue discussions here
=> Fix: Loosing environment variables at StartProcess

weed/filer/sqlite/sqlite_store_unsupported.go
alpine support mips64, will try to build on next version
=> sqlite also failed on mips64

weed/command/server.go, weed/command/volume.go, weed/server/volume_server.go, weed/server/volume_server_handlers.go, weed/server/volume_server_handlers_read.go
add support for preview picture in Cross-network environment.
for example:
10.128.36.xxx                                                     192.168.1.xxx
user ---------------------------->    nginx         ----------------------------->  weed
redirect ip 192.168.1.xxx is unreachable from 10.128.36.xxx
=> add proxy mode to read non-local volumes

weed/command/server.go
noticed this was missed in https://github.com/chrislusf/seaweedfs/pull/2168
=> remote -> proxy in server to match volume flags

weed/command/fuse.go
Related with #2159
It allow sets the path only if not set and add parameter to change path to find fusermount.
=> configurable fusermount path

weed/pb/filer_pb/filer_client.go, weed/s3api/filer_multipart.go, weed/s3api/filer_util.go
https://github.com/chrislusf/seaweedfs/issues/2173
=> fix s3 metadata error with multipart upload

weed/command/fuse.go
=> fix weed fuse parameters parsing

weed/server/filer_grpc_server_sub_meta.go
Recently I noticed issues with abnormal utilization of CPU and memory several times, even when servers have no incoming requests or background jobs like vacuum.
How to reproduce:
1. S3 starts to subscribe `/etc/iam/identity.json` by default.
2. GRPC connections will close about every 10 hours, likely to be caused by:  https://github.com/chrislusf/seaweedfs/commit/15c60cbb2660d60d2714d3386731044fcfeac473
> E0702 20:36:06 21571 auth_credentials_subscribe.go:67] subscribing filer meta change: rpc error: code = Unavailable desc = transport is closing
E0703 06:31:10 21571 auth_credentials_subscribe.go:67] subscribing filer meta change: rpc error: code = Unavailable desc = transport is closing
E0703 16:37:04 21571 auth_credentials_subscribe.go:67] subscribing filer meta change: rpc error: code …
=> Subscribe meta data: sync empty notification with timestamp

other/java/client/src/main/java/seaweedfs/client/ByteBufferPool.java
I propose to reduce min buffer size to 1MB for java client.
=> Change java client MIN_BUFFER_SIZE to 1MB

weed/server/volume_server_ui/templates.go, weed/server/volume_server_ui/volume.html, weed/util/reflect.go
=> show RemoteVolumes/EcVolumes only if it is not empty

weed/shell/command_fs_rm.go
=> weed shell: fs.rm remove file or directory

weed/shell/command_fs_rm.go
=> Add fs rm options

weed/command/fuse.go
=> Fix error handling

weed/filer/mysql/mysql_sql_gen.go
Fix mysql sql for batch delete
=> Fix mysql sql for batch delete

weed/shell/command_volume_tier_move.go
Replacing `collection` with `collectionPattern` for `volume.tier.move`, as explained in #2219
=> shell: ability to use wildcards for collections, all collections if ommited

weed/shell/command_volume_delete_empty.go
Add force option in volume.deleteEmpty command.
=> Add force option in volume.deleteEmpty command

go.mod, go.sum, weed/command/autocomplete.go, weed/command/command.go, weed/weed.go
Add `weed autocomplete`, `weed unautocomplete` commands for autocomplete.
=> Add autocomplete

weed/shell/command_fs_mkdir.go
Add crtime and mtime in fs.mkdir
=> Add crtime and mtime

weed/filesys/filehandle.go, weed/filesys/wfs.go
https://github.com/chrislusf/seaweedfs/issues/2248
=> Synchronize number of open files

weed/server/filer_server_handlers_read.go
=> Fix image resize

.github/workflows/container_latest.yml, .github/workflows/container_release.yml
Apologies for another contribution. Maybe I'll open an MR for test building containers on MRs. Related to #2282.
=> fix(ci): remove linux/riscv64

.github/workflows/container_latest.yml, .github/workflows/container_release.yml, .github/workflows/container_test.yml
Relates to #2285. Caused by #2282.
=> feature(ci): add container build testing

weed/shell/command_ec_decode.go, weed/shell/command_volume_fix_replication.go
https://github.com/chrislusf/seaweedfs/issues/1846
=> Topology update for every Nth id volume

weed/s3api/auth_credentials.go
https://github.com/chrislusf/seaweedfs/issues/2433
=> force overwrite s3-is-admin

weed/s3api/s3api_bucket_handlers.go
https://github.com/chrislusf/seaweedfs/issues/2434
=> Avoid forbiddening for HeadBucketHandler if owners are specified

docker/compose/fluent.json, docker/compose/local-auditlog-compose.yml, go.mod, go.sum, weed/command/filer.go, weed/command/s3.go, weed/command/server.go, weed/s3api/auth_credentials.go, weed/s3api/chunked_reader_v4.go, weed/s3api/http/header.go, weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_handlers.go, weed/s3api/s3api_object_copy_handlers.go, weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_object_handlers_postpolicy.go, weed/s3api/s3api_object_multipart_handlers.go, weed/s3api/s3api_object_tagging_handlers.go, weed/s3api/s3api_objects_list_handlers.go, weed/s3api/s3api_server.go, weed/s3api/s3err/audit_fluent.go, weed/s3api/s3err/error_handler.go
https://github.com/chrislusf/seaweedfs/issues/2255
=> S3 audit log

weed/filesys/dir_rename.go, weed/server/filer_grpc_server_rename.go
hello, i have tried to fix issue: https://github.com/chrislusf/seaweedfs/issues/2499, hope it is helpful.
=> rename operation returns the correct old parent path

weed/s3api/auth_credentials.go, weed/s3api/auth_credentials_test.go
https://github.com/chrislusf/seaweedfs/issues/2583
=> fix s3 access admin target

README.md
=> SeaweedFS on Telegram

weed/shell/command_volume_tier_move.go
Attempt to solve the issue #2591 
I'm using channels and keyed mutexes to avoid copying from the same or to the same server at once.
=> async volumeTierMove

weed/server/filer_server_handlers_read.go, weed/util/parse.go
fix preconditions according to https://tools.ietf.org/id/draft-ietf-httpbis-p4-conditional-26.html#preconditions
=> fix preconditions 

k8s/helm_charts2/templates/volume-statefulset.yaml
https://github.com/chrislusf/seaweedfs/issues/2630
=> graceful stop cluster http server default timeout 60 sec

weed/topology/store_replicate.go
https://github.com/chrislusf/seaweedfs/issues/2648
=> atomically write to replicas

weed/command/volume.go
https://github.com/chrislusf/seaweedfs/issues/2630
=> reduce to default http server KillTimeout and StopTimeout

weed/command/scaffold/filer.toml, weed/filer/redis_lua/redis_cluster_store.go, weed/filer/redis_lua/redis_sentinel_store.go, weed/filer/redis_lua/redis_store.go, weed/filer/redis_lua/stored_procedure/delete_entry.lua, weed/filer/redis_lua/stored_procedure/delete_folder_children.lua, weed/filer/redis_lua/stored_procedure/init.go, weed/filer/redis_lua/stored_procedure/insert_entry.lua, weed/filer/redis_lua/universal_redis_store.go, weed/filer/redis_lua/universal_redis_store_kv.go
=> FilerStore: add redis_lua

weed/command/server.go
Fix https://github.com/chrislusf/seaweedfs/issues/2695
=> Fix weed server panic when running iam

k8s/helm_charts2/templates/s3-deployment.yaml
=> Fix S3 liveness and readiness probe endpoint

weed/server/filer_server_handlers_write_autochunk.go, weed/server/filer_server_handlers_write_upload.go
=> filer: add back isAppend function

weed/filer/filechunk_manifest.go, weed/filer/filer_deletion.go, weed/shell/command_volume_fsck.go
In file modification, old chunks will be mis-deleted when they are merged(Manifestized).
=> [bugfix] filer: chunk mis-deletion

weed/server/filer_server_handlers_write_upload.go
[bugfix] filer:
1. Delete uploaded chunks when upload failed. 
2. Return error when upload is interrupted by user.
=> [bugfix] filer: upload files error

weed/storage/backend/disk_file.go
https://github.com/chrislusf/seaweedfs/issues/2658
=> checks disk file exist

.github/dependabot.yml
- Included dependabot config for GitHub actions.
=> Dependabot for GitHub actions

.github/dependabot.yml
- Dependabot config settings for golang
=> Dependabot config settings for golang

weed/server/volume_server_handlers.go
@chrislusf I'm not sure if this works, but you need to exit the request canceled loop
=> Need to exit waiting if request is was canceled

weed/server/raft_server.go
https://github.com/chrislusf/seaweedfs/issues/2804
=> Fix remove deleted peers

weed/server/raft_server.go
https://github.com/chrislusf/seaweedfs/issues/2804
=> always clear previous log to avoid server is promotable

weed/filer/meta_aggregator.go
https://github.com/chrislusf/seaweedfs/issues/2545
=> avoid connect to the old filler address

weed/server/raft_server.go
avoid open file operation not permitted
=> fix permission mkdir snapshot

.github/workflows/binaries_dev.yml, .github/workflows/binaries_release0.yml, .github/workflows/binaries_release1.yml, .github/workflows/binaries_release2.yml, .github/workflows/binaries_release3.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions

weed/remote_storage/remote_storage.go
remove Redundant type conversion and use strings.TrimSuffix to enhance readability
=> remove Redundant type conversion and use strings.TrimSuffix to enhance readability

weed/server/filer_ui/filer.html
Make operation buttons show when table row hovered. And adjust table row height.
=> [filer-ui]: Make operation buttons show when table row hovered

weed/storage/volume.go
https://github.com/chrislusf/seaweedfs/issues/2928
=> avoid invalid memory address or nil pointer dereference

k8s/helm_charts2/templates/filer-statefulset.yaml, k8s/helm_charts2/values.yaml
filer with leveldb2 may lose data.
fix https://github.com/chrislusf/seaweedfs/issues/2934
=> fix filer using leveldb2 may lose data

weed/shell/command_volume_fsck.go
check all replicas
and select volume id
=> fsck replicas

weed/iamapi/iamapi_management_handlers.go
According to AWS CLI doc [create-access-key](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/create-access-key.html), [delete-access-key](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/delete-access-key.html), [list-access-keys](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/list-access-keys.html)：
> If the UserName field is not specified, the user name is determined implicitly based on the Amazon Web Services access key ID used to sign the request. 
which means you can send these requests without specifying `UserName` then the system determines the implicit username based on who signs this request. For example, assume your AWS name is `test1`, then you send the request:
```
$ aws --no-verify-ssl --endpoint-url …
```
=> handle implicit username

weed/server/filer_server_handlers_read.go
=> fix http response error code

weed/server/master_grpc_server_raft.go
https://github.com/chrislusf/seaweedfs/issues/2987
=> avoid panic if hashicorp raft not initialized

k8s/helm_charts2/values.yaml
helm value `enablePVC` should inside filer: `.Values.filer.enablePVC`
=> fix filer helm pvc configuration

weed/filer/ydb/ydb_queries.go, weed/filer/ydb/ydb_store.go, weed/filer/ydb/ydb_store_kv.go, weed/filer/ydb/ydb_types.go
https://github.com/chrislusf/seaweedfs/pull/2996
=> fixes from comments

docker/Makefile, docker/compose/test-ydb-filer.yml, weed/filer/ydb/ydb_store.go, weed/filer/ydb/ydb_store_test.go
add some tests
https://github.com/chrislusf/seaweedfs/pull/2996
=> ydb test&refactor

docker/Makefile, docker/compose/local-nextcloud-compose.yml, docker/seaweedfs.sql, weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_objects_list_handlers.go
https://github.com/chrislusf/seaweedfs/issues/3086
Show dirs with Mime 
=> Create folders in s3 via nextcloud

weed/s3api/s3api_object_handlers.go, weed/s3api/s3err/s3api_errors.go
make s3tests
ranged_request_invalid_range
ranged_request_empty_object
return correct error message
- [yes ] I have added unit tests if possible.
- [yes ] I will add related wiki document changes and link to this PR after merging.
=> fix s3 tests ranged_requests

weed/command/filer_sync.go
#3150 
Thank you for your advice.
Now I've extracted the common code. but this code is not extracted to the outside.
Because if there is an exception inside the method, it will be used again.
```doSubscribeFilerMetaChanges->getOffset```
=> feat(filer.sync): add parameter fromTsMs. 

weed/shell/command_s3_bucket_create.go
fix: fix command prompt information of s3_bucket_create
remove useless flag '-replcation'
=> fix: fix command prompt information

.github/workflows/container_latest.yml, .github/workflows/container_release1.yml, .github/workflows/container_release2.yml, .github/workflows/container_release3.yml, .github/workflows/container_release4.yml, .github/workflows/container_release5.yml
=> fix build container

weed/wdclient/vid_map.go
=> fix(wdclient): GetLocations return

other/metrics/grafana_seaweedfs.json, weed/s3api/stats.go, weed/stats/metrics.go
=> add bucket label to s3 prometheus metrics

Makefile, docker/compose/tls.env, go.mod, go.sum, weed/security/tls.go
close connections
https://github.com/chrislusf/seaweedfs/issues/2802
credential reloading
https://github.com/chrislusf/seaweedfs/issues/2802
=> Advancedtls

weed/cluster/cluster.go, weed/cluster/cluster_test.go
fix #3248 
Put the lock in the outer layer and make the whole operation become a synchronous operation. Because the request volume of this interface is not large, it has little impact
- [ok ] I have added unit tests if possible.
=> fix `error: concurrent map writes` when add or remove cluster node

weed/command/update_full.go
weed removes supporting for hdfs, and adds tikv 
modify build tags
=> remove hdfs, add tikv for full version update

docker/README.md, docker/compose/local-dev-compose.yml, docker/seaweedfs-dev-compose.yml
S3 accessibility from docker
add ip.bind option
=> fix ip.bind cmd for docker compose

weed/wdclient/masterclient.go
When the requested master node is the leader, `VolumeLocation` or `ClusterNodeUpdate` may be returned here. If it is `VolumeLocation`, the update will be performed while resetting the vidMap, otherwise the event will be lost
This bug was introduced in #3228 
Processed separately for `VolumeLocation` response
=> fixed `volume xx not found` caused by missing VolumeLocation events

weed/shell/command_volume_server_evacuate.go
add option targetServer
https://github.com/chrislusf/seaweedfs/issues/3255
https://github.com/chrislusf/seaweedfs/issues/3255
https://github.com/chrislusf/seaweedfs/issues/3255
=> volumeServer.evacuate fix select empty node

weed/command/scaffold/filer.toml, weed/filer/tikv/tikv_store.go
=> filer tikv support tls

k8s/helm_charts2/templates/filer-statefulset.yaml, k8s/helm_charts2/templates/service-account.yaml
fix the spelling error
fix the spelling error
=> fix the spelling error

weed/iamapi/iamapi_server.go
=> fix iam CreatePolicy error

weed/iamapi/iamapi_management_handlers.go
There is no error handling logic when the username of the request is not found.
Add such logic and return appropriate error message according to https://docs.aws.amazon.com/IAM/latest/APIReference/API_PutUserPolicy.html
- [ √] I have added unit tests if possible.
- [ √] I will add related wiki document changes and link to this PR after merging.
=> refine PutUserPolicy

weed/iamapi/iamapi_management_handlers.go
Removing superfluous variables to make code more concise.
Refactor code.
- [√] I have added unit tests if possible.
- [√] I will add related wiki document changes and link to this PR after merging.
=> refactor code

weed/shell/command_s3_configure.go
=> Check whether there is a duplicate accessKey when modifying iam

weed/storage/disk_location.go
user can customize number of workers via env "GOMAXPROCS"
optimiz  maxproc for docker env
add ENV "GOMAXPROCS"
=> optimiz concurrency

weed/server/master_server.go
add remove logs
diagnostic info 
add remove logging  
=> raftServerRemoval typo and logs

weed/filer/meta_aggregator.go
https://github.com/chrislusf/seaweedfs/issues/3320
https://github.com/chrislusf/seaweedfs/issues/3320
move err msg to log level 1
=> err msg with duplicated local subscription detected move to log level 1

weed/shell/command_volume_server_evacuate.go, weed/shell/command_volume_server_evacuate_test.go
Since the volume server is physically located on one node, I want to move it to another physical node
Add option target server
- [ok ] I have added unit tests if possible.
=> volume server evacuate to target server

weed/server/master_server_handlers_admin.go, weed/server/master_server_handlers_ui.go, weed/topology/data_center.go, weed/topology/data_node.go, weed/topology/rack.go, weed/topology/topology_info.go, weed/topology/topology_map.go, weed/topology/volume_layout.go
Master UI http://localhost:9333/ change the order every time I refresh the page.
That make me feel bad.
change the store var type from map to []struct, then do sort to keep order
=> optimiz: master ui will render data in order

weed/storage/volume_vacuum.go
Correct comment.
Correct comment.
=> correct comment

weed/filer/stream.go
line with else gone
https://github.com/chrislusf/seaweedfs/commit/ec0edb1ac4b690b3c3fd5010b17558778737508a
https://github.com/chrislusf/seaweedfs/commit/ec0edb1ac4b690b3c3fd5010b17558778737508a
=> fix logic miss else for brake

weed/stats/metrics.go, weed/storage/store.go
[3341](https://github.com/chrislusf/seaweedfs/issues/3341)
[3341](https://github.com/chrislusf/seaweedfs/issues/3341)
[3341](https://github.com/chrislusf/seaweedfs/issues/3341)
=> delete disk_size metrics when collection deleted

k8s/helm_charts2/README.md
Clarity on usage of helm charts
Adding details currently only found (afaik) in github issues & improving the layout
=> Added details on helm deployment

weed/storage/volume_vacuum_test.go, weed/util/fla9/fla9.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
delete minor unreachable code cause by `return` or `t.Fatal`.
=> delete minor unreachable code

weed/server/filer_ui/filer.html
on filer server ui when we upload file there is no response
add js trigger output response on ui when request is done
tested on localhost, page did refresh after upload
=> add upload response

weed/server/master_server.go, weed/wdclient/masterclient.go
https://github.com/seaweedfs/seaweedfs/issues/3421
https://github.com/seaweedfs/seaweedfs/issues/3421
https://github.com/seaweedfs/seaweedfs/issues/3421
=> avoid infinite loop WaitUntilConnected()

weed/server/volume_grpc_read_all.go
nit: streaReadOneVolume -> streamReadOneVolume
=> fix naming typo

weed/filer/reader_at.go, weed/filer/reader_at_test.go
Do not leak data from the internal buffers of the FUSE server.
The issue was that buffers are reused, but when a file gap was found the buffer was not zeroed accordingly and the existing data of the buffer was kept and returned.
This change zeros read buffers when encountering file gaps during file/chunk reads in FUSE mounts.
It prevents leaking internal buffers of the FUSE server which could otherwise reveal metadata, directory listings, file contents and other data related to FUSE API calls.
Via unit tests and also following these reproduction steps:
- Do some actions on the mount, to fill up some fuse server buffers, like read, write, stat, list, ...
- Create a sparse file, or a file with zero gaps
- Dump the sparse file and see that gaps are sometimes filled with random data (leaked …
=> Fix FUSE server buffer leaks in file gaps

weed/filer/reader_cache.go
Sometimes when an unexpected error occurs the cacher would set an error and return.
However, it would not broadcast the condition signal in that case, therefore leaving the goroutine that runs readChunkAt stuck forever.
I figured that the condition is unnecessary because readChunkAt is acquiring a lock that is still held by the cacher goroutine anyway.
Callees of startCaching have to wait for a WaitGroup which makes sure that readChunkAt can't acquire the lock before startCaching.
This way readChunkAt can execute normally and check for the error.
Have `retriedFetchChunkData` return an unexpected error, like io.EOF, or anything else.
Can happen when the filer disappears and a file is read, for example.
=> Fix hanging reads in chunk cacher

weed/s3api/s3api_server.go
handle preflight cors requests
Added 'options' method to handle routing
=> Handle preflight cors requests

docker/Makefile
local dev with -race
add target dev_race
=> add target dev_race to MakeFile

weed/storage/disk_location.go, weed/storage/store.go
https://github.com/seaweedfs/seaweedfs/issues/3513
https://github.com/seaweedfs/seaweedfs/issues/3513
https://github.com/seaweedfs/seaweedfs/issues/3513
=> avoid race conditions for diskLocation.MaxVolumeCount

weed/filer/filer.go, weed/mq/broker/broker_server.go, weed/server/master_server.go, weed/wdclient/masterclient.go
https://github.com/seaweedfs/seaweedfs/issues/3524
https://github.com/seaweedfs/seaweedfs/issues/3524
https://github.com/seaweedfs/seaweedfs/issues/3524
=> avoid race conditions for OnPeerUpdate

weed/server/master_grpc_server.go
[3520](https://github.com/seaweedfs/seaweedfs/issues/3520)
Build DeletedVids before reset dn's children
=> fix: Build DeletedVids before reset dn's children

weed/topology/volume_layout.go
https://github.com/seaweedfs/seaweedfs/issues/3511
https://github.com/seaweedfs/seaweedfs/issues/3511
https://github.com/seaweedfs/seaweedfs/issues/3511
=> avoid race conditions access to  growRequestCount

weed/command/filer.go
https://github.com/seaweedfs/seaweedfs/issues/3508
https://github.com/seaweedfs/seaweedfs/issues/3508
https://github.com/seaweedfs/seaweedfs/issues/3508
=> avoid data race access to startDelay

weed/server/filer_server_handlers_write_upload.go
https://github.com/seaweedfs/seaweedfs/issues/3549
https://github.com/seaweedfs/seaweedfs/issues/3549
https://github.com/seaweedfs/seaweedfs/issues/3549
https://github.com/seaweedfs/seaweedfs/issues/3549
=> avoid data race access to uploadReaderToChunks.uploadErr

weed/wdclient/masterclient.go
https://github.com/seaweedfs/seaweedfs/issues/3510
https://github.com/seaweedfs/seaweedfs/issues/3510
https://github.com/seaweedfs/seaweedfs/issues/3510
=> avoid race conditions access to  MasterClient.currentMaster

weed/storage/volume.go
https://github.com/seaweedfs/seaweedfs/issues/3515
https://github.com/seaweedfs/seaweedfs/issues/3515
https://github.com/seaweedfs/seaweedfs/issues/3515
=> avoid race conditions access to  SuperBlock.Version

go.mod, go.sum, weed/server/raft_hashicorp.go
https://github.com/seaweedfs/seaweedfs/issues/3521
https://github.com/hashicorp/raft/issues/521
https://github.com/seaweedfs/seaweedfs/issues/3521
https://github.com/hashicorp/raft/issues/521
=> migrate from boltdb to bbolt

weed/filer/meta_aggregator.go
https://github.com/seaweedfs/seaweedfs/issues/3565
https://github.com/seaweedfs/seaweedfs/issues/3565
https://github.com/seaweedfs/seaweedfs/issues/3565
=> avoid data race on doSubscribeToOneFiler/ma.filer.UniqueFilerEpoch

weed/server/common.go
https://github.com/seaweedfs/seaweedfs/issues/3567
https://github.com/seaweedfs/seaweedfs/issues/3567
https://github.com/seaweedfs/seaweedfs/issues/3567
=> more error details in the log

weed/server/filer_server_handlers_write_upload.go
https://github.com/seaweedfs/seaweedfs/issues/3557
https://github.com/seaweedfs/seaweedfs/issues/3557
https://github.com/seaweedfs/seaweedfs/issues/3557
=> avoid data race read fileChunksSize

weed/util/grace/signal_handling.go
https://github.com/seaweedfs/seaweedfs/issues/3564
https://github.com/seaweedfs/seaweedfs/issues/3564
=> avoid data race on grace.hooks

weed/util/grace/signal_handling.go
https://github.com/seaweedfs/seaweedfs/issues/3564
https://github.com/seaweedfs/seaweedfs/issues/3564
=> [filer] DATA RACE on signal_handling fixed

weed/command/filer_sync.go
#3553
Added a new 'concurrency' parameter for filer.sync. Default value is set to 32, max value is limited to 1024.
After running for two days using a limit of 32, no more HTTP hangs observed on my system.
=> new 'concurrency' parameter for filer.sync

weed/notification/gocdk_pub_sub/gocdk_pub_sub.go
https://github.com/seaweedfs/seaweedfs/issues/3595
https://github.com/seaweedfs/seaweedfs/issues/3595
https://github.com/seaweedfs/seaweedfs/issues/3595
=> avoid data race on GoCDKPubSub.topic

weed/command/s3.go
https://github.com/seaweedfs/seaweedfs/issues/3607
https://github.com/seaweedfs/seaweedfs/issues/3607
=> avoid SIGSEGV on localFilerSocket

weed/topology/node.go
https://github.com/seaweedfs/seaweedfs/issues/3593
https://github.com/seaweedfs/seaweedfs/issues/3593
https://github.com/seaweedfs/seaweedfs/issues/3593
=> avoid data race on calc freeVolumeSlotCount

weed/topology/data_node.go
https://github.com/seaweedfs/seaweedfs/issues/3590
https://github.com/seaweedfs/seaweedfs/issues/3590
https://github.com/seaweedfs/seaweedfs/issues/3590
=> avoid data race on currentDiskUsage.maxVolumeCount

weed/server/master_grpc_server.go
Increased code readability https://github.com/seaweedfs/seaweedfs/pull/3616
Bring back complexity
=> refactor https://github.com/seaweedfs/seaweedfs/pull/3616

weed/storage/volume_read.go
It looks like it can add an assignment here.
=> simplify a bit

weed/shell/command_volume_fix_replication.go
In certain circumstances it is best to not delete over-replicated volumes, but still try to fix under-replicated ones. 
This will allow this with a new option for volume.fix.replication. Use '-noDelete' option to disable deletes but keep performing actions to solve under-replication.
Regression tests; testing new feature.
=> Add option in volume.fix.replication to only fix under-replication and not delete volumes

weed/command/filer_remote_sync.go, weed/command/filer_remote_sync_dir.go, weed/command/filer_sync_jobs.go
https://github.com/seaweedfs/seaweedfs/issues/3636
https://github.com/seaweedfs/seaweedfs/issues/3636
https://github.com/seaweedfs/seaweedfs/issues/3636
=> [sync] override amz storage class, None to delete

weed/pb/master_pb/master_helper.go, weed/server/master_grpc_server.go, weed/server/volume_grpc_client_to_master.go, weed/topology/configuration.go, weed/wdclient/masterclient.go
https://github.com/seaweedfs/seaweedfs/issues/3629
https://github.com/seaweedfs/seaweedfs/issues/3629
=> skip deltaBeat if dn is zero

weed/server/filer_server_handlers_write_upload.go, weed/topology/store_replicate.go
https://github.com/seaweedfs/seaweedfs/issues/3578
https://github.com/seaweedfs/seaweedfs/issues/3578
https://github.com/seaweedfs/seaweedfs/issues/3578
=> Removing chunks on failed to write to replicas

weed/s3api/filer_multipart.go
https://github.com/seaweedfs/seaweedfs/issues/3660
Offset is the final size of this object. We can save it to entry.
=> fix 0 size

weed/wdclient/resource_pool/semaphore.go
Final one-off `/wdclient/*` readability fix in a comment.
This completes this folder.
=> docs(wdclient): readability fix

weed/command/scaffold.go, weed/command/scaffold/filer.toml, weed/command/scaffold/notification.toml
Final one-off readability fixes in the `/command/*` path
This completes this folder
=> docs(command): readability fixes

weed/util/chunk_cache/chunk_cache_on_disk.go
`panicing` -> `panicking`
We're getting down to the smaller readability issues :)
=> docs: `panicing` -> `panicking`

weed/topology/store_replicate.go, weed/topology/volume_layout_test.go
One-off readability fixes in the `/topology/` path. 
Completes this folder
=> docs(topology): readability improvements

weed/filer/filer_deletion.go
Mulligan on `fildIdsToDelete` -> `fileIdsToDelete`
=> docs: update `fileIdsToDelete` var

weed/s3api/auth_signature_v2.go, weed/s3api/auth_signature_v4.go, weed/s3api/auto_signature_v4_test.go, weed/s3api/chunked_reader_v4.go, weed/s3api/policy/post-policy_test.go, weed/s3api/policy/postpolicyform.go
One-off readability improvements in the `/s3api/` path
=> docs(s3api): readability improvements

weed/shell/command_fs_configure.go, weed/shell/command_lock_unlock.go, weed/shell/command_remote_meta_sync.go, weed/shell/command_s3_circuitbreaker_test.go, weed/shell/command_s3_clean_uploads.go
One-off readability issues in `shell`
This completes this folder
=> refactor(shell): readability improvements

other/java/client/src/main/java/seaweedfs/client/SeaweedWrite.java
A server answering with HTTP error result in `NullPointerException` in Java client
Check for HTTP status code and wrap server's json message (if any) into `IOException`
Trivial
=> client-java: handle server HTTP errors

weed/command/filer_remote_sync_dir.go
https://github.com/seaweedfs/seaweedfs/issues/3636#issuecomment-1264239200
safe key removal
=> fix delete key panic of remote sync dir

weed/s3api/auth_credentials.go, weed/s3api/auth_credentials_test.go, weed/s3api/filer_util.go, weed/s3api/s3_constants/header.go, weed/s3api/s3api_acp.go, weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_server.go, weed/s3api/s3err/error_handler.go, weed/s3api/s3err/s3api_errors.go
[Controlling object ownership](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html)
=> add ownership rest apis

docker/compose/local-hashicorp-raft-compose.yml, weed/command/master.go, weed/server/master_server.go
An attempt to minimize the effect of bugs https://github.com/hashicorp/raft/issues/472
Transfer leadership on shutdown
=> master server graceful stop

weed/s3api/auth_credentials.go, weed/s3api/auth_credentials_test.go, weed/s3api/bucket_metadata.go, weed/s3api/bucket_metadata_test.go, weed/s3api/s3account/s3_account.go, weed/s3api/s3api_acp.go, weed/s3api/s3api_server.go
change s3_account.go package to avoid cycle dependency
mv `s3_account.go` to package `s3account`
=> change s3_account.go package to avoid cycle dependency

weed/server/filer_server_handlers_read.go
use GET method get directory metadata 
other systems to access
=> filer: get directory metadata

weed/storage/needle_map_leveldb.go, weed/storage/volume_vacuum.go
types packages is imported more than onece
=> types packages is imported more than onece

weed/util/log_buffer/log_buffer.go
=> avoid data race of LogBuffer isStopping

weed/storage/needle/needle_read_page.go
https://github.com/seaweedfs/seaweedfs/issues/3882
https://github.com/seaweedfs/seaweedfs/issues/3882
recover panic occurred to err
=> ReadNeedleMeta recovery panic occurred

weed/s3api/s3api_object_handlers.go
=> feat: simplify a bit

weed/shell/command_volume_check_disk.go
redundant replication of deleted files
avoid replication deleted files
=> avoid fix missing of deleted needles

weed/command/fix.go
https://github.com/seaweedfs/seaweedfs/issues/2945
https://github.com/seaweedfs/seaweedfs/issues/2945
=> [fix] add param for ignore error

weed/topology/topology_vacuum.go
In continuation https://github.com/seaweedfs/seaweedfs/pull/3923
if files were deleted from only one of the replicas, then after the vacuum and mouning the missing replica, the deleted files are not synchronized.
and fix vacuum filter by volume id
Do not make a vacuum until there are not enough replicas
=> [master] avoid vacuum if not enough replica copies

weed/shell/command_volume_fsck.go, weed/shell/commands.go
split PR https://github.com/seaweedfs/seaweedfs/pull/3879
=> [volume.fsck] check needles status from volume server

weed/filer/filer_deletion.go
split pr https://github.com/seaweedfs/seaweedfs/pull/3879
=> refactor error contains already deleted

weed/shell/command_volume_fsck.go
split PR https://github.com/seaweedfs/seaweedfs/pull/3879
collect all file ids from the file without cut off time for finding missing data from volumes
=> [volume.fsck] collect ids without cut off time for finding missing data from volumes

weed/remote_storage/azure/azure_storage_client.go
https://github.com/seaweedfs/seaweedfs/issues/3943
https://github.com/seaweedfs/seaweedfs/issues/3943
=> fix filer.remote.sync to azure with ContentType

weed/remote_storage/azure/azure_storage_client.go
https://github.com/seaweedfs/seaweedfs/issues/3952
https://github.com/seaweedfs/seaweedfs/issues/3952
https://github.com/seaweedfs/seaweedfs/issues/3952
@chrislusf This is my first ever PR in Go, open for feedback and corrections.
I've tested using the script in the related issue, and have confirmed the file gets uploaded to Azure and no errors are thrown
=> Replace dashes with underscores in x-amz-meta headers

weed/s3api/s3api_object_multipart_handlers.go
Signed-off-by: changlin.shi <changlin.shi@ly.com>
fix #3967
=> fix 'NoSuchUpload' when upload part

weed/shell/command_fs_meta_save.go
fix typo on fix fs.meta.save arg parsing
=> ADHOC: fix fs.meta.save typo

weed/shell/command_volume_list.go
to make a backup of the second replicas from the third DC, you need to exclude the volume of files from the first DC, and for this you need to get a list of file volumes from the first DC
Add filtering by DC for the volume.list command
=> volume.list show volumes only from the specified dc/rack/dn

weed/filer/filerstore_wrapper.go, weed/mount/meta_cache/meta_cache.go, weed/server/filer_grpc_server_rename.go
Signed-off-by: wusong <wangwusong@virtaitech.com>
HardLinkCounter incorrect during move operation 
keep HardLinkCounter unchanged
do test with commands( touch a, ln a b, mv b c, rm c) step by step and observe the value of HardLinkCounter.
=> Fix hardlink counting

weed/shell/command_fs_verify.go
t is necessary to check the integrity of files uploaded for the last day, week
Chunk Availability Check
```
> fs.verify
file:/buckets/test/Certificates2.zip needle status failed verify 6:4: rpc error: code = Unknown desc = not found
file:/buckets/test/Certificates4.zip needle status failed verify 4:6: rpc error: code = Unknown desc = not found
file:/buckets/test/Certificates6.zip needle status failed verify 6:1: rpc error: code = Unknown desc = not found
verified 10 files, error 3 files 
> fs.verify -v
file:/buckets/test/Certificates.zip needle status . verifed
file:/buckets/test/Certificates0.zip needle status . verifed
file:/buckets/test/Certificates1.zip needle status . verifed
file:/buckets/test/Certificates10.zip needle status . verifed
file:/buckets/test/Certificates11.zip needle …
```
=> fs.verify needles status of file

weed/s3api/filer_multipart_test.go
tiny fix
fix warning from IDE : "redundant type from array, slice, or map composite literal"
=> Fix ide warning

weed/shell/command_volume_vacuum_disable.go, weed/shell/command_volume_vacuum_enable.go
add more help message, in case of misunderstanding
=> add more help message, in case of misunderstanding

weed/images/cropping.go, weed/images/cropping_test.go, weed/server/volume_server_handlers_read.go
Add image cropping parameter support: `crop_x1, crop_y1, crop_x2, crop_y2`
Unit test and browser access testing.
=> Add image cropping.

weed/filer/filechunk_section_test.go, weed/mount/page_writer/page_chunk_mem.go, weed/mount/page_writer/page_chunk_swapfile.go
the connected chunks are uploaded separately
connect the chunks during upload
run virtual machines with the fix
=> merge chunks during upload

weed/mount/weedfs_file_mkrm.go
Signed-off-by: wusong <wangwusong@virtaitech.com>
delete entry twice in metacache
remove redundant code
=> [mount]: delete redundant code

weed/mount/page_writer/page_chunk_mem.go
Signed-off-by: wusong <wangwusong@virtaitech.com>
memchunk save content twice
delete redundant code
=> memchunk save content twice

weed/server/volume_server_handlers_write.go
Signed-off-by: Neo <zhaoxiaolong@virtaitech.com>
1. ReplicatedWrite for volume server get write err for some reasons and not return at that point.
2. Post handler generate invalid json resp  .
add return.
=> volume:fix return if Replicate write error

weed/shell/command_s3_bucket_create.go, weed/shell/command_s3_bucket_create_test.go
verify s3 bucket name according to aws rules on bucket creation.
=> ADHOC: s3 bucket name verification

k8s/helm_charts2/templates/master-statefulset.yaml
fixes dereference in master statefulset
missed one, sorry
@chrislusf 
I'm working on a helm chart publish action for you that will catch these with helm lint and publish the chart to github pages.
=> fix missing dereference 

weed/s3api/s3api_objects_list_handlers.go
…dlers returns less than the specified limit
如果 bucket 对应的数据库表有 10条数据，其中7条数据是目录（空目录），3条数据是文件；
当请求 s3 list_object 接口时，指定 limit 为2，客户端收到的响应中 Content 的数据可能少于 2条并且 isTruncted 是 false
导致客户端看到的是 seaweedfs 存储的文件是数据少于2条，并且不再继续检索（isTruncted 为 false 则没有继续检索的必要）
at weed/server/filer_grpc_server.go:65
因为 seaweedfs 遍历数目的时候把文件夹过滤了，过滤后limit就会减一，导致实际没有获取到正确的 limit 个数的文件
在外层加了 for 循环，直到 isTruncted 为 true 或者的确没有数据（empty 为true）才返回
=> Fix s3api_object_list_handlers returning contents less than the specified limit when more data actually exists

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
Database secrets as k8s envs
added values parameter for filer to have envs mounted from k8s secrets
add values for `filer.secretExtraEnvironmentVars`
=> added secret envs to filer

weed/topology/node.go
Typo/grammar in error message
Fixing the typo/grammar
=> fix(weed/topology/node.go): typo in error message

weed/shell/command_volume_server_evacuate.go
unclean variables with each run
clean variables
=> shell script  unclean variables

weed/topology/topology.go
Fixes regression introduced in
https://github.com/seaweedfs/seaweedfs/pull/4313
Related to #4307
Fixing leader selection retry logic.
Retrying until the selection timeout or a leader is selected.
* Ran unit tests
* Ran server and master commands with some logging to verify a leader selection retrying was happening and a leader was selected.
=> Retry until a leader is selected.

weed/command/mount_std.go
Permission to modify files in Linux system
fuseMountOptions EnableAcl :true
=> weed mount default EnableACL，Support chmod chown

weed/server/master_grpc_server_volume.go
It looks like a clerical error, you introduced useless code.
=> style: clerical error

weed/s3api/s3api_objects_list_handlers.go
```
make s3tests
docker exec -it seaweedfs-s3tests-1 tox s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_prefix
>       continuation_token = validate_bucket_listv2(bucket_name, prefix, delim, None, 1, True, ['boo/bar'], [])
s3tests_boto3/functional/test_s3.py:333: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
bucket_name = 'yournamehere-weird8qv2jjraydw-1', prefix = 'boo/', delimiter = '/', continuation_token = None, max_keys = 1, is_truncated = True, check_objs = ['boo/bar'], check_prefixes = [], last = False
def validate_bucket_listv2(bucket_name, prefix, delimiter, …
```
=> try fix s3test test_bucket_listv2_delimiter_prefix

weed/server/volume_grpc_erasure_coding.go
=> compilation fail

weed/filer/filer_delete_entry.go
fix #4535 
First delete the metadata and then delete the chunks.
=> fix 404 not found

weed/filer/redis/redis_cluster_store.go, weed/filer/redis/redis_store.go, weed/filer/redis/universal_redis_store.go, weed/filer/redis/universal_redis_store_kv.go, weed/filer/redis2/redis_cluster_store.go, weed/filer/redis2/redis_sentinel_store.go, weed/filer/redis2/redis_store.go, weed/filer/redis2/universal_redis_store.go, weed/filer/redis2/universal_redis_store_kv.go, weed/filer/redis3/ItemList.go, weed/filer/redis3/item_list_serde.go, weed/filer/redis3/kv_directory_children.go, weed/filer/redis3/kv_directory_children_test.go, weed/filer/redis3/redis_cluster_store.go, weed/filer/redis3/redis_sentinel_store.go, weed/filer/redis3/redis_store.go, weed/filer/redis3/skiplist_element_store.go, weed/filer/redis3/universal_redis_store.go, weed/filer/redis3/universal_redis_store_kv.go, weed/filer/redis_lua/redis_cluster_store.go, weed/filer/redis_lua/redis_sentinel_store.go, weed/filer/redis_lua/redis_store.go, weed/filer/redis_lua/stored_procedure/init.go, weed/filer/redis_lua/universal_redis_store.go, weed/filer/redis_lua/universal_redis_store_kv.go
https://github.com/seaweedfs/seaweedfs/issues/4532
Adding support for Redis version 7
Updating package imports
=> Initial patch for redis version 7 support

go.mod, go.sum, weed/storage/store.go, weed/storage/volume.go
https://github.com/seaweedfs/seaweedfs/pull/4561
=> fix from comment delete volume is empty

weed/storage/volume.go
fix get file stats for IsEmpty
=> fix get file stats for IsEmpty

weed/mount/weedfs_file_read.go
=> Fix buff use

weed/storage/store_vacuum.go
=> Fix DataBackend nil pointer

weed/storage/store.go
fix https://github.com/seaweedfs/seaweedfs/issues/4661
=> refresh max volume count after adjust

weed/server/raft_server_handlers.go
avoid logging nil error
check if err is not nill
=> avoid logging nil error

weed/mount/meta_cache/meta_cache.go
Fix #4648 
Add lock on meta cache
=> Fix data loss: add lock for metacache

weed/remote_storage/s3/s3_storage_client.go
trying to fix #4604
Concurrency 1 worker better in this case
build and run locally
=> Concurrency works better

weed/storage/disk_location.go, weed/storage/erasure_coding/ec_encoder.go, weed/storage/erasure_coding/ec_shard.go, weed/storage/erasure_coding/ec_volume.go, weed/storage/needle_map_sorted_file.go
Release resources when they are no longer needed.
=> Fix resource leaks

backers.md
N/A
Add [Nimbus Web Services](https://nimbusws.com) to the list of backers.
N/A
=> chore: add nimbus web services to backers.md

weed/stats/metrics.go, weed/storage/erasure_coding/ec_shard.go, weed/storage/volume.go, weed/storage/volume_loading.go, weed/storage/volume_vacuum.go
Add the type of disk to prometheus
Adding the corresponding label
Not tested
=> Add disk type to prometheus metrics

weed/stats/metrics.go, weed/storage/erasure_coding/ec_shard.go, weed/storage/volume.go, weed/storage/volume_loading.go, weed/storage/volume_vacuum.go
Reverts seaweedfs/seaweedfs#4736
Not sure whether this PR is ready or not.
=> Revert "Add disk type to prometheus metrics"

k8s/charts/seaweedfs/templates/filler-ingress.yaml, k8s/charts/seaweedfs/templates/master-ingress.yaml, k8s/charts/seaweedfs/values.yaml
need to disable basic auth
fix chart
local
=> [heml] fix default affinity and allow owerride ingress annotations

weed/mount/dirty_pages_chunked.go
=> avoid pass lock by value

weed/util/lock_table.go
=> fix lock table

weed/s3api/s3api_server.go
Updating the configuration with `kill -s HUP`
add kill signal handler
=> [s3] do reload s3 static config

unmaintained/see_dat/see_dat.go
see_dat print  file  name 
add name in visitneedle 
see_dat that has name file
=> see_dat add print name 

weed/filer/tikv/tikv_store.go
=> Fix: issues #4950

weed/server/volume_server_handlers.go
https://github.com/seaweedfs/seaweedfs/issues/4980
replace type metric to INVALID
localy
=> Replace an invalid method in a metric with an invalid one

weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_bucket_skip_handlers.go, weed/s3api/s3api_server.go
The ansible aws module requests the bucket version, but the listing is returned
https://docs.ansible.com/ansible/latest/collections/amazon/aws/s3_bucket_module.html#parameter-versioning
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.ClientError: An error occurred (504) when calling the GetBucketVersioning operation (reached max retries: 4): Gateway Timeout
failed: [host -> localhost] (item={'name': 'artifacts'}) => {"ansible_loop_var": "loop_s3_bucket", "boto3_version": "1.28.54", "botocore_version": "1.31.54", "changed": false, "error": {"code": "504", "message": "Gateway Timeout"}, "loop_s3_bucket": {"name": "artifacts"}, "msg": "Failed to get bucket versioning: An error occurred (504) when calling the …
```
=> [s3api] add default response for GetBucketVersioning

weed/shell/command_fs_merge_volumes.go
As you requested in #4999 directory path changed to a named parameter
Locally
=> fs.mergeVolumes: change dir to a named parameter

weed/server/master_grpc_server_assign.go
Trying to find out the reason
https://github.com/seaweedfs/seaweedfs/issues/3886
write intermediate errors to the log
=> logging PickForWrite error

.gitignore, weed/weed.go
- Updated the ordering of import
- Removing unused `rand.Seed` function call
- Update `.gitignore` to ignore image files generated as part of running the test suite
=> Minor cleanup & gitignore update

k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
=> fix helm install error for No such file or directory

k8s/charts/seaweedfs/templates/filer-service-client.yaml, k8s/charts/seaweedfs/templates/filer-service.yaml, k8s/charts/seaweedfs/templates/filer-servicemonitor.yaml, k8s/charts/seaweedfs/templates/filler-ingress.yaml, k8s/charts/seaweedfs/templates/master-ingress.yaml, k8s/charts/seaweedfs/templates/master-service.yaml, k8s/charts/seaweedfs/templates/master-servicemonitor.yaml, k8s/charts/seaweedfs/templates/s3-service.yaml, k8s/charts/seaweedfs/templates/s3-servicemonitor.yaml, k8s/charts/seaweedfs/templates/secret-seaweedfs-db.yaml, k8s/charts/seaweedfs/templates/volume-service.yaml, k8s/charts/seaweedfs/templates/volume-servicemonitor.yaml
Mainly deploy some resources independently and switch based on the enable field
=> helm enable resource for template

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
1. using external master address
=> helm using external master address

weed/s3api/s3api_object_handlers_postpolicy.go
when I upload file using S3 POST Policy，the real upload file‘s Content-Type is incorrect， such as "multipart/form-data; boundary=-------"
Fix  Content-Type with correct value,  such as "image/jpeg"。
By hand on a test server.
=> Adapt S3 POST ContentType

weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_server.go
=> refactor: put the auth outside

weed/storage/volume_vacuum.go
avoid unexpected compact size after https://github.com/seaweedfs/seaweedfs/issues/5215
return an error if the data size is smaller than the expected size
localy
```
1. make server
2. warp mixed --insecure --host 127.0.0.1:8000 --noclear  --obj.size 3KiB --concurrent 300 --noprefix --duration 20s --access-key some_access_key1 --secret-key some_secret_key1
3. echo -e "lock\nvolume.vacuum -garbageThreshold 0.01nvolume.list\n" | weed shell
```
=> avoid unexpected compact size

weed/s3api/s3api_objects_list_handlers.go
Object list delimiters currently raise a `ErrNotImplemented`
Issue #4853 
By grouping similar objects under the `CommonPrefixes` if a `Delimiter` is supplied by the request.
See docs here for implementation details:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax
Using `ceph/s3-tests` and based on the Dockerfile in tests/s3/compatibility.
```bash
docker run --name s3tests-seaweedfs \
--rm --net=host \
-e S3TEST_CONF=s3tests.conf \
-v ./s3tests.conf:/s3-tests/s3tests.conf \
-v ./tox:/s3-tests/.tox \
-it s3tests \
tox -- -v -W ignore::DeprecationWarning ./s3tests_boto3/functional/test_s3.py -k "test_bucket_listv2_delimiter and not (test_bucket_listv2_delimiter_basic or test_bucket_listv2_delimiter_prefix or …
```
=> feat: add support for S3 ListObjects and ListObjectsV2

weed/command/master_follower.go, weed/server/volume_grpc_copy.go, weed/storage/erasure_coding/ec_decoder.go
=> remove repetitive words

weed/server/filer_server_handlers.go
Security scanning results in the creation of eat many labels with methods in metrics in promiteus
which leads to increased memory consumption and freezing
replace an invalid methods in a metric with an invalid one
https://github.com/seaweedfs/seaweedfs/pull/4987
localy
```
1. make server
2 .curl -s "http://192.168.3.43:9324/metrics" | grep 'SeaweedFS_filer_request_total'
SeaweedFS_filer_request_total{code="200",type="GET"} 3
SeaweedFS_filer_request_total{code="201",type="POST"} 1
SeaweedFS_filer_request_total{code="405",type="INVALID"} 3
SeaweedFS_filer_request_total{code="409",type="POST"} 1
3. curl -sX BAD -o /dev/null  "http://localhost:8888/test/"                  
4. curl -s "http://192.168.3.43:9324/metrics" | grep 'SeaweedFS_filer_request_total' …
```
=> [filer] replace an invalid methods in a metric with an invalid one

weed/storage/backend/rclone_backend/rclone_backend.go
Compilation error related to rclone dependency update.
Adapt code to new rclone API.
TODO
=> Fix compilation error with rclone update

weed/mount/weedfs_attr.go
=> [mount] fix GetAttr blocks count

weed/stats/metrics.go, weed/topology/volume_growth_test.go, weed/topology/volume_layout.go
I'm trying to finish the PR  https://github.com/seaweedfs/seaweedfs/pull/5163
I added a test of the function that I plan to change and added metrics to see the changes in production
=> [master] add test for PickForWrite add metrics for volume layout

weed/server/master_grpc_server_assign.go, weed/server/master_server_handlers.go, weed/topology/volume_layout.go, weed/topology/volume_location_list.go
https://github.com/seaweedfs/seaweedfs/issues/5435
check if list not emty
=> fix panic 5435

weed/topology/volume_layout.go
https://github.com/seaweedfs/seaweedfs/issues/5456
https://github.com/seaweedfs/seaweedfs/issues/5456
=> fix panic at isAllWritable 

weed/ftpd/ftp_server.go, weed/s3api/auth_signature_v4.go, weed/s3api/auto_signature_v4_test.go, weed/s3api/s3api_bucket_handlers.go, weed/util/skiplist/skiplist.go
=> chore: fix function names in comment

k8s/charts/seaweedfs/README.md, k8s/charts/seaweedfs/values.yaml, weed/mq/client/cmd/weed_sub/subscriber.go, weed/server/filer_server.go, weed/server/volume_server_handlers.go
=> chore: fix some typos in comments

weed/storage/needle/needle_parse_upload.go
Hello!
This is my first pull request in golang ever, please review.
It worked locally, although I have the feeling parts of the code between the
two parse functions should be shared by using a separate function.
After extracting the file of a multipart upload, it would be used
by the same function as the direct upload file.
In some cases, the user should be able to submit data into SeaweedFS without creating a `multipart/form-data` (boundary etc). The user would just POST with the corresponding `content-type` header and be done (see JS snippet below as an example).
When an upload  happens, the headers are checked for the `content-type` header,
if a content-type is explicitly set, parsing of `multipart/form-data` is omitted
and the data is uploaded as is, using the `content-type` and …
=> feat: upload files directly without multipart/form-data

weed/server/master_grpc_server.go
当 masterServer 的  KeepConnected 连接断开后, messageChan 的消费停止，但 masterServer 仍然可能会往 messageChan 发送消息，当 messageChan 达到最大容量后（现在是：100）会导致 defer 逻辑阻塞，进而死锁
**解决**
当 stream 断开后，messageChan 会停止消费，此时启动一个协程来消费 messageChan（后续该 chan 就不会阻塞了）， defer 中 `ms.broadcastToClients(update)` 就能够正常执行，当删除该 client 时 `ms.deleteClient(clientName)` 关闭 messageChan，保证上面创建的消费协程正常退出
=> fix deadlock caused by message chan blocked

weed/mount/inode_to_path.go, weed/mount/weedfs.go, weed/mount/weedfs_file_sync.go
Open file handles were not updated
use invalidateFunc to reset dirty pages and entry for open filehandles
2 Server setup, as for issue #5649
=> Fix Issue #5649

weed/storage/disk_location.go
=> fixed fail to initialize existing ec volume when volume server has separate index dictory

unmaintained/stress_filer_upload/bench_filer_upload/bench_filer_upload.go, unmaintained/stress_filer_upload/stress_filer_upload_actual/stress_filer_upload.go, weed/command/master.go, weed/iamapi/iamapi_server.go, weed/iamapi/iamapi_test.go, weed/operation/chunked_file.go, weed/operation/upload_content.go, weed/s3api/auto_signature_v4_test.go, weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_object_handlers_put.go, weed/s3api/s3api_server.go, weed/server/common.go, weed/server/filer_server_handlers_read.go, weed/server/filer_server_handlers_write_autochunk.go, weed/server/volume_server_handlers_read.go, weed/shell/command_fs_merge_volumes.go, weed/storage/needle/needle_parse_upload.go, weed/util/http_util.go
Code consistency
replace all string methods to constant 
action tests
=> refactor all methods strings to const

weed/stats/metrics.go, weed/topology/volume_layout.go
the metric is not informative when using several data centers
add  datacenter to lables
=> metrics stats of volume layout depends on the data center

weed/topology/volume_layout.go
avoid counter overflow
https://github.com/seaweedfs/seaweedfs/issues/5735
atomic int to bool
=> [master] refactor HasGrowRequest to atomic bool

weed/shell/command_ec_balance.go
When running an `ec.balance` admin command, if the EC shard wants to be moved to a different volume server, but a suitable target can't be picked, the user gets no feedback on to why the move hasn't taken place. Currently it just skips over to the next shard without any feedback, i.e.:
```
I0715 19:04:01.095837 masterclient.go:228 master localhost:9333 redirected to leader 10.43.0.251:9333
10.43.0.251:8084 has 2 overlimit, moving ec shard 118.1
10.43.0.251:8084 has 1 overlimit, moving ec shard 118.4
10.43.0.251:8081 has 5 overlimit, moving ec shard 333.6
```
If a suitable target to move the shard to cannot be found, print a warning and a reason why it skipped each volume server it considered. e.g.
```
10.43.0.251:8082 has 5 overlimit, moving ec shard 65.6
WARNING: Could not find suitable …
```
=> Add warning with hints to why a EC shard cant be moved

unmaintained/diff_volume_servers/diff_volume_servers.go, unmaintained/repeated_vacuum/repeated_vacuum.go, unmaintained/stream_read_volume/stream_read_volume.go, unmaintained/volume_tailer/volume_tailer.go, weed/command/backup.go, weed/command/benchmark.go, weed/command/download.go, weed/command/filer.go, weed/command/filer_backup.go, weed/command/filer_cat.go, weed/command/filer_copy.go, weed/command/filer_meta_backup.go, weed/command/filer_meta_tail.go, weed/command/filer_remote_gateway.go, weed/command/filer_remote_sync.go, weed/command/filer_replication.go, weed/command/filer_sync.go, weed/command/iam.go, weed/command/master.go, weed/command/master_follower.go, weed/command/mount_std.go, weed/command/mq_broker.go, weed/command/s3.go, weed/command/server.go, weed/command/shell.go, weed/command/upload.go, weed/command/volume.go, weed/command/webdav.go, weed/util/config.go
Duplicate calls to load security config
Added sync.Once for loading security config
=> Added loadSecurityConfigOnce

weed/mount/filehandle.go, weed/mount/filehandle_map.go, weed/mount/filehandle_read.go, weed/mount/locked_entry.go, weed/mount/weedfs.go, weed/mount/weedfs_dir_lookup.go, weed/mount/weedfs_dir_read.go, weed/mount/weedfs_file_lseek.go, weed/mount/weedfs_file_sync.go
https://github.com/seaweedfs/seaweedfs/issues/5813
Reduce fh.entryLock
=> Fix dead lock

weed/server/filer_server_handlers_read_dir.go, weed/server/filer_ui/filer.html
In the Filer UI, the version is not indicated in the title, unlike in the Master UI and Volume UI.
I simply added the version display similar to the master and volume. This is just an aesthetic change to appease perfectionism :)
=> [filer] Added a version to the title of Filer UI

k8s/charts/seaweedfs/templates/cosi-cluster-role.yaml, k8s/charts/seaweedfs/templates/cosi-deployment.yaml, k8s/charts/seaweedfs/values.yaml
Fixed some issues with writing events and creating initial configuration
=> Update COSI driver v0.1.1

weed/command/s3.go, weed/security/tls.go
CVE-2016-2183
add tls configuration with tls min version, tls max version and cipher suites
=> fix CVE-2016-2183

weed/topology/data_node.go, weed/topology/disk.go
master panic: fatal error: concurrent map iteration and map write
=> [master] fix master panic

weed/storage/volume_loading.go
https://github.com/seaweedfs/seaweedfs/issues/5975
skip checking data integrity for volumes which has remote file
Tested on our environment with lot of remote volumes
=> Skip volume data integrity check for volume which has remote file

weed/filer/elastic/v7/elastic_store.go
env: filer store with elastic
problem:
when we delete some entry on top-level, the code acutally delete the `.seaweedfs_` es index, as the code show:
```
if strings.Count(string(fullpath), "/") == 1 {
return store.deleteIndex(ctx, index)
```
e.g.
If I have some entries like:
```
/dir1/
/some-file.png
/dir2/
...
```
If I delete one of the entry above, the whole index `.seaweedfs_` will be deleted.
Actually , we should delete index like: .seaweedfs_dir1, .seaweedfs_dir2
When delete top-level entry, find the entry first, if it's a directory, delete the corresponding Elasticsearch index.
manual test passed.
=> bug fixed to filer store elastic deleteEntry

.github/workflows/binaries_release5.yml
Completing https://github.com/seaweedfs/seaweedfs/pull/5578
Add OpenBSD `goos`.
Not yet tested, trusting https://github.com/seaweedfs/seaweedfs/pull/5578 for the build to work.
- ~~[ ] I have added unit tests if possible.~~
- ~~[ ] I will add related wiki document changes and link to this PR after merging.~~
=> Add release for OpenBSD

weed/server/master_grpc_server_volume.go, weed/topology/volume_layout.go
https://github.com/seaweedfs/seaweedfs/issues/5735
Growth with large volumes is not effective
Growing the number of volumes step by step
action s3 tests
=> [master] process grow request with must grow

weed/server/master_grpc_server_volume.go
prevent dead loop for followers of master node
=> prevent dead loop for followers of master node

weed/filer/reader_at.go, weed/filer/reader_cache.go, weed/util/chunk_cache/chunk_cache.go
https://github.com/seaweedfs/seaweedfs/issues/6020
handle nil structure
tested the file read
=> fix file read crash

k8s/charts/seaweedfs/Chart.yaml
The chart values have been updated but not the chart version.
=> Bump chart version

weed/s3api/auth_signature_v4.go
This PR closes #6086
Server checks if `X-Forwarded-Prefix` header was passed, in this case add additional URL signature check.
Additionally, `X-Forwarded-Host` is handled in same way as in f747767aa10da345c19a61a63687d52876efe6a5.
Tried to use s3cmd, aws-cli and rclone, everything worked fine.
=> s3api: Fix signature v4 with reverse proxy at sub-path

weed/storage/volume_checking.go
It wants to check the last 10 chunks, but actually only checks the last chunk and then exits.
=> fix: volume data integrity check

weed/storage/volume_write.go
When we execute ```volume.chech.disk```. Sometimes, We could see  following situation：
The algorithm think the replica in 10.8.8.60 missed 3 entries, and then call the ```WriteNeedleBlob``` RPC send the 3 entries to another server. 
But sometimes this is not the case. These three entries are first written to 10.8.11.60, and while being written to 10.8.8.60, we execute volume.check.disk. In this scenario, the three entries will be duplicated in the Volume on 10.8.8.60. So there are two copy of the 3 entry.
This is not we want.
Check if there is a same file before write. 
```shell
sudo weed benchmark -master=10.8.11.60:9333 -c=200 -n=1000000 -size=1024 -read=false -replication=001
lock; volume.check.disk -nonRepairThreshold 1.1 -syncDeleted -v; unlock
```
=> fix(volume): to avoid duplicate write a same needle

weed/shell/command_ec_encode.go
unitest weed/shell fail
fix unitest build fail
=> fix format

weed/filer/filer_notify_read.go, weed/server/filer_grpc_server_sub_meta.go, weed/util/log_buffer/log_buffer.go, weed/util/time.go
https://github.com/seaweedfs/seaweedfs/issues/6181
https://github.com/seaweedfs/seaweedfs/issues/6182
For 6181:
- when no entry is found (`processedTsNs` is 0), try next day
For 6182:
- set larger buf size
Using weed s3 and transfer 100 * 512MB files, no events is lost
=> Fix 6181/6182

Makefile, weed/shell/command_volume_balance.go, weed/shell/command_volume_balance_test.go, weed/shell/command_volume_server_evacuate.go, weed/shell/commands.go
alancing between racks and nodes
aad select dn options rack and nodes
=> [shell] volume.balance collect volume servers by dc rack node

weed/filer/filechunk_section.go
https://github.com/seaweedfs/seaweedfs/issues/6168
resolve the thread safty for function
not yet, will do long IO test
=> remove dup code for section.reader access

weed/shell/command_ec_common.go, weed/shell/command_ec_decode.go, weed/shell/command_ec_encode.go, weed/shell/command_fs_verify.go, weed/shell/command_volume_balance_test.go, weed/shell/command_volume_configure_replication.go, weed/shell/command_volume_delete_empty.go, weed/shell/command_volume_fix_replication.go, weed/shell/command_volume_fsck.go, weed/shell/command_volume_tier_download.go, weed/shell/command_volume_tier_move.go
Small TODO code cleanup for f2db7466.
No test affected.
=> Unify usage of shell.EcNode.dc as DataCenterId.

weed/command/filer_sync.go
The current filer.xdfs data synchronization tool does not support configuring the path with a '/' suffix in the directory name. This leads to inaccurate matching when multiple directories have the same prefix. For example, in the directories [/a/b, /a/bb, /a/bbb], it is not possible to accurately match /a/b. Although excludePaths can be used to exclude /a/bb and /a/bbb, directories are typically dynamically created and deleted, and a directory named /a/bbbb may be created in the future. excludePaths cannot solve all the problems.
Support adding '/' suffix in the configuration for accurate matching of specific directories.
test in my cluster，cluster A add/update/delete sync to cluster B
=> filer sync: source path and exclude path support dir suffix

weed/wdclient/exclusive_locks/exclusive_locker.go
Executing lock and unlock repeatedly, when the first goroutine is sleeping and lock is executed again, will result in two goroutines running simultaneously. This can potentially lead to one of the goroutines failing to renew and changing the value of isLocked to false. which is unreasonable although it does not currently cause any problems
ExclusiveLocker only create one renew goroutine
test in my cluster
Executing lock and unlock repeatedly, the issue did not reoccur.
=> ExclusiveLocker only create one renew goroutine

weed/server/volume_server_handlers_ui.go, weed/storage/store_ec.go
fix https://github.com/seaweedfs/seaweedfs/issues/6109
screenshot for current behavoir: https://github.com/seaweedfs/seaweedfs/issues/6274
we need to convert uint32 to int first, otherview it will overflow
=> fix EcVolumes sorting in volume UI

weed/stats/metrics.go
MasterPickForWriteErrorCounter metric does not work
register MasterPickForWriteErrorCounter
=> fix missing register master metric  MasterPickForWriteErrorCounter

weed/server/master_grpc_server_volume.go, weed/topology/topology.go, weed/topology/volume_layout.go
https://github.com/seaweedfs/seaweedfs/issues/6278
We check the DC and the Rack
=> use ShouldGrowVolumesByDcAndRack

weed/shell/command_volume_fix_replication.go
=> use readable bytes size string in shell output

weed/server/master_server.go, weed/server/raft_hashicorp.go
update LastLeaderChangeTime for hashicorp raft
=> [master] update LastLeaderChangeTime for hashicorp raft

weed/server/master_grpc_server_assign.go, weed/topology/topology.go, weed/topology/volume_layout.go
https://github.com/seaweedfs/seaweedfs/issues/6290
avoid timeout when assigning for main request with filter by DC or rack
=> [master] avoid timeout when assigning for main request with filter by DC or rack

weed/shell/command_cluster_check.go, weed/shell/command_volume_balance_test.go, weed/shell/command_volume_list.go, weed/storage/disk_location_test.go, weed/storage/types/volume_disk_type.go
=> [shell] use constant for hdd of type

weed/shell/command_volume_list.go
When the number of nodes tends to infinity when searching for a volume sheet by one ID, the output does not fit on the screen from empty data centers, racks and disk info
We show information on datasets, rivers and disk info only for found volumes
localy
```
make server
weed shell
> volume.list -volumeId 6
Topology volumeSizeLimit:1024 MB hdd(volume:7/23 active:7 free:16 remote:0)
DataCenter DefaultDataCenter hdd(volume:7/23 active:7 free:16 remote:0)
Rack DefaultRack hdd(volume:7/23 active:7 free:16 remote:0)
DataNode 172.30.225.133:8080 hdd(volume:7/23 active:7 free:16 remote:0)
Disk hdd(volume:7/23 active:7 free:16 remote:0)
volume id:6 size:248 file_count:1 version:3 modified_at_second:1733927883 
Disk hdd total size:248 file_count:1 
DataNode 172.30.225.133:8080 total size:248 …
```
=> volume.list avoid output empty data center and rack and disk info

weed/shell/command_volume_list.go
It is necessary to track the position of the writable volumes on the disks
Add writable. filer
=> [shell] volume.list show only writable volumes 

weed/stats/metrics.go
fix: filer may crash by bucketLastActiveTsNs concurrency access.
https://github.com/seaweedfs/seaweedfs/pull/6349
make bucketLastActiveTsNs concurrency write save by sync.Mutex
tested in my prod env.
=> fix: filer may crash by bucketLastActiveTsNs concurrency access.

weed/shell/command_ec_common.go
Makes EC re-balancing for shards across racks concurrent within `shell.EcBalance()`. Impacts both `ec.encode` and `ec.balance`.
No algorithmic changes, other than running EC sub-tasks in parallel.
=> Parallelize EC shards balancing across racks.

weed/shell/command_ec_common.go
Makes EC re-balancing for shards within racks concurrent within `shell.EcBalance()`. Impacts both `ec.encode` and `ec.balance`.
No algorithmic changes, other than running EC sub-tasks in parallel.
=> Parallelize EC shards balancing within racks

weed/shell/command_ec_encode.go
Fix volume replica parallelization for `ec.encode`. In particular, this PR makes the number of parallel tasks configurable.
See 826edd5d.
No functional / test changes.
=> Fix volume replica parallelization within `ec.encode`.

weed/shell/command_volume_fix_replication.go
When I executing `volume.fix.replication` command, I found that the command will return immediately once an error happens. I thought it would be better to wait for the command to fix other volumes. After all the command was designed to fix all volumes.
```shell
> volume 1 replication 010 is not well placed 10.48.1.82:8080
volume 54977 replication 010 is not well placed 10.48.1.47:8080
volume 67201 replication 010 is not well placed 10.48.1.47:8080
volume 77312 replication 010 is not well placed 10.48.1.73:8080
volume 73191 replication 010 is not well placed 10.48.1.47:8080
volume 66930 replication 010 is not well placed 10.48.1.47:8080
skip delete volume 1 as collection juicefs-algorithm is mismatch:
skip delete volume 1 as collection juicefs-algorithm is mismatch:
deleting volume 54977 …
```
=> skip error while executing volume.fix.replication

weed/shell/command_volume_fix_replication.go
Change the parameter of `volume.fix.replication` from `-n` to `-force` which is much straightforward.
=> [weed] change -n to -force

weed/shell/command_volume_balance.go
close  #6423
set value after args are parsed
it works in my local cluster.
=> fix force arg dropped during volume balance command

weed/s3api/auth_credentials.go
close #6353 
unify processing for authTypeStreamingSigned and normal v4 authentication
Tested in local cluster.
=> Bugfix s3 audit missing requester for PUT requests

weed/shell/command_ec_encode.go
Fix https://github.com/seaweedfs/seaweedfs/issues/6445 , caused by a bug introduced during the implementation of https://github.com/seaweedfs/seaweedfs/discussions/6179 .
`ec.balance` is no longer deleting source volumes after EC conversion.
This logic was originally part of `spreadEcShards()`, which got removed during the unification effort with `ec.balance` (https://github.com/seaweedfs/seaweedfs/pull/6344), accidentally breaking functionality in the process.
The MR restores the deletion code for EC'd volumes - with parallelization support.
There're no tests verifying the deletion of volumes after EC conversion - which is also why the bug slipped by in the first place :disappointed: 
I'll follow up with proper tests once this change is merged.
=> `ec.encode`: Fix bug causing source volumes not being deleted after EC conversion.

weed/shell/command_ec_common.go
When no collections are defined, `ec.balance` and other commands performing EC re-balancing such as `ec.encode`, fail to complete.
This change allows for EC re-balancing without any collections defined. The end result is that EC shards
won't be balanced EC shards across volumes, but will still be balanced across racks.
No existing functional tests affected.
=> `ec.balance`: Allow EC balancing without collections.

weed/server/master_server.go
https://github.com/seaweedfs/seaweedfs/issues/6492
This PR removes a rate limit semaphore on leader selection logic for masters.
It was introduced by 054374c7 (2024-03-12) and serves no practical purpose, yet it caps the maximum QPS master servers can handle.
No functional changes for set ups not doing 1000+ QPS. Surfacing this issue will likely require integration testing.
=> Remove rate limit semaphore on master's leader selection logic.

weed/s3api/auth_signature_v4.go
=> use X-Forwarded-Host and X-Forwarded-Port to determine correct host for AWS signature

weed/s3api/s3api_object_handlers_delete.go, weed/s3api/s3api_object_handlers_multipart.go, weed/s3api/s3api_object_handlers_put.go, weed/s3api/stats.go, weed/stats/metrics.go
add fixed for the new metrics
more detail: https://github.com/seaweedfs/seaweedfs/pull/6349
=> fix: record and delete bucket metrics after inactive

weed/command/mount_std.go, weed/shell/command_ec_common.go
Fixes a couple newlines missing i found while playing with `weed.shell`.
No testing required.
=> Nit: remove missing newlines on `weed shell` commands output.

weed/s3api/auth_credentials.go, weed/s3api/auth_signature_v4.go, weed/s3api/auto_signature_v4_test.go, weed/s3api/chunked_reader_v4.go, weed/s3api/chunked_reader_v4_test.go, weed/s3api/s3api_auth.go, weed/s3api/s3api_object_handlers_put.go
- **add tests for s3 signature**
- **add test for newSignV4ChunkedReader.Read()**
We add tests so that we can tackle the following issues, without breaking existing stuff:
- https://github.com/seaweedfs/seaweedfs/issues/6526
- https://github.com/seaweedfs/seaweedfs/issues/6517
- [c] I have added unit tests if possible.
=> add s3 signature tests and prepare implementation of STREAMING-UNSIGNED-PAYLOAD-TRAILER

weed/shell/command_ec_encode.go
This PR guarantees EC shards for converted volumes are immediately available after encoding, even when not affected
by subsequent re-balancing.
No unit/integration tests cover this command :disappointed: Tested on a local dummy `weed server` setup:
```
> volume.list
Topology volumeSizeLimit:30000 MB hdd(volume:7/8 active:7 free:1 remote:0)
DataCenter DefaultDataCenter hdd(volume:7/8 active:7 free:1 remote:0)
Rack DefaultRack hdd(volume:7/8 active:7 free:1 remote:0)
DataNode 192.168.10.117:8001 hdd(volume:7/8 active:7 free:1 remote:0)
Disk hdd(volume:7/8 active:7 free:1 remote:0)
volume id:4  size:70182392  file_count:1388  version:3  modified_at_second:1738956668 
volume id:3  size:73913728  file_count:1473  version:3 …
```
=> `ec.encode`: Explictly mount EC shards after volume conversion.

k8s/charts/seaweedfs/Chart.yaml, k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/templates/master-statefulset.yaml, k8s/charts/seaweedfs/templates/volume-statefulset.yaml
Reverts seaweedfs/seaweedfs#6581
https://github.com/seaweedfs/seaweedfs/issues/6596
=> Revert "Removed unused certificate mounts from helm chart"

weed/s3api/chunked_reader_v4.go, weed/storage/idx/binary_search.go
make function comment match function name
=> chore: make function comment match function name

weed/s3api/auth_signature_v4.go
Fix s3 auth failed with X-Forwarded-Host and X-Forwarded-Port
deal with X-Forwarded-Host contain port
=> Fix s3 auth failed with X-Forwarded-Host and X-Forwarded-Port

weed/mount/filehandle_read.go
fix https://github.com/seaweedfs/seaweedfs/issues/6672
=> errors when reading uncached files from cloud drive

weed/command/filer.go, weed/command/s3.go
Reverts seaweedfs/seaweedfs#6685
=> Revert "[filer] void panic if s3opt.tlsCACertificate is nill"

weed/s3api/auth_signature_v4.go
=> * Fix s3 auth failed with X-Forwarded-Host and X-Forwarded-Port

weed/topology/topology.go, weed/topology/topology_test.go
Currently, `CollectionListRequest.include_normal_volumes` is ignored; the call always returns regular volumes regardless of value.
Modified `weed.topology.ListCollections()` so `includeNormalVolumes` is properly evaluated.
Added unit tests for `ListCollections()` verifying parameter behavior.
=> Fix implementation of `master_pb.CollectionList` RPC call

weed/s3api/s3api_object_handlers_multipart.go
=> [s3] use chunkedReader in PutObjectPartHandler to handle aws-chunked encoding

.github/workflows/test-s3-over-https-using-awscli.yml
add tests for #6526 , #6703 , #6727
=> [s3] add tests for s3 over https using aws-cli

weed/s3api/s3api_object_handlers_multipart.go, weed/s3api/s3api_object_handlers_put.go, weed/s3api/s3api_put_object_helper.go
Code duplication prevented #6526 and #6703 from being addressed together.
Refactored duplicate put-object code paths into a shared function.
=> [s3] refactor duplicate put-object code paths

weed/server/filer_server.go
https://github.com/seaweedfs/seaweedfs/issues/6765
Put filer LoadConfiguration earlier than get max_file_name_length
Build new filer image and load options with max_file_name_length = 1024, and touch a file with ~1000 characters of filename
=> load configuration before get max_file_name_length

weed/shell/command_ec_encode.go
Improve EC encoding efficiency.
Instead of processing one volume at at time, perform all EC conversion steps (mark readonly -> generate EC shards -> delete volume -> remount) in parallel for all of them.
This should substantially increase speed when EC encoding entire collections.
Affects only `weed shell`, all existing unit/integration tests should pass with this change in place.
=> Improve parallelization for `ec.encode`

weed/s3api/filer_multipart.go
Allow empty files fix.
#6728 
Remove the zero check on the last part of a multipart upload.
Tested locally.
We are unsure about the onward impact of this.
=> Unable to upload empty files to seaweed via. multipart when length is unknown

k8s/charts/seaweedfs/templates/filer-statefulset.yaml, k8s/charts/seaweedfs/values.yaml
fix https://github.com/seaweedfs/seaweedfs/issues/6900
add ip bind for filer
=> Helm Charts: add ip bind for filer

weed/cluster/lock_manager/lock_ring.go, weed/cluster/lock_manager/lock_ring_test.go
lock ring tests sometimes fail
need to get locks on reading
unit tests
=> Improve lock ring

weed/admin/dash/admin_server.go, weed/admin/dash/user_management.go, weed/command/iam.go, weed/command/s3.go, weed/command/scaffold.go, weed/command/scaffold/credential.toml, weed/command/scaffold/example.go, weed/credential/README.md, weed/credential/config_loader.go, weed/credential/credential_manager.go, weed/credential/credential_store.go, weed/credential/credential_test.go, weed/credential/filer_etc/filer_etc_store.go, weed/credential/memory/memory_store.go, weed/credential/memory/memory_store_test.go, weed/credential/migration.go, weed/credential/postgres/postgres_store.go, weed/credential/sqlite/sqlite_store.go, weed/credential/test/integration_test.go, weed/iamapi/iamapi_server.go, weed/s3api/auth_credentials.go, weed/s3api/s3api_put_object_helper_test.go, weed/s3api/s3api_server.go
Credentials read and write operations are complicated.
* Separate credential store into an interface.
* Load credential.toml
=> Add credential storage

weed/admin/dash/admin_server.go, weed/admin/static/js/admin.js, weed/admin/view/app/cluster_collections.templ, weed/admin/view/app/cluster_collections_templ.go, weed/admin/view/app/cluster_volumes.templ, weed/admin/view/app/cluster_volumes_templ.go
If a column has only one value, no need to show the column
add dynamic column showing for disk type, data center, rack
=> weed admin UI dynamically show columns

weed/command/filer.go, weed/command/iam.go, weed/command/master.go, weed/command/master_follower.go, weed/command/s3.go, weed/command/server.go, weed/command/volume.go
Undefined http serve behaiver.
Use new object http server in every goroutine
=> * Fix undefined http serve behaiver

weed/notification/webhook/http.go, weed/notification/webhook/http_test.go, weed/notification/webhook/webhook_queue.go, weed/server/filer_server.go
- Implement webhook publisher with MessageQueue interface
- Support bearer token authentication
- Send notifications as JSON with key and protobuf message
Real-time file event notifications by Enabling external systems to react immediately to file operations
Introducing a new configurable webhook notifications queue
Manuall and unit testing
- [yes] I have added unit tests if possible.
- [yes] I will add related wiki document changes and link to this PR after merging.
=> [Notifications] Support webhook notifications

.github/workflows/s3tests.yml, .gitignore, Makefile, docker/compose/local-clusters-compose.yml, docker/compose/local-filer-backup-compose.yml, docker/compose/local-minio-gateway-compose.yml, docker/compose/local-registry-compose.yml, docker/compose/test-etcd-filer.yml, test/s3/versioning/Makefile, test/s3/versioning/s3_versioning_test.go, weed/Makefile, weed/s3api/filer_multipart.go, weed/s3api/s3api_bucket_config.go, weed/s3api/s3api_bucket_handlers.go, weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_object_handlers_copy.go, weed/s3api/s3api_object_handlers_delete.go, weed/s3api/s3api_object_handlers_put.go, weed/s3api/s3api_object_versioning.go
=> test versioning also

.github/workflows/s3tests.yml, weed/cluster/lock_manager/lock_ring.go
=> add CORS tests

weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_object_handlers_put.go, weed/s3api/s3api_object_versioning.go, weed/util/fullpath.go
=> Read write directory object

weed/server/filer_server_handlers_read.go
In order to prevent image resizing attempts causing memory issue, filer needs to remove the support for image resizing. Only volume server still support it.
fix https://github.com/seaweedfs/seaweedfs/issues/6544
It is not a good idea to resize image on filer level anyway.
=> filer: remove filer support for image resizing

test/s3/basic/object_tagging_test.go, weed/server/filer_server_handlers_write_autochunk.go
fix https://github.com/seaweedfs/seaweedfs/issues/7040#issuecomment-3145615630
=> fix parsing s3 tag

weed/s3api/auth_signature_v4.go, weed/s3api/auto_signature_v4_test.go
follow up for https://github.com/seaweedfs/seaweedfs/pull/7068
=> Support X-Forwarded-Port

weed/notification/webhook/webhook_queue.go
Fix proto messages logging for webhook deadletter messages
=> fix: dead letter message log message

weed/server/volume_grpc_erasure_coding.go, weed/server/volume_server_handlers_ui.go, weed/storage/erasure_coding/ec_volume.go
https://github.com/seaweedfs/seaweedfs/issues/7065
Fixing data types
=> volume server UI: fix ec volume ui

weed/shell/command_ec_common.go
same rack count limit should plus one
=> ec candidate selection needs to adjust same rack count compare

weed/server/filer_server_handlers_copy.go, weed/server/filer_server_handlers_write.go
https://github.com/seaweedfs/seaweedfs/issues/7117
implement server side copying
=> filer: server side copying

weed/s3api/filer_util.go, weed/s3api/s3_constants/header.go, weed/s3api/s3api_conditional_headers_test.go, weed/s3api/s3api_object_handlers.go, weed/s3api/s3api_object_handlers_multipart.go, weed/s3api/s3api_object_handlers_put.go, weed/s3api/s3err/s3api_errors.go
https://github.com/seaweedfs/seaweedfs/issues/7153
https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-reads.html
Add support for conditional put
unit tests
=> S3 API: conditional read and write

k8s/charts/seaweedfs/values.yaml
https://github.com/seaweedfs/seaweedfs/issues/7179
find alternatives
=> k8s: resizeHook avoids bitnami in values.yaml

weed/s3api/auth_signature_v4.go, weed/s3api/auto_signature_v4_test.go, weed/server/master_server.go
fix https://github.com/seaweedfs/seaweedfs/issues/7222
use correct scheme when talking with other raft servers
=> master: Fix raft url
